// ======================= S25 ABUSE & ASSAULT =======================
// Sources: WHO clinical management of rape & IPV survivors 2019/2020; CDC STI Treatment Guidelines 2021; CDC nPEP 2025 update / WHO PEP 2024; DOH HIV PEP guidance;
// PH RA 8353 (Anti-Rape 1997), RA 8505 (Rape Victim Assistance), RA 9262 (VAWC 2004), RA 7610, RA 11648 (2022, age of sexual consent 16), RA 9994 (Expanded Senior Citizens), DOH AO 2013-0011 WCPU; FIGO/WHO emergency contraception.
Object.assign(REVIEW, {
  'ab-ec':   {t:'Emergency contraception: levonorgestrel 1.5 mg PO single dose ≤ 72 h (some efficacy to 120 h; consider 3 mg if BMI > 30); ulipristal 30 mg ≤ 120 h if available; copper IUD ≤ 5 days most effective', r:'WHO/FIGO; ulipristal availability in PH is limited – confirm local formulary.', tab:'Abuse'},
  'ab-sti':  {t:'STI prophylaxis after sexual assault (adolescents/adults): ceftriaxone 500 mg IM once (1 g if ≥ 150 kg) + doxycycline 100 mg PO BID × 7 d + metronidazole 500 mg PO BID × 7 d (women); azithromycin 1 g once if doxycycline contraindicated/pregnant', r:'CDC STI 2021; WHO alternative regimens differ.', tab:'Abuse'},
  'ab-pep':  {t:'HIV PEP ≤ 72 h: tenofovir DF 300 mg + lamivudine 300 mg (or emtricitabine 200 mg) + dolutegravir 50 mg daily × 28 days; children: weight-band dosing per DOH/WHO', r:'WHO 2024 / CDC nPEP; PH supply via DOH treatment hubs – confirm local protocol and starter packs.', tab:'Abuse / ID'},
  'ab-hbv':  {t:'Hepatitis B after assault: start/complete HBV vaccine if not immune; HBIG if source known HBsAg-positive', r:'CDC 2021.', tab:'Abuse'},
  'ab-law':  {t:'PH laws: RA 8353 (rape as crime against persons), RA 11648 (age of sexual consent raised to 16), RA 9262 (VAWC – barangay protection order), RA 7610 (child abuse), RA 9994 (senior citizens); WCPU referral (DOH AO 2013-0011)', r:'Legal summary – confirm with hospital WCPU/legal officer.', tab:'Abuse'}
});
Object.assign(D, {
  abLng: {n:'Levonorgestrel – emergency contraception', flag:'ab-ec', a:[F('PO','1.5 mg single dose as soon as possible (≤ 72 h; reduced efficacy to 120 h)'),F('Ulipristal (if available)','30 mg PO single dose ≤ 120 h')], p:[F('Post-menarche adolescent','1.5 mg PO single dose')]},
  abSti: {n:'STI prophylaxis after assault', flag:'ab-sti', a:[F('Ceftriaxone','500 mg IM once'),F('Doxycycline','100 mg PO BID × 7 days (azithromycin 1 g once if pregnant)'),F('Metronidazole (women)','500 mg PO BID × 7 days')], p:[B('Ceftriaxone IM once (< 45 kg; ≥ 45 kg use adult regimen)',25,50,'mg/kg',{max:250,flag:'ab-sti',note:'Prepubertal: test first; treat if positive or high-risk exposure. Add azithromycin 20 mg/kg (max 1 g) for chlamydia if indicated.'})]},
  abPep: {n:'HIV post-exposure prophylaxis (28 days)', flag:'ab-pep', a:[F('PO daily','TDF 300 mg + 3TC 300 mg (or FTC 200 mg) + DTG 50 mg × 28 days; start ≤ 72 h, ideally ≤ 2 h')], p:[F('Children','Weight-band TDF/3TC (or ABC/3TC) + DTG per DOH/WHO pediatric tables – contact HIV treatment hub')]}
});
defCards('abuse','Abuse',[
 {id:'sexassault', title:'Sexual assault – medical care, forensic exam, EC, STI & HIV PEP, PH WCPU', kw:'sexual assault rape forensic emergency contraception levonorgestrel PEP HIV STI prophylaxis WCPU RA 8353 RA 11648 medico-legal', h:'🛡️ Sexual assault',
  render:w=>ol(['Treat injuries first; private room, chaperone, trauma-informed approach (explain each step, allow the survivor to stop)','Consent for each part: medical care, forensic evidence, photography, police notification (adult survivors decide; mandatory reporting for minors)',`<b>PH</b>: refer to the hospital <b>Women and Children Protection Unit (WCPU)</b> / medico-legal officer (PNP Crime Lab / NBI); RA 8505 rape crisis centres${vt('ab-law')}`,'Forensic evidence best collected ≤ 72 h (up to 5–7 days for some samples); avoid washing/changing clothes before exam if possible; document injuries with body map, measurements, photos','Baseline tests: pregnancy test, HIV, HBsAg, syphilis, hepatitis C; NAAT for gonorrhea/chlamydia/trichomonas if available',`Emergency contraception, STI prophylaxis, HIV PEP (≤ 72 h), hepatitis B vaccine${vt('ab-hbv')}, tetanus if wounds (${gto('tetanus','tetanus')})`,'Mental health first aid, safety assessment, follow-up at 2 weeks, 6 weeks, 3 and 6 months (HIV/syphilis serology)'])+drugs(['abLng','abSti','abPep'],w)},
 {id:'ipv', title:'Intimate partner violence & VAWC (RA 9262) – screening, safety planning, documentation', kw:'intimate partner violence domestic violence VAWC RA 9262 protection order barangay safety plan strangulation', h:'🏠 Intimate partner violence',
  render:w=>ul(['Ask privately (without partner/family): "Has anyone at home hurt you or made you feel afraid?" – screen all women of reproductive age and pregnant women','Clues: delayed presentation, injuries inconsistent with story, central injuries (face, breasts, abdomen), injuries in pregnancy, repeated visits, controlling partner','<b>Strangulation</b>: may have few external signs – voice change, petechiae, dysphagia, neck pain → consider CTA neck (dissection), observe for airway swelling','High lethality risk: strangulation, weapon threats, escalating frequency, pregnancy, recent separation, threats to kill → urgent safety planning','Document verbatim statements, body map, photos (with consent); records may be used in court',`<b>PH</b>: RA 9262 (VAWC) – Barangay Protection Order (BPO) from barangay VAW desk; Temporary/Permanent Protection Orders from court; PNP Women and Children Protection Desk; WCPU referral; DSWD shelters${vt('ab-law')}`,'Children in the household: assess for abuse ('+gto('childabuse','child maltreatment')+')'])},
 {id:'elderabuse', title:'Elder abuse & neglect', kw:'elder abuse neglect older adult financial abuse senior citizen RA 9994', h:'👵 Elder abuse',
  render:w=>ul(['Types: physical, sexual, psychological, financial, neglect (including self-neglect)','Clues: unexplained bruises (especially arms, trunk, ears), pressure injuries, dehydration/malnutrition, delays in seeking care, caregiver who answers for the patient, medication non-adherence or over-sedation','Interview patient alone; assess cognition and capacity; check medication levels where possible','Admit if unsafe discharge; involve social services',`<b>PH</b>: refer to hospital social worker, DSWD and the local Office of Senior Citizens Affairs (OSCA); RA 9994 Expanded Senior Citizens Act${vt('ab-law')}`])},
 {id:'absrc', title:'Abuse & assault sources', h:'📚 Abuse &amp; assault sources', render:w=>nt('WHO Clinical management of rape and intimate partner violence survivors (2020) · WHO Responding to intimate partner violence and sexual violence against women (2013) · CDC Sexually Transmitted Infections Treatment Guidelines 2021 · WHO Guidelines for HIV post-exposure prophylaxis 2024; CDC nPEP guideline 2025 · FIGO/WHO emergency contraception statements · Philippine RA 8353, RA 8505, RA 9262, RA 7610, RA 11648, RA 9994 · DOH Administrative Order 2013-0011 (Women and Children Protection Units) · Child abuse content: see Pediatrics. Tintinalli 9e Section 25 used only as a topic map.')}
]);
