// ======================= S5 ANALGESIA, ANESTHESIA & PROCEDURAL SEDATION =======================
// Sources: ACEP clinical policy procedural sedation 2014 & ketamine 2011 (Green); ASA 2018 moderate sedation; ACEP opioid policy 2020;
// ASRA LAST checklist 2020; WHO analgesic guidance; AAP/ACEP pediatric pain; PH FDA product labels.
Object.assign(REVIEW, {
  'an-apap':  {t:'Acetaminophen: adult 1 g PO/IV q6h, max 4 g/day (≤ 3 g/day if liver disease, alcohol use, malnutrition, < 50 kg use 15 mg/kg); peds 15 mg/kg q6h, max 75 mg/kg/day (max 1 g/dose)', r:'Common label/guideline values; IV dosing < 50 kg weight-based.', tab:'Analgesia'},
  'an-nsaid': {t:'NSAIDs: ibuprofen 400 mg PO q6–8h (peds 10 mg/kg, max 400 mg); ketorolac 10–15 mg IV/IM single dose (analgesic ceiling; peds 0.5 mg/kg, max 15 mg) – avoid in AKI, GI bleed, late pregnancy, dengue', r:'ACEP/ED studies show ketorolac 10 mg ≈ 30 mg; dengue warning is PH-specific practice.', tab:'Analgesia'},
  'an-opioid':{t:'Opioids: morphine 0.05–0.1 mg/kg IV (adult 2.5–5 mg increments); fentanyl 1 mcg/kg IV, intranasal 1.5 mcg/kg (max 100 mcg); tramadol 50–100 mg PO q6h (max 400 mg/day; not < 12 y)', r:'Titrate to effect; elderly/renal: lower doses. Tramadol: seizures, serotonin syndrome, CYP2D6 variability.', tab:'Analgesia'},
  'an-sdk':   {t:'Sub-dissociative ketamine analgesia 0.1–0.3 mg/kg IV over 10–15 min (or 0.15 mg/kg/hr infusion); intranasal 0.5–1 mg/kg', r:'ACEP/ED trials; dysphoria with fast push.', tab:'Analgesia'},
  'an-psa':   {t:'Procedural sedation: ketamine 1–2 mg/kg IV (peds 1.5–2) or 4–5 mg/kg IM; propofol 0.5–1 mg/kg then 0.25–0.5 mg/kg q1–3 min; ketofol 1:1 0.5 mg/kg each; etomidate 0.1–0.15 mg/kg; midazolam 0.02–0.05 mg/kg + fentanyl 0.5–1 mcg/kg', r:'ACEP 2014 policy and ketamine guideline (Green 2011); fasting need not delay ED sedation.', tab:'Analgesia'},
  'an-la':    {t:'Local anesthetic maximum doses: lidocaine 4.5 mg/kg plain (max 300 mg), 7 mg/kg with epinephrine (max 500 mg); bupivacaine 2.5 mg/kg plain (max 175 mg), 3 mg/kg with epinephrine (max 225 mg)', r:'Classic textbook maxima; ASRA emphasises site and patient factors. 1% = 10 mg/mL.', tab:'Analgesia / Wound'},
  'an-fib':   {t:'Fascia iliaca block for hip fracture: ~ 30–40 mL of dilute long-acting LA (e.g. bupivacaine 0.25% or levobupivacaine) within weight maxima, ultrasound-guided', r:'AAGBI/NICE hip fracture; volume must respect mg/kg limits.', tab:'Analgesia'}
});
Object.assign(D, {
  anApap: {n:'Acetaminophen (paracetamol)', flag:'an-apap',
    a:[C('PO / IV q6h',w=>({main: ok(w)&&w<50?`${fmt(15*w)} mg (15 mg/kg)`:'1 g', lines:['Max 4 g/day; ≤ 3 g/day if liver disease, chronic alcohol, malnutrition, < 50 kg']}))],
    p:[B('PO / IV / PR q6h',15,15,'mg/kg',{max:1000,note:'Max 75 mg/kg/day (and 4 g). Neonates: lower doses.'})]},
  anIbu: {n:'Ibuprofen', flag:'an-nsaid', a:[F('PO','400 mg q6–8h (max 1.2 g/day OTC, 2.4 g/day Rx)')], p:[B('PO q6–8h',10,10,'mg/kg',{max:400,note:'Avoid in dehydration, dengue, < 3 months.'})]},
  anKeto: {n:'Ketorolac', flag:'an-nsaid', a:[F('IV/IM','10 – 15 mg single dose (no extra analgesia above 15 mg)',{note:'≤ 5 days total; avoid > 65 y high-risk, AKI, bleeding, dengue.'})], p:[B('IV/IM',0.5,0.5,'mg/kg',{max:15})]},
  anMorph: {n:'Morphine IV', flag:'an-opioid', a:[F('IV titration','2.5 – 5 mg q5–10 min to effect (elderly 1–2 mg)')], p:[B('IV',0.05,0.1,'mg/kg',{max:5,conc:1,note:'Repeat q10 min titrated; monitor sedation and SpO₂.'})]},
  anFentIN: {n:'Fentanyl', flag:'an-opioid', a:[B('IV',0.5,1,'mcg/kg',{note:'Repeat q5–10 min; 50 mcg/mL.'})], p:[B('Intranasal (atomiser, split nostrils)',1.5,1.5,'mcg/kg',{max:100,conc:50,note:'Repeat 0.5–1 mcg/kg after 10 min if needed.'}),B('IV',0.5,1,'mcg/kg',{max:50})]},
  anTram: {n:'Tramadol (commonly used in PH)', flag:'an-opioid', a:[F('PO / IV','50 – 100 mg q6h (max 400 mg/day; ≥ 75 y max 300 mg)',{note:'Avoid: seizures, SSRIs/MAOI, CYP2D6 ultra-rapid metabolisers.'})], p:[F('Children','Not recommended < 12 y')]},
  anSDK: {n:'Ketamine – sub-dissociative analgesia', flag:'an-sdk', a:[B('IV over 10–15 min',0.1,0.3,'mg/kg',{conc:10})], p:[B('IV over 10–15 min',0.1,0.3,'mg/kg',{max:30}),B('Intranasal',0.5,1,'mg/kg',{max:50})]},
  anKetPSA: {n:'Ketamine – dissociative sedation', flag:'an-psa', a:[B('IV over 30–60 s',1,2,'mg/kg',{conc:50,note:'Repeat 0.5 mg/kg q5–10 min. IM 4–5 mg/kg.'})], p:[B('IV over 30–60 s',1.5,2,'mg/kg',{max:200,note:'IM 4–5 mg/kg (max 500 mg). Laryngospasm: jaw thrust, BVM, small-dose succinylcholine.'})]},
  anProp: {n:'Propofol – sedation', flag:'an-psa', a:[B('IV load',0.5,1,'mg/kg',{conc:10,note:'Then 0.25–0.5 mg/kg q1–3 min. Hypotension, apnea.'})], p:[B('IV load',1,1,'mg/kg',{max:100,note:'Then 0.5 mg/kg PRN.'})]},
  anMdz: {n:'Midazolam (+ fentanyl) – moderate sedation', flag:'an-psa', a:[B('IV',0.02,0.05,'mg/kg',{note:'Max ~ 2.5 mg per dose in adults; elderly 0.5–1 mg.'})], p:[B('IV',0.05,0.1,'mg/kg',{max:2.5}),B('Intranasal',0.2,0.3,'mg/kg',{max:10})]},
  anEtoS: {n:'Etomidate – brief sedation (e.g. cardioversion)', flag:'an-psa', a:[B('IV',0.1,0.15,'mg/kg',{note:'Myoclonus common.'})], p:[B('IV',0.1,0.2,'mg/kg',{max:20})]}
});
function laCalc(w){ if(!ok(w)) return nt('Enter weight to calculate maximum local anesthetic volumes.');
  const rows=[['Lidocaine plain',4.5,300],['Lidocaine + epinephrine',7,500],['Bupivacaine plain',2.5,175],['Bupivacaine + epinephrine',3,225]].map(([n,mk,mx])=>{ const mg=Math.min(mk*w,mx); return [n+vt('an-la'),`${mk} mg/kg (max ${mx} mg)`,`<b>${fmt(mg)} mg</b>`, n.startsWith('Lido')?`${fmt(mg/10)} mL of 1% · ${fmt(mg/20)} mL of 2%`:`${fmt(mg/2.5)} mL of 0.25% · ${fmt(mg/5)} mL of 0.5%`]; });
  return tbl(['Agent','Max','For '+fmt(w)+' kg'+vt('an-la'),'Volume'],rows)+nt('Doses are additive across agents (sum the fractions of each maximum). Reduce in elderly, heart/liver failure, highly vascular sites (scalp, intercostal).'); }
defCards('analg','Analgesia',[
 {id:'pain', title:'Acute pain – multimodal ladder (acetaminophen, NSAIDs, opioids, ketamine)', kw:'pain analgesia paracetamol acetaminophen ibuprofen ketorolac morphine fentanyl intranasal tramadol ketamine renal colic', h:'💊 Acute pain management',
  render:w=>nt('Assess pain with a score (0–10, Wong–Baker faces, FLACC in preverbal children); treat early and re-assess within 30–60 min. Combine agents with different mechanisms; use non-pharmacological measures (splint, ice, elevation, distraction).')+
   drugs(['anApap','anIbu','anKeto','anMorph','anFentIN','anTram','anSDK'],w)+
   ul(['Renal colic: NSAID first-line (better than opioids), add IV acetaminophen; avoid if AKI','Dengue (common in PH): <b>avoid NSAIDs and IM injections</b> – acetaminophen only','Elderly: start low (morphine 1–2 mg), avoid tramadol/codeine combinations with confusion risk; constipation prophylaxis'+vt('an-opioid'),'Codeine: avoid in children and breastfeeding mothers (ultrarapid metabolisers)'])},
 {id:'psa', title:'Procedural sedation & analgesia (ketamine, propofol, midazolam/fentanyl)', kw:'procedural sedation PSA ketamine propofol ketofol midazolam etomidate fasting capnography laryngospasm', h:'😴 Procedural sedation',
  render:w=>h3('Before')+ul(['ASA class I–II ideal for ED; III–IV and difficult airways → senior/anesthesia','Recent food intake is not a reason to delay ED sedation (ACEP 2014) – weigh urgency vs aspiration risk','Consent, two clinicians (one dedicated to sedation/airway), monitoring incl. <b>capnography</b>, suction, BVM, reversal agents, resuscitation drugs'])+
   drugs(['anKetPSA','anProp','anMdz','anEtoS'],w)+
   ul(['Reversal: naloxone ('+gto('naloxone','dosing')+'); flumazenil only for iatrogenic benzodiazepine sedation in benzodiazepine-naïve patients','Ketamine cautions: age &lt; 3 months, active psychosis; emergence reactions – calm environment, small midazolam dose if severe','Discharge: back to baseline mental status, tolerating fluids, responsible adult, written instructions'])},
 {id:'regional', title:'Local & regional anesthesia – maximum dose calculator, digital/hematoma/fascia iliaca blocks, LAST', kw:'local anesthetic lidocaine bupivacaine maximum dose digital block hematoma block fascia iliaca LAST lipid', h:'💉 Local &amp; regional anesthesia',
  render:w=>laCalc(w)+ul(['Lidocaine with epinephrine is safe in fingers, toes, nose and ears in healthy patients','Less painful injection: warm, buffer (lidocaine : 8.4% bicarbonate = 10 : 1), small needle, inject slowly through wound edges','<b>Digital block</b>: ring or single-injection volar (transthecal/subcutaneous) 2–3 mL per side'+vt('an-la'),'<b>Hematoma block</b> (distal radius): aspirate hematoma, inject 10 mL 1% lidocaine'+vt('an-la'),`<b>Fascia iliaca block</b> for hip/femur fracture: large-volume dilute LA under ultrasound${vt('an-fib')}`,'<b>LAST</b>: perioral numbness, tinnitus, seizures, arrhythmia/arrest → stop injection, airway, benzodiazepine, 20% lipid emulsion ('+gto('antidotes','antidotes – lipid')+'), prolonged CPR'])},
 {id:'chronicpain', title:'Chronic pain & opioid use disorder in the ED', kw:'chronic pain opioid use disorder buprenorphine naloxone prescribing', h:'🔄 Chronic pain &amp; opioid use disorder',
  render:w=>ul(['Look for a new acute cause behind a chronic pain flare (red flags: fever, weight loss, neuro deficit, cancer, IV drug use)','Prefer non-opioid multimodal therapy; if opioids needed, shortest course (≤ 3 days), lowest dose, no long-acting formulations from the ED; check for other prescribers','Opioid withdrawal: COWS score; buprenorphine initiation from the ED where available (limited in PH – refer to DOH-accredited treatment and rehabilitation centres)','Offer naloxone and overdose education to people who use opioids','Sickle cell crisis, cancer pain: treat promptly and adequately – do not label as drug-seeking'])},
 {id:'ansrc', title:'Analgesia & sedation sources', h:'📚 Analgesia &amp; sedation sources', render:w=>nt('ACEP Clinical policy: procedural sedation and analgesia in the ED (2014) · Green et al., Clinical practice guideline for emergency department ketamine dissociative sedation (Ann Emerg Med 2011) · ASA practice guidelines for moderate procedural sedation 2018 · ACEP policy on opioid prescribing · ASRA checklist for local anesthetic systemic toxicity 2020 · AAGBI/NICE hip fracture analgesia · WHO cancer pain guidelines 2018 · Philippine FDA product information. Tintinalli 9e Section 5 used only as a topic map.')}
]);
