// ======================= S20 DERMATOLOGY =======================
// Sources: BAD SJS/TEN guidelines 2016; SCORTEN (Bastuji-Garin 2000); RegiSCAR DRESS; IDSA SSTI 2014; CDC/WHO scabies & ivermectin; IUSTI/WHO; EAACI/GA²LEN urticaria 2021;
// DOH leprosy & dengue programmes; CPIC HLA-B*15:02 carbamazepine.
Object.assign(REVIEW, {
  'dm-scorten':{t:'SCORTEN (1 point each: age ≥ 40, HR ≥ 120, malignancy, detachment > 10% BSA day 1, urea > 10 mmol/L (28 mg/dL), bicarbonate < 20, glucose > 14 mmol/L (252 mg/dL)); predicted mortality 0–1: ~3%, 2: ~12%, 3: ~35%, 4: ~58%, ≥ 5: ~90%', r:'Original 2000 derivation; recalibrated versions exist.', tab:'Derm'},
  'dm-ssti':  {t:'Cellulitis/abscess: drain abscesses; non-purulent cellulitis – cephalexin 500 mg QID (peds 12.5–25 mg/kg q6h, max 500 mg) × 5 d; MRSA risk/purulent – TMP-SMX 1–2 DS tab BID or clindamycin 300–450 mg TID; severe – cefazolin 2 g IV q8h ± vancomycin', r:'IDSA 2014; PH community MRSA rates vary.', tab:'Derm'},
  'dm-nf':    {t:'Necrotising soft-tissue infection: emergency surgical debridement; piperacillin–tazobactam 4.5 g IV q6h (or meropenem) + clindamycin 900 mg IV q8h (toxin suppression) + vancomycin', r:'IDSA 2014; LRINEC is not sensitive enough to rule out.', tab:'Derm'},
  'dm-scab':  {t:'Scabies: permethrin 5% cream neck down (include scalp/face in infants), wash off after 8–14 h, repeat in 7 days; or ivermectin 200 mcg/kg PO on days 1 and 8 (not < 15 kg or pregnancy); treat all household contacts', r:'CDC/WHO; crusted scabies needs combined therapy.', tab:'Derm'},
  'dm-zoster':{t:'Herpes zoster (within 72 h or new lesions/ophthalmic/immunocompromised): valacyclovir 1 g PO TID × 7 d or acyclovir 800 mg 5×/day × 7 d; disseminated/immunocompromised: acyclovir 10 mg/kg IV q8h', r:'Renal dose adjustment required.', tab:'Derm'},
  'dm-urt':   {t:'Urticaria: second-generation antihistamine (cetirizine 10 mg daily, up to 4× standard dose); short prednisone 0.5 mg/kg (max 40–50 mg) × 3–5 d for severe acute urticaria; peds cetirizine 2.5 mg (6 mo–2 y), 5 mg (2–5 y), 10 mg (≥ 6 y)', r:'EAACI/GA²LEN 2021; updosing off-label.', tab:'Derm'},
  'dm-dress': {t:'DRESS: stop culprit; systemic corticosteroids (prednisone 0.5–1 mg/kg/day, slow taper over weeks) when organ involvement', r:'Expert consensus; no RCTs.', tab:'Derm'},
  'dm-hla':   {t:'HLA-B*15:02 (carbamazepine/phenytoin SJS/TEN risk) is common in Southeast Asian populations incl. Filipinos – screen before carbamazepine where available', r:'CPIC; local allele frequency estimates vary.', tab:'Derm'}
});
Object.assign(D, {
  dmCeph: {n:'Cephalexin – non-purulent cellulitis', flag:'dm-ssti', a:[F('PO','500 mg QID × 5 days (extend if not improving)')], p:[B('PO QID',12.5,25,'mg/kg',{max:500})]},
  dmTmp: {n:'TMP-SMX – purulent / MRSA-risk SSTI', flag:'dm-ssti', a:[F('PO','1–2 DS tablets (160/800 mg) BID × 5–7 days')], p:[B('PO BID (trimethoprim)',4,6,'mg/kg',{max:320})]},
  dmClin: {n:'Clindamycin', flag:'dm-ssti', a:[F('PO / IV','300–450 mg PO TID · 600–900 mg IV q8h')], p:[B('PO / IV q8h',10,13,'mg/kg',{max:900})]},
  dmNf: {n:'Necrotising infection – empiric', flag:'dm-nf', a:[F('IV','Piperacillin–tazobactam 4.5 g q6h + clindamycin 900 mg q8h + vancomycin 25 mg/kg load')], p:[B('Clindamycin IV q8h',13,13,'mg/kg',{max:900}),B('Piperacillin–tazobactam IV q6–8h (piperacillin)',100,100,'mg/kg',{max:4000})]},
  dmIver: {n:'Ivermectin – scabies', flag:'dm-scab', b:[C('PO day 1 and day 8',w=>ok(w)?(w<15?{main:'Not for < 15 kg – use permethrin',lines:[]}:{main:`${fmt(Math.round(0.2*w/3)*3)} mg (≈ 200 mcg/kg, 3-mg tablets)`,lines:['Take with food; avoid in pregnancy']}):{main:'Enter weight',lines:['200 mcg/kg on days 1 and 8']})]},
  dmVala: {n:'Valacyclovir / acyclovir – herpes zoster', flag:'dm-zoster', a:[F('PO','Valacyclovir 1 g TID × 7 d (or acyclovir 800 mg 5×/day)'),B('IV (disseminated / immunocompromised)',10,10,'mg/kg',{note:'q8h; hydrate; renal adjust.'})], p:[B('Acyclovir PO 4×/day (varicella > 2 y)',20,20,'mg/kg',{max:800}),B('Acyclovir IV q8h',10,10,'mg/kg',{max:800})]},
  dmCet: {n:'Cetirizine – urticaria', flag:'dm-urt', a:[F('PO','10 mg daily (may increase up to 4×)')], p:[C('PO daily by age',w=>{ const y=ageYears(); return {main: y==null?'Enter age':y<2?'2.5 mg (6 mo–2 y)':y<6?'5 mg':'10 mg', lines:[]}; })]},
  dmPred: {n:'Prednisone – severe urticaria / DRESS', flag:'dm-urt', a:[F('Urticaria','40–50 mg daily × 3–5 days'),F('DRESS with organ involvement','0.5–1 mg/kg/day, taper over weeks',{flag:'dm-dress'})], p:[B('Urticaria PO daily',0.5,1,'mg/kg',{max:40})]}
});
const SCT=[['sct_age','Age ≥ 40'],['sct_hr','Heart rate ≥ 120'],['sct_ca','Cancer / hematologic malignancy'],['sct_bsa','Epidermal detachment > 10% BSA'],['sct_urea','Urea > 10 mmol/L (BUN > 28 mg/dL)'],['sct_hco3','Bicarbonate < 20 mmol/L'],['sct_glu','Glucose > 14 mmol/L (252 mg/dL)']];
defCards('derm','Derm',[
 {id:'rashfever', title:'Dangerous rashes – fever + rash, approach by morphology', kw:'rash fever petechiae purpura meningococcemia dengue measles toxic shock Kawasaki morphology vesicles erythroderma', h:'🔎 Dangerous rashes',
  render:w=>tbl(['Pattern','Think of','First steps'],[['Petechiae/purpura + fever','Meningococcemia, dengue (very common in PH), leptospirosis, sepsis/DIC, ITP/leukemia','Blood cultures, antibiotics within 1 h if meningococcus possible; CBC, platelets'],['Diffuse erythema + shock','Toxic shock syndrome (tampons, wounds), scarlet fever','Source removal, clindamycin + β-lactam/vancomycin'],['Mucosal erosions + skin pain/blisters','SJS/TEN','Stop drugs, SCORTEN, burn/ICU'],['Maculopapular + cough, coryza, conjunctivitis','Measles (outbreaks in PH) – Koplik spots','Airborne isolation, vitamin A, notify'],['Fever ≥ 5 days child + rash/eyes/lips/hands','Kawasaki disease','Echo, IVIG – see Pediatrics'],['Erythroderma (&gt; 90% BSA)','Drug reaction, psoriasis, eczema, lymphoma','Fluids, temperature, admit']])+
   ul(['Describe: distribution, morphology (macule, papule, vesicle, bulla, pustule, petechia), mucosa, Nikolsky sign, blanching','Dengue: flushing/"islands of white in a sea of red" in recovery; tourniquet test; avoid NSAIDs/IM injections'])},
 {id:'sjs', title:'SJS/TEN (SCORTEN), DRESS, blistering diseases', kw:'Stevens-Johnson TEN toxic epidermal necrolysis SCORTEN DRESS pemphigus pemphigoid drug eruption allopurinol carbamazepine HLA-B 1502', h:'🔥 SJS/TEN &amp; severe drug reactions',
  inputs: SCT.map(([id,t])=>ck(id,t)).join(''),
  render:w=>{ const n=nsum(SCT.map(x=>x[0])); const m=['~3%','~3%','~12%','~35%','~58%','~90%','~90%','~90%'][n];
   return score(n,7,'SCORTEN')+`<div class="big">Predicted mortality ${m}${vt('dm-scorten')}</div>`+
   ol([['shock','<b>Stop every non-essential drug</b>; culprit usually started 4–28 days before (allopurinol, carbamazepine, phenytoin, lamotrigine, sulfonamides, nevirapine, NSAIDs oxicams)'+vt('dm-hla')],'Treat like a burn: warm room, fluids (less than Parkland), non-adherent dressings, analgesia, eye and genital care – ophthalmology early (lifelong scarring)','Transfer to a burn unit/ICU if &gt; 10% detachment; immunomodulators (cyclosporine, IVIG, steroids) per dermatology'])+
   ul(['<b>DRESS</b>: rash + fever + eosinophilia/atypical lymphocytes + organ involvement (hepatitis, nephritis) 2–8 weeks after drug (anticonvulsants, allopurinol, sulfa, vancomycin) – stop drug, steroids'+vt('dm-dress'),'<b>Pemphigus vulgaris</b> (mucosal, flaccid bullae, Nikolsky +) vs <b>bullous pemphigoid</b> (elderly, tense bullae, itchy) – dermatology, steroids','Staphylococcal scalded skin (young children): Nikolsky +, no mucosa – IV antistaphylococcal antibiotics'])+drugs(['dmPred'],w); }},
 {id:'skininf', title:'Skin infections: cellulitis, abscess, necrotising fasciitis, scabies, zoster, impetigo, leprosy', kw:'cellulitis abscess incision drainage MRSA necrotizing fasciitis Fournier scabies permethrin ivermectin herpes zoster shingles impetigo leprosy tinea', h:'🦠 Skin &amp; soft-tissue infections',
  render:w=>ul(['<b>Abscess</b>: incision and drainage (ultrasound helps); antibiotics if &gt; 2 cm, cellulitis, systemic signs, immunosuppression, extremes of age','<b>Cellulitis</b>: mark margins; bilateral "cellulitis" is usually stasis dermatitis; elevate; treat tinea pedis portal','<b>Necrotising fasciitis</b>: pain out of proportion, rapid spread, bullae, crepitus, shock – <b>surgeon now</b>; imaging must not delay'+vt('dm-nf')])+drugs(['dmCeph','dmTmp','dmClin','dmNf'],w)+
   ul(['<b>Scabies</b> (common in PH households, institutions): nocturnal itch, web-space burrows – treat everyone at once; wash bedding'+vt('dm-scab'),'<b>Herpes zoster</b>: antiviral within 72 h; nose-tip lesions → ophthalmology'+vt('dm-zoster'),'<b>Impetigo</b>: topical mupirocin for limited; oral cephalexin for extensive','<b>Leprosy</b> (still endemic in PH): anesthetic hypopigmented patches, thickened nerves – refer to DOH leprosy programme (free MDT); reactions (painful nerves, ENL) need steroids','Tinea corporis/capitis: topical azole/terbinafine; capitis needs oral therapy'])+drugs(['dmIver','dmVala'],w)},
 {id:'urticaria', title:'Urticaria, drug eruptions & regional rashes (face, trunk, groin, extremities)', kw:'urticaria hives antihistamine cetirizine drug eruption intertrigo candidiasis erythema nodosum pressure injury contact dermatitis', h:'🌸 Urticaria &amp; regional rashes',
  render:w=>ul(['Urticaria with any airway, breathing or circulation problem = anaphylaxis ('+gto('anaph','IM epinephrine')+')','Acute urticaria: non-sedating antihistamine regularly for 1–2 weeks; avoid triggers (NSAIDs, codeine)'+vt('dm-urt')])+drugs(['dmCet','dmPred'],w)+
   tbl(['Region','Common ED problems'],[['Face &amp; scalp','Erysipelas (raised sharp border), herpes zoster ophthalmicus, angioedema, impetigo, seborrheic dermatitis, tinea capitis/kerion'],['Trunk','Pityriasis rosea (herald patch), drug exanthem, tinea versicolor, zoster (dermatomal), scabies'],['Groin &amp; skinfolds','Intertrigo/candidiasis (satellite lesions), tinea cruris (spares scrotum), <b>Fournier gangrene</b> (pain, crepitus – surgical emergency), hidradenitis'],['Extremities','Cellulitis vs stasis dermatitis, erythema nodosum (TB, strep, sarcoid, leprosy), pressure injuries, contact dermatitis, diabetic foot ulcers']])},
 {id:'dmsrc', title:'Dermatology sources', h:'📚 Dermatology sources', render:w=>nt('Creamer et al., UK guidelines for SJS/TEN in adults (BAD 2016) · Bastuji-Garin et al., SCORTEN (J Invest Dermatol 2000) · Kardaun et al., RegiSCAR DRESS · Stevens et al., IDSA SSTI guideline 2014 · CDC scabies treatment guidance; WHO ivermectin mass drug administration guidance · Zuberbier et al., EAACI/GA²LEN/EuroGuiDerm/APAAACI urticaria guideline 2021 · Phillips et al., CPIC guideline HLA-B carbamazepine 2017 · DOH National Leprosy Control Program. Tintinalli 9e Section 20 used only as a topic map.')}
]);
