// ======================= S2 DISASTER MANAGEMENT =======================
// Sources: START/JumpSTART (Romig); SALT (CDC/ACEP 2008); DOH leptospirosis prophylaxis guidance (DOH 2010/AO); ISN Renal Disaster Relief Task Force crush syndrome 2012;
// CDC blast injury fact sheets; CHEMM / OPCW; FDA/WHO potassium iodide guidance; REMM (HHS); DOH Health Emergency Management Bureau.
Object.assign(REVIEW, {
  'ds-start':  {t:'START triage cut-offs: RR > 30 → immediate; radial pulse absent or capillary refill > 2 s → immediate; cannot follow simple commands → immediate; JumpSTART: RR < 15 or > 45, 5 rescue breaths if apneic with pulse', r:'START/JumpSTART published algorithms; SALT is the US national guideline alternative.', tab:'Disaster'},
  'ds-lepto':  {t:'Leptospirosis post-flood prophylaxis (DOH): low risk – doxycycline 200 mg single dose within 24–72 h of exposure; moderate risk (wounds, repeated wading, swallowed water) – 200 mg once daily for 3–5 days; high risk (continuous exposure) – 200 mg once weekly until exposure ends', r:'DOH categories recalled; pregnant women/children: azithromycin or amoxicillin per DOH – confirm current DOH memorandum.', tab:'Disaster / Infectious'},
  'ds-crush':  {t:'Crush syndrome: start 0.9% NaCl ~1 L/hr (children 15–20 mL/kg/hr) before/during extrication, then titrate to urine output ~200–300 mL/hr; avoid K⁺-containing fluids; treat hyperkalemia', r:'ISN Renal Disaster Relief Task Force 2012; volumes must be reduced in elderly/anuric patients.', tab:'Disaster'},
  'ds-ki':     {t:'Potassium iodide (radioiodine release only): adult 130 mg; 3–18 y 65 mg (adolescents ≥ 70 kg 130 mg); 1 month–3 y 32 mg; < 1 month 16 mg – single daily dose, only on public-health instruction', r:'FDA 2001 / WHO 2017; protects thyroid only; PH: on PNRI/DOH advice.', tab:'Disaster'},
  'ds-nerve':  {t:'Nerve agent mass casualty: atropine 2–6 mg IV/IM (peds 0.05–0.1 mg/kg) repeated every 5 min to dry secretions; pralidoxime 1–2 g IV over 15–30 min (peds 25–50 mg/kg); diazepam/midazolam for seizures', r:'CHEMM/US Army MRICD values; autoinjector dosing differs.', tab:'Disaster'}
});
Object.assign(D, {
  dsDoxy: {n:'Doxycycline – leptospirosis prophylaxis (flood exposure)', flag:'ds-lepto',
    a:[F('Low risk','200 mg PO single dose within 24–72 h'),F('Moderate risk','200 mg PO once daily × 3–5 days'),F('High risk (continuous)','200 mg PO once weekly until exposure ends')],
    p:[F('Children / pregnancy','Azithromycin or amoxicillin per DOH guidance – avoid prolonged doxycycline in < 8 y')]},
  dsKI: {n:'Potassium iodide (radioiodine)', flag:'ds-ki', b:[C('Single dose',w=>{ const y=ageYears(); if(y==null) return {main:'Enter age',lines:['Adult 130 mg · 3–18 y 65 mg · 1 mo–3 y 32 mg · < 1 mo 16 mg']};
     const m = y>=18?130 : y>=3?((ok(w)&&w>=70)?130:65) : y>=1/12?32:16; return {main:`${m} mg PO`,lines:['Only with public-health instruction; once daily while exposure continues']}; })]},
  dsAtro: {n:'Atropine – nerve agent / mass organophosphate', flag:'ds-nerve',
    a:[F('IV/IM','2 – 6 mg, repeat q5 min (double if no effect) until secretions dry')],
    p:[B('IV/IM',0.05,0.1,'mg/kg',{max:6,note:'Repeat q5 min until secretions dry.'})]},
  dsPam: {n:'Pralidoxime (2-PAM)', flag:'ds-nerve',
    a:[F('IV over 15–30 min','1 – 2 g, then infusion ~ 8 mg/kg/hr or repeat per protocol')],
    p:[B('IV over 15–30 min',25,50,'mg/kg',{max:2000})]}
});
const START_IDS=['stWalk','stBreath','stRR','stPerf','stCmd'];
function startTriage(){ const g=id=>sv(id); const peds=PU()==='p';
  if(g('stWalk')==='y') return ['🟢 MINOR (green)','Walking wounded – direct to a collection point; re-triage'];
  if(g('stBreath')==='n') return peds&&g('stRR')==='pulse' ? ['🔴 IMMEDIATE (red)','JumpSTART: apneic with pulse → 5 rescue breaths; if breathing resumes → red'] : ['⚫ EXPECTANT / DECEASED (black)','No breathing after airway repositioning'+(peds?' (and no pulse / no response to 5 rescue breaths)':'')];
  if(g('stRR')==='hi') return ['🔴 IMMEDIATE (red)', peds?'RR < 15 or > 45':'RR > 30'];
  if(g('stPerf')==='bad') return ['🔴 IMMEDIATE (red)', peds?'No palpable peripheral pulse':'No radial pulse or capillary refill > 2 s – control bleeding'];
  if(g('stCmd')==='n') return ['🔴 IMMEDIATE (red)', peds?'AVPU: P (inappropriate) or U':'Cannot follow simple commands'];
  if(START_IDS.every(i=>g(i))) return ['🟡 DELAYED (yellow)','Serious but can wait; re-triage regularly'];
  return null; }
defCards('disaster','Disaster',[
 {id:'mci', title:'Mass-casualty triage (START / JumpSTART helper, SALT)', kw:'triage MCI mass casualty START JumpSTART SALT disaster tag', h:'🏷️ Mass-casualty triage',
  inputs: sel('stWalk','Walking?',[['','–'],['y','Yes'],['n','No']])+sel('stBreath','Breathing (after airway reposition)?',[['','–'],['y','Yes'],['n','No']])+
   sel('stRR','Respiratory rate',[['','–'],['ok','Adult ≤ 30 · Child 15–45'],['hi','Adult > 30 · Child < 15 or > 45'],['pulse','(Child, apneic) has peripheral pulse']])+
   sel('stPerf','Perfusion',[['','–'],['ok','Radial pulse present / CRT ≤ 2 s'],['bad','No radial pulse / CRT > 2 s']])+sel('stCmd','Mental status',[['','–'],['y','Follows commands (child: A, V, or appropriate P)'],['n','Does not (child: inappropriate P or U)']]),
  render:w=>{ const r=startTriage(); return (r?`<div class="big">${r[0]}</div>${nt(r[1])}`:nt(`Answer top to bottom; ${PU()==='p'?'JumpSTART (pediatric) logic active':'START (adult) logic active – switch to Pediatric mode for JumpSTART'}.`))+vt('ds-start')+
    ul(['Life-saving interventions allowed during triage: open airway, control major bleeding (tourniquet), decompress tension pneumothorax, autoinjector antidotes','<b>SALT</b>: Sort (walk / wave / still), Assess, Life-saving interventions, Treatment/Transport – adds an "expectant" category based on resources','Re-triage at every step (scene, casualty collection point, ED door); under-triage kills, over-triage overwhelms','Hospital: activate the code (e.g. Code Orange), incident command, surge beds, cancel elective cases, call-back lists; DOH HEMB / regional operations centre informed']); }},
 {id:'natdis', title:'Natural disasters: typhoon, flood (leptospirosis), earthquake (crush syndrome)', kw:'typhoon flood leptospirosis doxycycline earthquake crush syndrome volcano landslide evacuation', h:'🌀 Typhoons, floods, earthquakes',
  render:w=>h3('Typhoon / flood')+ul(['Injuries: lacerations, drowning, electrocution (downed lines), CO poisoning from generators ('+gto('co','Environmental: CO')+')','Infections 1–3 weeks later: <b>leptospirosis</b>, diarrhea/cholera, dengue, wound infections (Vibrio, Aeromonas), tetanus','Interrupted dialysis, insulin and TB/HIV medicines – plan supplies; evacuation-centre outbreaks (measles, ARI)'])+
   drugs(['dsDoxy'],w)+h3('Earthquake / collapse – crush syndrome')+
   ol([['drugstep',`Start IV fluid <b>before extrication</b>: 0.9% NaCl ~1 L/hr adult${P_(w,15,20)}${vt('ds-crush')}`],'After release: cardiac monitor – sudden hyperkalemia/arrhythmia; treat ('+gto('rnhyperk','hyperkalemia')+')',`Target urine output ~200–300 mL/hr in adults; if anuric, stop forcing fluids – dialysis${vt('ds-crush')}`,'Compartment syndrome: measure/suspect early; fasciotomy decisions by surgeon (infection risk in disaster settings)','Tetanus prophylaxis and wound care ('+gto('tetanus','tetanus table')+')'])+
   h3('Volcanic eruption (e.g. Taal, Mayon)')+ul(['Ash: respiratory irritation, asthma/COPD flares, eye abrasions – N95 masks, eye irrigation','Lahar/pyroclastic flow injuries: burns, inhalation injury, trauma'])},
 {id:'blast', title:'Bomb, blast & crush injuries', kw:'blast explosion bomb tympanic membrane blast lung primary secondary tertiary quaternary', h:'💥 Blast injuries',
  render:w=>tbl(['Mechanism','Typical injuries'],[['<b>Primary</b> – pressure wave','Blast lung, TM rupture, bowel perforation, eye globe rupture, TBI'],['<b>Secondary</b> – projectiles','Penetrating wounds anywhere (most common)'],['<b>Tertiary</b> – body thrown','Blunt trauma, fractures, amputations'],['<b>Quaternary</b> – everything else','Burns, crush, inhalation (smoke, CO, cyanide), psychological']])+
   ul(['Blast lung: hypoxia, hemoptysis, "butterfly" CXR; may appear up to 48 h; lung-protective ventilation, judicious fluids; air embolism risk with positive pressure','TM rupture alone does not rule in or out other primary blast injury; observe symptomatic patients ≥ 6–8 h (CXR, SpO₂)','Expect a surge of walking wounded to the nearest hospital before the severely injured arrive – keep resus bays free','Possible secondary device / contamination (dirty bomb) – security and radiation screening'])},
 {id:'chemdis', title:'Chemical disasters & decontamination (nerve agents, chlorine, ammonia)', kw:'chemical hazmat decontamination nerve agent sarin organophosphate chlorine ammonia pralidoxime', h:'☣️ Chemical incidents &amp; decontamination',
  render:w=>ol(['Protect staff first: PPE, zones (hot – warm/decontamination – cold), decontaminate <b>outside</b> the ED','Remove all clothing (removes most contamination), bag it, then copious water rinse ± mild soap 3–5 min; dry decontamination (blotting) for limited water','Life-saving care in the warm zone: airway, autoinjector antidotes, hemorrhage control'])+
   tbl(['Agent','Clues','Treatment'],[['Nerve agents / organophosphates','SLUDGE + miosis, bronchorrhea, fasciculations, seizures','Atropine to dry secretions, pralidoxime, benzodiazepine ('+gto('pest','Tox: pesticides')+')'],['Chlorine, ammonia (industrial, pool)','Eye/throat burning, cough, wheeze, delayed pulmonary edema','O₂, bronchodilators, observe 6–24 h'],['Cyanide (fires, industrial)','Sudden collapse, seizures, lactate > 8','Hydroxocobalamin ('+gto('antidotes','antidotes')+')'],['Vesicants (mustard)','Delayed blistering, eye, airway injury','Decontaminate early; burn-type care']])+
   drugs(['dsAtro','dsPam'],w)},
 {id:'radbio', title:'Radiation emergencies & bioterrorism', kw:'radiation acute radiation syndrome potassium iodide Prussian blue contamination anthrax smallpox plague bioterrorism PNRI', h:'☢️ Radiation &amp; biological threats',
  render:w=>h3('Radiation')+ul(['Life-threatening injuries first – contaminated patients rarely endanger staff with standard precautions; remove clothing (removes ~90% external contamination), wash skin, cover wounds','Acute radiation syndrome severity: time to vomiting &lt; 1 h and falling absolute lymphocyte count at 24–48 h = high dose; repeat CBC q6–12h','Internal contamination: potassium iodide (radioiodine only), Prussian blue (cesium/thallium), DTPA (plutonium/americium) – via national authority','PH: Philippine Nuclear Research Institute (PNRI) and DOH for advice'])+drugs(['dsKI'],w)+
   h3('Bioterrorism / unusual outbreaks')+ul(['Clues: clusters of severe illness in healthy people, unusual season/geography, simultaneous animal deaths','Inhalational anthrax (widened mediastinum, sepsis), plague (pneumonic – droplet precautions), smallpox (synchronous centrifugal vesicles – airborne/contact)','Isolate, notify DOH Epidemiology Bureau / RITM immediately; specimens via RITM'])},
 {id:'dssrc', title:'Disaster sources', h:'📚 Disaster sources', render:w=>nt('Romig, JumpSTART pediatric MCI triage · Lerner et al., SALT mass casualty triage (Disaster Med Public Health Prep 2008) · CDC Explosions and blast injuries primer · Sever &amp; Vanholder, ISN Renal Disaster Relief Task Force recommendations for crush casualties (NDT 2012) · DOH leptospirosis prevention/prophylaxis guidance · CHEMM (HHS) chemical emergencies · REMM (HHS) radiation emergency medical management · FDA potassium iodide guidance 2001 / WHO iodine thyroid blocking 2017 · WHO/DOH HEMB disaster health guidance. Tintinalli 9e Section 2 used only as a topic map.')}
]);
function P_(w,lo,hi){ return PU()==='p' ? ` · <b>child ${lo}–${hi} mL/kg/hr${ok(w)?` = ${fmt(lo*w)}–${fmt(hi*w)} mL/hr`:''}</b>` : ''; }
