// ======================= S19 EYE, EAR, NOSE, THROAT & ORAL =======================
// Sources: AAO Preferred Practice Patterns (2020–2023); AHA/ASA 2021 CRAO statement; AAP 2013 AOM; AAO-HNS sudden hearing loss 2019, Bell palsy 2013, epistaxis 2020;
// IADT dental trauma 2020; Difficult Airway Society/NTSP tracheostomy 2012; HAE WAO/EAACI 2021; IDSA 2012 pharyngitis.
Object.assign(REVIEW, {
  'ee-epig': {t:'Epiglottitis: ceftriaxone 2 g IV daily (peds 50 mg/kg, max 2 g) ± vancomycin if MRSA risk', r:'IDSA/expert; airway management takes priority.', tab:'EENT'},
  'ee-chem':  {t:'Chemical eye injury: irrigate immediately with ≥ 1–2 L (≥ 30 min) normal saline/Ringer’s lactate or tap water until pH 7.0–7.5 (recheck 20–30 min after stopping)', r:'AAO/ED consensus; alkali needs longer irrigation.', tab:'EENT'},
  'ee-aacg':  {t:'Acute angle-closure: timolol 0.5% 1 drop, apraclonidine/brimonidine 1 drop, pilocarpine 2% 1 drop every 15 min × 2 once IOP begins to fall, acetazolamide 500 mg IV/PO, ± mannitol 1–2 g/kg IV (or oral glycerol)', r:'AAO PPP 2020; avoid acetazolamide in sulfa allergy/sickle cell.', tab:'EENT'},
  'ee-canth': {t:'Retrobulbar hemorrhage with vision loss + IOP > 40 mmHg or proptosis/RAPD → lateral canthotomy and inferior cantholysis within ~ 90–120 min', r:'Expert consensus; ophthalmology may not arrive in time.', tab:'EENT'},
  'ee-open':  {t:'Open globe: rigid shield, NPO, antiemetic, analgesia, tetanus, IV antibiotics (e.g. vancomycin 15 mg/kg + ceftazidime 50 mg/kg, or adult levofloxacin 750 mg) – no pressure, no topical drops', r:'Regimens vary; ophthalmology preference.', tab:'EENT'},
  'ee-aom':   {t:'AOM: amoxicillin 80–90 mg/kg/day ÷ BID (max 4 g/day) × 10 d if < 2 y or severe, 5–7 d if older; penicillin allergy (non-anaphylactic) cefdinir/cefuroxime; observation option for non-severe AOM ≥ 2 y', r:'AAP 2013.', tab:'EENT / Pediatr'},
  'ee-ssnhl': {t:'Sudden sensorineural hearing loss (< 2 weeks): prednisone 1 mg/kg/day (max 60 mg) × 7–14 days then taper; ENT/audiology', r:'AAO-HNS 2019 (option); exclude stroke (vertigo + hearing loss).', tab:'EENT'},
  'ee-txa':   {t:'Epistaxis topical tranexamic acid: 500 mg (5 mL of 100 mg/mL) on pledget/packing for 10–15 min', r:'NoPAC trial 2021 found no benefit vs placebo for packing need; earlier trials positive – owner to decide.', tab:'EENT'},
  'ee-bell':  {t:'Bell palsy (within 72 h): prednisolone 50 mg daily × 10 days or 60 mg × 5 days then taper; antiviral (valacyclovir 1 g TID × 7 d) only as add-on for severe palsy; eye protection', r:'AAO-HNS 2013 / Cochrane.', tab:'EENT'},
  'ee-dent':  {t:'Odontogenic infection: amoxicillin 500 mg TID (or amoxicillin–clavulanate 875/125 BID) × 5–7 d with drainage; penicillin allergy clindamycin 300 mg QID; Ludwig angina: ampicillin–sulbactam 3 g IV q6h (or ceftriaxone 2 g + metronidazole 500 mg q8h)', r:'ADA 2019 / IDSA; clindamycin C. difficile risk.', tab:'EENT'},
  'ee-pta':   {t:'Peritonsillar abscess: needle aspiration or I&D; amoxicillin–clavulanate or clindamycin; single dexamethasone 10 mg IV (peds 0.6 mg/kg, max 10 mg) for pain/trismus', r:'Steroid evidence modest.', tab:'EENT'},
  'ee-ang':   {t:'ACE-inhibitor angioedema: stop ACEi; airway-first; icatibant 30 mg SC or FFP 2 units (evidence weak); hereditary angioedema: C1-INH 20 IU/kg IV or icatibant 30 mg SC', r:'WAO/EAACI 2021 (HAE); icatibant/C1-INH rarely stocked in PH EDs.', tab:'EENT'}
});
Object.assign(D, {
  eeAceta: {n:'Acetazolamide – acute angle closure', flag:'ee-aacg', a:[F('IV / PO','500 mg once, then 250 mg q6h PO')]},
  eeMann: {n:'Mannitol 20% – refractory IOP', flag:'ee-aacg', a:[B('IV over 30–60 min',1,2,'g/kg',{conc:0.2})]},
  eeAmox: {n:'Amoxicillin – acute otitis media', flag:'ee-aom', a:[F('PO','500 mg – 1 g TID × 5–7 d (adult AOM/sinusitis)')], p:[B('PO BID (80–90 mg/kg/day)',40,45,'mg/kg',{max:2000,note:'× 10 d if < 2 y or severe; 5–7 d if ≥ 6 y non-severe.'})]},
  eePred: {n:'Prednisone – sudden SNHL / Bell palsy', flag:'ee-ssnhl', a:[F('Sudden SNHL','60 mg PO daily × 7–14 d, then taper'),F('Bell palsy','Prednisolone 50 mg daily × 10 d (or 60 mg × 5 d then taper)',{flag:'ee-bell'})], p:[B('PO daily',1,1,'mg/kg',{max:60})]},
  eeTxa: {n:'Tranexamic acid – topical for epistaxis', flag:'ee-txa', b:[F('Topical','500 mg (5 mL of 100 mg/mL) soaked pledget, 10–15 min')]},
  eeDent: {n:'Odontogenic infection', flag:'ee-dent', a:[F('Outpatient','Amoxicillin 500 mg PO TID (or amoxicillin–clavulanate 875/125 BID) × 5–7 d'),F('Ludwig / deep neck','Ampicillin–sulbactam 3 g IV q6h')], p:[B('Amoxicillin PO TID',15,15,'mg/kg',{max:500}),B('Ampicillin–sulbactam IV q6h (ampicillin)',50,50,'mg/kg',{max:2000})]},
  eeDex: {n:'Dexamethasone – pharyngitis/PTA pain, airway edema', flag:'ee-pta', a:[F('IV/PO','10 mg single dose')], p:[B('IV/PO',0.6,0.6,'mg/kg',{max:10})]},
  eeIcat: {n:'Icatibant / C1-esterase inhibitor (bradykinin angioedema)', flag:'ee-ang', a:[F('Icatibant SC','30 mg'),F('C1-INH (plasma-derived) IV','20 IU/kg'),F('Fresh frozen plasma','2 units (if nothing else)')]}
});
defCards('eent','EENT',[
 {id:'eye', title:'Eye emergencies: chemical burn, CRAO, angle closure, open globe, retrobulbar hematoma, red eye', kw:'eye red eye chemical burn irrigation CRAO central retinal artery angle closure glaucoma open globe retrobulbar canthotomy corneal abrasion orbital cellulitis vision loss', h:'👁️ Eye emergencies',
  render:w=>nt('Always record visual acuity (each eye, with glasses/pinhole) – it is the vital sign of the eye.')+
   ol([['shock',`<b>Chemical injury</b> (alkali worst – cement, lye, drain cleaner): irrigate <b>before</b> anything else; topical anesthetic, eyelid speculum/Morgan lens; check pH${vt('ee-chem')}`],
     ['shock','<b>Sudden painless monocular vision loss</b> = CRAO until proven otherwise: stroke pathway, urgent ophthalmology/stroke team (thrombolysis within 4.5 h in some centres), check ESR/CRP for giant cell arteritis if &gt; 50 y'],
     `<b>Acute angle closure</b>: painful red eye, halos, mid-dilated fixed pupil, rock-hard globe, vomiting – IOP-lowering drops + acetazolamide; laser iridotomy${vt('ee-aacg')}`,
     `<b>Open globe</b>: peaked pupil, Seidel positive, 360° subconjunctival hemorrhage – shield, no pressure, antibiotics, CT, surgery${vt('ee-open')}`,
     `<b>Retrobulbar hemorrhage</b>: proptosis, tense orbit, vision loss after trauma – lateral canthotomy now${vt('ee-canth')}`])+drugs(['eeAceta','eeMann'],w)+
   tbl(['Red eye','Clue','Action'],[['Corneal abrasion','FB sensation, fluorescein uptake','Topical antibiotic; no patching; contact lens → antipseudomonal drops, no lens'],['Keratitis / corneal ulcer','White infiltrate, contact lens','Same-day ophthalmology'],['Herpes zoster ophthalmicus','Rash on nose tip (Hutchinson)','Oral antiviral, ophthalmology'],['Orbital cellulitis','Pain on eye movement, proptosis, ↓ vision','IV antibiotics, CT, ENT/ophtho'],['Conjunctivitis','Discharge, normal vision','Hygiene; antibiotics if bacterial; hyperacute purulent → gonococcal']])},
 {id:'ear', title:'Ear disorders: otitis media/externa, mastoiditis, sudden hearing loss, foreign body', kw:'ear otitis media externa mastoiditis hearing loss sudden sensorineural foreign body insect button battery', h:'👂 Ear disorders',
  render:w=>ul([`<b>AOM</b>: bulging TM; amoxicillin high dose or observation in selected children${vt('ee-aom')}`,'<b>Otitis externa</b>: topical fluoroquinolone drops (safe with perforation), wick if canal swollen; diabetic/elderly with severe pain + granulation tissue = <b>malignant otitis externa</b> → IV antipseudomonal, CT','<b>Mastoiditis</b>: post-auricular swelling, protruding ear – IV antibiotics, CT, ENT',`<b>Sudden sensorineural hearing loss</b>: Weber lateralises to good ear – steroids within 2 weeks, urgent ENT; with vertigo/neuro signs consider posterior circulation stroke${vt('ee-ssnhl')}`,'<b>Foreign body</b>: live insect – drown with lidocaine/mineral oil first; button battery = emergency removal; do not irrigate vegetable matter','TM perforation (trauma/barotrauma): keep dry, most heal in weeks'])+drugs(['eeAmox','eePred'],w)},
 {id:'nose', title:'Epistaxis & nasal emergencies (septal hematoma, nasal fracture, sinusitis)', kw:'epistaxis nosebleed tranexamic packing cautery posterior bleed septal hematoma nasal fracture sinusitis', h:'👃 Epistaxis &amp; nose',
  render:w=>ol(['Sit up, lean forward, firm pressure on the soft nose for <b>10–15 min</b> uninterrupted; ice to the bridge','Clear clots, topical vasoconstrictor + anesthetic (oxymetazoline/phenylephrine + lidocaine) for 10 min; identify the site',`Visible anterior site: silver nitrate cautery (one side of the septum only); topical tranexamic acid option${vt('ee-txa')}`,'Persistent: anterior packing (nasal tampon/balloon) for 48–72 h; antibiotic prophylaxis not routinely needed','Posterior bleed (bilateral, down the throat despite anterior pack): double-balloon or Foley catheter, admit, ENT – risk of hypoxia/aspiration'])+drugs(['eeTxa'],w)+
   ul(['Anticoagulated: usually continue unless life-threatening; check INR; reverse only for severe bleeding','Hypertension often reflects anxiety/pain – treat the bleed first','<b>Septal hematoma</b> after nasal trauma (boggy purple swelling): drain the same day to prevent septal necrosis/abscess','Nasal fracture: reduce within 5–10 days after swelling settles (ENT); CSF rhinorrhea → CT','Acute sinusitis: mostly viral; antibiotics if &gt; 10 days, severe, or worsening after improvement; orbital/intracranial complications are emergencies'])},
 {id:'oral', title:'Oral & dental emergencies: avulsed tooth, dental abscess, Ludwig angina, post-extraction bleeding', kw:'dental tooth avulsion reimplant abscess Ludwig angina toothache extraction bleeding dry socket', h:'🦷 Oral &amp; dental',
  render:w=>ul(['<b>Avulsed permanent tooth</b>: hold by the crown, rinse briefly, reimplant immediately (best &lt; 60 min); otherwise store in milk/saliva/saline; splint and dentist; <b>never reimplant primary (baby) teeth</b>','Dental fractures: exposed pulp (pink/bleeding) → urgent dentist; cover dentin','Dental abscess: drainage + antibiotics; facial swelling crossing midline, trismus, floor-of-mouth swelling, voice change → <b>Ludwig angina</b>: airway (awake fibreoptic/surgical), IV antibiotics, CT, OR','Post-extraction bleeding: bite on gauze (or gauze soaked in tranexamic acid) 20–30 min, local anesthetic with epinephrine, sutures, check anticoagulants','Dry socket (2–4 days after extraction): irrigate, medicated dressing, analgesia (not an infection)'])+drugs(['eeDent'],w)},
 {id:'neckair', title:'Neck & upper airway: angioedema, epiglottitis, peritonsillar/retropharyngeal abscess, tracheostomy emergencies', kw:'angioedema ACE inhibitor hereditary icatibant epiglottitis peritonsillar abscess quinsy retropharyngeal deep neck infection tracheostomy blocked displaced', h:'🗣️ Neck &amp; upper airway',
  render:w=>ol([['shock','Upper-airway threat (stridor, drooling, tripod, muffled voice): keep patient upright and calm, call the most experienced airway operator, prepare for awake fibreoptic intubation and front-of-neck access; avoid lying flat or provoking with tongue depressors in children'],
    `<b>Angioedema</b>: allergic (urticaria, itching) → IM epinephrine (${gto('anaph','anaphylaxis')}); ACE-inhibitor/hereditary (no urticaria) → bradykinin-mediated: epinephrine works poorly; icatibant/C1-INH/FFP; airway early if tongue/floor of mouth/voice involved${vt('ee-ang')}`,
    '<b>Epiglottitis</b> (adults now more common than children – Hib vaccination): sore throat out of proportion, thumb sign on lateral neck X-ray; ceftriaxone 2 g IV (peds 50 mg/kg), airway in OR/resus room'+vt('ee-epig'),
    `<b>Peritonsillar abscess</b>: trismus, uvular deviation, "hot potato" voice – aspiration/drainage, antibiotics, steroid${vt('ee-pta')}`,'<b>Retropharyngeal/deep neck abscess</b>: fever, neck stiffness/torticollis, dysphagia – CT neck, IV antibiotics, ENT drainage'])+drugs(['eeDex','eeIcat'],w)+
   h3('Tracheostomy / laryngectomy emergency (NTSP approach)')+ul(['Apply high-flow O₂ to <b>face and stoma</b>; capnography; is the patient breathing?','Laryngectomy = neck breather only – oxygenate via stoma, cannot intubate from above','Blocked/displaced tube: remove inner cannula, pass suction catheter; if it will not pass → deflate cuff → remove tube; oxygenate via stoma (or orally if patent upper airway)','Reinsert a new tube (same size or smaller) via stoma – bougie/fibreoptic; oral intubation if upper airway intact'])},
 {id:'face', title:'Face & jaw: Bell palsy, TMJ dislocation, mandible fracture, facial infections', kw:'Bell palsy facial nerve TMJ dislocation jaw mandible fracture parotitis', h:'😶 Face &amp; jaw',
  render:w=>ul([`<b>Bell palsy</b>: forehead involved (peripheral); steroids within 72 h; eye protection (lubricant, tape at night); forehead sparing = central lesion → stroke pathway${vt('ee-bell')}`,'Look for Ramsay Hunt (vesicles in ear – add antiviral), Lyme, otitis media, parotid tumour','<b>TMJ dislocation</b>: open locked jaw – reduce with thumbs on molars (wrapped), downward then backward pressure; procedural sedation if needed','<b>Mandible fracture</b>: malocclusion, step, sublingual hematoma; open fractures (into mouth) need antibiotics and maxillofacial referral','<b>Acute suppurative parotitis</b> (elderly, dehydrated): antistaphylococcal antibiotics, hydration, sialogogues'])+drugs(['eePred'],w)},
 {id:'eesrc', title:'EENT sources', h:'📚 EENT sources', render:w=>nt('American Academy of Ophthalmology Preferred Practice Patterns (angle-closure, conjunctivitis, corneal edema/opacification) · Mac Grory et al., AHA scientific statement on CRAO 2021 · Lieberthal et al., AAP AOM guideline 2013 · Chandrasekhar et al., AAO-HNS sudden hearing loss 2019 · Baugh et al., AAO-HNS Bell palsy 2013 · Tunkel et al., AAO-HNS epistaxis 2020 · Reuben et al., NoPAC trial (Lancet Resp Med 2021) · Fouad et al., IADT dental trauma guidelines 2020 · McGrath et al., NTSP tracheostomy/laryngectomy algorithms 2012 · Maurer et al., WAO/EAACI HAE guideline 2021 · Shulman et al., IDSA pharyngitis 2012. Tintinalli 9e Section 19 used only as a topic map.')}
]);
