// ======================= S9 GASTROINTESTINAL DISORDERS =======================
// Sources: ACG 2021 upper GI & ulcer bleeding; ESGE 2021 NVUGIH; Baveno VII 2022; AASLD 2021 ascites/SBP & 2014 HE; ACG 2024 acute pancreatitis; WATERFALL 2022;
// Tokyo Guidelines 2018; WSES appendicitis 2020; AGA 2021 diverticulitis; WHO/UNICEF diarrhoea & zinc 2004/2017; WHO typhoid 2018; PH DOH typhoid/cholera guidance; HALT-IT 2020.
Object.assign(REVIEW, {
  'gi-ppi':   {t:'Ulcer bleeding PPI: pantoprazole/esomeprazole 80 mg IV bolus then 40 mg IV BID (or 8 mg/hr infusion × 72 h after endoscopic therapy)', r:'ACG 2021 accepts intermittent high-dose; pre-endoscopy PPI downstages lesions but no mortality benefit.', tab:'GI'},
  'gi-var':   {t:'Suspected variceal bleed: octreotide 50 mcg IV bolus then 50 mcg/hr × 2–5 days (or terlipressin 2 mg IV q4h); ceftriaxone 1 g IV daily (max 7 days); endoscopy ≤ 12 h; restrictive transfusion (Hb 7–8)', r:'Baveno VII 2022.', tab:'GI'},
  'gi-erythro':{t:'Erythromycin 250 mg IV over 30 min, 30–120 min before endoscopy (improves visualisation)', r:'ESGE/ACG; QT caution.', tab:'GI'},
  'gi-gbs':   {t:'Glasgow-Blatchford score ≤ 1 (ACG: ≤ 1; ESGE: ≤ 1) → very low risk, outpatient management possible', r:'Thresholds differ slightly between guidelines; some use 0 only.', tab:'GI'},
  'gi-txfx':  {t:'Restrictive transfusion: Hb threshold 7 g/dL (8 g/dL with cardiovascular disease); aim 7–9 g/dL', r:'ACG 2021 / AABB 2023.', tab:'GI / Heme'},
  'gi-panc':  {t:'Acute pancreatitis fluids: moderate goal-directed lactated Ringer’s – 10 mL/kg bolus only if hypovolemic, then 1.5 mL/kg/hr, reassess at 12, 24, 48 h', r:'WATERFALL 2022 / ACG 2024; aggressive fluids harmful.', tab:'GI'},
  'gi-abx':   {t:'Intra-abdominal infection: ceftriaxone 2 g IV daily + metronidazole 500 mg IV q8h; severe/healthcare-associated: piperacillin–tazobactam 4.5 g IV q6h', r:'IDSA/SIS 2010/2017, Tokyo 2018 for biliary; local antibiogram governs.', tab:'GI'},
  'gi-he':    {t:'Hepatic encephalopathy: lactulose 20–30 mL (13–20 g) PO/NG q1–2h until bowel movement, then titrate to 2–3 soft stools/day (or enema 300 mL in 700 mL water); add rifaximin 550 mg BID', r:'AASLD/EASL 2014.', tab:'GI'},
  'gi-sbp':   {t:'SBP: ascitic PMN ≥ 250 cells/mm³ → cefotaxime 2 g IV q8h or ceftriaxone 2 g daily; albumin 1.5 g/kg day 1 and 1 g/kg day 3 if creatinine > 1 mg/dL, BUN > 30 or bilirubin > 4', r:'AASLD 2021.', tab:'GI'},
  'gi-anti':  {t:'Antiemetics: ondansetron 4–8 mg IV/PO (peds 0.15 mg/kg, max 4 mg IV; ODT 2 mg 8–15 kg, 4 mg 15–30 kg, 8 mg > 30 kg); metoclopramide 10 mg IV over 2 min; promethazine not < 2 y', r:'Common ED dosing; QT prolongation with ondansetron.', tab:'GI'},
  'gi-ors':   {t:'Dehydration (WHO): Plan A home ORS; Plan B 75 mL/kg ORS over 4 h; Plan C (severe) Ringer’s lactate 100 mL/kg – infants 30 mL/kg in 1 h then 70 mL/kg in 5 h; older 30 mL/kg in 30 min then 70 mL/kg in 2.5 h; zinc 20 mg/day × 10–14 d (10 mg if < 6 months)', r:'WHO 2005 Treatment of diarrhoea; cholera adults may need more.', tab:'GI / Pediatr'},
  'gi-diarabx':{t:'Diarrhea antibiotics: cholera – azithromycin 1 g single dose (peds 20 mg/kg) or doxycycline 300 mg; shigellosis – azithromycin 500 mg × 3 d (peds 10 mg/kg/d); typhoid (uncomplicated) – azithromycin 1 g day 1 then 500 mg daily × 6 d (peds 20 mg/kg/d), severe – ceftriaxone 2 g IV daily (peds 50–80 mg/kg); amoebic dysentery – metronidazole 500–750 mg TID × 7–10 d', r:'WHO / DOH PH; rising azithromycin and fluoroquinolone resistance – follow RITM/ARSP data.', tab:'GI / Infectious'},
  'gi-alv':   {t:'Alvarado score: ≤ 4 appendicitis unlikely; 5–6 equivocal (imaging); ≥ 7 likely (surgical review)', r:'WSES 2020 prefers AIR/AAS scores; Alvarado less accurate in women and children.', tab:'GI'},
  'gi-food':  {t:'Esophageal food impaction: endoscopy within 24 h, within 6 h if complete obstruction (drooling) or sharp object/battery; glucagon not recommended', r:'ESGE 2016 / ASGE 2011.', tab:'GI'}
});
Object.assign(D, {
  giPpi: {n:'Proton-pump inhibitor – upper GI bleed', flag:'gi-ppi', a:[F('IV','80 mg bolus, then 40 mg IV BID (or 8 mg/hr after endoscopic therapy)')], p:[B('IV',1,2,'mg/kg',{max:80,note:'Then 1 mg/kg q12h (max 40 mg). Pediatric GI input.'})]},
  giOct: {n:'Octreotide – variceal bleeding', flag:'gi-var', a:[F('IV','50 mcg bolus, then 50 mcg/hr infusion × 2–5 days')], p:[B('IV bolus',1,1,'mcg/kg',{max:50,note:'Then 1 mcg/kg/hr (max 50 mcg/hr).'})]},
  giTerli: {n:'Terlipressin (if available)', flag:'gi-var', a:[F('IV','2 mg q4h × 24–48 h, then 1 mg q4h',{note:'Ischemia risk – avoid in coronary/peripheral vascular disease.'})]},
  giCef: {n:'Ceftriaxone – cirrhosis with GI bleed', flag:'gi-var', a:[F('IV','1 g daily (max 7 days)')], p:[B('IV daily',50,50,'mg/kg',{max:1000})]},
  giErythro: {n:'Erythromycin – pre-endoscopy', flag:'gi-erythro', a:[F('IV over 30 min','250 mg, 30–120 min before endoscopy')], p:[B('IV',3,3,'mg/kg',{max:250})]},
  giAbx: {n:'Intra-abdominal / biliary infection', flag:'gi-abx', a:[F('Community, mild–moderate','Ceftriaxone 2 g IV daily + metronidazole 500 mg IV q8h'),F('Severe / healthcare-associated','Piperacillin–tazobactam 4.5 g IV q6h')],
    p:[B('Ceftriaxone IV daily',50,75,'mg/kg',{max:2000}),B('+ Metronidazole IV q8h',10,10,'mg/kg',{max:500})]},
  giLact: {n:'Lactulose – hepatic encephalopathy', flag:'gi-he', a:[F('PO / NG','20 – 30 mL q1–2h until bowel movement, then 2–3 soft stools/day'),F('Enema','300 mL lactulose + 700 mL water, retained 30–60 min')]},
  giAlb: {n:'Albumin – SBP (day 1 / day 3)', flag:'gi-sbp', a:[C('IV',w=>ok(w)?{main:`Day 1: ${fmt(1.5*w)} g · Day 3: ${fmt(w)} g`,lines:['1.5 g/kg day 1, 1 g/kg day 3 (20% or 25% albumin)']}:{main:'Enter weight',lines:['1.5 g/kg day 1, 1 g/kg day 3']})]},
  giOnd: {n:'Ondansetron', flag:'gi-anti', a:[F('IV / PO / ODT','4 – 8 mg q8h')], p:[B('IV',0.15,0.15,'mg/kg',{max:4}),C('ODT by weight',w=>({main: ok(w)?(w<8?'Not for < 8 kg / < 6 mo':w<15?'2 mg':w<30?'4 mg':'8 mg'):'2 mg (8–15 kg) · 4 mg (15–30 kg) · 8 mg (> 30 kg)',lines:[]}))]},
  giMeto: {n:'Metoclopramide', flag:'gi-anti', a:[F('IV over ≥ 2 min','10 mg (akathisia: slow infusion; diphenhydramine)')], p:[B('IV',0.1,0.15,'mg/kg',{max:10,note:'Dystonia risk higher in children.'})]},
  giOrs: {n:'Rehydration (WHO plans B and C)', flag:'gi-ors', b:[C('Volumes',w=>{ if(!ok(w)) return {main:'Enter weight',lines:['Plan B: 75 mL/kg ORS over 4 h','Plan C: 100 mL/kg Ringer’s lactate']};
     const y=ageYears(), inf = y!=null && y<1; return {main:`Plan B: ${fmt(75*w)} mL ORS over 4 h`,lines:[`Plan C (severe): ${fmt(30*w)} mL RL over ${inf?'1 h':'30 min'}, then ${fmt(70*w)} mL over ${inf?'5 h':'2.5 h'} (100 mL/kg)`,'Reassess every 1–2 h; give ORS as soon as able to drink']}; })]},
  giZinc: {n:'Zinc (children with diarrhea)', flag:'gi-ors', p:[C('PO daily × 10–14 days',w=>{ const y=ageYears(); return {main: y!=null&&y<0.5?'10 mg':'20 mg', lines:['< 6 months 10 mg; ≥ 6 months 20 mg']}; })]},
  giAzi: {n:'Azithromycin – cholera / shigella / typhoid', flag:'gi-diarabx', a:[F('Cholera','1 g PO single dose'),F('Shigella','500 mg PO daily × 3 days'),F('Typhoid (uncomplicated)','1 g day 1, then 500 mg daily × 6 days')],
    p:[B('Cholera single dose',20,20,'mg/kg',{max:1000}),B('Typhoid daily × 7 d',20,20,'mg/kg',{max:1000}),B('Shigella daily × 3 d',10,10,'mg/kg',{max:500})]},
  giMetro: {n:'Metronidazole – amoebic colitis / liver abscess', flag:'gi-diarabx', a:[F('PO / IV','500 – 750 mg TID × 7–10 days, then luminal agent (paromomycin/diloxanide)')], p:[B('PO TID',10,15,'mg/kg',{max:750})]}
});
const GBS_IDS=['gbBun','gbHb','gbSbp','gbHr','gbMel','gbSyn','gbLiv','gbHf'];
const ALV=[['alv_mig','Migratory pain to RLQ',1],['alv_ano','Anorexia',1],['alv_nv','Nausea / vomiting',1],['alv_rlq','RLQ tenderness',2],['alv_reb','Rebound tenderness',1],['alv_fev','Temperature ≥ 37.3 °C',1],['alv_wbc','WBC > 10 × 10⁹/L',2],['alv_shift','Neutrophils > 75%',1]];
defCards('gi','GI',[
 {id:'abdpain', title:'Acute abdominal pain – red flags, appendicitis (Alvarado), surgical emergencies', kw:'abdominal pain appendicitis Alvarado mesenteric ischemia perforation obstruction volvulus diverticulitis hernia', h:'🫃 Acute abdominal pain',
  inputs: ALV.map(([id,t,p])=>ck(id,`${t} (+${p})`)).join(''),
  render:w=>{ const s=ALV.reduce((a,[id,,p])=>a+(nc(id)?p:0),0); return score(s,10,'Alvarado score'+vt('gi-alv'))+`<div class="big">${s>=7?'<span class="due">≥ 7: appendicitis likely – surgical review</span>':s>=5?'<span class="soon">5–6: equivocal – ultrasound (children/pregnancy) or CT</span>':'≤ 4: appendicitis unlikely (not excluded)'}</div>`+
   ul(['Always: pregnancy test in women of reproductive age, ECG in older patients (MI presents as epigastric pain), glucose, lipase, urinalysis','<b>Elderly / immunosuppressed / diabetics</b>: blunted signs – low threshold for CT; high mortality','<b>Pain out of proportion to exam</b> (AF, vascular disease): mesenteric ischemia → CT angiography; lactate rises late','<b>Sudden severe pain + shock</b>: ruptured AAA ('+gto('aorta','aorta card')+'), perforated viscus (erect CXR/CT free air), ectopic ('+gto('obearly','OB early pregnancy')+')','<b>Bowel obstruction</b>: CT, NG decompression, IV fluids; strangulation (fever, peritonism, lactate) → surgery; sigmoid volvulus → endoscopic decompression','<b>Incarcerated hernia</b>: gentle reduction with analgesia if &lt; 6–12 h and no signs of strangulation','<b>Diverticulitis</b>: uncomplicated in immunocompetent patients may not need antibiotics (AGA 2021); abscess/perforation → CT, antibiotics, drainage','Early analgesia does not mask surgical diagnoses'])+drugs(['giAbx'],w); }},
 {id:'ugib', title:'Upper GI bleeding – Glasgow-Blatchford score, PPI, variceal bundle', kw:'upper GI bleed hematemesis melena Blatchford variceal octreotide terlipressin PPI pantoprazole endoscopy cirrhosis', h:'🩸 Upper GI bleeding',
  inputs: sel('gbBun','BUN / urea',[['0','< 18.2 mg/dL (< 6.5 mmol/L) · 0'],['2','18.2–22.3 (6.5–7.9) · 2'],['3','22.4–27.9 (8–9.9) · 3'],['4','28–69.9 (10–24.9) · 4'],['6','≥ 70 (≥ 25) · 6']])+
    sel('gbHb','Hemoglobin (g/dL)',[['0','Men ≥ 13 / women ≥ 12 · 0'],['1','Men 12–12.9 / women 10–11.9 · 1'],['3','Men 10–11.9 · 3'],['6','< 10 (either) · 6']])+
    sel('gbSbp','Systolic BP',[['0','≥ 110 · 0'],['1','100–109 · 1'],['2','90–99 · 2'],['3','< 90 · 3']])+
    ck('gbHr2','Pulse ≥ 100 (+1)')+ck('gbMel2','Melena (+1)')+ck('gbSyn2','Syncope (+2)')+ck('gbLiv2','Hepatic disease (+2)')+ck('gbHf2','Cardiac failure (+2)'),
  render:w=>{ const s=['gbBun','gbHb','gbSbp'].reduce((a,i)=>a+(parseInt(sv(i),10)||0),0)+(nc('gbHr2')?1:0)+(nc('gbMel2')?1:0)+(nc('gbSyn2')?2:0)+(nc('gbLiv2')?2:0)+(nc('gbHf2')?2:0);
   return score(s,23,'Glasgow-Blatchford')+`<div class="big">${s<=1?'<span class="okc">≤ 1: very low risk – outpatient endoscopy may be appropriate</span>':s>=8?'<span class="due">High risk – admit, early endoscopy, consider ICU</span>':'<span class="soon">Admit for endoscopy within 24 h</span>'}${vt('gi-gbs')}</div>`+
   ol([['shock','Two large-bore IVs, crossmatch, crystalloid to perfusion; activate '+gto('mtp','MTP')+' if exsanguinating; protect airway in massive hematemesis/encephalopathy'],`Transfuse to Hb 7 g/dL (8 with cardiovascular disease)${vt('gi-txfx')}; reverse anticoagulants (${gto('antidotes','PCC / vitamin K')}); platelets if &lt; 50 × 10⁹/L and bleeding`,'Suspected varices (cirrhosis, stigmata): vasoactive drug + antibiotic <b>before</b> endoscopy; endoscopy within 12 h; balloon tamponade (Sengstaken/Minnesota) as a bridge','Non-variceal: endoscopy within 24 h after resuscitation; PPI; tranexamic acid <b>not</b> recommended (HALT-IT)'])+drugs(['giPpi','giOct','giTerli','giCef','giErythro'],w)+
   ul(['Lower GI bleeding: most stop spontaneously; unstable → CT angiography then embolisation/colonoscopy; an upper source causes ~10–15% of brisk hematochezia (check BUN:Cr, consider NG aspirate/endoscopy)']); }},
 {id:'pancbil', title:'Pancreatitis, biliary colic, cholecystitis & cholangitis', kw:'pancreatitis lipase lactated Ringer cholecystitis cholangitis Charcot Tokyo gallstone biliary colic', h:'🟡 Pancreas &amp; biliary tree',
  render:w=>h3('Acute pancreatitis (revised Atlanta: 2 of pain, lipase ≥ 3× ULN, imaging)')+ol([`<b>Moderate fluids</b>: lactated Ringer’s – bolus 10 mL/kg only if hypovolemic, then 1.5 mL/kg/hr${ok(w)?` (= ${fmt(1.5*w)} mL/hr)`:''}${vt('gi-panc')}`,'Analgesia (opioids acceptable), early oral feeding as tolerated; no prophylactic antibiotics','Causes: gallstones (ultrasound), alcohol, triglycerides &gt; 1,000 mg/dL, hypercalcemia, drugs, post-ERCP; urgent ERCP only with cholangitis','Severity: persistent organ failure &gt; 48 h = severe; SIRS, BUN rise and hematocrit rise predict poor outcome'])+
   h3('Biliary')+tbl(['Condition','Key features','Action'],[['Biliary colic','RUQ pain &lt; 6 h, no fever, normal labs','Analgesia (NSAID), elective surgery'],['Acute cholecystitis','Pain &gt; 6 h, fever, Murphy sign, US wall thickening/fluid','Antibiotics, early laparoscopic cholecystectomy (&lt; 72 h)'],['Acute cholangitis','Fever + jaundice + RUQ pain (Charcot) ± shock/confusion','Antibiotics + fluids; biliary drainage (ERCP) urgently if severe (Tokyo 2018)']])+drugs(['giAbx'],w)},
 {id:'liver', title:'Liver disease: hepatic encephalopathy, SBP, acute liver failure, amoebic abscess', kw:'cirrhosis hepatic encephalopathy lactulose rifaximin ascites SBP paracentesis albumin acute liver failure hepatitis amoebic liver abscess', h:'🟤 Liver emergencies',
  render:w=>ul(['<b>Hepatic encephalopathy</b>: find the trigger (GI bleed, infection/SBP, constipation, hypokalemia, sedatives); lactulose ± rifaximin; protect airway if grade 3–4','<b>SBP</b>: diagnostic paracentesis in every admitted cirrhotic with ascites (PMN ≥ 250/mm³); antibiotics + albumin','<b>Acute liver failure</b> (INR ≥ 1.5 + encephalopathy, no prior cirrhosis): ICU, NAC for acetaminophen and some non-acetaminophen causes, glucose monitoring, early transplant-centre contact','<b>Hepatitis</b> A and E (water-borne, common in PH), B (HBsAg high prevalence in PH) – check INR, bilirubin, glucose','<b>Amoebic liver abscess</b> (PH): fever, RUQ pain, single right-lobe abscess – metronidazole; aspirate if large/left lobe/no response'])+drugs(['giLact','giAlb','giMetro'],w)+nt('SBP antibiotics: cefotaxime 2 g IV q8h or ceftriaxone 2 g daily'+vt('gi-sbp')+'.')},
 {id:'nvd', title:'Nausea, vomiting, diarrhea & dehydration (ORS, zinc, cholera, typhoid)', kw:'vomiting diarrhea gastroenteritis dehydration ORS oral rehydration zinc cholera shigella typhoid amoebiasis ondansetron metoclopramide', h:'🚽 Vomiting, diarrhea &amp; dehydration',
  render:w=>drugs(['giOnd','giMeto'],w)+h3('Rehydration')+drugs(['giOrs','giZinc'],w)+
   ul(['Red flags: bloody diarrhea with fever (shigella/amoebiasis), rice-water stools with severe dehydration (cholera – notify DOH), prolonged fever with relative bradycardia (typhoid), recent antibiotics (C. difficile), immunosuppression','Avoid loperamide in bloody/febrile diarrhea and in children','Food poisoning within 1–6 h of eating (Staph aureus, Bacillus cereus "fried rice") – supportive','Persistent vomiting: check glucose, electrolytes, pregnancy, DKA, bowel obstruction, raised ICP, cannabis hyperemesis (hot showers; haloperidol/capsaicin)'])+drugs(['giAzi','giMetro'],w)},
 {id:'esoanor', title:'Esophageal emergencies, anorectal disorders & GI devices', kw:'food bolus impaction esophagus Boerhaave caustic hemorrhoid anal fissure perianal abscess PEG tube gastrostomy', h:'🍖 Esophagus, anorectum &amp; GI devices',
  render:w=>h3('Esophagus')+ul([`Food bolus: able to swallow saliva → observe briefly; drooling/complete obstruction → endoscopy within 6 h${vt('gi-food')}`,'Button battery or magnets: emergency (see '+gto('toxmisc','Tox: button battery')+')','Boerhaave (forceful vomiting → chest pain, subcutaneous emphysema): CT with oral contrast, NPO, broad antibiotics, surgery','Caustic ingestion: no emesis/neutralisation; airway; endoscopy 12–24 h'])+
   h3('Anorectal')+ul(['Thrombosed external hemorrhoid &lt; 72 h: excision under local anesthesia; later → conservative (sitz baths, stool softeners)','Anal fissure: fibre, sitz baths, topical nifedipine/GTN','Perianal abscess: incision and drainage; perirectal/ischiorectal or diabetics/immunosuppressed → surgeon; Fournier gangrene = emergency'])+
   h3('Devices &amp; post-op')+ul(['Dislodged gastrostomy (PEG) tube: tract may close within hours – insert a Foley/replacement promptly if tract &gt; 4–6 weeks old; confirm position with contrast if new tract','Post-op fever: wound, urine, lungs, DVT/PE, anastomotic leak (tachycardia, peritonism days 3–7)'])},
 {id:'gisrc', title:'GI sources', h:'📚 GI sources', render:w=>nt('Laine et al., ACG clinical guideline: upper GI and ulcer bleeding 2021 · Gralnek et al., ESGE NVUGIH 2021 · de Franchis et al., Baveno VII 2022 · Biggins et al., AASLD guidance on ascites, SBP, HRS 2021 · Vilstrup et al., AASLD/EASL hepatic encephalopathy 2014 · Tenner et al., ACG acute pancreatitis 2024 · de-Madaria et al., WATERFALL trial (NEJM 2022) · Tokyo Guidelines 2018 · Di Saverio et al., WSES Jerusalem appendicitis guidelines 2020 · Peery et al., AGA diverticulitis 2021 · WHO The treatment of diarrhoea (2005) · WHO typhoid vaccines/treatment notes · HALT-IT trial 2020 · ESGE foreign body removal 2016. Tintinalli 9e Section 9 used only as a topic map.')}
]);
