// ======================= S18 HEMATOLOGIC & ONCOLOGIC DISORDERS =======================
// Sources: AABB 2023 RBC transfusion & 2015 platelet guidelines; BSH; WFH guidelines for hemophilia 2020; NHLBI/ASH vWD 2021; ASH 2020 VTE/DOAC reversal;
// ACC 2020 ECDP bleeding on oral anticoagulants; IDSA 2010 / ASCO-IDSA 2018 febrile neutropenia; Cairo-Bishop TLS; ESMO/ASCO; ISTH TTP 2020; ASH HIT 2018;
// PH newborn screening (RA 9288) G6PD data.
Object.assign(REVIEW, {
  'hm-txfx':  {t:'Transfusion: 1 unit PRBC raises Hb ~1 g/dL in adults; children 10–15 mL/kg raises Hb ~2–3 g/dL; platelets: prophylactic < 10 × 10⁹/L, procedure/bleeding < 50, CNS/eye < 100; FFP 10–15 mL/kg; cryoprecipitate 1 unit per 10 kg (fibrinogen < 1.5 g/L)', r:'AABB 2015/2023, BSH; local blood bank products (PH: PRC volumes ~ 250 mL) differ.', tab:'Heme'},
  'hm-doac':  {t:'DOAC reversal (life-threatening bleed): dabigatran → idarucizumab 5 g IV; apixaban/rivaroxaban → andexanet alfa (low/high dose) or 4-factor PCC 50 IU/kg (or fixed 2,000 IU)', r:'ACC 2020 ECDP / ASH; andexanet rarely available in PH – PCC is the practical option.', tab:'Heme'},
  'hm-factor':{t:'Factor replacement: FVIII units = weight × desired rise (%) × 0.5; FIX units = weight × desired rise (%) × 1 (plasma-derived; recombinant ~1.2–1.4); life-threatening bleed target 80–100%', r:'WFH 2020; PH factor supply limited – cryoprecipitate (FVIII) / FFP (FIX) as fallback.', tab:'Heme'},
  'hm-ddavp': {t:'Desmopressin 0.3 mcg/kg IV/SC (max 20 mcg) over 30 min for mild hemophilia A / type 1 vWD (fluid restriction, hyponatremia; avoid < 2 y)', r:'WFH/ASH vWD 2021.', tab:'Heme'},
  'hm-fn':    {t:'Febrile neutropenia (T ≥ 38.3 °C once or ≥ 38.0 °C for 1 h, ANC < 500): antipseudomonal β-lactam within 60 min – cefepime 2 g IV q8h or piperacillin–tazobactam 4.5 g IV q6h (peds cefepime 50 mg/kg q8h, max 2 g); add vancomycin for line infection, skin/soft tissue, MRSA, hemodynamic instability', r:'IDSA 2010 / ASCO-IDSA 2018; local resistance (ESBL in PH) may require a carbapenem.', tab:'Heme'},
  'hm-tls':   {t:'Tumour lysis: IV fluids 2–3 L/m²/day (urine output 80–100 mL/m²/hr); rasburicase 0.1–0.2 mg/kg IV (contraindicated in G6PD deficiency); allopurinol 100 mg/m² q8h (max 800 mg/day) for prevention', r:'Cairo-Bishop / BSH 2015; check G6PD (common in PH) before rasburicase.', tab:'Heme'},
  'hm-hca':   {t:'Hypercalcemia of malignancy: 0.9% NaCl 200–300 mL/hr titrated to urine output 100–150 mL/hr; zoledronic acid 4 mg IV over 15 min (adjust for CrCl); calcitonin 4 IU/kg SC/IM q12h for 24–48 h', r:'Endocrine Society 2023 hypercalcemia guideline.', tab:'Heme'},
  'hm-mscc':  {t:'Malignant spinal cord compression: dexamethasone 10 mg IV then 4 mg q6h (16 mg/day; some use 16 mg/day without load); MRI whole spine within 24 h', r:'NICE 2023 / ESMO; high-dose 96 mg loading no longer favoured.', tab:'Heme'},
  'hm-g6pd':  {t:'G6PD deficiency (PH newborn screening, prevalence ~ 2–3%): avoid oxidants – primaquine, dapsone, nitrofurantoin, sulfonamides/co-trimoxazole (high dose), methylene blue, rasburicase, naphthalene (mothballs), fava beans', r:'WHO/G6PD Deficiency Foundation lists; risk depends on variant and dose.', tab:'Heme'}
});
Object.assign(D, {
  hmPcc: {n:'4-factor PCC – factor Xa inhibitor bleed', flag:'hm-doac', a:[C('IV',w=>ok(w)?{main:`${fmt(Math.min(50*w,5000))} IU (50 IU/kg)`,lines:['Or fixed 2,000 IU (some protocols); max ~5,000 IU','Plus tranexamic acid per bleeding site protocol']}:{main:'Enter weight',lines:['50 IU/kg (or fixed 2,000 IU)']})]},
  hmIda: {n:'Idarucizumab – dabigatran reversal', flag:'hm-doac', a:[F('IV','5 g (2 × 2.5 g vials) as bolus or two 5–10 min infusions')]},
  hmDdavp: {n:'Desmopressin (DDAVP) – mild hemophilia A / vWD type 1 / uremic platelets', flag:'hm-ddavp', b:[B('IV/SC over 30 min',0.3,0.3,'mcg/kg',{max:20,note:'Restrict fluids 24 h; check Na. Not < 2 y.'})]},
  hmCryo: {n:'Cryoprecipitate', flag:'hm-txfx', b:[C('IV',w=>ok(w)?{main:`${Math.max(1,Math.round(w/10))} units`,lines:['≈ 1 unit / 10 kg raises fibrinogen ~0.5 g/L (adult pool of 10 = 10 units)']}:{main:'Enter weight',lines:['1 unit per 10 kg']})]},
  hmFfp: {n:'Fresh frozen plasma', flag:'hm-txfx', b:[B('IV',10,15,'mL/kg',{max:1200,note:'≈ 4 units adult; check volume overload.'})]},
  hmPrbc: {n:'Packed red cells', flag:'hm-txfx', a:[F('IV','1 unit, then reassess (≈ +1 g/dL)')], p:[B('IV over 3–4 h',10,15,'mL/kg',{max:350,note:'≈ +2–3 g/dL; slower in chronic severe anemia (risk of heart failure).'})]},
  hmFn: {n:'Febrile neutropenia – empiric antibiotics (within 60 min)', flag:'hm-fn', a:[F('IV','Cefepime 2 g q8h or piperacillin–tazobactam 4.5 g q6h (meropenem 1 g q8h if ESBL risk)')], p:[B('Cefepime IV q8h',50,50,'mg/kg',{max:2000})]},
  hmRas: {n:'Rasburicase – tumour lysis (check G6PD first)', flag:'hm-tls', b:[B('IV over 30 min',0.1,0.2,'mg/kg',{max:15,note:'Single dose often sufficient; fixed 3–6 mg used in adults.'})]},
  hmZol: {n:'Zoledronic acid – hypercalcemia of malignancy', flag:'hm-hca', a:[F('IV over ≥ 15 min','4 mg (reduce if CrCl 30–60; avoid < 30)')]},
  hmCalci: {n:'Calcitonin', flag:'hm-hca', a:[B('SC/IM q12h',4,4,'IU/kg',{note:'Rapid but short effect (tachyphylaxis in 48 h).'})]},
  hmDex: {n:'Dexamethasone – cord compression', flag:'hm-mscc', a:[F('IV','10 mg, then 4 mg q6h')], p:[B('IV',0.25,0.5,'mg/kg',{max:10,note:'Then per oncology.'})]}
});
defCards('heme','Heme',[
 {id:'transfuse', title:'Anemia & transfusion therapy (thresholds, products, reactions)', kw:'anemia transfusion PRBC platelets FFP cryoprecipitate reaction TRALI TACO hemolytic thalassemia polycythemia', h:'🩸 Anemia &amp; transfusion',
  render:w=>ul([`Restrictive thresholds: Hb 7 g/dL for most stable inpatients, 8 g/dL with cardiovascular disease/orthopedic surgery; symptoms and bleeding override numbers${vt('gi-txfx')}`,`Platelets: &lt; 10 prophylactic, &lt; 50 bleeding or procedure, &lt; 100 intracranial/ocular bleeding${vt('hm-txfx')}`,'Chronic severe anemia (e.g. thalassemia, common in PH; nutritional): transfuse slowly, diuretic between units if heart failure; send hemoglobin electrophoresis/iron studies <b>before</b> transfusion','Polycythemia (Hct &gt; 55–60%) with symptoms: phlebotomy; secondary causes (COPD, OSA, testosterone, high altitude)'])+drugs(['hmPrbc','hmFfp','hmCryo'],w)+
   h3('Transfusion reactions – stop the transfusion first')+tbl(['Reaction','Clues','Action'],[['Acute hemolytic (ABO)','Fever, back pain, hypotension, hemoglobinuria, DIC','Stop, fluids, recheck identity, DAT, notify blood bank'],['Anaphylaxis','Hypotension, wheeze, angioedema (IgA deficiency)','IM epinephrine ('+gto('anaph','anaphylaxis')+')'],['TRALI','Hypoxia, bilateral infiltrates within 6 h, often hypotension','O₂/ventilation; no diuretic'],['TACO','Hypoxia, hypertension, raised JVP','Diuretic, slow rates, sit up'],['Febrile non-hemolytic','Fever/chills only','Antipyretic; exclude hemolysis/sepsis'],['Allergic (urticaria only)','Hives','Antihistamine; may resume slowly']])},
 {id:'reversal', title:'Anticoagulant reversal & bleeding (warfarin, DOACs, heparin, thrombolytics)', kw:'anticoagulant reversal DOAC apixaban rivaroxaban dabigatran idarucizumab andexanet PCC warfarin vitamin K heparin protamine', h:'🔄 Anticoagulant reversal',
  render:w=>ul(['Life-threatening or critical-site bleed (intracranial, airway, GI with shock, compartment): reverse <b>now</b>, resuscitate, source control','Warfarin: vitamin K 10 mg IV + 4F-PCC by INR ('+gto('antidotes','antidotes card')+'); FFP only if no PCC'+vt('pcc'),'Heparin / enoxaparin: protamine ('+gto('antidotes','antidotes')+')','Thrombolytic-associated bleed: stop infusion, cryoprecipitate (fibrinogen), tranexamic acid','Time since last DOAC dose and renal function decide drug levels (dabigatran especially renally cleared – dialyzable)'])+drugs(['hmIda','hmPcc'],w)},
 {id:'hemophilia', title:'Hemophilia & von Willebrand disease – factor dose calculator', kw:'hemophilia factor VIII factor IX von Willebrand desmopressin DDAVP bleeding joint hemarthrosis', h:'🩹 Hemophilia &amp; vWD',
  inputs: sel('fxType','Factor',[['8','Factor VIII (hemophilia A)'],['9','Factor IX (hemophilia B, plasma-derived)']])+sel('fxTgt','Target level',[['40','40% – minor joint/muscle bleed'],['60','60% – major muscle, oral'],['80','80% – major bleed'],['100','100% – CNS, airway, life-threatening']])+num('fxBase','Baseline level (%), if known','e.g. 1'),
  render:w=>{ const t=parseFloat(sv('fxTgt'))||80, b=fv('fxBase')||0, f=sv('fxType')||'8', rise=Math.max(0,t-b);
   const main = ok(w) ? `<b>${fmt(Math.round(w*rise*(f==='8'?0.5:1)/250)*250)} units</b> of factor ${f==='8'?'VIII':'IX'} (rounded to 250-unit vials)` : 'Enter weight';
   return `<div class="cline"><div class="dl">Factor ${f==='8'?'VIII':'IX'} dose${vt('hm-factor')}</div>${main}<div class="note">units = weight × rise (${rise}%) × ${f==='8'?'0.5':'1'}${f==='9'?' (recombinant FIX needs ~1.2–1.4×)':''}</div></div>`+
   ol([['shock','<b>Treat first, image later</b>: give factor immediately for head injury, neck/throat bleeds, iliopsoas bleed, or any suspected serious bleed – even before CT'],'Ask the patient/family: they often know their dose and carry factor; inhibitor patients need bypassing agents (rFVIIa / aPCC) – call hematology','No IM injections, no NSAIDs; acetaminophen for pain; RICE for joint bleeds','PH: factor concentrate access is limited – cryoprecipitate (contains FVIII, vWF, fibrinogen) or FFP (FIX) if no factor; Philippine Hemophilia Foundation / NCHH for support'])+drugs(['hmDdavp'],w); }},
 {id:'hemolysis', title:'Hemolytic anemias: G6PD deficiency, sickle cell, TTP/HUS, DIC, HIT', kw:'G6PD deficiency hemolysis sickle cell crisis TTP HUS PLASMIC DIC HIT thrombocytopenia schistocytes', h:'🔴 Hemolysis, TTP/HUS, DIC, HIT',
  render:w=>h3('G6PD deficiency (common in PH)')+ul([`Acute hemolysis after oxidant drug, infection or fava beans/mothballs: pallor, dark urine, jaundice; supportive, transfuse if severe${vt('hm-g6pd')}`,'Methylene blue for methemoglobinemia is contraindicated – use ascorbic acid/exchange transfusion via toxicology'])+
   h3('Thrombotic microangiopathy (schistocytes + low platelets)')+ul(['<b>TTP</b> (ADAMTS13 &lt; 10%): PLASMIC score ≥ 6 → urgent plasma exchange, steroids; avoid platelet transfusion unless life-threatening bleed','<b>HUS</b> (often post-diarrheal E. coli in children): supportive, dialysis; no antibiotics/antimotility for STEC','<b>DIC</b>: treat the cause (sepsis, obstetric, trauma, APL); replace platelets/fibrinogen if bleeding (ISTH score)','<b>HIT</b> (platelet fall &gt; 50% 5–10 days after heparin; 4Ts score): stop all heparin, start non-heparin anticoagulant (argatroban, fondaparinux, DOAC); no platelet transfusion'])+
   h3('Sickle cell disease (uncommon in PH)')+ul(['Pain crisis: analgesia within 60 min, fluids if dehydrated; acute chest syndrome (fever, chest pain, new infiltrate) → O₂, antibiotics, transfusion; stroke → exchange transfusion; fever = emergency (functional asplenia)'])},
 {id:'oncem', title:'Oncologic emergencies: febrile neutropenia, TLS, hypercalcemia, cord compression, SVC, hyperviscosity', kw:'febrile neutropenia tumor lysis rasburicase hypercalcemia zoledronic spinal cord compression dexamethasone SVC syndrome hyperviscosity leukostasis', h:'🎗️ Oncologic emergencies',
  render:w=>h3('Febrile neutropenia')+ol([['shock',`Antibiotics within 60 min of arrival – do not wait for counts if recent chemotherapy${vt('hm-fn')}`],'Cultures (peripheral + each line lumen), lactate; MASCC ≥ 21 / CISNE low risk → possible oral outpatient therapy'])+drugs(['hmFn'],w)+
   h3('Tumour lysis syndrome')+ul([`High uric acid, K, phosphate; low Ca; AKI – after chemo for high-grade lymphoma/leukemia or spontaneously. Hydration, no K in fluids, treat hyperkalemia (${gto('rnhyperk','card')}), rasburicase (not with G6PD deficiency)${vt('hm-tls')}`])+drugs(['hmRas'],w)+
   h3('Hypercalcemia of malignancy')+ul([`Confusion, polyuria, constipation, short QT: saline rehydration, then bisphosphonate; calcitonin for rapid effect${vt('hm-hca')}`])+drugs(['hmZol','hmCalci'],w)+
   h3('Spinal cord compression')+ul([`Back pain + weakness/sensory level/sphincter loss in cancer: dexamethasone, MRI whole spine within 24 h, radiotherapy/surgery${vt('hm-mscc')}`])+drugs(['hmDex'],w)+
   ul(['<b>SVC syndrome</b>: facial swelling, distended neck veins – elevate head, CT; stridor = airway emergency; tissue diagnosis before steroids if lymphoma suspected','<b>Hyperviscosity</b> (Waldenström, myeloma) / <b>leukostasis</b> (WBC &gt; 100 × 10⁹/L): neuro, visual, respiratory symptoms → plasmapheresis/leukapheresis, hydration; avoid transfusing RBCs before leukoreduction'])},
 {id:'hmsrc', title:'Heme/Onc sources', h:'📚 Heme/Onc sources', render:w=>nt('Carson et al., AABB international guidelines for RBC transfusion (JAMA 2023) · Kaufman et al., AABB platelet transfusion 2015 · Srivastava et al., WFH guidelines for the management of hemophilia, 3rd ed (2020) · Connell/James et al., ASH ISTH NHF WFH vWD guidelines 2021 · Tomaselli et al., 2020 ACC ECDP on bleeding with oral anticoagulants · Freifeld et al., IDSA febrile neutropenia 2010; Taplitz et al., ASCO/IDSA 2018 · Cairo &amp; Bishop TLS classification; Jones et al., BSH TLS 2015 · Shane et al., Endocrine Society hypercalcemia of malignancy 2023 · NICE NG234 metastatic spinal cord compression 2023 · Zheng et al., ISTH TTP guidelines 2020 · Cuker et al., ASH HIT 2018 · PH Newborn Screening Program (RA 9288). Tintinalli 9e Section 18 used only as a topic map.')}
]);
