// ======================= S13 INFECTIOUS DISEASES (extends v1 Sepsis) =======================
// Sources: WHO dengue guideline 2009 & WHO arboviral disease clinical management 2025; DOH Revised Dengue Clinical Case Management Guidelines 2011 / PPS-PIDSP dengue CPG;
// DOH/PSMID leptospirosis CPG 2010; WHO malaria guidelines 2024 & DOH Malaria Control Program (artemether-lumefantrine first line); WHO measles vitamin A; CDC influenza antivirals;
// CDC STI 2021; Duke-ISCVID 2023 endocarditis criteria; WHO/CDC PEP; PH RA 11166 (HIV/AIDS Policy Act 2018), RA 11332, NTP Manual of Procedures 6th ed.
Object.assign(REVIEW, {
  'id-dfl':  {t:'Dengue fluids (WHO 2009/DOH): warning signs without shock – isotonic crystalloid 5–7 mL/kg/h × 1–2 h, then 3–5 mL/kg/h × 2–4 h, then 2–3 mL/kg/h, taper over 24–48 h guided by Hct/vitals/urine; compensated shock – 5–10 mL/kg/h (adult) or 10–20 mL/kg/h (child) × 1 h; hypotensive shock – 20 mL/kg over 15–30 min, repeat/colloid if no response; use IBW in obesity', r:'WHO 2009 / DOH 2011; WHO 2025 arboviral guideline wording differs slightly – confirm.', tab:'ID'},
  'id-lep':  {t:'Leptospirosis treatment: mild – doxycycline 100 mg PO BID × 7 d (children 2 mg/kg/dose BID, or amoxicillin); moderate–severe – penicillin G 1.5 MU IV q6h or ceftriaxone 1–2 g IV daily × 7 d', r:'DOH/PSMID 2010 leptospirosis CPG.', tab:'ID'},
  'id-mal':  {t:'Malaria: uncomplicated P. falciparum – artemether-lumefantrine (20/120 mg) weight-band 6-dose regimen over 3 days with fatty food; severe – IV artesunate 2.4 mg/kg (3 mg/kg if < 20 kg) at 0, 12, 24 h then daily; primaquine (single low dose 0.25 mg/kg for falciparum; G6PD testing before radical cure of vivax)', r:'WHO 2024; DOH Malaria Control Program (Palawan is main endemic area) – confirm drug access.', tab:'ID'},
  'id-vita': {t:'Measles vitamin A: < 6 mo 50 000 IU, 6–11 mo 100 000 IU, ≥ 12 mo 200 000 IU PO daily × 2 days (3rd dose 2–4 weeks later if eye signs)', r:'WHO.', tab:'ID'},
  'id-osel': {t:'Oseltamivir × 5 days: adult 75 mg BID; child ≥ 1 y – ≤ 15 kg 30 mg, 15–23 kg 45 mg, 23–40 kg 60 mg, > 40 kg 75 mg BID; < 1 y 3 mg/kg BID', r:'CDC/AAP; renal adjustment.', tab:'ID'},
  'id-sti':  {t:'STIs: gonorrhea ceftriaxone 500 mg IM once (1 g if ≥ 150 kg); chlamydia doxycycline 100 mg BID × 7 d (azithromycin 1 g in pregnancy); early syphilis benzathine penicillin G 2.4 MU IM once (late: weekly × 3); PID ceftriaxone + doxycycline + metronidazole × 14 d', r:'CDC 2021; PH benzathine penicillin shortages occur.', tab:'ID'},
  'id-ie':   {t:'Endocarditis empiric (native valve, after cultures): vancomycin 25–30 mg/kg load + ceftriaxone 2 g IV daily (or + gentamicin); prosthetic valve: vancomycin + gentamicin + rifampicin (specialist)', r:'ESC 2023 / AHA 2015.', tab:'ID'},
  'id-tb':   {t:'TB: airborne isolation for suspected pulmonary TB; Xpert MTB/RIF first test (NTP); do not start empiric single-drug therapy in ED', r:'NTP MOP 6th ed 2020.', tab:'ID'},
  'id-hiv':  {t:'PH HIV: RA 11166 – voluntary, confidential testing with counselling (minors 15–17 may consent); link to DOH treatment hub; PCP: TMP-SMX 15–20 mg/kg/day (TMP) ÷ q6–8h + prednisone if PaO₂ < 70 mmHg', r:'RA 11166 IRR; IDSA/NIH OI guidelines.', tab:'ID'}
});
Object.assign(D, {
  idDoxy: {n:'Doxycycline – leptospirosis (mild) / rickettsia / scrub typhus', flag:'id-lep', a:[F('PO','100 mg BID × 7 days')], p:[B('PO BID',2,2,'mg/kg',{max:100,note:'Short courses acceptable at any age.'})]},
  idPen: {n:'Penicillin G / ceftriaxone – severe leptospirosis', flag:'id-lep', a:[F('Penicillin G','1.5 million units IV q6h × 7 days'),F('Ceftriaxone','1 – 2 g IV daily × 7 days')], p:[B('Ceftriaxone IV daily',50,80,'mg/kg',{max:2000})]},
  idAL: {n:'Artemether-lumefantrine 20/120 mg – uncomplicated falciparum', flag:'id-mal', b:[C('Tablets per dose (6 doses: 0, 8, 24, 36, 48, 60 h)',w=>({main: w? (w<5?'Specialist advice (< 5 kg)':w<15?'1 tablet':w<25?'2 tablets':w<35?'3 tablets':'4 tablets'):'Enter weight', lines:['With fatty food/milk; repeat dose if vomited within 30 min']}))]},
  idArt: {n:'Artesunate IV – severe malaria', flag:'id-mal', b:[C('IV at 0, 12, 24 h then daily',w=>({main: w? `${Math.round((w<20?3:2.4)*w*10)/10} mg`:'Enter weight', lines:[w&&w<20?'3 mg/kg (< 20 kg)':'2.4 mg/kg','Switch to full oral ACT course once tolerating']}))]},
  idVitA: {n:'Vitamin A – measles', flag:'id-vita', b:[C('PO daily × 2 days',w=>{ const y=ageYears(); return {main: y==null?'Enter age': y<0.5?'50 000 IU': y<1?'100 000 IU':'200 000 IU', lines:[]}; })]},
  idOsel: {n:'Oseltamivir – influenza (5 days)', flag:'id-osel', a:[F('PO','75 mg BID')], p:[C('PO BID',w=>{ const y=ageYears(); if(!w) return {main:'Enter weight',lines:[]}; if(y!=null&&y<1) return {main:`${Math.round(3*w)} mg`,lines:['3 mg/kg (< 1 y)']}; return {main: w<=15?'30 mg':w<=23?'45 mg':w<=40?'60 mg':'75 mg', lines:[]}; })]},
  idSti: {n:'STI treatment', flag:'id-sti', a:[F('Gonorrhea','Ceftriaxone 500 mg IM once'),F('Chlamydia','Doxycycline 100 mg PO BID × 7 days (pregnancy: azithromycin 1 g once)'),F('Early syphilis','Benzathine penicillin G 2.4 million units IM once')], p:[B('Ceftriaxone IM once (&lt; 45 kg)',25,50,'mg/kg',{max:250})]},
  idIe: {n:'Empiric endocarditis (native valve)', flag:'id-ie', a:[B('Vancomycin IV load',25,30,'mg/kg',{max:3000}),F('+ Ceftriaxone','2 g IV daily')], p:[B('Vancomycin IV q6h',15,15,'mg/kg',{max:1000}),B('+ Ceftriaxone IV daily',100,100,'mg/kg',{max:4000})]}
});
defCards('infect','Infect|ID',[
 {id:'dengue', title:'Dengue – phases, warning signs, WHO/DOH groups & fluid calculator', kw:'dengue DHF dengue shock warning signs NS1 hematocrit platelet fluid calculator crystalloid plasma leakage', h:'🦟 Dengue',
  inputs: sel('dgGrp','Clinical group',[['a','A – no warning signs, tolerating fluids'],['b','B – warning signs / risk factors'],['c1','C – compensated shock'],['c2','C – hypotensive shock']]),
  render:w=>{ const g=sv('dgGrp')||'a', kid=peds(); const wt=(!kid&&typeof ibw==='function'&&ibw()&&w>ibw()*1.2)? ibw():w;
   const r=(a,b)=> wt? `${Math.round(a*wt)}–${Math.round(b*wt)} mL/h`:'enter weight';
   const olv=a=>ol(a.map(x=>/mL/.test(x)&&!/vt\(|vtag/.test(x)?x+vt('id-dfl'):x));
   let plan;
   if(g==='a') plan=ul(['Home care if able to drink, passing urine every 4–6 h, no warning signs: oral fluids (ORS, juice, soup), paracetamol only (no NSAIDs/aspirin, no IM injections)','Daily review (CBC) from day 3 until 48 h after defervescence; return immediately with warning signs']);
   else if(g==='b') plan=olv([`Isotonic crystalloid (PNSS/LR) ${r(5,7)} (5–7 mL/kg/h) × 1–2 h`,`Then ${r(3,5)} (3–5 mL/kg/h) × 2–4 h`,`Then ${r(2,3)} (2–3 mL/kg/h); taper over 24–48 h`,'Check Hct before and after each change: rising Hct + unstable → increase rate; stable → reduce'+vt('id-dfl')]);
   else if(g==='c1') plan=olv([`Crystalloid ${kid? r(10,20)+' (10–20 mL/kg/h)':r(5,10)+' (5–10 mL/kg/h)'} × 1 h`+vt('id-dfl'),'Improving → step down gradually (e.g. 7–10 → 5–7 → 3–5 → 2–3 mL/kg/h) over 24–48 h','Not improving: Hct up → second bolus/colloid; Hct down → suspect bleeding → transfuse (fresh whole blood 10–20 mL/kg / PRBC 5–10 mL/kg)']);
   else plan=olv([`Bolus ${wt? Math.round(20*wt)+' mL':'20 mL/kg'} crystalloid or colloid over 15–30 min${vt('id-dfl')}`,'Reassess; repeat bolus/colloid if no improvement; vasopressor/ICU if persistent','Falling Hct with shock = hemorrhage → blood','Monitor urine output (0.5 mL/kg/h), lactate, glucose, calcium']);
   return (wt&&wt!==w?nt(`Obese adult: rates calculated on IBW ${Math.round(wt)} kg.`):'')+plan+
    h3('Recognise')+ul(['Phases: febrile (days 1–3), critical (around defervescence, days 3–7 – plasma leak, 24–48 h), recovery (fluid reabsorption – watch for overload)','<b>Warning signs</b>: abdominal pain/tenderness, persistent vomiting, fluid accumulation, mucosal bleeding, lethargy/restlessness, liver &gt; 2 cm, rising Hct with rapid platelet fall','Shock may have normal BP with narrow pulse pressure (≤ 20 mmHg) and cold peripheries','Tests: NS1 antigen (days 1–5), IgM (after day 5), CBC with Hct trend; tourniquet test supportive','Prophylactic platelet transfusion is not recommended in stable patients','Risk groups: infants, pregnancy, elderly, obesity, diabetes, renal/heart disease, living far from care','PH: peak June–November; report to local epidemiology surveillance unit (RA 11332)']); }},
 {id:'lepto', title:'Leptospirosis (post-flood fever) – treatment & complications', kw:'leptospirosis flood Weil disease doxycycline penicillin pulmonary hemorrhage AKI jaundice', h:'🐀 Leptospirosis',
  render:w=>ul(['Suspect: fever + myalgia (calves), conjunctival suffusion, flood/wading exposure within 2–30 days','Severe (Weil): jaundice, AKI (often non-oliguric, hypokalemic), pulmonary hemorrhage (high mortality), myocarditis, thrombocytopenia','Tests: MAT/IgM, PCR early; do not wait – treat empirically','Severe: admit, early dialysis for AKI, lung-protective ventilation for hemorrhage','Prophylaxis after exposure: '+gto('natdis','natural disaster card')])+drugs(['idDoxy','idPen'],w)},
 {id:'tropical', title:'Malaria, typhoid, measles, influenza, TB & tropical fever in travelers', kw:'malaria artemether lumefantrine artesunate Palawan typhoid measles vitamin A influenza oseltamivir tuberculosis TB GeneXpert scrub typhus traveler fever', h:'🌏 Malaria, measles, TB &amp; tropical fever',
  render:w=>h3('Malaria')+ul(['PH: mainly Palawan (and returning travelers/workers from Africa, Papua); malaria-free status in most provinces','Test every febrile patient from an endemic area: thick/thin smear or RDT; repeat if negative and suspicion persists','Severe: impaired consciousness, convulsions, shock, acidosis, hypoglycemia, severe anemia, jaundice, parasitemia &gt; 5–10 %'+vt('id-mal')])+drugs(['idAL','idArt'],w)+
   h3('Measles')+ul(['Fever, cough, coryza, conjunctivitis, then rash from face down; Koplik spots','Airborne isolation; complications – pneumonia, diarrhea, encephalitis, keratitis; vitamin A for all cases'+vt('id-vita'),'PH outbreaks follow low vaccination coverage – check MMR/MR status, notify'])+drugs(['idVitA'],w)+
   h3('Influenza')+ul(['Antiviral for hospitalized, severe, or high-risk patients (age &lt; 5 or ≥ 65, pregnancy, chronic disease) – best within 48 h but still useful later in severe disease'+vt('id-osel')])+drugs(['idOsel'],w)+
   h3('TB &amp; others')+ul(['PH has one of the highest TB burdens: cough ≥ 2 weeks, weight loss, hemoptysis → mask/isolate, Xpert MTB/RIF, refer to TB-DOTS'+vt('id-tb'),'Typhoid ('+gto('nvd','GI card')+'), scrub typhus/rickettsia (eschar – doxycycline), melioidosis (diabetes, rice farmers – ceftazidime/meropenem)','Returning traveler: where, when, activities, vaccines, prophylaxis; malaria first in fever from endemic zones'])},
 {id:'hivsti', title:'HIV, opportunistic infections, STIs & occupational exposure (PEP)', kw:'HIV AIDS opportunistic PCP cryptococcal toxoplasmosis RA 11166 STI gonorrhea chlamydia syphilis PID needlestick occupational exposure PEP', h:'🎗️ HIV, STIs &amp; PEP',
  render:w=>ul(['PH: rapidly growing HIV epidemic (young men who have sex with men, PWID); offer testing to everyone with STI, TB, pneumonia, unexplained weight loss/fever'+vt('id-hiv'),'Advanced HIV (CD4 &lt; 200): PCP (hypoxemia, LDH, diffuse infiltrates – TMP-SMX + steroids), cryptococcal meningitis (headache, high opening pressure – CrAg), toxoplasmosis (ring-enhancing lesions), TB (often extrapulmonary), CMV','IRIS after ART start; drug interactions with ART (rifampicin, statins, antiepileptics)','<b>STIs</b>: treat partners, test for HIV/syphilis, abstain 7 days; syphilis is rising in PH (congenital syphilis screening in pregnancy)'+vt('id-sti'),'<b>Occupational exposure</b> (needlestick/splash): wash with soap and water (do not squeeze/scrub with bleach), assess source (HIV, HBV, HCV testing with consent), start HIV PEP within 72 h (ideally ≤ 2 h) if significant exposure ('+gto('sexassault','PEP regimen')+'), HBV vaccine ± HBIG if non-immune, baseline and follow-up testing'])+drugs(['idSti'],w)},
 {id:'endocard', title:'Infective endocarditis (Duke-ISCVID 2023) & empiric therapy', kw:'endocarditis Duke criteria blood cultures echocardiography vegetation embolic prosthetic valve rheumatic heart disease', h:'💗 Infective endocarditis',
  render:w=>ul(['Fever + new murmur, embolic phenomena, prosthetic valve, PWID ('+gto('pwid','PWID card')+'), or rheumatic heart disease (still common in PH)','Three sets of blood cultures from separate sites before antibiotics (unless septic shock – take 2 sets quickly and treat)','Echo: TTE first, TEE for prosthetic valves/high suspicion','Major criteria: typical organism in blood cultures, imaging evidence (vegetation, abscess, new dehiscence); minor: predisposition, fever, vascular/immunologic phenomena','Urgent surgery: heart failure from valve dysfunction, uncontrolled infection/abscess, large vegetation with embolism'+vt('id-ie')])+drugs(['idIe'],w)},
 {id:'idlinks', title:'Other infections – quick links (sepsis, SSTI, tetanus, rabies, typhoid, meningitis)', kw:'infection links sepsis skin soft tissue tetanus rabies typhoid cholera meningitis', h:'🔗 Other infections',
  render:w=>ul([gto('bundle','Sepsis bundle'),gto('skininf','Skin & soft-tissue infections'),gto('tetanus','Tetanus prophylaxis & treatment'),gto('rabies','Rabies post-exposure prophylaxis'),gto('nvd','Gastroenteritis, typhoid & cholera'),gto('cnsinf','Meningitis & encephalitis'),gto('febinf','Febrile infant'),gto('natdis','Leptospirosis prophylaxis after floods')])},
 {id:'idsrc', title:'Infectious diseases sources', h:'📚 Infectious diseases sources', render:w=>nt('WHO Dengue: guidelines for diagnosis, treatment, prevention and control (2009) · WHO clinical management of arboviral diseases (2025) · DOH Revised Dengue Clinical Case Management Guidelines (2011) · DOH/PSMID/PPS Leptospirosis CPG (2010) · WHO Guidelines for malaria (2024); DOH Malaria Control and Elimination Program · WHO vitamin A for measles · CDC influenza antiviral guidance · CDC STI Treatment Guidelines 2021 · Fowler et al., Duke-ISCVID criteria (Clin Infect Dis 2023); ESC endocarditis 2023 · DOH NTP Manual of Procedures 6th ed. · Philippine RA 11166, RA 11332 · NIH/IDSA adult OI guidelines. Tintinalli 9e Section 13 used only as a topic map.')}
]);
