// ======================= S23 MUSCULOSKELETAL DISORDERS =======================
// Sources: ACP 2017 low back pain; NICE NG59; ACR 2020 gout; EULAR 2016 gout; BSR/BHPR septic arthritis; Kocher criteria (1999); BSR 2020 GCA; IWGDF/IDSA 2023 diabetic foot;
// IDSA vertebral osteomyelitis 2015; WHO/DOH TB; Kanavel signs.
Object.assign(REVIEW, {
  'ms-gout':  {t:'Acute gout: colchicine 1.2 mg then 0.6 mg 1 h later (then 0.6 mg daily–BID; reduce with CKD/interacting drugs); or naproxen 500 mg BID; or prednisone 30–40 mg daily × 5 d; intra-articular steroid for single joint; do not stop allopurinol', r:'ACR 2020 low-dose colchicine; EULAR uses 1 mg then 0.5 mg.', tab:'MSK'},
  'ms-sept':  {t:'Septic arthritis empiric: cefazolin 2 g IV q8h (or vancomycin if MRSA risk); gonococcal: ceftriaxone 1 g IV daily; peds: cefazolin 50 mg/kg q8h (MRSA risk: clindamycin/vancomycin)', r:'BSR/IDSA practice; Kingella in < 4 y responds to cefazolin/cefuroxime.', tab:'MSK'},
  'ms-kocher':{t:'Kocher criteria (child with irritable hip): non-weight-bearing, fever > 38.5 °C, ESR > 40 mm/h, WBC > 12 × 10⁹/L – septic arthritis probability ~3% (1), 40% (2), 93% (3), 99% (4); CRP > 2 mg/dL often added', r:'Kocher 1999 derivation; lower in validation cohorts.', tab:'MSK / Pediatr'},
  'ms-gca':   {t:'Giant cell arteritis: prednisone 40–60 mg daily immediately (before biopsy); visual symptoms → IV methylprednisolone 500–1,000 mg daily × 3 days', r:'BSR 2020 / ACR 2021.', tab:'MSK'},
  'ms-ces':   {t:'Cauda equina: post-void residual > 200 mL (with symptoms) increases likelihood – emergency MRI regardless', r:'Observational; normal PVR does not exclude.', tab:'MSK'},
  'ms-dfi':   {t:'Diabetic foot infection: mild – cephalexin/amoxicillin–clavulanate; moderate–severe – piperacillin–tazobactam 4.5 g IV q6h ± vancomycin; probe-to-bone/X-ray/MRI for osteomyelitis', r:'IWGDF/IDSA 2023; local MDR prevalence.', tab:'MSK'}
});
Object.assign(D, {
  msColch: {n:'Colchicine – acute gout (low-dose)', flag:'ms-gout', a:[F('PO','1.2 mg, then 0.6 mg after 1 h (max 1.8 mg day 1); then 0.6 mg daily–BID',{note:'Halve/avoid in CKD, with clarithromycin, azoles, verapamil, cyclosporine.'})]},
  msNap: {n:'Naproxen / prednisone – acute gout', flag:'ms-gout', a:[F('Naproxen','500 mg PO BID × 5–7 d (avoid CKD, GI bleed, HF)'),F('or Prednisone','30–40 mg PO daily × 5 days')]},
  msSept: {n:'Septic arthritis – empiric (after aspiration)', flag:'ms-sept', a:[F('IV','Cefazolin 2 g q8h (vancomycin 25 mg/kg load if MRSA risk); gonococcal: ceftriaxone 1 g daily')], p:[B('Cefazolin IV q8h',50,50,'mg/kg',{max:2000})]},
  msGca: {n:'Steroids – giant cell arteritis', flag:'ms-gca', a:[F('No visual loss','Prednisone 40–60 mg PO daily'),F('Visual symptoms','Methylprednisolone 500–1,000 mg IV daily × 3 d')]},
  msDfi: {n:'Diabetic foot infection', flag:'ms-dfi', a:[F('Mild','Cephalexin 500 mg QID or amoxicillin–clavulanate 875/125 BID'),F('Moderate–severe','Piperacillin–tazobactam 4.5 g IV q6h ± vancomycin')]}
});
const KOC=[['kc_nwb','Non-weight-bearing'],['kc_fev','Fever > 38.5 °C'],['kc_esr','ESR > 40 mm/h'],['kc_wbc','WBC > 12 × 10⁹/L']];
defCards('msk','MSK',[
 {id:'backpain', title:'Neck & back pain red flags (cauda equina, epidural abscess, malignancy, TB spine)', kw:'back pain red flags cauda equina epidural abscess spinal TB Pott malignancy sciatica neck pain', h:'🔙 Neck &amp; back pain',
  render:w=>ol([['shock',`<b>Cauda equina</b>: bilateral sciatica, saddle anesthesia, urinary retention/incontinence, reduced anal tone → emergency MRI and spinal surgery${vt('ms-ces')}`],['shock','<b>Spinal epidural abscess</b>: back pain + fever ± neuro deficit; risks diabetes, IV drug use, recent procedure, bacteremia; ESR/CRP, MRI, blood cultures, antibiotics after cultures (vancomycin + ceftriaxone/cefepime), surgery'],'<b>Malignancy</b>: history of cancer, weight loss, night pain, age &gt; 50 – MRI; cord compression ('+gto('oncem','oncology card')+')','<b>Fracture</b>: elderly/osteoporosis/steroids, trauma; <b>AAA</b> in older patients with back pain + hypotension ('+gto('aorta','aorta')+')','<b>Spinal TB (Pott disease)</b> – relevant in PH: insidious back pain, gibbus, constitutional symptoms, paraparesis – MRI, TB work-up'])+
   ul(['No red flags: reassure, stay active, NSAID/acetaminophen, heat; avoid routine imaging and opioids; most improve in 4–6 weeks','Radiculopathy: same plus follow-up; progressive motor deficit → MRI','Neck pain: look for cervical artery dissection (headache, Horner, neuro deficits), meningitis, retropharyngeal abscess'])},
 {id:'hotjoint', title:'Hot swollen joint: septic arthritis (Kocher), gout, pseudogout', kw:'septic arthritis hot joint aspiration synovial fluid gout colchicine pseudogout Kocher criteria irritable hip transient synovitis', h:'🔥 Hot swollen joint',
  inputs: h3('Child with limp / irritable hip – Kocher criteria')+KOC.map(([id,t])=>ck(id,t)).join(''),
  render:w=>{ const n=nsum(KOC.map(x=>x[0])); return score(n,4,'Kocher')+`<div class="note">Septic hip probability ≈ ${['&lt; 1%','3%','40%','93%','99%'][n]} ${vt('ms-kocher')} – ≥ 2 → urgent ultrasound/aspiration, orthopedics</div>`+
   ol([['shock','A single hot swollen joint is <b>septic until proven otherwise</b> – aspirate before antibiotics (unless septic shock); send cell count, Gram stain, culture, crystals'],'Synovial WBC &gt; 50,000/mm³ (often &gt; 90% neutrophils) strongly suggests infection; crystals do not exclude co-existing infection','Young sexually active: disseminated gonococcal infection (tenosynovitis, pustules, migratory arthralgia) – ceftriaxone','Prosthetic joint: do not aspirate in the ED – orthopedics'])+drugs(['msSept'],w)+
   h3('Gout / pseudogout')+ul([`Gout: monosodium urate (needle, negative birefringence); first MTP, ankle, knee; triggers – alcohol, seafood/organ meat, diuretics, dehydration${vt('ms-gout')}`,'Pseudogout (CPPD): knee/wrist, elderly, rhomboid positively birefringent crystals; same anti-inflammatory approach'])+drugs(['msColch','msNap'],w); }},
 {id:'rheum', title:'Systemic rheumatic disease emergencies (GCA, lupus, vasculitis, RA neck) & viral arthritis', kw:'giant cell arteritis temporal arteritis polymyalgia lupus SLE vasculitis rheumatoid atlantoaxial chikungunya arthritis', h:'🧬 Rheumatic emergencies',
  render:w=>ul([`<b>Giant cell arteritis</b> (&gt; 50 y, new headache, jaw claudication, scalp tenderness, visual loss, high ESR/CRP): steroids immediately – do not wait for biopsy${vt('ms-gca')}`,'<b>SLE flare</b>: fever in lupus = infection until proven (immunosuppressed); lupus nephritis, serositis, cytopenias, CNS lupus, antiphospholipid thrombosis','<b>Vasculitis</b>: pulmonary-renal syndrome (hemoptysis + AKI) → ICU, plasma exchange/steroids','<b>Rheumatoid arthritis</b>: atlantoaxial instability – careful neck handling during intubation; drug toxicity (methotrexate: cytopenias, pneumonitis)','<b>Chikungunya</b> (PH outbreaks): fever + severe symmetric polyarthralgia; supportive (acetaminophen until dengue excluded); arthralgia may persist months','Steroid-treated patients: adrenal crisis risk with acute illness ('+gto('adrenal','adrenal crisis')+')'])+drugs(['msGca'],w)},
 {id:'regionalmsk', title:'Shoulder, hip, knee, hand & foot pain (tenosynovitis, felon, diabetic foot)', kw:'shoulder pain rotator cuff frozen shoulder hip pain knee pain bursitis flexor tenosynovitis Kanavel felon paronychia diabetic foot plantar fasciitis ingrown toenail', h:'🖐️ Regional musculoskeletal pain',
  render:w=>tbl(['Region','ED-relevant problems'],[['Shoulder','Rotator cuff tendinopathy/tear, adhesive capsulitis, calcific tendinitis; <b>referred pain</b> (MI, diaphragmatic irritation, Pancoast)'],['Hip','Older: occult fracture, OA, trochanteric bursitis; child: transient synovitis vs septic hip vs SCFE (obese adolescent, knee pain) vs Perthes'],['Knee','Effusion: aspirate if septic concern; prepatellar bursitis (septic in kneelers – aspirate); Baker cyst rupture mimics DVT'],['Hand','<b>Flexor tenosynovitis</b> (Kanavel: fusiform swelling, flexed posture, pain on passive extension, sheath tenderness) → IV antibiotics + hand surgeon; felon (drain), paronychia (drain), herpetic whitlow (no incision)'],['Foot','<b>Diabetic foot infection</b> – grade severity, probe to bone, X-ray, offload'+vt('ms-dfi')+'; plantar fasciitis; ingrown toenail (partial avulsion); gout']])+drugs(['msDfi'],w)},
 {id:'mssrc', title:'MSK sources', h:'📚 MSK sources', render:w=>nt('Qaseem et al., ACP low back pain guideline 2017 · NICE NG59 low back pain and sciatica · FitzGerald et al., 2020 ACR gout guideline · Richette et al., EULAR gout 2016 · Coakley et al., BSR/BHPR hot swollen joint guideline 2006 · Kocher et al., septic hip criteria (JBJS 1999) · Mackie et al., BSR GCA guideline 2020 · Senneville et al., IWGDF/IDSA diabetic foot infection 2023 · Berbari et al., IDSA native vertebral osteomyelitis 2015 · WHO TB guidelines. Tintinalli 9e Section 23 used only as a topic map.')}
]);
