// ======================= S14 NEUROLOGY (extends v1 Neurology panel) =======================
// Sources: Perry et al., Ottawa SAH rule (JAMA 2013) & 6-hour CT rule (BMJ 2011); AHA/ASA spontaneous ICH 2022 & aSAH 2023; AHS/ACEP headache policies (ACEP 2019); HINTS (Kattah 2009), ACEP/GRACE-3 dizziness 2023;
// IDSA/ESCMID bacterial meningitis (ESCMID 2016, NICE NG240 2024); IDSA encephalitis 2008; GBS (EAN/PNS 2023); MGFA; AAN/AAO-HNS Bell palsy 2013.
Object.assign(REVIEW, {
  'nr-mig':  {t:'Migraine (adult): metoclopramide 10 mg IV or prochlorperazine 10 mg IV (+ diphenhydramine 25 mg for akathisia); ketorolac 15–30 mg IV; dexamethasone 10 mg IV to reduce recurrence; avoid opioids; peds: metoclopramide 0.1–0.15 mg/kg (max 10 mg), ibuprofen 10 mg/kg (max 400–600 mg)', r:'ACEP 2019 / AHS 2016.', tab:'Neuro'},
  'nr-ich':  {t:'Spontaneous ICH: target SBP ~140 mmHg (avoid < 130), start within 2 h, smooth (labetalol 10–20 mg IV / nicardipine 5 mg/h titrate); reverse anticoagulation; aSAH: nimodipine 60 mg PO q4h × 21 d, BP < 160 until aneurysm secured', r:'AHA 2022 ICH / 2023 aSAH.', tab:'Neuro'},
  'nr-mng':  {t:'Bacterial meningitis (adult): dexamethasone 10 mg IV q6h × 4 d (start with/before first antibiotic); ceftriaxone 2 g IV q12h + vancomycin 15–20 mg/kg q8–12h; + ampicillin 2 g IV q4h if > 50 y/immunocompromised/pregnant; acyclovir 10 mg/kg IV q8h if encephalitis possible. Contacts of meningococcal disease: ciprofloxacin 500 mg PO once (or rifampicin 600 mg BID × 2 d; ceftriaxone 250 mg IM in pregnancy). Peds: ceftriaxone 50 mg/kg q12h (100 mg/kg/day, max 4 g), vancomycin 15 mg/kg q6h, dexamethasone 0.15 mg/kg q6h', r:'IDSA 2004 / ESCMID 2016 / NICE NG240; PH pneumococcal resistance data limited.', tab:'Neuro / ID'},
  'nr-vert': {t:'Vertigo symptomatic relief (short course only): meclizine 25 mg PO, dimenhydrinate 50 mg PO/IV, diazepam 2–5 mg; vestibular neuritis: prednisone 50–60 mg × 5 d (evidence limited)', r:'GRACE-3 2023.', tab:'Neuro'},
  'nr-bell': {t:'Bell palsy: prednisolone 50 mg × 10 d or 60 mg × 5 d then taper, within 72 h; add valacyclovir 1 g TID × 7 d only in severe palsy (optional); eye protection', r:'AAN/AAO-HNS 2013.', tab:'Neuro'},
  'nr-gbs':  {t:'GBS/myasthenia respiratory failure thresholds ("20/30/40"): FVC < 20 mL/kg, NIF weaker than −30 cmH₂O, PEF/MEP < 40 cmH₂O → intubation/ICU; GBS: IVIG 0.4 g/kg/day × 5 d or plasma exchange', r:'EAN/PNS 2023; MGFA.', tab:'Neuro'},
  'nr-mscc': {t:'Malignant spinal cord compression: dexamethasone 10 mg IV load then 16 mg/day (some use 8–16 mg); MRI whole spine within 24 h', r:'NICE NG234 (2023).', tab:'Neuro'},
  'nr-coma': {t:'Coma "cocktail" – give based on findings: glucose (adult D50 25 g / child D10 2–5 mL/kg) if low, thiamine 100–500 mg IV before/with glucose if at risk, naloxone 0.04–0.4 mg IV titrated if opioid toxidrome', r:'Standard practice.', tab:'Neuro'}
});
Object.assign(D, {
  nMeto: {n:'Metoclopramide / prochlorperazine – migraine', flag:'nr-mig', a:[F('Metoclopramide IV','10 mg slow IV'),F('Prochlorperazine IV','10 mg (with diphenhydramine 25 mg)')], p:[B('Metoclopramide IV',0.1,0.15,'mg/kg',{max:10})]},
  nKet: {n:'NSAID – headache', flag:'nr-mig', a:[F('Ketorolac IV/IM','15 – 30 mg (15 mg if ≥ 65 y)')], p:[B('Ibuprofen PO',10,10,'mg/kg',{max:600}),B('Ketorolac IV (&gt; 2 y)',0.5,0.5,'mg/kg',{max:15})]},
  nDexH: {n:'Dexamethasone – migraine recurrence prevention', flag:'nr-mig', a:[F('IV','10 mg once')]},
  nNimo: {n:'Nimodipine – aneurysmal SAH', flag:'nr-ich', a:[F('PO / NG','60 mg q4h × 21 days (30 mg q2h if hypotension)')]},
  nCtx: {n:'Ceftriaxone – bacterial meningitis', flag:'nr-mng', a:[F('IV','2 g q12h')], p:[B('IV q12h',50,50,'mg/kg',{max:2000})]},
  nVanc: {n:'Vancomycin – meningitis', flag:'nr-mng', a:[B('IV q8–12h',15,20,'mg/kg',{max:2000,note:'Load 25–30 mg/kg in critically ill; levels.'})], p:[B('IV q6h',15,15,'mg/kg',{max:1000})]},
  nAmp: {n:'Ampicillin – Listeria cover', flag:'nr-mng', a:[F('IV','2 g q4h (if > 50 y, immunocompromised, pregnant, alcohol)')], p:[B('IV q6h (neonates: see febrile infant)',75,75,'mg/kg',{max:2000})]},
  nDexM: {n:'Dexamethasone – bacterial meningitis', flag:'nr-mng', a:[F('IV','10 mg q6h × 4 days, first dose before/with antibiotic')], p:[B('IV q6h × 4 d',0.15,0.15,'mg/kg',{max:10})]},
  nAcy: {n:'Acyclovir – HSV encephalitis', flag:'nr-mng', a:[B('IV q8h',10,10,'mg/kg',{max:1000,note:'Use IBW in obesity; hydrate; renal adjust.'})], p:[B('IV q8h (3 mo–12 y: 10–15 mg/kg)',10,15,'mg/kg',{max:1000})]},
  nVert: {n:'Vestibular suppressant (short term)', flag:'nr-vert', a:[F('Meclizine PO','25 mg q8h PRN (≤ 3 days)'),F('Dimenhydrinate PO/IV','50 mg q6h PRN')]},
  nPred: {n:'Prednisolone – Bell palsy', flag:'nr-bell', a:[F('PO','50 mg daily × 10 days (or 60 mg × 5 days then taper)')], p:[B('PO daily × 5–10 d',1,2,'mg/kg',{max:60})]}
});
const OSAH=[['os_age','Age ≥ 40'],['os_neck','Neck pain or stiffness'],['os_loc','Witnessed loss of consciousness'],['os_ex','Onset during exertion'],['os_tc','Thunderclap (instantly peaking) headache'],['os_flex','Limited neck flexion on exam']];
defCards('neuro','Neuro',[
 {id:'headache', title:'Headache – red flags, Ottawa SAH rule, migraine treatment', kw:'headache thunderclap subarachnoid Ottawa SAH rule migraine metoclopramide ketorolac dexamethasone giant cell arteritis CVST red flags', h:'🤕 Headache &amp; Ottawa SAH rule',
  inputs: nt('Ottawa SAH rule: alert patients ≥ 15 y with new severe non-traumatic headache peaking within 1 h.')+OSAH.map(([id,t])=>ck(id,t)).join(''),
  render:w=>{ const n=nsum(OSAH.map(x=>x[0]));
   return `<div class="big">${n?'<span class="due">Ottawa SAH rule positive → non-contrast CT; if CT ≤ 6 h from onset on modern scanner read by an experienced radiologist and normal, SAH effectively excluded; &gt; 6 h → LP (xanthochromia) or CTA</span>':'<span class="ok">Rule negative – SAH unlikely (sensitivity ~100 %); still consider other red flags</span>'}</div>`+
   h3('Red flags')+ul(['Sudden/thunderclap, worst ever, exertional/positional, new after age 50, fever/neck stiffness, focal deficit, papilledema, immunosuppression, cancer, pregnancy/postpartum (preeclampsia – '+gto('obhtn','OB HTN')+', CVST), anticoagulation, head injury','Older adults: giant cell arteritis (jaw claudication, visual symptoms, ESR/CRP) → steroids same day to protect vision','Household clusters/winter/charcoal or generator use → carbon monoxide ('+gto('co','CO')+')'])+
   h3('Migraine / primary headache')+ul(['Antiemetic dopamine antagonist ± NSAID, IV fluids if dehydrated; dexamethasone reduces 72-h recurrence; avoid opioids and butalbital','Occipital nerve block or sphenopalatine block for refractory cases','Cluster: high-flow oxygen 12–15 L/min via non-rebreather × 15 min'+vt('nr-mig')])+drugs(['nMeto','nKet','nDexH'],w); }},
 {id:'ich', title:'Intracerebral & subarachnoid hemorrhage – BP targets, reversal, nimodipine', kw:'intracerebral hemorrhage ICH subarachnoid hemorrhage aneurysm blood pressure target nimodipine reversal ICH score', h:'🩸 ICH &amp; SAH',
  render:w=>ul(['Airway if GCS ≤ 8 or deteriorating; head of bed 30°; treat fever, glucose 140–180 mg/dL','<b>ICH</b>: lower SBP to ~140 mmHg within 2 h, smoothly (avoid &lt; 130 and big swings)'+vt('nr-ich'),'Reverse anticoagulants immediately: '+gto('reversal','anticoagulant reversal card')+'; platelet transfusion not helpful for antiplatelet-associated ICH unless surgery','Neurosurgery: cerebellar hematoma &gt; 3 cm / brainstem compression / hydrocephalus; spot sign = expansion risk','<b>aSAH</b>: Hunt–Hess/WFNS grade; BP &lt; 160 until aneurysm secured; nimodipine; seizure treatment if seizures (no routine prophylaxis); EVD for hydrocephalus','PH: hypertensive ICH very common – check adherence to antihypertensives; transfer early to neurosurgical centre'])+drugs(['nNimo'],w)},
 {id:'vertigo', title:'Dizziness & vertigo – TiTrATE, HINTS, Dix-Hallpike/Epley', kw:'vertigo dizziness HINTS head impulse nystagmus test of skew BPPV Dix-Hallpike Epley vestibular neuritis posterior circulation stroke', h:'🌀 Vertigo (HINTS)',
  render:w=>tbl(['Pattern','Approach'],[['Triggered episodic (seconds, positional)','BPPV: Dix-Hallpike (torsional upbeat nystagmus) → Epley maneuver; supine roll test for horizontal canal'],['Spontaneous episodic (minutes–hours)','Vestibular migraine, Ménière; <b>TIA</b> (posterior circulation – ABCD², imaging)'],['Acute vestibular syndrome (continuous, with nystagmus)','<b>HINTS</b> by a trained examiner: <i>central</i> if head impulse normal, direction-changing nystagmus, or skew deviation present (any one) → MRI (CT misses posterior strokes); plus gait (truncal ataxia = central)'],['Toxic/metabolic','Drugs (anticonvulsants, alcohol), CO, hypoglycemia']])+
   ul(['Hearing loss with acute vertigo can be labyrinthine infarction (AICA) – treat as central','Vestibular suppressants only briefly; vestibular rehabilitation'+vt('nr-vert')])+drugs(['nVert'],w)},
 {id:'coma', title:'Altered mental status & coma – causes, first steps', kw:'altered mental status coma AEIOU TIPS confusion obtunded nonconvulsive status thiamine naloxone glucose', h:'😵 Altered mental status &amp; coma',
  render:w=>ol(['ABCs, glucose at the bedside, temperature, SpO₂/CO₂','Treat reversible: glucose if low, thiamine if at risk, naloxone if opioid toxidrome'+vt('nr-coma')+' ('+gto('naloxone','naloxone')+', '+gto('hypogly','hypoglycemia')+')','Look for: meningism, focal signs, pupils, toxidrome ('+gto('toxidromes','toxidromes')+'), trauma, needle marks, medical-alert IDs','Mnemonic AEIOU-TIPS: Alcohol, Epilepsy/Encephalopathy/Electrolytes, Insulin, Opioids/Oxygen, Uremia; Trauma/Temperature, Infection, Psychiatric/Poisoning, Stroke/Shock','CT head; labs (Na, Ca, renal/liver, ammonia, VBG, tox screen, cultures); LP if infection possible; EEG for non-convulsive status (subtle twitching, unexplained persistent coma after seizure)','PH: consider cerebral malaria (Palawan), Japanese encephalitis, TB meningitis, rabies, dengue encephalopathy'])},
 {id:'weakness', title:'Acute weakness: GBS, myasthenic crisis, cord compression, Bell palsy, periodic paralysis', kw:'Bell palsy facial palsy Guillain Barre myasthenia gravis crisis spinal cord compression hypokalemic periodic paralysis weakness botulism FVC NIF', h:'💪 Acute neuromuscular weakness',
  render:w=>tbl(['Condition','Key points'],[['Guillain–Barré','Ascending weakness, areflexia, post-infection (Campylobacter, dengue, Zika); autonomic instability; serial FVC/NIF'+vt('nr-gbs')+'; IVIG or plasma exchange'],['Myasthenic crisis','Fatigable ptosis/diplopia, bulbar and respiratory weakness; triggers – infection, drugs (aminoglycosides, fluoroquinolones, macrolides, magnesium, β-blockers); avoid succinylcholine resistance/rocuronium sensitivity – use reduced rocuronium; IVIG/PLEX'],['Spinal cord compression','Back pain + bilateral leg weakness, sensory level, retention – MRI whole spine urgently; malignant: dexamethasone 10 mg IV'+vt('nr-mscc')+' + oncology/radiotherapy ('+gto('oncem','oncologic emergencies')+'); epidural abscess'],['Bell palsy','Lower motor neuron facial palsy involving forehead; exclude stroke (forehead sparing), Ramsay Hunt (vesicles), otitis/parotid, Lyme; steroids ≤ 72 h, eye care'+vt('nr-bell')],['Hypokalemic periodic paralysis','Sudden weakness after carbohydrate load/exercise; thyrotoxic form in Asian men – check K and TFTs; cautious K replacement (rebound hyperkalemia)'],['Botulism / tetanus','Descending paralysis (botulism – home-canned food, wound); tetanus – '+gto('tetanus','tetanus card')]])+drugs(['nPred'],w)},
 {id:'cnsinf', title:'Meningitis, encephalitis & brain abscess – empiric therapy, LP timing', kw:'meningitis encephalitis brain abscess lumbar puncture CT before LP ceftriaxone vancomycin dexamethasone acyclovir Japanese encephalitis TB meningitis eosinophilic', h:'🧫 Meningitis &amp; encephalitis',
  render:w=>ol(['Suspected bacterial meningitis: blood cultures then <b>antibiotics within 1 h</b> – do not delay for CT/LP','CT before LP if: immunocompromised, focal deficit, papilledema, new seizure, GCS &lt; 10–12, history of CNS lesion','Dexamethasone before or with the first antibiotic dose (benefit mainly pneumococcal; stop if not bacterial)'+vt('nr-mng'),'Encephalitis (confusion, seizures, behaviour change, fever): acyclovir empirically; HSV PCR, MRI, EEG','CSF: bacterial – high neutrophils, low glucose ratio (&lt; 0.4), high protein; viral – lymphocytes, normal glucose; TB – lymphocytes, very high protein, low glucose','Droplet precautions for meningococcal disease; chemoprophylaxis for close contacts (ciprofloxacin 500 mg once / rifampicin)'+vt('nr-mng'),'PH: TB meningitis (subacute, cranial nerve palsies), Japanese encephalitis, eosinophilic meningitis from raw snails/kuhol (Angiostrongylus), neurocysticercosis, rabies'])+drugs(['nDexM','nCtx','nVanc','nAmp','nAcy'],w)},
 {id:'nrsrc', title:'Neurology (extended) sources', h:'📚 Neurology (extended) sources', render:w=>nt('Perry et al., Ottawa SAH rule (JAMA 2013) and CT within 6 h (BMJ 2011) · ACEP clinical policy: acute headache 2019 · AHS acute migraine treatment (Orr 2016) · Greenberg et al., AHA/ASA spontaneous ICH guideline 2022 · Hoh et al., AHA/ASA aSAH guideline 2023 · Kattah et al., HINTS (Stroke 2009); Edlow et al., GRACE-3 (Acad Emerg Med 2023) · van de Beek et al., ESCMID bacterial meningitis 2016; Tunkel et al., IDSA 2004; NICE NG240 (2024) · Tunkel et al., IDSA encephalitis 2008 · van Doorn et al., EAN/PNS GBS guideline 2023 · Sanders et al., MGFA consensus 2016/2020 · Baugh et al., AAO-HNS Bell palsy 2013. Tintinalli 9e Section 14 used only as a topic map.')}
]);
