// ======================= S22 ORTHOPEDICS =======================
// Sources: Ottawa ankle/foot (Stiell 1992) & knee rules (Stiell 1995); BOAST open fractures 2017; EAST open fracture antibiotics 2011; AAOS hip fracture 2021;
// BOAST compartment syndrome 2016; NICE NG38 fractures 2016; ATLS 10th.
Object.assign(REVIEW, {
  'or-open':  {t:'Open fracture antibiotics within 1 h: cefazolin 2 g IV (3 g if ≥ 120 kg; peds 30 mg/kg, max 2 g) q8h; add gram-negative cover (e.g. gentamicin 5 mg/kg daily or ceftriaxone) for Gustilo III; farm/soil contamination – add penicillin/metronidazole for clostridia', r:'EAST 2011 / BOAST 2017; regimens vary by institution.', tab:'Ortho'},
  'or-comp':  {t:'Compartment syndrome: fasciotomy if compartment pressure within 30 mmHg of diastolic BP (ΔP < 30 mmHg) with clinical signs', r:'McQueen threshold; clinical diagnosis in alert patients.', tab:'Ortho'},
  'or-hip':   {t:'Hip fracture: analgesia within 30 min incl. fascia iliaca block; surgery within 24–48 h', r:'AAOS 2021 / NICE CG124.', tab:'Ortho'}
});
Object.assign(D, {
  orCefaz: {n:'Cefazolin – open fracture (within 1 h)', flag:'or-open', a:[C('IV q8h',w=>({main: ok(w)&&w>=120?'3 g':'2 g', lines:['≥ 120 kg: 3 g; Gustilo III: add gram-negative cover']}))], p:[B('IV q8h',30,30,'mg/kg',{max:2000})]},
  orGent: {n:'Gentamicin – Gustilo III add-on', flag:'or-open', a:[B('IV daily',5,5,'mg/kg',{note:'Use adjusted body weight if obese; renal function.'})], p:[B('IV daily',5,7.5,'mg/kg',{max:560})]}
});
const OTT=[['ot_mal','Bone tenderness: posterior edge/tip of lateral malleolus (distal 6 cm)'],['ot_med','Bone tenderness: posterior edge/tip of medial malleolus'],['ot_bear','Unable to bear weight 4 steps (immediately and in ED)'],['ot_5mt','Bone tenderness: base of 5th metatarsal'],['ot_nav','Bone tenderness: navicular']];
const OKN=[['ok_age','Age ≥ 55'],['ok_fib','Tenderness at fibular head'],['ok_pat','Isolated patellar tenderness'],['ok_flex','Cannot flex to 90°'],['ok_wb','Unable to bear weight 4 steps (immediately and in ED)']];
defCards('ortho','Ortho',[
 {id:'orthoeval', title:'Initial evaluation of orthopedic injuries – open fractures, neurovascular checks, splinting', kw:'fracture open fracture Gustilo cefazolin splint neurovascular reduction dislocation', h:'🦴 Orthopedic injury basics',
  render:w=>ol(['Check and document distal pulses, capillary refill, motor and sensory function <b>before and after</b> any reduction or splint','Pale/pulseless limb with deformity → immediate gentle realignment with traction, then reassess (knee/elbow dislocations: ankle-brachial index &lt; 0.9 → CT angiography)',`<b>Open fracture</b>: photograph, remove gross contamination, saline-soaked dressing, splint, IV antibiotics within 1 h, tetanus (${gto('tetanus','table')}), orthopedics for debridement${vt('or-open')}`,'X-ray the joint above and below; repeat after reduction; children – compare views, consider Salter-Harris injuries','Analgesia early (see '+gto('pain','pain ladder')+' and '+gto('regional','hematoma/fascia iliaca blocks')+')'])+drugs(['orCefaz','orGent'],w)+
   ul(['Splint padding over bony prominences; check skin and circulation; elevate; written cast/splint care instructions (pain, numbness, colour change → return)','Suspect non-accidental injury: fractures in non-ambulant infants, posterior rib, metaphyseal corner, inconsistent history ('+gto('childabuse','child abuse')+')'])},
 {id:'ottawa', title:'Ottawa ankle/foot & knee rules (imaging decision)', kw:'Ottawa ankle rule knee rule foot x-ray imaging decision sprain', h:'🦶 Ottawa rules',
  inputs: h3('Ankle / foot')+OTT.map(([id,t])=>ck(id,t)).join('')+h3('Knee')+OKN.map(([id,t])=>ck(id,t)).join(''),
  render:w=>{ const ank = nc('ot_mal')||nc('ot_med')||nc('ot_bear'), ft = nc('ot_5mt')||nc('ot_nav')||nc('ot_bear'), kn=nsum(OKN.map(x=>x[0]))>0;
   return tbl(['Region','Result'],[['Ankle X-ray',ank?'<span class="due">Indicated</span>':'Not needed by rule'],['Foot X-ray',ft?'<span class="due">Indicated</span>':'Not needed by rule'],['Knee X-ray',kn?'<span class="due">Indicated</span>':'Not needed by rule']])+
   nt('Validated for adults (ankle rule also &gt; 5 y); not for intoxicated, multiple injuries, decreased sensation, or &gt; 10 days after injury. Clinical judgment overrides.'); }},
 {id:'upperlimb', title:'Upper limb: shoulder dislocation, elbow, wrist/scaphoid, hand & finger injuries', kw:'shoulder dislocation reduction FARES Cunningham external rotation clavicle supracondylar nursemaid elbow scaphoid distal radius boxer fracture mallet finger gamekeeper', h:'💪 Upper limb injuries',
  render:w=>tbl(['Injury','Key points'],[['Anterior shoulder dislocation','Pre-reduction X-ray (fracture?), check axillary nerve (regimental badge sensation); reduce with external rotation, FARES, Cunningham or scapular manipulation ± intra-articular lidocaine/sedation; sling, post-reduction X-ray'],['Posterior shoulder dislocation','Seizure/electrocution; arm held internally rotated – "lightbulb" sign; often missed'],['Clavicle','Sling; surgery if skin tenting, open, neurovascular injury'],['Supracondylar fracture (child)','Check radial pulse and AIN (OK sign); displaced/pulseless → urgent orthopedics'],['Radial head subluxation ("nursemaid")','Age 1–4, pulled arm; reduce by hyperpronation or supination-flexion; no X-ray if typical'],['Scaphoid','Snuffbox/tubercle tenderness with normal X-ray → thumb spica, repeat imaging/MRI in 10–14 d (avascular necrosis risk)'],['Distal radius','Hematoma block + reduction; neurovascular (median nerve) check'],['Hand','Boxer’s (5th metacarpal neck) – check rotation; mallet finger – extension splint 6–8 weeks; gamekeeper’s thumb (UCL) – thumb spica; fight bite ('+gto('handwound','wound card')+')']])},
 {id:'lowerlimb', title:'Lower limb & pelvis: hip/femur fracture, pelvic binder, knee dislocation, Achilles, ankle, Lisfranc', kw:'hip fracture neck of femur fascia iliaca pelvic fracture binder femur traction knee dislocation patella ACL Achilles rupture Thompson ankle Weber Lisfranc fifth metatarsal Jones', h:'🦵 Lower limb &amp; pelvis',
  render:w=>tbl(['Injury','Key points'],[['Pelvic fracture with shock','Binder at greater trochanters, MTP, eFAST, angio-embolisation/packing ('+gto('abcde','trauma')+')'],['Hip fracture (elderly)',`Shortened externally rotated leg; fascia iliaca block, delirium prevention, surgery within 24–48 h${vt('or-hip')}; occult → CT/MRI`],['Femoral shaft','Traction splint (not with pelvic/knee injury), blood loss 1–1.5 L'],['Knee dislocation','Often spontaneously reduced – check ABI/vascular imaging (popliteal artery injury), peroneal nerve'],['Patellar dislocation','Reduce by extending knee with medial pressure; X-ray for osteochondral fragment'],['Achilles rupture','Positive Thompson (calf squeeze) test; equinus cast/boot, orthopedics'],['Ankle fracture','Weber C/bimalleolar/talar shift → orthopedics; dislocated ankle with skin tenting → reduce immediately'],['Foot','Lisfranc (plantar ecchymosis, widened 1st–2nd MT gap – easily missed); 5th MT avulsion vs Jones fracture (non-weight-bearing, higher non-union)']])},
 {id:'compart', title:'Compartment syndrome', kw:'compartment syndrome fasciotomy pressure pain passive stretch tibia forearm crush cast', h:'⚠️ Compartment syndrome',
  render:w=>ol([['shock','<b>Pain out of proportion</b>, pain on passive stretch, tense compartment – earliest signs; pulselessness and paralysis are late'],'Remove/split casts and dressings to skin, limb at heart level (not elevated), treat hypotension, avoid excessive opioids masking pain',`Measure pressures in obtunded/uncertain patients; ΔP (diastolic − compartment) &lt; 30 mmHg supports fasciotomy${vt('or-comp')}`,'Emergency fasciotomy by surgeon; check CK, potassium, renal function (rhabdomyolysis)'])+
   ul(['High risk: tibial and forearm fractures, crush (earthquake/collapse '+gto('natdis','crush card')+'), snakebite (rarely true compartment syndrome – measure first), burns, IV infiltration, reperfusion after vascular repair'])},
 {id:'orsrc', title:'Orthopedics sources', h:'📚 Orthopedics sources', render:w=>nt('Stiell et al., Ottawa ankle rules (JAMA 1993) and Ottawa knee rule (JAMA 1996) · BOAST open fractures 2017 · Hoff et al., EAST open fracture antibiotic guideline 2011 · AAOS hip fracture in older adults guideline 2021 · NICE CG124 hip fracture · BOAST compartment syndrome 2016; McQueen &amp; Court-Brown pressure threshold · NICE NG38 non-complex fractures · ATLS 10th ed. Tintinalli 9e Section 22 used only as a topic map.')}
]);
