// ======================= S12 PEDIATRICS – emergencies (extends v1 Pediatric tools) =======================
// Sources: AAP febrile infant CPG 2021; Kuppermann PECARN febrile infant rule (JAMA Pediatr 2019); PECARN head injury rule (Lancet 2009); AAP bronchiolitis 2014 (2023 reaffirmed);
// Cochrane/BMJ croup reviews; AHA Kawasaki statement 2017 (2024 update); AAP BRUE 2016 (2025 update); AAP hyperbilirubinemia 2022; AAP UTI 2011/2016; IDSA pediatric CAP 2011 / PIDSP-PAPP pCAP guideline 2016;
// TEN-4-FACESp (Pierce 2021); PH RA 7610 child protection, RA 9288 newborn screening, DSWD Bantay Bata 163.
Object.assign(REVIEW, {
  'pd-fi':    {t:'Febrile infant empiric antibiotics: ≤ 28 d – ampicillin 50 mg/kg IV q8h (100 mg/kg if meningitis) + gentamicin 4 mg/kg IV q24h or cefotaxime/ceftazidime 50 mg/kg q8h; 29–60 d – ceftriaxone 50 mg/kg IV q24h (100 mg/kg if meningitis); acyclovir 20 mg/kg IV q8h if HSV risk', r:'AAP 2021; neonatal intervals vary with postnatal age; avoid ceftriaxone in neonates on IV calcium/with hyperbilirubinemia.', tab:'Pediatr'},
  'pd-pecfi': {t:'PECARN febrile infant (29–60 d) low risk: normal UA, ANC ≤ 4090/µL, procalcitonin ≤ 0.5 ng/mL; AAP 2021 inflammatory marker thresholds: PCT > 0.5, ANC > 4000–5200, CRP > 2 mg/dL, T > 38.5 °C', r:'Applies to well-appearing term infants only.', tab:'Pediatr'},
  'pd-croup': {t:'Croup: dexamethasone 0.15–0.6 mg/kg PO/IM once (max 16 mg; 0.15 mg/kg as effective for mild–moderate); nebulized epinephrine 1:1000 0.5 mL/kg (max 5 mL) for moderate–severe, observe 2–4 h after', r:'Cochrane 2023; budesonide 2 mg neb alternative.', tab:'Pediatr'},
  'pd-kd':    {t:'Kawasaki disease: IVIG 2 g/kg IV over 10–12 h + aspirin 30–50 mg/kg/day (moderate) or 80–100 mg/kg/day (high) divided q6h until afebrile 48 h, then 3–5 mg/kg/day', r:'AHA 2017/2024; IVIG supply/cost in PH; consider dosing obese adolescents by IBW.', tab:'Pediatr'},
  'pd-pge':   {t:'Alprostadil (PGE1) for suspected duct-dependent lesion: 0.05–0.1 mcg/kg/min IV (maintenance down to 0.01–0.05); apnea risk – airway ready', r:'Neonatal formularies.', tab:'Pediatr'},
  'pd-uti':   {t:'Pediatric UTI (> 2 mo): cefixime 8 mg/kg PO daily (max 400 mg) or cefalexin 50–100 mg/kg/day ÷ q6–8h × 7–14 d (febrile); IV ceftriaxone 50 mg/kg if unwell/vomiting', r:'AAP 2011/2016; local E. coli resistance (PH ESBL common).', tab:'Pediatr'},
  'pd-cap':   {t:'Pediatric CAP (non-severe, outpatient): amoxicillin 45 mg/kg BID (90 mg/kg/day, max 4 g/day) × 5 days; severe: ampicillin 50 mg/kg IV q6h (max 2 g) or ceftriaxone 50–100 mg/kg/day', r:'IDSA 2011 / PIDSP-PAPP pCAP 2016 (PH guideline doses may differ – confirm); 5-day course per SCOUT-CAP.', tab:'Pediatr'},
  'pd-meta':  {t:'Suspected metabolic crisis: stop protein, D10 with electrolytes at 1.5 × maintenance (glucose 8–10 mg/kg/min); ammonia urgently; specialist (metabolic) advice for scavengers/dialysis', r:'BIMDG emergency protocols.', tab:'Pediatr'},
  'pd-law':   {t:'PH child protection: RA 7610 – physicians must report suspected child abuse (to DSWD/police) within 48 h; hospital WCPU; DSWD Bantay Bata 163 hotline', r:'Confirm reporting timeframe and hotline number with hospital WCPU.', tab:'Pediatr'},
  'pd-jaun':  {t:'Neonatal jaundice: use AAP 2022 hour-specific phototherapy/exchange thresholds (gestational age, neurotoxicity risk factors); jaundice < 24 h of life, conjugated hyperbilirubinemia or ill infant = urgent', r:'AAP 2022; thresholds require the nomogram tool.', tab:'Pediatr'}
});
Object.assign(D, {
  pdAmp: {n:'Ampicillin – febrile neonate / meningitis', flag:'pd-fi', b:[B('IV q8h (≤ 28 d)',50,50,'mg/kg',{max:2000,note:'100 mg/kg/dose if meningitis suspected.'})]},
  pdGent: {n:'Gentamicin – neonate (with ampicillin)', flag:'pd-fi', b:[B('IV q24h',4,4,'mg/kg',{max:400,note:'Levels if > 48 h; interval longer in preterm.'})]},
  pdCtx: {n:'Ceftriaxone – infant 29–60 d / older child SBI', flag:'pd-fi', b:[B('IV q24h',50,50,'mg/kg',{max:2000,note:'Meningitis: 100 mg/kg/day (max 4 g). Neonates ≤ 28 d: use cefotaxime/ceftazidime 50 mg/kg q8h instead.'})]},
  pdAcy: {n:'Acyclovir – neonatal HSV risk', flag:'pd-fi', b:[B('IV q8h',20,20,'mg/kg',{max:800,note:'Ensure hydration; adjust for renal function.'})]},
  pdDex: {n:'Dexamethasone – croup', flag:'pd-croup', b:[B('PO / IM once',0.15,0.6,'mg/kg',{max:16})]},
  pdEpi: {n:'Nebulized epinephrine 1:1000 (1 mg/mL) – croup', flag:'pd-croup', b:[B('Nebulized',0.5,0.5,'mL/kg',{max:5,note:'Observe ≥ 2–4 h for rebound.'})]},
  pdIvig: {n:'IVIG – Kawasaki disease', flag:'pd-kd', b:[B('IV over 10–12 h',2,2,'g/kg',{max:140,note:'Single infusion; consider IBW in obesity.'})]},
  pdAsa: {n:'Aspirin – Kawasaki (acute phase)', flag:'pd-kd', b:[B('PO per day (÷ q6h)',30,50,'mg/kg',{max:4000,note:'Then 3–5 mg/kg/day once daily (max 81–325 mg) after 48 h afebrile.'})]},
  pdPge: {n:'Alprostadil (PGE1) – duct-dependent lesion', flag:'pd-pge', b:[I('Infusion',0.05,0.1,'mcg/kg/min',10,{note:'Example dilution 10 mcg/mL. Apnea/hypotension – be ready to ventilate.'})]},
  pdCfx: {n:'Cefixime – pediatric UTI (oral)', flag:'pd-uti', b:[B('PO once daily',8,8,'mg/kg',{max:400})]},
  pdAmox: {n:'Amoxicillin – pediatric pneumonia / otitis', flag:'pd-cap', b:[B('PO BID',45,45,'mg/kg',{max:2000})]}
});
const PEC2=[['ph_ams','GCS &lt; 15 / altered mental status / palpable skull fracture',1],['ph_hem','Occipital, parietal or temporal scalp hematoma',2],['ph_loc','LOC ≥ 5 s',2],['ph_mech','Severe mechanism',2],['ph_beh','Not acting normally per parent',2]];
const PECO=[['po_ams','GCS &lt; 15 / altered mental status / signs of basilar skull fracture',1],['po_loc','Any LOC',2],['po_vom','Vomiting',2],['po_mech','Severe mechanism',2],['po_ha','Severe headache',2]];
defCards('pedsem','Pediatr',[
 {id:'febinf', title:'Febrile infant ≤ 60 days & fever in children (PECARN / AAP 2021)', kw:'febrile infant fever neonate serious bacterial infection SBI PECARN procalcitonin lumbar puncture Rochester AAP 2021 sepsis ampicillin', h:'🌡️ Febrile infant &amp; fever',
  inputs: num('fiDays','Age (days)','e.g. 35')+sel('fiUA','Urinalysis',[['','—'],['n','Normal'],['a','Abnormal (LE / nitrite / pyuria)']])+num('fiAnc','ANC (/µL)','e.g. 3500')+num('fiPct','Procalcitonin (ng/mL)','e.g. 0.2','0.01'),
  render:w=>{ const d=fv('fiDays'), anc=fv('fiAnc'), pct=fv('fiPct'), ua=sv('fiUA');
   let out='';
   if(d!=null){ if(d<=28) out='<span class="due">≤ 28 days: full sepsis evaluation (blood, urine, CSF cultures), admit, empiric IV antibiotics</span>';
    else if(d<=60){ if(!ua||anc==null||pct==null) out='Enter UA, ANC and procalcitonin for PECARN rule';
     else { const hi= ua==='a'||anc>4090||pct>0.5; out= hi? '<span class="due">Not low risk (PECARN): blood/urine cultures, consider LP (especially if PCT/ANC raised), antibiotics, admit</span>':'<span class="ok">Low risk by PECARN: no LP needed; may observe without antibiotics if reliable follow-up within 24 h</span>'; } }
    else out='&gt; 60 days: clinical assessment – focus on UTI (urinalysis in girls &lt; 2 y, uncircumcised boys), pneumonia, dengue, measles, malaria in endemic areas'; }
   return `<div class="big">${out||'Enter age in days'}${vt('pd-pecfi')}</div>`+
   ul(['Applies to <b>well-appearing, term</b> infants; ill-appearing = sepsis workup and antibiotics at any age','Fever = rectal ≥ 38.0 °C; parental report of measured fever counts','HSV risk (maternal lesions, seizures, vesicles, hepatitis, CSF pleocytosis, age &lt; 21 d) → add acyclovir, HSV PCR','Older children: look for focus; sepsis signs (tachycardia, cap refill &gt; 3 s, altered mentation) → '+gto('bundle','sepsis bundle'),'PH: in febrile children ≥ 2–3 days consider dengue ('+gto('dengue','dengue')+'), typhoid, leptospirosis after floods, measles (check vaccination)'])+drugs(['pdAmp','pdGent','pdCtx','pdAcy'],w); }},
 {id:'pedresp', title:'Croup, bronchiolitis, epiglottitis, foreign body & pediatric pneumonia', kw:'croup Westley dexamethasone nebulized epinephrine bronchiolitis RSV high flow epiglottitis stridor foreign body aspiration pneumonia amoxicillin wheeze', h:'🫁 Stridor, wheeze &amp; pneumonia',
  inputs: sel('wsStr','Stridor',[['0','None'],['1','With agitation'],['2','At rest']])+sel('wsRet','Retractions',[['0','None'],['1','Mild'],['2','Moderate'],['3','Severe']])+sel('wsAir','Air entry',[['0','Normal'],['1','Decreased'],['2','Markedly decreased']])+sel('wsCy','Cyanosis',[['0','None'],['4','With agitation'],['5','At rest']])+sel('wsLoc','Consciousness',[['0','Normal'],['5','Disoriented']]),
  render:w=>{ const s=['wsStr','wsRet','wsAir','wsCy','wsLoc'].reduce((a,k)=>a+(parseInt(sv(k),10)||0),0);
   return h3('Westley croup score')+score(s,17,'Westley')+`<div class="big">${s<=2?'Mild: dexamethasone, discharge with advice':s<=7?'<span class="soon">Moderate: dexamethasone + consider nebulized epinephrine; observe</span>':'<span class="due">Severe (≥ 8): nebulized epinephrine + dexamethasone, senior/airway help, PICU</span>'}${vt('pd-croup')}</div>`+drugs(['pdDex','pdEpi'],w)+
   tbl(['Condition','Key points'],[['Bronchiolitis (&lt; 2 y)','Supportive: nasal suction, feeding support (NG), oxygen if SpO₂ &lt; 90–92 %, HFNC for work of breathing; salbutamol, steroids, antibiotics and routine CXR not recommended; high risk: &lt; 6–12 wk, prematurity, CHD'],['Epiglottitis / bacterial tracheitis','Toxic, drooling, tripod, muffled voice – keep calm with parent, no throat exam, airway expert in OR; ceftriaxone; Hib vaccination status'],['Foreign body aspiration','Sudden choking, unilateral wheeze; inspiratory/expiratory or decubitus films; rigid bronchoscopy. Button batteries in esophagus = emergency ('+gto('toxmisc','tox')+')'],['Asthma (child)','See '+gto('asthma','asthma card')],['Pneumonia',`Tachypnea and chest indrawing; amoxicillin high dose outpatient; admit if hypoxemic, &lt; 3–6 mo, unable to feed, severe distress${vt('pd-cap')}`]])+drugs(['pdAmox'],w); }},
 {id:'kawasaki', title:'Kawasaki disease & MIS-C (criteria, incomplete KD, IVIG + aspirin)', kw:'Kawasaki disease mucocutaneous lymph node incomplete IVIG aspirin coronary aneurysm MIS-C prolonged fever', h:'❤️ Kawasaki disease',
  inputs: ['kdConj','Bilateral non-exudative conjunctival injection','kdLips','Lip/oral changes (red cracked lips, strawberry tongue)','kdRash','Polymorphous rash','kdExt','Extremity changes (erythema/edema, later peeling)','kdNode','Cervical lymph node ≥ 1.5 cm (usually unilateral)'].reduce((a,x,i,arr)=>i%2?a:a+ck(x,arr[i+1]),'')+ck('kdFev','Fever ≥ 5 days'),
  render:w=>{ const n=nsum(['kdConj','kdLips','kdRash','kdExt','kdNode']), f=nc('kdFev');
   return score(n,5,'principal features')+`<div class="big">${f&&n>=4?'<span class="due">Meets criteria for complete Kawasaki disease → echo, IVIG + aspirin</span>':f&&n>=2?'<span class="soon">Possible incomplete KD → CRP/ESR; if CRP ≥ 3 mg/dL or ESR ≥ 40 check supplementary labs (albumin, ALT, platelets, WBC, urine WBC, anemia) and echo</span>':'Criteria not met – reassess daily if fever persists'}${vt('pd-kd')}</div>`+
   ul(['Infants &lt; 6 months may have fever alone – low threshold for echo','Treat within 10 days of fever onset (ideally ≤ 7) to reduce coronary aneurysms','MIS-C: fever + multisystem involvement + recent SARS-CoV-2 – shock, myocarditis; IVIG + steroids with specialist input','PH: Kawasaki disease is relatively common in East/Southeast Asian children'])+drugs(['pdIvig','pdAsa'],w); }},
 {id:'pecarnhead', title:'PECARN pediatric head injury rule (CT decision)', kw:'PECARN head injury child CT decision minor head trauma concussion', h:'🧠 PECARN head injury',
  inputs: sel('phAge','Age',[['lt2','&lt; 2 years'],['ge2','≥ 2 years']])+h3('&lt; 2 years')+PEC2.map(([id,t])=>ck(id,t)).join('')+h3('≥ 2 years')+PECO.map(([id,t])=>ck(id,t)).join(''),
  render:w=>{ const L=sv('phAge')==='ge2'?PECO:PEC2; const hi=L.some(([id,t,g])=>g===1&&nc(id)), mid=L.some(([id,t,g])=>g===2&&nc(id));
   return `<div class="big">${hi?'<span class="due">High risk (~4 % ciTBI): CT recommended</span>':mid?'<span class="soon">Intermediate risk (~0.9 %): CT vs observation – consider experience, multiple findings, worsening, age &lt; 3 mo, parental preference</span>':'<span class="ok">Very low risk (&lt; 0.05 %): CT not recommended</span>'}</div>`+
   nt('Applies to GCS 14–15 within 24 h of injury. Severe mechanism: MVC with ejection/rollover/death, pedestrian or unhelmeted cyclist struck, fall &gt; 0.9 m (&lt; 2 y) or &gt; 1.5 m (≥ 2 y), head struck by high-impact object. Consider abuse in infants (' + gto('childabuse','child maltreatment') + ').'); }},
 {id:'neonate', title:'Neonatal emergencies & BRUE (sick neonate, jaundice, duct-dependent lesions, inborn errors)', kw:'neonate sick newborn BRUE ALTE jaundice hyperbilirubinemia duct dependent prostaglandin alprostadil inborn errors metabolism hyperammonemia SUID newborn screening', h:'👶 Neonatal emergencies &amp; BRUE',
  render:w=>h3('Sick neonate – think broadly')+ul(['Sepsis (most common) – cultures and antibiotics early (see febrile infant)','Cardiac: duct-dependent lesion presents day 3–14 with shock/cyanosis, weak femoral pulses, hepatomegaly → alprostadil'+vt('pd-pge'),'Metabolic: hypoglycemia, inborn errors (vomiting, lethargy, acidosis, high ammonia), congenital adrenal hyperplasia (salt-wasting, low Na/high K)'+vt('pd-meta'),'Surgical: bilious vomiting = malrotation with volvulus until proven otherwise → urgent surgery/contrast study; NEC; Hirschsprung','Neurologic: seizures (subtle), non-accidental trauma; toxins/formula errors','PH: check expanded newborn screening results (RA 9288 – includes G6PD deficiency, CAH, MSUD, galactosemia)'])+drugs(['pdPge'],w)+
   h3('Jaundice')+ul(['Jaundice in first 24 h, rapidly rising, conjugated (pale stools/dark urine), or unwell infant → urgent evaluation','Total serum bilirubin plotted on hour-specific AAP 2022 thresholds; risk factors lower thresholds (prematurity, hemolysis/G6PD deficiency, sepsis, albumin &lt; 3)'+vt('pd-jaun'),'Feeding support; intensive phototherapy; exchange transfusion if at threshold or signs of encephalopathy'])+
   h3('BRUE (brief resolved unexplained event)')+ul(['&lt; 1 y; &lt; 1 min; resolved; unexplained after history/exam: cyanosis/pallor, absent/irregular breathing, tone change, altered responsiveness','<b>Lower risk</b>: age &gt; 60 d, GA ≥ 32 wk (PCA ≥ 45 wk), first event, &lt; 1 min, no CPR by trained provider, no concerning features → education, CPR training, brief observation with pulse oximetry, ECG optional','Higher risk → admit/observe; consider abuse, infection (pertussis, RSV), seizures, cardiac (long QT), metabolic','Sudden unexpected infant death: support family, medico-legal notification; safe-sleep counselling for siblings'])},
 {id:'pedabd', title:'Pediatric abdomen & GU: intussusception, pyloric stenosis, volvulus, appendicitis, torsion, UTI, dehydration', kw:'intussusception pyloric stenosis malrotation volvulus bilious vomiting appendicitis testicular torsion TWIST UTI pediatric dehydration ORS hernia', h:'🧸 Pediatric abdomen &amp; GU',
  render:w=>tbl(['Condition','Key points'],[['Intussusception','6 mo–3 y, intermittent colicky pain with drawing up of legs, lethargy, vomiting, "red currant jelly" stool (late); ultrasound (target sign) → air/hydrostatic enema; surgery if perforation/peritonitis'],['Pyloric stenosis','2–8 weeks, projectile non-bilious vomiting, hungry; hypochloremic hypokalemic metabolic alkalosis; ultrasound; correct fluids/electrolytes before surgery'],['Malrotation/volvulus','Bilious (green) vomiting in infant = surgical emergency'],['Appendicitis','Younger children perforate more often; Pediatric Appendicitis Score/ultrasound first, limit CT'],['Testicular torsion','Peak neonatal &amp; adolescent; absent cremasteric reflex, high-riding testis; TWIST score; urology without delay (do not wait for ultrasound if high suspicion; 6-hour window)'],['Incarcerated inguinal hernia','Reduce with analgesia; surgery if irreducible/ischemic'],['Dehydration','Assess with clinical dehydration scale; ORS first ('+gto('nvd','ORS plans')+'); hypoglycemia check'],['UTI',`Catheter or suprapubic sample in non-toilet-trained; febrile UTI in &lt; 2 mo = admit/IV; renal ultrasound after first febrile UTI &lt; 2 y${vt('pd-uti')}`]])+drugs(['pdCfx'],w)},
 {id:'pedortho', title:'Pediatric orthopedics: limp, septic hip, SCFE, Perthes, Salter–Harris, supracondylar', kw:'limp septic hip child transient synovitis SCFE slipped capital femoral epiphysis Perthes Salter Harris supracondylar toddler fracture osteomyelitis', h:'🦿 Pediatric orthopedics &amp; limp',
  render:w=>tbl(['Condition','Key points'],[['Septic hip vs transient synovitis','Fever, non-weight-bearing, ESR/CRP, WBC → Kocher criteria ('+gto('hotjoint','hot joint card')+'); ultrasound for effusion; aspirate if suspicious'],['SCFE','10–16 y, obese; hip, thigh <b>or knee</b> pain; frog-leg lateral X-ray; non-weight-bearing, urgent orthopedics'],['Perthes','4–10 y, painless/mild limp; X-ray; orthopedics'],['Osteomyelitis','Bone tenderness, fever; MRI; S. aureus coverage'],['Toddler fracture','Spiral tibial fracture, may be occult; immobilize, repeat X-ray'],['Salter–Harris','Physis injuries (I–V): types III–V need orthopedics; tenderness over physis with normal X-ray = presume type I'],['Supracondylar humerus','Check radial pulse, AIN/radial/ulnar nerves; pulseless pink vs white hand ('+gto('upperlimb','upper limb')+')'],['Leukemia/tumor','Night pain, systemic symptoms, abnormal CBC – do not miss']])},
 {id:'childabuse', title:'Child maltreatment – sentinel injuries, TEN-4-FACESp, skeletal survey, PH reporting (RA 7610)', kw:'child abuse maltreatment neglect non-accidental injury abusive head trauma shaken baby TEN-4 skeletal survey RA 7610 Bantay Bata WCPU', h:'🧒 Child maltreatment',
  render:w=>ul(['Red flags: history inconsistent with injury/development ("those who don\'t cruise rarely bruise"), delay in seeking care, changing story, injury blamed on sibling','<b>TEN-4-FACESp</b> bruising: Torso, Ears, Neck, Frenulum, Angle of jaw, Cheeks, Eyelids, Subconjunctivae in &lt; 4 y; <b>any</b> bruise in an infant &lt; 4–6 months; patterned bruises','High-specificity fractures: classic metaphyseal lesions, posterior rib, scapula, spinous process, sternum; multiple fractures of different ages','Abusive head trauma: irritability, vomiting, seizures, apnea, bulging fontanelle; subdural hematoma + retinal hemorrhage','Work-up (&lt; 2 y with concerns): skeletal survey, CT head (± MRI), ophthalmology, LFTs/lipase (abdominal injury), urinalysis, coagulation screen; screen siblings',`Neglect, sexual abuse (refer to WCPU – ${gto('sexassault','sexual assault')}), medical child abuse also occur`,`<b>PH</b>: RA 7610 – report suspected abuse to DSWD/PNP; hospital Women and Children Protection Unit (WCPU); DSWD Bantay Bata 163${vt('pd-law')}`,'Admit when safety is uncertain; document objectively with body map and photographs'])},
 {id:'pdsrc', title:'Pediatric emergencies sources', h:'📚 Pediatric emergencies sources', render:w=>nt('Pantell et al., AAP CPG febrile infants 8–60 days (Pediatrics 2021) · Kuppermann et al., PECARN febrile infant rule (JAMA Pediatr 2019) · Kuppermann et al., PECARN head injury rule (Lancet 2009) · Ralston et al., AAP bronchiolitis guideline 2014 · Gates et al., Cochrane glucocorticoids for croup 2023; Westley score (1978) · McCrindle et al., AHA Kawasaki statement 2017 · Tieder et al., AAP BRUE guideline 2016 · Kemper et al., AAP hyperbilirubinemia 2022 · AAP UTI guideline 2011 (reaffirmed 2016) · Bradley et al., IDSA pediatric CAP 2011; PIDSP/PAPP pediatric CAP guideline 2016 · Kocher et al. (JBJS 1999) · Pierce et al., TEN-4-FACESp (JAMA Netw Open 2021) · Philippine RA 7610, RA 9288 (Newborn Screening Act) · BIMDG emergency guidelines. Tintinalli 9e Section 12 used only as a topic map.')}
]);
