// ======================= S24 PSYCHOSOCIAL DISORDERS =======================
// Sources: Project BETA consensus (WestJEM 2012); NICE NG10 violence & aggression 2015; ACEP agitation policy 2023; NICE CG115/ASAM 2020 alcohol withdrawal; RCP Wernicke guidance;
// Columbia C-SSRS / NIMH ASQ; PH RA 11036 Mental Health Act (2018) & IRR; NCMH crisis hotline; APA eating disorders 2023 / MARSIPAN.
Object.assign(REVIEW, {
  'ps-agit':  {t:'Agitation (adult): midazolam 5 mg IM (2.5 mg elderly); haloperidol 5 mg IM ± midazolam 5 mg or lorazepam 2 mg; olanzapine 10 mg IM (no parenteral benzodiazepine within 1 h); droperidol 5–10 mg IM; severe/dangerous: ketamine 4–5 mg/kg IM (1–2 mg/kg IV)', r:'BETA 2012 / NICE NG10 / ACEP 2023; elderly and intoxicated need lower doses; ECG for QT with antipsychotics.', tab:'Psych'},
  'ps-agitp': {t:'Pediatric agitation: diphenhydramine 1 mg/kg (max 50 mg) PO/IM; midazolam 0.1–0.15 mg/kg IM (max 5 mg); olanzapine 2.5–5 mg (< 12 y) / 5–10 mg (≥ 12 y); haloperidol 0.05–0.1 mg/kg IM (max 5 mg) in ≥ 6 y', r:'AACAP/BETA pediatric consensus 2019; specialist input.', tab:'Psych / Pediatr'},
  'ps-awd':   {t:'Alcohol withdrawal: CIWA-Ar ≥ 10 → diazepam 10–20 mg PO/IV q1–2h (or lorazepam 2–4 mg if liver failure/elderly); refractory: phenobarbital 10 mg/kg IV over 30 min (or escalating doses) in monitored setting', r:'ASAM 2020; phenobarbital loading regimens vary.', tab:'Psych'},
  'ps-thia':  {t:'Thiamine: prophylaxis 100–250 mg IV/IM daily; suspected Wernicke encephalopathy 500 mg IV TID × 3 days then 250 mg daily', r:'RCP/EFNS; give before or with glucose (do not delay glucose).', tab:'Psych / Neuro'},
  'ps-dyst':  {t:'Acute dystonia: diphenhydramine 25–50 mg IV/IM (peds 1 mg/kg, max 50 mg) or benztropine 1–2 mg IV/IM; akathisia: propranolol 10–20 mg or diphenhydramine', r:'Standard practice.', tab:'Psych'},
  'ps-mha':   {t:'PH Mental Health Act (RA 11036, 2018): voluntary, informed consent is the default; emergency treatment without consent is permitted only to prevent imminent harm, for up to 72 h, documented and reviewed', r:'Summary of IRR provisions – confirm details with hospital legal/psychiatry.', tab:'Psych'},
  'ps-hot':   {t:'PH NCMH Crisis Hotline: 1553 (Luzon-wide toll-free landline), 0917-899-8727 / 0966-351-4518 / 0908-639-2672', r:'Numbers from public NCMH listings – confirm before posting.', tab:'Psych'},
  'ps-refeed':{t:'Eating disorder admission thresholds (adult): HR < 40–50, SBP < 90, K < 3.0, phosphate < 0.8 mmol/L, BMI < 13–15, syncope, temperature < 35.5 °C; start refeeding cautiously (thiamine, phosphate monitoring)', r:'MARSIPAN/APA 2023 thresholds vary; adolescents have stricter criteria.', tab:'Psych'}
});
Object.assign(D, {
  psMdz: {n:'Midazolam IM – agitation', flag:'ps-agit', a:[F('IM','5 mg (2.5 mg if elderly/frail); repeat after 10–15 min if needed')], p:[B('IM',0.1,0.15,'mg/kg',{max:5,flag:'ps-agitp'})]},
  psHalo: {n:'Haloperidol (± benzodiazepine)', flag:'ps-agit', a:[F('IM','5 mg (2.5 mg elderly), may combine with midazolam 5 mg; ECG when feasible')], p:[B('IM (≥ 6 y)',0.05,0.1,'mg/kg',{max:5,flag:'ps-agitp'})]},
  psOlz: {n:'Olanzapine', flag:'ps-agit', a:[F('IM / ODT','10 mg (5 mg elderly); no IM benzodiazepine within 1 h')], p:[C('PO / IM',w=>{ const y=ageYears(); return {main: y==null?'Enter age':y<12?'2.5 – 5 mg':'5 – 10 mg', lines:[]}; },{flag:'ps-agitp'})]},
  psKet: {n:'Ketamine – severe dangerous agitation', flag:'ps-agit', a:[B('IM',4,5,'mg/kg',{conc:50,note:'Or 1–2 mg/kg IV. Airway-capable clinician, monitoring; laryngospasm, emergence.'})]},
  psDiph: {n:'Diphenhydramine – mild agitation (child) / acute dystonia', flag:'ps-dyst', a:[F('IV/IM','25 – 50 mg')], p:[B('PO / IM / IV',1,1,'mg/kg',{max:50})]},
  psDzp: {n:'Diazepam – alcohol withdrawal (symptom-triggered)', flag:'ps-awd', a:[F('PO / IV','10 – 20 mg q1–2h while CIWA-Ar ≥ 10 (IV 5–10 mg q5–10 min for severe)'),F('Lorazepam (liver failure, elderly)','1 – 4 mg PO/IV q1–2h')]},
  psPhb: {n:'Phenobarbital – refractory alcohol withdrawal', flag:'ps-awd', a:[B('IV over 30 min',10,10,'mg/kg',{note:'Monitored setting; additive respiratory depression with benzodiazepines.'})]},
  psThia: {n:'Thiamine', flag:'ps-thia', a:[F('Prophylaxis','100 – 250 mg IV/IM daily'),F('Suspected Wernicke','500 mg IV TID × 3 days, then 250 mg daily')], p:[F('Children (malnutrition)','10 – 25 mg IV/IM daily (specialist)')]}
});
const CIWA=[['cwN','Nausea/vomiting',7],['cwT','Tremor',7],['cwS','Sweating',7],['cwA','Anxiety',7],['cwG','Agitation',7],['cwTa','Tactile disturbance',7],['cwAu','Auditory disturbance',7],['cwV','Visual disturbance',7],['cwH','Headache',7],['cwO','Orientation',4]];
defCards('psych','Psych',[
 {id:'psyeval', title:'Mental health evaluation, medical clearance, capacity & PH Mental Health Act', kw:'psychiatric evaluation medical clearance capacity involuntary RA 11036 Mental Health Act consent hotline NCMH', h:'🧠 Mental health evaluation',
  render:w=>ol(['Safety first: search/remove dangerous items, safe room, observation level; staff never alone with an agitated patient','<b>Medical evaluation</b>: vital signs, glucose, focused history/exam; look for delirium (fluctuating attention), intoxication/withdrawal, head injury, hypoxia, infection, thyroid disease. Routine labs are not required when history/exam are reassuring','Red flags for organic cause: age &gt; 40 with first psychiatric episode, abnormal vitals, visual hallucinations, disorientation, focal neurology, recent medication change','<b>Capacity</b> is decision-specific: understands, retains, weighs, communicates – document',`PH RA 11036 Mental Health Act: rights, informed consent, least-restrictive care; emergency treatment without consent only to prevent imminent harm, time-limited and documented${vt('ps-mha')}`,`Crisis support: NCMH Crisis Hotline 1553${vt('ps-hot')}`])},
 {id:'agitation', title:'Acute agitation – de-escalation, IM sedation (midazolam, haloperidol, olanzapine, ketamine), restraint', kw:'agitation violence aggression sedation midazolam haloperidol olanzapine droperidol ketamine restraint de-escalation shabu methamphetamine', h:'😠 Acute agitation',
  render:w=>ol(['<b>Verbal de-escalation</b>: one calm speaker, respect personal space, listen, offer choices (food, drink, oral medication), set clear limits','Offer <b>oral</b> medication if cooperating (lorazepam 1–2 mg, olanzapine ODT 5–10 mg, risperidone 2 mg)'+vt('ps-agit'),'Danger to self/others → IM medication; physical restraint only as a last resort, minimum time, continuous observation, vital signs every 15 min, document',`Methamphetamine ("shabu") intoxication: benzodiazepines first, cool, check temperature/CK/ECG (${gto('symp','Tox: sympathomimetic')})`])+drugs(['psMdz','psHalo','psOlz','psKet','psDiph'],w)+
   ul(['After sedation: airway position, SpO₂, capnography if deep, glucose, temperature, search for cause','Excited delirium features (hyperthermia, extreme agitation, superhuman strength) → rapid sedation, cooling, avoid prone restraint (asphyxia)'])},
 {id:'suicide', title:'Suicide risk & self-harm (screening, safety, disposition)', kw:'suicide self-harm overdose risk assessment C-SSRS ASQ means restriction safety plan depression', h:'🆘 Suicide risk &amp; self-harm',
  render:w=>ol(['Treat the medical injury/overdose first ('+gto('txapproach','Tox approach')+'); paracetamol level in every intentional overdose','Screen: ask directly about suicidal thoughts, plan, intent, means, previous attempts (C-SSRS screener; ASQ for 10–24 y) – asking does not increase risk','High risk: plan/intent, recent attempt, access to lethal means (pesticides, firearms, medication stockpiles), psychosis, intoxication, hopelessness, social isolation, recent loss','Constant observation, remove belongings with potential for harm, psychiatric assessment before discharge','Discharge only if low risk with a safety plan, means restriction counselling (family to secure medicines/pesticides), follow-up within days, crisis numbers'+vt('ps-hot')])},
 {id:'psychosis', title:'Psychosis, mood & anxiety disorders, older adults (delirium vs dementia), eating disorders', kw:'psychosis schizophrenia mania depression anxiety panic attack delirium dementia CAM older adults eating disorder anorexia refeeding dystonia', h:'💭 Psychosis, mood, anxiety &amp; older adults',
  render:w=>ul(['New psychosis: exclude delirium, substances (methamphetamine, cannabis, steroids), encephalitis (autoimmune/HSV), HIV, thyroid, seizures; urine drug screen helps little','Antipsychotic side effects: acute dystonia/oculogyric crisis, akathisia → diphenhydramine/benztropine'+vt('ps-dyst')+'; NMS ('+gto('symp','Tox')+'); QT prolongation','Mania: sleep loss, grandiosity – lithium toxicity check if on lithium ('+gto('toxmisc','Tox: lithium')+')','Panic attack is a diagnosis of exclusion: ECG, SpO₂, glucose; consider PE, ACS, thyrotoxicosis, arrhythmia, asthma','<b>Older adults</b>: delirium (acute, fluctuating, inattention – CAM) is a medical emergency; avoid benzodiazepines/anticholinergics; low-dose haloperidol only if distressing/dangerous; look for urinary retention, constipation, infection, drugs, pain',`<b>Eating disorders</b>: bradycardia, hypotension, hypokalemia, hypophosphatemia, hypoglycemia – admit if unstable; refeeding syndrome risk${vt('ps-refeed')}`])+drugs(['psDiph'],w)},
 {id:'awd', title:'Alcohol withdrawal (CIWA-Ar calculator), Wernicke, substance use disorders', kw:'alcohol withdrawal CIWA delirium tremens seizures diazepam lorazepam phenobarbital thiamine Wernicke substance use lambanog', h:'🍺 Alcohol withdrawal &amp; substance use',
  inputs: CIWA.map(([id,t,mx])=>sel(id,`${t} (0–${mx})`,Array.from({length:mx+1},(_,i)=>[String(i),String(i)]))).join(''),
  render:w=>{ const s=CIWA.reduce((a,[id])=>a+(parseInt(sv(id),10)||0),0);
   return score(s,67,'CIWA-Ar')+`<div class="big">${s<10?'&lt; 10: minimal – supportive care, reassess q4–8h':s<=18?'<span class="soon">10–18: moderate – symptom-triggered benzodiazepine, reassess hourly</span>':'<span class="due">&gt; 18: severe – frequent IV benzodiazepines, monitored bed, consider phenobarbital/ICU</span>'}${vt('ps-awd')}</div>`+
   ul(['Timeline: tremor/anxiety 6–24 h; seizures 12–48 h; hallucinosis 12–48 h; delirium tremens 48–96 h (mortality without treatment)','CIWA requires a communicating patient; if sedated/delirious use RASS-guided treatment','<b>Thiamine before or with glucose</b> in every malnourished/alcohol-dependent patient; Wernicke = confusion, ataxia, ophthalmoplegia (often incomplete)'+vt('ps-thia'),'Also replace Mg, K, phosphate; look for head injury, GI bleed, pancreatitis, infection, hypoglycemia, methanol from adulterated lambanog ('+gto('toxalc','Tox: toxic alcohols')+')'])+drugs(['psDzp','psPhb','psThia'],w)+
   ul(['Other substance use: methamphetamine (most common illicit drug in PH), cannabis, inhalants ("rugby" solvent sniffing in street children), opioids ('+gto('naloxone','naloxone')+') – brief intervention and referral to DOH-accredited treatment and rehabilitation centres']); }},
 {id:'pssrc', title:'Psychosocial sources', h:'📚 Psychosocial sources', render:w=>nt('Holloman &amp; Zeller, Project BETA consensus statements (West J Emerg Med 2012) · NICE NG10 violence and aggression 2015 · ACEP clinical policy: severe agitation 2023 · Gerson et al., BETA pediatric agitation consensus 2019 · ASAM clinical practice guideline on alcohol withdrawal management 2020 · Sullivan et al., CIWA-Ar (Br J Addict 1989) · Thomson et al., RCP Wernicke guidance · Posner et al., C-SSRS; NIMH ASQ toolkit · Philippine RA 11036 Mental Health Act and IRR (2018) · National Center for Mental Health crisis hotline · APA eating disorders guideline 2023; MARSIPAN. Tintinalli 9e Section 24 used only as a topic map.')}
]);
