// ======================= S4 RESUSCITATIVE PROCEDURES (extends v1) =======================
// Sources: AHA 2020 guidelines + 2023/2024 focused updates (post-arrest care, TTM); ILCOR 2023 temperature control; ERC-ESICM post-resuscitation 2021/2025; BLS/ALS termination-of-resuscitation rules (Morrison 2006);
// INS vascular access standards 2021; ASE/ESC pericardial disease 2015; ACC/AHA bradycardia 2018 (pacing).
Object.assign(REVIEW, {
  'rp-io':   {t:'IO in conscious patient: 2 % lidocaine (preservative-free) 40 mg (2 mL) slowly over 2 min via IO, wait 60 s, flush, then 20 mg; peds 0.5 mg/kg (max 40 mg)', r:'Manufacturer (EZ-IO) guidance.', tab:'Resus proc'},
  'rp-post': {t:'Post-arrest targets: SpO₂ 92–98 %, PaCO₂ 35–45 mmHg, MAP ≥ 65 (consider higher), glucose 140–180 mg/dL, prevent fever (≤ 37.5 °C) for ≥ 72 h (TTM 32–36 °C optional per AHA 2023), prognosticate ≥ 72 h after normothermia', r:'AHA 2023 / ILCOR 2023 / ERC-ESICM 2025.', tab:'Resus proc'},
  'rp-mon':  {t:'Monitoring targets: MAP ≥ 65 mmHg, capillary refill ≤ 3 s, urine output ≥ 0.5 mL/kg/h, PLR stroke-volume rise ≥ 10–15 %, ScvO₂ ≥ 70 %', r:'SSC 2021 / ANDROMEDA-SHOCK.', tab:'Resus proc'},
  'rp-pace': {t:'Transcutaneous pacing: rate 60–80/min, increase output from ~50 mA until electrical capture then add ~10 % (often 50–100 mA); confirm mechanical capture by pulse/ultrasound; analgesia/sedation (e.g. fentanyl 0.5–1 mcg/kg, midazolam 1–2 mg)', r:'ACC/AHA 2018 bradycardia guideline.', tab:'Resus proc'}
});
Object.assign(D, {
  rpIoLido: {n:'Lidocaine 2 % (preservative-free) – IO infusion pain', flag:'rp-io', a:[F('IO','40 mg (2 mL) over 2 min, wait 60 s, flush; then 20 mg')], p:[B('IO over 2 min',0.5,0.5,'mg/kg',{max:40})]}
});
defCards('proc','Resus proc|Proc',[
 {id:'vascaccess', title:'Vascular access – ultrasound-guided IV, intraosseous, central venous, arterial line', kw:'vascular access intraosseous IO ultrasound guided IV central line femoral internal jugular arterial line Seldinger', h:'🩸 Vascular access',
  render:w=>tbl(['Route','Key points'],[['Peripheral IV','Two large-bore (16–18 gauge) for resuscitation; ultrasound-guided long catheters for difficult access'],['Intraosseous','Fastest in arrest/shock: proximal tibia (2 cm below tibial tuberosity, medial), proximal humerus (adults – faster flow, arm adducted, hand on abdomen), distal femur in infants; all drugs/blood can be given; pressure bag; avoid fractured bone, prosthesis, infected site; remove within 24 h'+vt('rp-io')],['Central venous','Ultrasound-guided IJ or femoral (femoral fastest in arrest – compressions not interrupted); confirm venous placement (ultrasound/manometry) before dilating; CXR for IJ/subclavian'],['Arterial line','Radial (ultrasound); for vasopressors, frequent ABGs, labile BP'],['Children','IO after 2 failed IV attempts or 90 s in arrest; umbilical venous catheter in neonates']])+drugs(['rpIoLido'],w)},
 {id:'hemomon', title:'Hemodynamic monitoring – MAP, fluid responsiveness, lactate, ScvO₂', kw:'hemodynamic monitoring MAP fluid responsiveness passive leg raise IVC pulse pressure variation lactate ScvO2 capillary refill', h:'📈 Hemodynamic monitoring',
  render:w=>ul(['MAP ≥ 65 mmHg for most shock (higher if chronic hypertension; permissive lower targets in uncontrolled hemorrhage until control, except head injury)','Fluid responsiveness: passive leg raise with real-time stroke volume/VTI (≥ 10–15 % rise), pulse pressure variation in ventilated patients in sinus rhythm; IVC size/collapse is a weak guide','Perfusion targets: capillary refill ≤ 3 s (ANDROMEDA-SHOCK), lactate clearance, urine output ≥ 0.5 mL/kg/h, mentation'+vt('rp-mon'),'ScvO₂ &lt; 70 % suggests inadequate delivery (anemia, low output); very high ScvO₂ with high lactate – mitochondrial/shunt (sepsis, cyanide)','Stop fluids when no longer responsive or signs of congestion (B-lines, rising JVP, hypoxemia)'])},
 {id:'pericardio', title:'Pericardiocentesis – ultrasound-guided', kw:'pericardiocentesis tamponade pericardial effusion ultrasound guided subxiphoid parasternal', h:'💧 Pericardiocentesis',
  render:w=>ol(['Indication: tamponade with hemodynamic compromise (non-traumatic, or traumatic as a bridge to surgery – '+gto('chesttr','chest trauma')+')','Ultrasound to find the largest, closest pocket: parasternal (5th ICS, lateral to sternum – avoid internal mammary 1 cm lateral) or apical or subxiphoid','Sterile prep, local anesthesia; 18-gauge needle/catheter; aspirate as you advance under ultrasound; agitated saline confirms position','Seldinger pigtail catheter left for drainage; removing even a small volume may restore BP','Complications: ventricular puncture, coronary laceration, pneumothorax, arrhythmia; ECG monitoring throughout'])},
 {id:'postarrest', title:'Post-cardiac arrest care – targets, temperature control, prognostication', kw:'post-arrest post cardiac arrest ROSC care targeted temperature management TTM fever prevention prognostication coronary angiography', h:'💓 Post-arrest care',
  render:w=>ol(['Airway secured, ETCO₂ waveform; ventilate to normocapnia; titrate FiO₂ to SpO₂ 92–98 % (avoid hyperoxia and hypoxia)'+vt('rp-post'),'12-lead ECG: STEMI → emergent coronary angiography; no STEMI but likely cardiac cause → individualised','Hemodynamics: MAP ≥ 65, avoid hypotension; norepinephrine first-line; echo','Temperature: actively prevent fever (≤ 37.5 °C) for at least 72 h in comatose patients; avoid prophylactic prehospital cold fluids','Seizures: EEG if comatose; treat clinical seizures; glucose control; sedation/analgesia','Find and treat cause (H’s and T’s – '+gto('algo','ACLS card')+')','Prognostication: multimodal, not before 72 h after normothermia/sedation clearance; avoid premature withdrawal'])},
 {id:'pacing', title:'Cardiac pacing & implanted devices (transcutaneous, transvenous, magnet use)', kw:'transcutaneous pacing transvenous pacemaker ICD magnet bradycardia capture', h:'🔋 Pacing &amp; implanted devices',
  render:w=>ul(['Unstable bradycardia unresponsive to atropine: transcutaneous pacing or chronotropic infusion (epinephrine/dopamine – '+gto('arrestdrugs','arrest drugs')+')','Pads anterior–posterior; set rate, increase output until capture; confirm mechanical capture'+vt('rp-pace'),'Transvenous pacing (right IJ/left subclavian) as soon as possible if ongoing pacing needed','<b>Magnet</b> over a pacemaker → asynchronous pacing (useful for pacemaker-mediated tachycardia); over an ICD → suspends shocks (inappropriate shocks), pacing unaffected','Pacemaker malfunction: failure to pace, failure to capture, under/over-sensing – CXR (lead position), electrolytes, device interrogation','Defibrillating patients with devices: pads ≥ 8 cm from the generator, interrogate afterwards'])},
 {id:'resethics', title:'Ethics of resuscitation – DNR, termination of resuscitation, family presence', kw:'ethics resuscitation DNR do not resuscitate termination of resuscitation TOR rule futility family presence advance directive', h:'⚖️ Ethics of resuscitation',
  render:w=>ul(['Respect valid patient wishes (advance directives, DNR orders); when unknown, resuscitate and clarify','BLS termination-of-resuscitation rule (out-of-hospital): arrest not witnessed by EMS, no shock delivered, no ROSC before transport → consider stopping (validated in adults)','Factors favouring stopping: prolonged downtime without CPR, persistent asystole, ETCO₂ &lt; 10 mmHg after 20 min of high-quality ALS (one factor, never alone)','Factors favouring continuing: hypothermia, drowning in cold water, toxicologic arrest, pregnancy, ECPR candidate','Offer family presence; designate a staff member to support them','PH: no specific advance-directive law – follow hospital DNR policy, document discussion with patient/family; '+gto('deathnotif','death notification')])},
 {id:'rpsrc', title:'Resuscitative procedures (extended) sources', h:'📚 Resuscitative procedures (extended) sources', render:w=>nt('Perman et al., AHA 2023 focused update on adult advanced cardiovascular life support · Nolan et al., ERC-ESICM post-resuscitation care guidelines 2021/2025 · ILCOR temperature control CoSTR 2023 · Morrison et al., BLS termination-of-resuscitation rule (NEJM 2006) · Gorski et al., INS Infusion Therapy Standards of Practice 2021 · Adler et al., ESC pericardial diseases 2015 · Kusumoto et al., ACC/AHA/HRS bradycardia guideline 2018 · Hernández et al., ANDROMEDA-SHOCK (JAMA 2019) · Monnet et al., passive leg raising (Crit Care 2015). Tintinalli 9e Section 4 used only as a topic map.')}
]);
