// ======================= S3 RESUSCITATION (extends v1) – shock, acid–base, HBO, sudden cardiac death =======================
// Sources: SSC 2021; Perera et al., RUSH exam (2010); Berend et al., acid–base (NEJM 2014) / Winter's formula; UHMS indications 13th/15th ed; ESC 2022 ventricular arrhythmias & SCD; Brugada expert consensus (J-wave 2016).
Object.assign(REVIEW, {
  'rs-push': {t:'Push-dose epinephrine (bridge only): 10 mcg/mL, give 0.5–2 mL (5–20 mcg) IV q2–5 min; peds 1 mcg/kg (max 10–20 mcg); start norepinephrine infusion early', r:'Common ED practice; dilution errors reported – use pre-made syringes if available.', tab:'Resus'},
  'rs-fluid':{t:'Undifferentiated shock: crystalloid boluses 250–500 mL (peds 10–20 mL/kg) with reassessment after each; norepinephrine 0.05–0.5 mcg/kg/min early if MAP < 65 despite fluids', r:'SSC 2021; avoid fixed large volumes in cardiogenic shock.', tab:'Resus'},
  'rs-hbo':  {t:'HBO indications per UHMS (CO poisoning with LOC/neurologic signs/pregnancy/COHb > 25 %, decompression sickness, arterial gas embolism, necrotizing infections, crush, CRAO, etc.); PH chambers are few – contact facility early', r:'UHMS 15th ed; PH chamber locations must be confirmed (Navy/AFP and a few private hospitals).', tab:'Resus'}
});
Object.assign(D, {
  rsPush: {n:'Push-dose epinephrine (10 mcg/mL)', flag:'rs-push', a:[F('IV','5 – 20 mcg (0.5–2 mL) every 2–5 min')], p:[B('IV',1,1,'mcg/kg',{max:10,note:'10 mcg/mL dilution.'})]}
});
defCards('shock','Resus|Shock',[
 {id:'undiffshock', title:'Undifferentiated shock – RUSH exam, first steps, push-dose pressors', kw:'shock hypotension undifferentiated RUSH ultrasound pump tank pipes lactate push dose epinephrine norepinephrine obstructive distributive cardiogenic hypovolemic', h:'📉 Undifferentiated shock',
  render:w=>ol(['Recognise: hypotension <i>or</i> hypoperfusion (mottling, cap refill &gt; 3 s, altered mentation, oliguria, lactate &gt; 2–4) – normotensive shock exists','Two large-bore IVs/IO, monitor, lactate, VBG, glucose, ECG, cultures if sepsis possible','<b>RUSH</b> ultrasound – <b>Pump</b> (effusion/tamponade, LV function, RV dilation), <b>Tank</b> (IVC, FAST, pleural fluid, lung B-lines), <b>Pipes</b> (aortic aneurysm/dissection, DVT)','Treat by type: hypovolemic/hemorrhagic → blood ('+gto('mtp','MTP')+'); distributive → fluids + norepinephrine ('+gto('pressors','pressors')+'), anaphylaxis ('+gto('anaph','anaphylaxis')+'), adrenal ('+gto('adrenal','adrenal crisis')+'); cardiogenic → cautious fluid, inotrope, revascularization; obstructive → decompress PTX, drain tamponade, lyse massive PE ('+gto('pe','PE')+')',`Fluids in small boluses with reassessment${vt('rs-fluid')}; start norepinephrine peripherally if needed (large proximal vein, check site)`,'Push-dose epinephrine only as a bridge during intubation or while preparing infusion'])+drugs(['rsPush'],w)},
 {id:'abg', title:'Acid–base & blood gas interpreter (anion gap, Winter\'s, delta ratio)', kw:'acid base ABG VBG blood gas anion gap Winters formula delta ratio metabolic acidosis alkalosis respiratory compensation osmolar gap', h:'⚗️ Acid–base interpreter',
  inputs: num('abPH','pH','7.25','0.01')+num('abCO2','PaCO₂ (mmHg)','30')+num('abHCO3','HCO₃⁻ (mEq/L)','14')+num('abNa','Na (mEq/L)','138')+num('abCl','Cl (mEq/L)','104')+num('abAlb','Albumin (g/dL)','4.0','0.1'),
  render:w=>{ const ph=fv('abPH'), co2=fv('abCO2'), hc=fv('abHCO3'), na=fv('abNa'), cl=fv('abCl'), alb=fv('abAlb');
   if(ph==null||co2==null||hc==null) return '<div class="big">Enter pH, PaCO₂ and HCO₃⁻</div>'+nt('Venous pH runs ~0.03 lower and venous HCO₃⁻ ~1–2 higher than arterial; VBG PCO₂ is unreliable for exact CO₂ in shock.');
   const L=[]; let prim;
   if(ph<7.35) prim = hc<22 ? 'met-acid' : co2>45 ? 'resp-acid' : 'mixed';
   else if(ph>7.45) prim = hc>26 ? 'met-alk' : co2<35 ? 'resp-alk' : 'mixed';
   else prim = (hc<22&&co2<35)||(hc>26&&co2>45) ? 'mixed-normal' : 'normal';
   const names={'met-acid':'Metabolic acidosis','resp-acid':'Respiratory acidosis','met-alk':'Metabolic alkalosis','resp-alk':'Respiratory alkalosis','mixed':'Mixed disorder','mixed-normal':'Normal pH with abnormal CO₂/HCO₃⁻ – compensated or mixed disorder','normal':'No acid–base disorder evident'};
   L.push(`<b>${names[prim]}</b>`);
   if(prim==='met-acid'){ const e=1.5*hc+8; L.push(`Winter's expected PaCO₂ ${(e-2).toFixed(0)}–${(e+2).toFixed(0)} mmHg → ${co2>e+2?'<span class="due">concurrent respiratory acidosis</span>':co2<e-2?'<span class="soon">concurrent respiratory alkalosis</span>':'appropriate compensation'}`); }
   if(prim==='met-alk'){ const e=0.7*hc+21; L.push(`Expected PaCO₂ ≈ ${(e-2).toFixed(0)}–${(e+2).toFixed(0)} mmHg → ${co2>e+2?'concurrent respiratory acidosis':co2<e-2?'concurrent respiratory alkalosis':'appropriate compensation'}`); }
   if(prim==='resp-acid'){ const d=(co2-40)/10; L.push(`Expected HCO₃⁻: acute ${(24+d).toFixed(0)}, chronic ${(24+3.5*d).toFixed(0)} mEq/L`); }
   if(prim==='resp-alk'){ const d=(40-co2)/10; L.push(`Expected HCO₃⁻: acute ${(24-2*d).toFixed(0)}, chronic ${(24-5*d).toFixed(0)} mEq/L`); }
   if(na!=null&&cl!=null){ const ag=na-cl-hc, cag=alb!=null? ag+2.5*(4-alb):ag; L.push(`Anion gap ${ag.toFixed(0)}${alb!=null?` (albumin-corrected ${cag.toFixed(0)})`:''} ${cag>12?'<span class="due">– elevated</span>':'– normal'}`);
     if(cag>12){ const dr=(cag-12)/(24-hc||1); L.push(`Delta ratio ${dr.toFixed(1)} → ${dr<0.4?'hyperchloremic NAGMA':dr<1?'HAGMA + NAGMA':dr<=2?'pure HAGMA':'HAGMA + metabolic alkalosis (or chronic respiratory acidosis)'}`); } }
   return ul(L)+tbl(['Disorder','Common causes'],[['High AG acidosis','Lactate (shock, sepsis, metformin), ketones (DKA, alcohol, starvation), renal failure, toxic alcohols (osmolar gap), salicylate, iron, isoniazid'],['Normal AG acidosis','Diarrhea, large-volume saline, RTA, ureteral diversion, acetazolamide, early renal failure'],['Metabolic alkalosis','Vomiting/NG loss, diuretics, hypokalemia, mineralocorticoid excess, contraction'],['Respiratory acidosis','Hypoventilation: COPD, sedatives/opioids, neuromuscular weakness, obesity hypoventilation'],['Respiratory alkalosis','Anxiety, pain, hypoxemia, PE, sepsis (early), salicylate, pregnancy, liver failure']])+
    nt('Osmolar gap = measured − (2×Na + glucose/18 + BUN/2.8); &gt; 10 suggests toxic alcohol ('+gto('toxalc','toxic alcohols')+'). Interpret with the clinical picture.'); }},
 {id:'hbo', title:'Hyperbaric oxygen therapy – indications & PH access', kw:'hyperbaric oxygen HBO chamber carbon monoxide decompression sickness gas embolism necrotizing infection', h:'🫧 Hyperbaric oxygen',
  render:w=>ul(['Emergency indications: CO poisoning with neurologic signs, LOC, pregnancy or very high COHb ('+gto('co','CO card')+'); decompression sickness and arterial gas embolism (diving – 100 % O₂, supine, fluids, '+gto('drown','diving/drowning')+'); necrotizing soft-tissue infection (adjunct to surgery); crush injury; central retinal artery occlusion (early); severe anemia when transfusion impossible','Contraindication: untreated pneumothorax (insert chest tube before chamber)','Transfer: keep on 100 % O₂; for divers, fly low (cabin pressure ≤ 300 m) or ground transport','PH: very few chambers (naval/military and some private hospitals) – identify the nearest facility in advance and call before transfer'+vt('rs-hbo')])},
 {id:'scd', title:'Sudden cardiac death & survivors – Brugada ("bangungot"), long QT, HCM, WPW', kw:'sudden cardiac death bangungot Brugada long QT HCM WPW ARVC syncope young ECG ICD', h:'⚡ Sudden cardiac death &amp; inherited arrhythmias',
  render:w=>ul(['Survivor of cardiac arrest: post-arrest care ('+gto('postarrest','post-arrest card')+'), 12-lead ECG, echo, coronary angiography if ischemic cause likely','Look on the ECG for: <b>Brugada</b> type 1 pattern (coved ST elevation ≥ 2 mm V1–V2, unmasked by fever), long/short QT, pre-excitation (WPW), epsilon wave/T inversion V1–V3 (ARVC), LVH with deep Q waves (HCM)','PH: <b>bangungot</b> (sudden unexplained nocturnal death in young Southeast Asian men) is linked to Brugada syndrome – treat fever aggressively, avoid sodium-channel blockers and other Brugada-provoking drugs (see brugadadrugs.org), refer for ICD evaluation; screen first-degree relatives','Syncope with exertion, while supine, preceded by palpitations, or family history of sudden death → admit/cardiology','Electrical storm: '+gto('arrhy','arrhythmia card')])},
 {id:'shsrc', title:'Resuscitation (extended) sources', h:'📚 Resuscitation (extended) sources', render:w=>nt('Evans et al., Surviving Sepsis Campaign 2021 · Perera et al., RUSH exam (Emerg Med Clin North Am 2010) · Berend, Seifter et al., Physiological approach to assessment of acid–base disturbances (NEJM 2014) · Albert, Dell &amp; Winters (1967) · UHMS Hyperbaric Oxygen Therapy Indications, 15th ed. · Zeppenfeld et al., ESC ventricular arrhythmias and SCD 2022 · Antzelevitch et al., J-wave syndromes expert consensus 2016 · Gervacio-Domingo et al., Brugada/bangungot in Filipinos (various). Tintinalli 9e Section 3 used only as a topic map.')}
]);
