// ======================= S26 SPECIAL SITUATIONS =======================
// Sources: AHA infective endocarditis in PWID 2022; AST infectious disease guidelines (transplant) 2019; Erstad/ASHP obesity dosing reviews; Janmahasatian LBW (2005);
// WPATH SOC8 2022; NICE NG31 last days of life / NHPCO; Tintinalli death notification topics; TCCC guidelines 2024; PH RA 10173 Data Privacy, RA 11332 notifiable diseases, RA 10932 Anti-Hospital Deposit, Family Code (age of majority 18), RA 7170/11037? (organ donation RA 7170).
Object.assign(REVIEW, {
  'sp-ie':    {t:'Suspected endocarditis in PWID (after ≥ 2–3 blood cultures): vancomycin 25–30 mg/kg IV load (max 3 g) then per levels ± ceftriaxone 2 g or cefazolin per local flora; do not delay in sepsis', r:'AHA 2015/2022; local MRSA rates.', tab:'Special'},
  'sp-wt':    {t:'Obesity dosing weights: IBW (Devine), adjusted BW = IBW + 0.4 × (TBW − IBW), lean BW (Janmahasatian); drug-weight pairings (sux TBW, rocuronium IBW/LBW, propofol induction LBW, ketamine LBW/IBW, enoxaparin TBW with anti-Xa if > 150 kg, vancomycin load TBW max 3 g, aminoglycosides AdjBW)', r:'ASHP/Erstad reviews; pairings vary by source.', tab:'Special'},
  'sp-pal':   {t:'Palliative (opioid-naïve): morphine 2.5–5 mg PO q4h or 1–2 mg IV/SC q1h PRN for dyspnea/pain; on opioids: 10–15 % of daily dose as breakthrough; secretions: glycopyrrolate 0.2 mg SC q4h or hyoscine butylbromide 20 mg SC q4h; terminal delirium: haloperidol 0.5–1 mg SC, midazolam 2.5–5 mg SC', r:'NICE NG31 / palliative formularies; titrate to effect.', tab:'Special'},
  'sp-tx':    {t:'Transplant: stress-dose steroids if on chronic prednisone and shocked (hydrocortisone 100 mg IV); avoid nephrotoxins; check tacrolimus/cyclosporine level and interacting drugs (macrolides, azoles, rifampicin)', r:'AST 2019; contact transplant team before changing immunosuppression.', tab:'Special'},
  'sp-legal': {t:'PH legal points: age of majority 18 (Family Code); RA 10932 bans hospital deposit/refusal in emergencies; RA 10173 Data Privacy Act; RA 11332 mandatory notifiable disease reporting; RA 7170 organ donation; medico-legal cases reported to PNP', r:'Legal summary – confirm with hospital legal office.', tab:'Special'},
  'sp-tq':    {t:'Tactical care: tourniquet high and tight for massive limb bleeding, convert/reassess within 2 h; TXA 2 g IV/IO ≤ 3 h; ketamine 20–30 mg IV / 50–100 mg IM for analgesia', r:'TCCC 2024.', tab:'Special'}
});
Object.assign(D, {
  spVanc: {n:'Vancomycin – suspected endocarditis/sepsis in PWID', flag:'sp-ie', a:[B('IV load',25,30,'mg/kg',{max:3000,note:'Then dose by levels/AUC; add ceftriaxone 2 g IV daily if Gram-negative cover needed.'})], p:[B('IV',15,15,'mg/kg',{max:1000,note:'q6h; levels.'})]},
  spMor: {n:'Morphine – palliative dyspnea/pain (opioid-naïve)', flag:'sp-pal', a:[F('PO','2.5 – 5 mg q4h + PRN'),F('IV / SC','1 – 2 mg q1h PRN (elderly/renal: lower dose, consider hydromorphone or fentanyl)')], p:[B('IV / SC',0.05,0.1,'mg/kg',{max:2,note:'Palliative care team.'})]},
  spGly: {n:'Antisecretory – terminal secretions', flag:'sp-pal', a:[F('Glycopyrrolate','0.2 mg SC/IV q4h PRN'),F('Hyoscine butylbromide','20 mg SC q4h PRN')], p:[B('Glycopyrrolate SC/IV',0.004,0.01,'mg/kg',{max:0.2})]},
  spHal: {n:'Terminal delirium / agitation', flag:'sp-pal', a:[F('Haloperidol','0.5 – 1 mg SC q2–4h PRN'),F('Midazolam','2.5 – 5 mg SC q1h PRN')]}
});
defCards('special','Special',[
 {id:'pwid', title:'People who inject drugs (endocarditis, abscess, spinal infection, wound botulism)', kw:'PWID IVDU injection drug use endocarditis abscess epidural abscess nalbuphine Nubain hepatitis C HIV', h:'💉 People who inject drugs',
  render:w=>ul(['Fever in PWID = endocarditis until proven otherwise: ≥ 2–3 sets of blood cultures before antibiotics, echocardiography (TTE then TEE); right-sided (tricuspid) disease → septic pulmonary emboli','Back pain + fever → spinal epidural abscess / vertebral osteomyelitis: MRI whole spine','Skin abscess: incision and drainage; necrotizing infection signs (pain out of proportion, crepitus) → surgery ('+gto('skininf','skin infections')+')','Wound botulism (descending paralysis, ptosis, diplopia, clear sensorium) → antitoxin, airway watch; tetanus ('+gto('tetanus','tetanus')+')','Also: retained needle fragments, pseudoaneurysm (do not incise a pulsatile groin mass), HIV/HBV/HCV testing, naloxone for take-home','PH: injected nalbuphine ("Nubain") and shared needles drove an HIV outbreak among PWID in Cebu – offer HIV testing and link to treatment hubs'])+drugs(['spVanc'],w)},
 {id:'transplant', title:'Solid organ transplant recipient', kw:'transplant immunosuppression rejection tacrolimus cyclosporine kidney transplant NKTI fever opportunistic infection', h:'🫘 Transplant recipient',
  render:w=>ul(['Call the transplant team early (PH: National Kidney and Transplant Institute for many kidney recipients)','Fever: blunted signs; timeline – < 1 month nosocomial/surgical, 1–6 months opportunistic (CMV, PCP, fungal, TB reactivation), &gt; 6 months community-acquired; low threshold for cultures, imaging, broad antibiotics','Rejection: graft tenderness, rising creatinine, fever – ultrasound with Doppler; do not stop immunosuppression without specialist advice','Drug interactions: macrolides, azoles, diltiazem/verapamil raise calcineurin inhibitor levels; rifampicin, phenytoin, carbamazepine lower them; avoid NSAIDs and IV contrast where possible',`Chronic steroids → adrenal suppression: stress-dose hydrocortisone in shock (${gto('adrenal','adrenal crisis')})${vt('sp-tx')}`])},
 {id:'obesity', title:'Obesity – dosing weight calculator (IBW / adjusted / lean), airway & imaging', kw:'obesity bariatric dosing weight IBW ideal body weight adjusted lean body weight calculator', h:'⚖️ Obesity &amp; dosing weights', inputs:nt('Uses weight, height and sex from the patient bar.'),
  render:w=>{ const i=ibw(), h=HT(), s=SEX();
   if(!w||!i) return '<div class="big">Enter weight, height and sex in the patient bar.</div>'+ul(['Airway: ramp position (ear to sternal notch), preoxygenate with head-up 25–30° + PEEP/HFNO; shorter safe apnea time','Imaging may exceed scanner weight limits – check table limits early']);
   const adj=w>i? i+0.4*(w-i):w, bmi=w/Math.pow(h/100,2);
   const lbw = s==='m'? 9270*w/(6680+216*bmi) : 9270*w/(8780+244*bmi);
   return tbl(['Weight','kg'],[['Total (TBW)',w.toFixed(0)],['Ideal (IBW, Devine)',i.toFixed(0)],['Adjusted (AdjBW)',adj.toFixed(0)],['Lean (LBW)',lbw.toFixed(0)],['BMI',bmi.toFixed(1)]])+
    h3('Typical weight to use'+vt('sp-wt'))+tbl(['Drug','Weight'],[['Succinylcholine','TBW'],['Rocuronium','IBW (or LBW)'],['Propofol / etomidate induction','LBW'],['Ketamine','LBW/IBW'],['Enoxaparin (treatment)','TBW (anti-Xa if &gt; 150 kg)'],['Vancomycin load','TBW (max 3 g)'+vt('sp-wt')],['Aminoglycosides','AdjBW'],['Ventilator tidal volume','IBW (PBW) 6–8 mL/kg'+vt('sp-wt')],['Fluids (bolus)','IBW/AdjBW']])+
    ul(['Airway: ramp position, head-up preoxygenation with PEEP/HFNO, video laryngoscopy, expect rapid desaturation','Imaging may exceed scanner weight limits; ultrasound is technically harder','Pressure injury, rhabdomyolysis and VTE risk higher; appropriately sized BP cuff']); }},
 {id:'transgender', title:'Transgender & gender-diverse patients', kw:'transgender gender diverse hormone therapy estrogen testosterone organ inventory pronouns', h:'🏳️‍⚧️ Transgender &amp; gender-diverse patients',
  render:w=>ul(['Use the patient\'s name and pronouns; ask respectfully only what is clinically relevant','<b>Organ inventory</b>: anatomy present determines differential and screening – prostate in transfeminine people, pregnancy and ovarian/uterine pathology possible in transmasculine people (pregnancy test when relevant)','Estrogen: VTE risk (higher with ethinyl estradiol, smoking), hyperkalemia with spironolactone','Testosterone: polycythemia, hypertension, acne; does not reliably prevent pregnancy','Lab reference ranges (creatinine, hemoglobin) depend on hormonal status – interpret with care','Post-operative complications of gender-affirming surgery: neovaginal stenosis/fistula, urethral stricture, flap problems → contact surgical team','Do not stop hormone therapy routinely; screen for self-harm risk (higher prevalence)'])},
 {id:'palliative', title:'Palliative care in the ED – symptoms, goals of care, last days', kw:'palliative end of life dyspnea secretions death rattle terminal delirium morphine glycopyrrolate DNR goals of care hospice', h:'🕊️ Palliative care',
  render:w=>ul(['Goals-of-care conversation: what does the patient know, what matters most, what are they afraid of, what trade-offs are acceptable; involve family as the patient wishes (family-centred decisions are common in PH)','Record code status (DNR/DNI) and treatment limits clearly; time-limited trials are an option','Dyspnea: opioid, fan to face, positioning; oxygen only if hypoxemic and helps','Pain: regular plus breakthrough opioid; laxative with every opioid','Last days: stop non-essential drugs/monitoring, mouth care, treat secretions (reposition, antisecretory), delirium, nausea'+vt('sp-pal')])+drugs(['spMor','spGly','spHal'],w)},
 {id:'deathnotif', title:'Death notification, family presence, organ donation & medico-legal deaths', kw:'death notification breaking bad news grief family presence resuscitation organ donation death certificate medico-legal', h:'🕯️ Death notification',
  render:w=>ol(['Prepare: confirm identity and facts, private room, sit down, bring a nurse/social worker, silence phones','Introduce yourself; find out what the family knows; give a warning shot ("I have bad news")','Say "died" or "dead" clearly; avoid euphemisms; then pause and allow silence and emotion','Explain what happened briefly; answer questions; offer to let them see the body; respect religious/cultural practices (PH: prayers, priest/pastor/imam, wakes)','Offer family presence during resuscitation where feasible – it does not worsen outcomes','Organ/tissue donation: follow local protocol (PH: Philippine Network for Organ Sharing; RA 7170)'+vt('sp-legal'),'Violent, suspicious or unexplained deaths, deaths on arrival, and deaths within 24 h of injury → medico-legal case; notify PNP; do not remove lines/tubes before medico-legal review','Look after the team: brief debrief after difficult deaths'])},
 {id:'legal', title:'Legal & ethical issues (PH): consent, minors, refusal, confidentiality, RA 10932', kw:'hospital deposit legal consent minors capacity refusal HAMA against medical advice confidentiality data privacy RA 10932 RA 10173 notifiable disease police', h:'⚖️ Legal &amp; ethical issues (PH)',
  render:w=>ul(['Consent: informed, voluntary, by a person with capacity; emergency doctrine permits life-saving treatment when consent cannot be obtained','Minors (&lt; 18 y in PH): parent/guardian consent; treat emergencies without delay; child protection concerns override confidentiality','Refusal / leaving against advice ("HAMA" – home against medical advice): assess capacity, explain risks in plain language, offer alternatives, document, invite return','<b>RA 10932</b> (Anti-Hospital Deposit Law): hospitals may not demand deposits or refuse/detain emergency patients for inability to pay','<b>RA 10173</b> Data Privacy Act: disclose only to those entitled; avoid patient details in messaging groups','<b>RA 11332</b>: report notifiable diseases to the local epidemiology surveillance unit (e.g., measles, dengue clusters, leptospirosis)','Police cases (assault, gunshot, stab, vehicular): medico-legal certificate, chain of custody for evidence'+vt('sp-legal')])},
 {id:'military', title:'Military & tactical medicine (brief)', kw:'military tactical TCCC MARCH tourniquet care under fire blast', h:'🎖️ Military &amp; tactical medicine',
  render:w=>ul(['TCCC phases: care under fire (return fire, tourniquet only), tactical field care, tactical evacuation','<b>MARCH</b>: Massive hemorrhage (tourniquet, wound packing, junctional devices), Airway, Respiration (needle decompression, vented chest seal), Circulation (TXA, blood/fluids), Hypothermia/Head injury','Tourniquet high and tight; note time; reassess for conversion within 2 h'+vt('sp-tq'),'Blast and penetrating injury patterns ('+gto('blast','blast injury')+'); PH relevance: armed-conflict areas in Mindanao, mass-casualty events'])},
 {id:'spsrc', title:'Special situations sources', h:'📚 Special situations sources', render:w=>nt('Baddour et al., AHA infective endocarditis scientific statements (2015) and PWID statement (2022) · AST Infectious Diseases Community of Practice guidelines 2019 · Erstad, dosing in obesity reviews; Janmahasatian et al., lean body weight (Clin Pharmacokinet 2005) · WPATH Standards of Care v8 (2022) · NICE NG31 Care of dying adults in the last days of life · Committee on TCCC guidelines 2024 · Philippine Family Code; RA 10932, RA 10173, RA 11332, RA 7170 · DOH HIV surveillance reports (Cebu PWID). Tintinalli 9e Section 26 used only as a topic map.')}
]);
