// ======================= S21 TRAUMA (extends v1 Trauma panel) =======================
// Sources: Stiell et al., Canadian C-spine rule (JAMA 2001) & Canadian CT head rule (Lancet 2001); Hoffman et al., NEXUS (NEJM 2000); PECARN pediatric c-spine (Leonard 2019/2024);
// ACS ATLS 11th ed (2025); EAST guidelines (rib fractures, penetrating neck, resuscitative thoracotomy 2015, geriatric trauma); AUA urotrauma guideline 2020; WTA.
Object.assign(REVIEW, {
  'tr-rib':  {t:'Rib fractures (older adults): multimodal analgesia – paracetamol 1 g q6h, NSAID if no contraindication, opioid PRN, early regional block (serratus anterior/erector spinae); ≥ 3 fractures or age ≥ 65 → admit/monitor', r:'EAST 2016 / regional anesthesia practice; local block availability.', tab:'Trauma'},
  'tr-thor': {t:'Resuscitative thoracotomy indications: penetrating thoracic trauma with signs of life lost < 15 min of prehospital CPR (strong), blunt trauma < 10 min (conditional); not for blunt trauma without signs of life', r:'EAST 2015 / WTA.', tab:'Trauma'},
  'tr-hemo': {t:'Massive hemothorax: initial chest tube output > 1500 mL or > 200 mL/h for 2–4 h → thoracotomy consideration; tube size 28–32 Fr (or 14 Fr pigtail for stable patients)', r:'ATLS 11th ed; small-bore increasingly acceptable.', tab:'Trauma'}
});
const CCS_HI=[['cc_age','Age ≥ 65'],['cc_mech','Dangerous mechanism (fall ≥ 1 m/5 stairs, axial load, high-speed/rollover/ejection MVC, motorized recreational vehicle, bicycle collision)'],['cc_par','Paresthesias in extremities']];
const CCS_LO=[['cl_mvc','Simple rear-end MVC'],['cl_sit','Sitting position in ED'],['cl_amb','Ambulatory at any time'],['cl_del','Delayed onset of neck pain'],['cl_mid','Absence of midline c-spine tenderness']];
const CTH_HI=[['ch_gcs','GCS &lt; 15 at 2 h after injury'],['ch_open','Suspected open or depressed skull fracture'],['ch_bas','Sign of basal skull fracture (hemotympanum, raccoon eyes, Battle sign, CSF oto/rhinorrhea)'],['ch_vom','Vomiting ≥ 2 episodes'],['ch_age','Age ≥ 65']];
const CTH_MD=[['cm_amn','Retrograde amnesia ≥ 30 min before impact'],['cm_mech','Dangerous mechanism (pedestrian struck, ejection, fall &gt; 1 m/5 stairs)']];
defCards('trauma','Trauma',[
 {id:'cspine', title:'Cervical spine imaging – Canadian C-spine rule & NEXUS', kw:'cervical spine c-spine Canadian C-spine rule NEXUS imaging collar clearance neck injury', h:'🦴 Canadian C-spine rule',
  inputs: nt('Alert (GCS 15), stable adult trauma patient with neck pain or mechanism.')+h3('High-risk factors (any → image)')+CCS_HI.map(([id,t])=>ck(id,t)).join('')+h3('Low-risk factors (allow ROM assessment)')+CCS_LO.map(([id,t])=>ck(id,t)).join('')+ck('cc_rot','Able to actively rotate neck 45° left and right'),
  render:w=>{ const hi=nsum(CCS_HI.map(x=>x[0]))>0, lo=nsum(CCS_LO.map(x=>x[0]))>0, rot=nc('cc_rot');
   const r= hi?'<span class="due">High risk → CT c-spine</span>': !lo?'<span class="due">No low-risk factor → CT c-spine</span>': rot?'<span class="ok">No imaging needed by rule</span>':'<span class="due">Unable to rotate 45° → CT c-spine</span>';
   return `<div class="big">${r}</div>`+ul(['NEXUS alternative: no imaging if no midline tenderness, no focal deficit, normal alertness, no intoxication, no painful distracting injury','CT is the first-line modality in adults; MRI for neurologic deficit or ligamentous concern','Children: PECARN c-spine factors (altered mental status, abnormal airway/breathing/circulation, focal deficit, torticollis, substantial torso injury, high-risk MVC, diving) – prefer X-ray/observation to limit radiation','Neurogenic shock: hypotension with bradycardia; avoid over-fluid; norepinephrine; MAP 85–90 often targeted for spinal cord injury (evidence weak)','PH: motorcycle crashes (often unhelmeted, multiple riders) and falls from trees/roofs are common mechanisms']); }},
 {id:'cthead', title:'Canadian CT head rule (minor head injury) & anticoagulated patients', kw:'Canadian CT head rule minor head injury concussion CT decision anticoagulant older adult', h:'🧠 Canadian CT head rule',
  inputs: nt('GCS 13–15 with witnessed LOC, amnesia or disorientation; not for &lt; 16 y, anticoagulated, seizure after injury.')+h3('High risk (neurosurgical intervention)')+CTH_HI.map(([id,t])=>ck(id,t)).join('')+h3('Medium risk (brain injury on CT)')+CTH_MD.map(([id,t])=>ck(id,t)).join(''),
  render:w=>{ const hi=nsum(CTH_HI.map(x=>x[0]))>0, md=nsum(CTH_MD.map(x=>x[0]))>0;
   return `<div class="big">${hi?'<span class="due">High risk → CT head</span>':md?'<span class="soon">Medium risk → CT head</span>':'<span class="ok">CT not required by rule</span>'}</div>`+ul(['Anticoagulated or on antiplatelets + head injury → low threshold for CT; reverse if bleed ('+gto('reversal','reversal')+')','Children: '+gto('pecarnhead','PECARN head rule'),'Discharge with written concussion advice and a responsible adult; return for vomiting, worsening headache, confusion, seizures','Moderate/severe TBI: avoid hypoxia and hypotension (SBP ≥ 100–110), '+gto('icp','raised ICP card')]); }},
 {id:'chesttr', title:'Chest & cardiac trauma – tension PTX, hemothorax, flail, tamponade, thoracotomy, aortic injury', kw:'chest trauma hemothorax flail chest tamponade resuscitative thoracotomy blunt cardiac injury aortic injury rib fractures pulmonary contusion', h:'🫀 Chest &amp; cardiac trauma',
  render:w=>tbl(['Injury','Key points'],[['Tension pneumothorax','Clinical diagnosis – decompress (4th/5th ICS anterior axillary line or 2nd ICS MCL) then chest tube ('+gto('ptx','PTX card')+')'],['Massive hemothorax','Chest tube + blood; surgery by output and physiology'+vt('tr-hemo')],['Flail chest / pulmonary contusion','Analgesia, NIV if appropriate, avoid fluid overload; intubate for failure'],['Cardiac tamponade','Penetrating precordial wound, hypotension, FAST effusion → OR/thoracotomy; pericardiocentesis only as bridge ('+gto('pericardio','pericardiocentesis')+')'],['Resuscitative thoracotomy','Penetrating trauma with recent loss of signs of life'+vt('tr-thor')],['Blunt cardiac injury','ECG + troponin; normal both → excludes significant injury; arrhythmias → monitor, echo'],['Blunt aortic injury','Deceleration; widened mediastinum → CTA; HR &lt; 100 and SBP &lt; 120 (esmolol) to limit shear'],['Rib fractures (older adults)','High morbidity – analgesia and pulmonary toilet; incentive spirometry'+vt('tr-rib')]])},
 {id:'abdgu', title:'Abdominal, flank & genitourinary trauma (eFAST, penetrating wounds, urethral injury)', kw:'abdominal trauma FAST penetrating stab gunshot laparotomy splenic liver injury flank buttock genitourinary urethral injury hematuria bladder', h:'🩻 Abdominal &amp; GU trauma',
  render:w=>ul(['Blunt: eFAST in primary survey; unstable + positive FAST → OR/IR; stable → CT with IV contrast; seat-belt sign = hollow viscus/Chance fracture risk','Penetrating: hypotension, peritonitis or evisceration → laparotomy; stable stab wounds → local wound exploration/CT/serial exams; gunshot to abdomen usually laparotomy','Flank/buttock penetrating: triple-contrast CT (retroperitoneal colon, ureter, rectum); rectal/vaginal exam for blood','<b>Urethral injury</b>: blood at meatus, perineal hematoma, high-riding prostate → retrograde urethrogram before catheter (or one gentle attempt per local practice)','Gross hematuria/pelvic fracture → CT cystogram; renal injury mostly non-operative','Solid organ injuries in stable patients: non-operative management with serial Hb and exams; angioembolization','Hollow viscus injuries may be missed on early CT – re-examine','Pregnancy: '+gto('obarrest','OB arrest / trauma')])},
 {id:'faceneck', title:'Face & neck trauma – zones, hard signs, orbit, airway', kw:'retrobulbar hematoma canthotomy neck trauma penetrating zones hard signs platysma facial fracture Le Fort orbital blowout retrobulbar hematoma lateral canthotomy mandible', h:'😶 Face &amp; neck trauma',
  render:w=>ul(['Penetrating neck: <b>hard signs</b> (expanding/pulsatile hematoma, active bleeding, bruit/thrill, air bubbling, stridor, shock, neurologic deficit) → OR; otherwise CTA neck ("no-zone" approach) regardless of zone','Do not probe or explore beyond platysma in ED; direct pressure (Foley balloon tamponade for bleeding tracts)','Airway: early intubation if expanding hematoma or voice change; prepare for surgical airway','Blunt cerebrovascular injury (seat-belt neck, hanging, cervical fracture, Horner) → CTA','Face: midface (Le Fort) fractures – airway and bleeding; mandible – malocclusion, open fractures need antibiotics; nasal septal hematoma – drain','Orbit: retrobulbar hematoma (proptosis, ↑IOP, ↓vision) → lateral canthotomy within 90–120 min; blowout fracture with entrapment (esp. children – "white-eyed" blowout with vomiting/bradycardia) → urgent surgery ('+gto('eye','eye card')+')'])},
 {id:'oldtrauma', title:'Trauma in older adults – undertriage, anticoagulants, falls', kw:'geriatric trauma older adult falls anticoagulation frailty undertriage beta blocker', h:'👴 Trauma in older adults',
  render:w=>ul(['Undertriage is common: SBP &lt; 110 may be shock at age ≥ 65; HR may not rise (β-blockers)','Low-energy falls cause serious injury (c-spine, subdural, hip, ribs); low threshold for CT including c-spine','Check anticoagulants/antiplatelets early; lactate/base deficit for occult hypoperfusion','Look for why they fell (syncope, arrhythmia, infection, stroke, hypoglycemia, medications) and for elder abuse ('+gto('elderabuse','elder abuse')+')','Delirium prevention, early mobility, early goals-of-care discussion; rib fracture care'+vt('tr-rib')])},
 {id:'trxsrc', title:'Trauma (extended) sources', h:'📚 Trauma (extended) sources', render:w=>nt('Stiell et al., Canadian C-spine rule (JAMA 2001) and Canadian CT head rule (Lancet 2001) · Hoffman et al., NEXUS (NEJM 2000) · Leonard et al., PECARN cervical spine (Lancet Child Adolesc Health 2024) · ACS ATLS 11th edition · Seamon et al., EAST resuscitative thoracotomy 2015 · Galvagno et al., EAST rib fracture analgesia 2016 · Sperry et al., WTA penetrating neck (no-zone) 2013 · Morey et al., AUA urotrauma guideline 2020 · EAST geriatric trauma guideline. Tintinalli 9e Section 21 used only as a topic map.')}
]);
