// ======================= S6 WOUND MANAGEMENT =======================
// Sources: WHO rabies position paper 2018 & Expert Consultation (TRS 1012, 2018); DOH National Rabies Prevention & Control Program (Manual of Procedures 2019);
// ACIP tetanus/Tdap 2018–2020; WHO tetanus position 2017; IDSA SSTI guideline 2014 (bites); ACEP/AAFP laceration reviews; Cochrane wound irrigation.
Object.assign(REVIEW, {
  'wd-rabies': {t:'Rabies PEP (WHO 2018, DOH): Category II → vaccine; Category III → vaccine + rabies immunoglobulin. Vaccine: intradermal 2-site on days 0, 3, 7 (PH ABTC regimen) or IM 1 dose on days 0, 3, 7 and 14–28; previously vaccinated → 2 doses (days 0, 3), no RIG', r:'Schedules per WHO 2018 / DOH NRPCP; confirm current DOH memorandum and product (PCECV/PVRV) ID volume (0.1 mL per site).', tab:'Wound / Infectious'},
  'wd-rig':    {t:'Rabies immunoglobulin: HRIG 20 IU/kg or ERIG 40 IU/kg, infiltrated into and around all wounds as far as anatomically feasible (no need to inject the remainder IM); given up to day 7 after first vaccine dose', r:'WHO 2018; ERIG skin testing not required by WHO but some PH protocols still perform it.', tab:'Wound / Infectious'},
  'wd-tet':    {t:'Tetanus prophylaxis: < 3 or unknown doses → Td/Tdap (DTaP if < 7 y) for all wounds + TIG 250 IU IM for dirty/major wounds; ≥ 3 doses → booster if > 10 y (clean minor) or > 5 y (other wounds)', r:'ACIP; PH: TIG supply limited – equine antitoxin (ATS 1,500 IU after sensitivity test) still used in some facilities.', tab:'Wound'},
  'wd-irr':    {t:'Irrigation: potable tap water as effective as sterile saline; ~ 50–100 mL per cm of wound, 5–8 psi (e.g. 30–60 mL syringe + 18–19 G cannula)', r:'Cochrane/ED trials; volumes are expert consensus.', tab:'Wound'},
  'wd-bite':   {t:'Bite prophylaxis (dog/cat/human, high-risk wounds): amoxicillin–clavulanate 875/125 mg PO BID × 3–5 days (peds 25 mg/kg/dose amoxicillin component BID, max 875 mg); penicillin allergy: doxycycline or TMP-SMX + metronidazole/clindamycin', r:'IDSA 2014; peds dose formulations vary (7:1 vs 4:1).', tab:'Wound'},
  'wd-sut':    {t:'Suture removal times: face 5 d, scalp 7–10 d, trunk/arms 7–10 d, legs 10–14 d, over joints/hands/feet 10–14 d; children slightly earlier', r:'Consensus ranges; absorbable sutures avoid removal visits in children.', tab:'Wound'}
});
Object.assign(D, {
  wdAmc: {n:'Amoxicillin–clavulanate – bite prophylaxis', flag:'wd-bite', a:[F('PO','875/125 mg BID × 3–5 days')], p:[B('PO BID (amoxicillin component)',25,25,'mg/kg',{max:875,note:'× 3–5 days.'})]},
  wdRig: {n:'Rabies immunoglobulin (Category III)', flag:'wd-rig',
    b:[C('Dose by weight',w=>ok(w)?{main:`HRIG ${fmt(20*w)} IU or ERIG ${fmt(40*w)} IU`,lines:[`HRIG 20 IU/kg (300 IU/2 mL → ${fmt(20*w/150,1)} mL) · ERIG 40 IU/kg (product concentration varies)`,'Infiltrate all wounds; dilute with saline if many wounds; do not give in same syringe/site as vaccine']}:{main:'Enter weight',lines:['HRIG 20 IU/kg · ERIG 40 IU/kg']})]},
  wdTig: {n:'Tetanus immunoglobulin (human)', flag:'wd-tet', b:[F('IM (different site from toxoid)','250 IU (500 IU if > 24 h old, heavy contamination or burns – some protocols)')]}
});
const RAB_IDS=['rbCat','rbPrev','rbAnimal'];
defCards('wound','Wound',[
 {id:'woundeval', title:'Wound evaluation, preparation & timing of closure', kw:'laceration wound evaluation irrigation tap water foreign body x-ray tendon nerve closure timing', h:'🔍 Wound evaluation &amp; preparation',
  render:w=>ul(['History: mechanism (crush, bite, glass, organic matter), time since injury, tetanus status, diabetes/immunosuppression','Examine with good light and bloodless field: distal neurovascular function <b>before</b> anesthesia; tendon function against resistance; look into the base through full range of motion','Imaging: X-ray for glass (most ≥ 2 mm visible) and metal; ultrasound for wood/plastic','Closure timing: most wounds can be closed up to ~12–18 h (face/scalp up to 24 h or more); contaminated/late wounds → delayed primary closure at 3–5 days'])+
   ol([`Anesthetise first (${gto('regional','max dose calculator')}); clip – do not shave – hair; never shave eyebrows`,`Irrigate with clean tap water or saline${vt('wd-irr')}; remove debris and devitalised tissue`,'Explore for foreign bodies and deep-structure injury; extend the wound if needed'])},
 {id:'closure', title:'Wound closure – suture choice, adhesive, removal times by site', kw:'suture staples tissue adhesive glue removal face scalp lip hair apposition', h:'🪡 Wound closure',
  render:w=>tbl(['Site','Material','Removal'+vt('wd-sut')],[['Face','6-0 non-absorbable (or 5-0/6-0 fast-absorbing); adhesive for low tension','5 days'],['Lip','Align vermilion border first; 6-0 skin, 5-0 absorbable mucosa/muscle','5 days'],['Scalp','Staples or 4-0; hair apposition with adhesive','7–10 days'],['Trunk, arms','4-0 (deep 4-0 absorbable if gaping)','7–10 days'],['Legs','4-0','10–14 days'],['Hands, feet, over joints','4-0 / 5-0; splint joints','10–14 days']])+
   ul(['Tissue adhesive: clean, linear, low-tension wounds; not on mucosa, joints, hands with movement','Children: absorbable sutures avoid painful removal','Do not close: infected wounds, high-risk bites on hands, puncture wounds, very contaminated wounds > 24 h'])},
 {id:'handwound', title:'Hand, face & extremity laceration red flags (tendon, nerve, injection injury, fight bite)', kw:'hand laceration tendon nerve fight bite clenched fist high-pressure injection nail bed', h:'✋ Special wounds – hands, face, legs',
  render:w=>ul(['<b>Clenched-fist ("fight bite")</b> over MCP joint: assume joint penetration – explore, X-ray, no primary closure, amoxicillin–clavulanate, hand surgery if joint/tendon involved','<b>High-pressure injection injury</b> (paint, grease): tiny wound, catastrophic damage – emergency surgical referral, no digital block','Partial tendon lacerations &gt; 50%, flexor tendon injuries, digital nerve injuries → hand surgeon (repair within days)','Nail bed: repair lacerations; drain subungual hematoma by trephination','Ear/nose cartilage: cover cartilage, pressure dressing for auricular hematoma','Lower leg pretibial flaps in elderly: Steri-Strips, avoid tension sutures'])},
 {id:'bites', title:'Puncture wounds & bites (dog, cat, human) – antibiotic prophylaxis', kw:'dog bite cat bite human bite puncture wound nail through shoe Pseudomonas Pasteurella antibiotic', h:'🐕 Bites &amp; puncture wounds',
  render:w=>ul(['Irrigate thoroughly; debride devitalised tissue; facial dog bites may be closed primarily; hand bites and cat punctures left open','Prophylactic antibiotics for: cat bites, hand/foot/genital/face bites, deep punctures, crush injury, immunocompromise/asplenia, wounds needing closure, human bites','Plantar puncture through a shoe: Pseudomonas risk if infected – treat infection (adults ciprofloxacin), no routine prophylaxis','Report animal bites; assess rabies risk on every mammal bite ('+gto('rabies','rabies PEP')+')'])+drugs(['wdAmc'],w)},
 {id:'rabies', title:'Rabies post-exposure prophylaxis (WHO 2018, DOH Animal Bite Treatment Centres)', kw:'rabies dog bite cat bite PEP vaccine immunoglobulin ERIG HRIG category ABTC animal bite center', h:'🦠 Rabies post-exposure prophylaxis',
  inputs: sel('rbCat','Exposure category (WHO)',[['','–'],['1','I – touching/feeding, licks on intact skin'],['2','II – nibbling uncovered skin, minor scratches/abrasions without bleeding'],['3','III – transdermal bites/scratches, licks on broken skin or mucosa, bat contact']])+sel('rbPrev','Previous complete rabies vaccination?',[['','–'],['n','No / incomplete / unknown'],['y','Yes (pre- or post-exposure series)']])+sel('rbAnimal','Animal status',[['','–'],['unk','Unknown / stray / died / unobservable'],['obs','Available for 10-day observation']]),
  render:w=>{ const c=sv('rbCat'), pv=sv('rbPrev'), an=sv('rbAnimal'); let adv='';
    if(c==='1') adv='<span class="okc">Category I: no PEP</span> – wash the area';
    else if(c==='2'||c==='3'){ if(pv==='y') adv='<span class="soon">Previously vaccinated: 2 vaccine doses (days 0 and 3) – no RIG</span>';
      else adv = c==='2' ? '<span class="soon">Category II: wound washing + vaccine (no RIG unless immunocompromised)</span>' : '<span class="due">Category III: wound washing + vaccine + rabies immunoglobulin</span>'; }
    return (adv?`<div class="big">${adv}${vt('wd-rabies')}</div>`:nt('Select the exposure category.'))+
    ol([['shock','<b>Wash every bite/scratch immediately for 15 min with soap and running water</b>, then povidone-iodine or alcohol – the single most effective step'],
      `Vaccine (PCECV/PVRV): <b>intradermal 0.1 mL at 2 sites on days 0, 3 and 7</b> (PH Animal Bite Treatment Centre regimen), or IM 1 vial on days 0, 3, 7 and 14–28${vt('wd-rabies')}`,
      `Category III (or II if immunocompromised): RIG into and around all wounds on day 0 (up to day 7)${vt('wd-rig')}`,
      an==='obs'?'Dog/cat observed healthy for 10 days → PEP may be discontinued (start it anyway – do not wait)':'Do not delay PEP for animal observation or lab confirmation; PEP is never contraindicated (pregnancy, infants included)',
      'Delay suturing large bites if possible; if closure needed, infiltrate RIG first'])+(c==='3'&&pv!=='y'?drugs(['wdRig'],w):'')+
    nt('Refer to the nearest DOH-accredited Animal Bite Treatment Centre (ABTC) for the series; rabies is nearly 100% fatal once symptomatic (hydrophobia, aerophobia, agitation) – palliative care and isolation.'); }},
 {id:'tetanus', title:'Tetanus prophylaxis table (Td/Tdap, TIG)', kw:'tetanus toxoid Td Tdap TIG immunoglobulin antitetanus serum ATS wound', h:'💉 Tetanus prophylaxis',
  render:w=>tbl(['Doses of tetanus toxoid','Clean minor wound','All other wounds'],[['Unknown or &lt; 3','Td/Tdap (DTaP &lt; 7 y)','Td/Tdap <b>+ TIG</b>'],['≥ 3, last &lt; 5 y','Nothing','Nothing'],['≥ 3, last 5–10 y','Nothing','Td/Tdap'],['≥ 3, last &gt; 10 y','Td/Tdap','Td/Tdap']])+vt('wd-tet')+
   ul(['"Other" wounds: contaminated (dirt, feces, saliva), punctures, avulsions, crush, burns, frostbite, missiles','Pregnancy: Tdap is safe and recommended (also protects the newborn against pertussis)','Clinical tetanus: see Infectious Diseases (metronidazole, TIG, magnesium, airway)'])+drugs(['wdTig'],w)},
 {id:'fb', title:'Soft-tissue foreign bodies', kw:'foreign body splinter glass fish hook ultrasound removal', h:'🪵 Soft-tissue foreign bodies',
  render:w=>ul(['Image first: X-ray for glass/metal/stone; ultrasound (hyperechoic with shadow) for wood/thorns','Set a time limit (~ 20–30 min); remove only if accessible – deep or near nerves/vessels/joints → refer','Fish hook: advance-and-cut, string-yank or needle-cover techniques','Organic material (wood, thorns, sea urchin spines) causes infection/granulomas – remove completely; consider antibiotics','Tell patients a retained foreign body is possible; return if pain, swelling, discharge'])},
 {id:'wdsrc', title:'Wound sources', h:'📚 Wound sources', render:w=>nt('WHO Rabies vaccines position paper (WER 2018) and WHO Expert Consultation on Rabies, 3rd report (TRS 1012, 2018) · DOH National Rabies Prevention and Control Program Manual of Procedures · ACIP recommendations for tetanus/diphtheria/pertussis vaccines (2018–2020) · WHO tetanus vaccines position paper 2017 · Stevens et al., IDSA SSTI guideline 2014 · Fernandez et al., Water for wound cleansing (Cochrane) · ACEP/AAFP laceration repair reviews. Tintinalli 9e Section 6 used only as a topic map.')}
]);
