// =====================================================================
// Built-in demo cases (fictional). expect = intended diagnosis (must rank top 3);
// mnm = dangerous diagnoses that should appear in the Must-not-miss section.
// =====================================================================
'use strict';
const P=1, N=-1;
const CASES = [
{id:'dengue', name:'Dengue with warning signs (24 F, fever day 5)', expect:'dengue', mnm:['dengue','sepsis'],
 I:{age:24, sex:'F', preg:'no', cc:'Fever', onset:'acute', dur:5, durU:'d', feverDay:5,
    chips:{fever:P,myalgia:P,retro_orb:P,headache:P,abd_pain:P,persist_vomit:P,vomiting:P,bleeding:P,lethargy:P,dengue_area:P,cough:N,dysuria:N,flood:N,
           petechiae:P,hepatomegaly:P,conj_suff:N,rlq_tender:N,neck_stiff:N},
    v:{hr:112,sbp:100,dbp:80,rr:22,t:37.6,spo2:98,gcs:15,glu:96,gluU:'mg'}, lab:{wbc:2.8,plt:62,hct:46},
    text:'5 araw nang nilalagnat, masakit ang katawan at likod ng mata. Suka nang suka kaninang umaga, dumudugo ang gilagid. Walang ubo.'}},
{id:'stemi', name:'Anterior STEMI (58 M, smoker, DM)', expect:'stemi', mnm:['stemi','dissection'],
 I:{age:58, sex:'M', cc:'Chest pain', onset:'sudden', dur:1, durU:'h',
    chips:{chest_pain:P,cp_pressure:P,cp_radiate:P,diaphoresis:P,nausea:P,cp_pleuritic:N,cp_back:N,htn:P,dm:P,smoker:P,dyslipid:P,ecg_ste:P,pulse_deficit:N},
    v:{hr:98,sbp:150,dbp:90,rr:20,t:36.8,spo2:96,gcs:15,glu:210,gluU:'mg'}, lab:{},
    text:'Biglang sumakit ang dibdib habang nagbubuhat, parang dinadaganan, papunta sa braso, pawis na pawis.'}},
{id:'cap', name:'CAP – PCAP moderate risk (68 M)', expect:'cap', mnm:['sepsis'],
 I:{age:68, sex:'M', cc:'Cough', onset:'subacute', dur:4, durU:'d',
    chips:{cough:P,sputum:P,fever:P,chills:P,dyspnea:P,cp_pleuritic:P,crackles_focal:P,bronchial:P,cxr_consol:P,orthopnea:N,dvt_signs:N,htn:P,chronic_cough:N},
    v:{hr:118,sbp:100,dbp:58,rr:32,t:38.9,spo2:90,gcs:15,glu:140,gluU:'mg'}, lab:{wbc:16.2,neut:86,urea:9.1,ureaU:'mmol'},
    text:'Ubo na may plema x 4 days, nilalagnat at giniginaw, hinihingal.'}},
{id:'appy', name:'Acute appendicitis (19 M)', expect:'appy', mnm:['appy'],
 I:{age:19, sex:'M', cc:'Abdominal pain', onset:'acute', dur:18, durU:'h',
    chips:{abd_pain:P,migration:P,rlq_pain:P,anorexia:P,nausea:P,vomiting:P,diarrhea:N,dysuria:N,rlq_tender:P,rebound:P,rovsing:P,cva_tender:N},
    v:{hr:104,sbp:124,dbp:78,rr:18,t:37.9,spo2:99,gcs:15}, lab:{wbc:14.2,neut:84}, text:'Sakit ng tiyan sa pusod kagabi, lumipat sa kanan ibaba. Walang gana kumain, nasusuka.'}},
{id:'dka', name:'DKA (22 F, type 1 DM, missed insulin)', expect:'dka', mnm:['dka'],
 I:{age:22, sex:'F', preg:'no', cc:'High blood sugar', onset:'subacute', dur:2, durU:'d',
    chips:{polyuria:P,polydipsia:P,vomiting:P,abd_pain:P,malaise:P,missed_insulin:P,dm:P,dm1:P,m_insulin:P,dehydration:P,kussmaul:P,ketones:P,acidosis:P},
    v:{hr:124,sbp:102,dbp:64,rr:30,t:37.2,spo2:99,gcs:15,glu:27.5,gluU:'mmol'}, lab:{wbc:13}, text:'Uhaw na uhaw, ihi nang ihi, nagsusuka. Hindi nag-insulin for 3 days.'}},
{id:'ectopic', name:'Ruptured ectopic pregnancy (28 F)', expect:'ectopic', mnm:['ectopic'],
 I:{age:28, sex:'F', preg:'possible', cc:'Abdominal pain', onset:'sudden', dur:3, durU:'h',
    chips:{abd_pain:P,llq_pain:P,vag_bleed:P,amenorrhea:P,syncope:P,dizziness:P,ectopic_rf:P,fever:N,vag_discharge:N,adnexal:P,cmt:P,pallor:P,hcg_pos:P,us_fluid:P},
    v:{hr:122,sbp:86,dbp:54,rr:24,t:36.6,spo2:98,gcs:15}, lab:{}, text:'Atrasado ang regla ng 7 linggo, may spotting, biglang sumakit ang puson at nahimatay.'}},
{id:'pe', name:'Pulmonary embolism (45 F, OCP, post-op)', expect:'pe', mnm:['pe'],
 I:{age:45, sex:'F', preg:'no', cc:'Shortness of breath', onset:'sudden', dur:6, durU:'h', peLikely:true,
    chips:{dyspnea:P,cp_pleuritic:P,chest_pain:P,hemoptysis:P,cough:N,fever:N,orthopnea:N,immobil:P,m_estrogen:P,dvt_signs:P,crackles_bilat:N,wheeze_pe:N},
    v:{hr:118,sbp:112,dbp:70,rr:26,t:37.4,spo2:89,gcs:15}, lab:{}, text:'Biglang hinihingal at masakit pag huminga, 10 days after knee surgery, on contraceptive pills.'}},
{id:'lepto', name:'Leptospirosis – Weil disease (35 M, post-flood)', expect:'lepto', mnm:['lepto','dengue'],
 I:{age:35, sex:'M', cc:'Fever', onset:'acute', dur:6, durU:'d', feverDay:6,
    chips:{fever:P,chills:P,myalgia:P,calf_pain:P,headache:P,jaundice:P,oliguria:P,flood:P,conj_suff:P,icterus:P,bleeding:N,rash:N},
    v:{hr:108,sbp:104,dbp:66,rr:22,t:38.8,spo2:96,gcs:15}, lab:{wbc:14.5,plt:88}, text:'Lumusong sa baha 10 araw na ang nakaraan. Nilalagnat, masakit ang binti, naninilaw, konti ang ihi.'}},
{id:'dissection', name:'Type A aortic dissection (66 M, HTN)', expect:'dissection', mnm:['dissection','nstemi'],
 I:{age:66, sex:'M', cc:'Chest pain', onset:'sudden', dur:1, durU:'h',
    chips:{chest_pain:P,cp_back:P,diaphoresis:P,syncope:P,htn:P,smoker:P,pulse_deficit:P,murmur:P,cp_pleuritic:N,ecg_ste:N},
    v:{hr:104,sbp:182,dbp:96,rr:22,t:36.7,spo2:96,gcs:15}, lab:{}, text:'Sudden tearing chest pain radiating to the back, tumatagos sa likod.'}},
{id:'stroke', name:'Acute ischemic stroke (71 M, AF, 1 h)', expect:'stroke', mnm:['stroke'],
 I:{age:71, sex:'M', cc:'One-sided weakness / stroke symptoms', onset:'sudden', dur:1, durU:'h',
    chips:{focal_weak:P,facial_droop:P,speech:P,headache:N,seizure:N,fever:N,htn:P,af:P,hemiparesis:P,aphasia:P,irregular:P},
    v:{hr:96,sbp:176,dbp:98,rr:18,t:36.6,spo2:97,gcs:14,glu:118,gluU:'mg'}, lab:{}, text:'Biglang hindi maigalaw ang kaliwang braso, tabingi ang mukha at bulol magsalita.'}},
{id:'op', name:'Organophosphate poisoning (30 M, farmer)', expect:'op', mnm:['op'],
 I:{age:30, sex:'M', cc:'Poisoning / overdose', onset:'acute', dur:2, durU:'h',
    chips:{pesticide:P,vomiting:P,diarrhea:P,dyspnea:P,confusion:P,miosis:P,secretions:P,fasciculation:P,crackles_bilat:P,wheeze_pe:P,diaphoresis:P},
    v:{hr:48,sbp:96,dbp:60,rr:28,t:36.5,spo2:88,gcs:12}, lab:{}, text:'Uminom ng insecticide matapos mag-away. Naglalaway, nagsusuka, nanginginig ang kalamnan.'}},
{id:'meningitis', name:'Bacterial meningitis (20 M)', expect:'meningitis', mnm:['meningitis','sepsis'],
 I:{age:20, sex:'M', cc:'Headache', onset:'acute', dur:1, durU:'d',
    chips:{fever:P,headache:P,neck_stiff_sx:P,photophobia:P,vomiting:P,confusion:P,thunderclap:N,focal_weak:N,neck_stiff:P,kernig:P,petechiae:P,toxic:P},
    v:{hr:122,sbp:98,dbp:60,rr:24,t:39.6,spo2:96,gcs:13}, lab:{wbc:21}, text:'Mataas ang lagnat, matinding sakit ng ulo, matigas ang batok, nalilito.'}},
{id:'anaphylaxis', name:'Anaphylaxis (32 F, shrimp)', expect:'anaphylaxis', mnm:['anaphylaxis'],
 I:{age:32, sex:'F', preg:'no', cc:'Allergic reaction', onset:'sudden', dur:30, durU:'h',
    chips:{allergen:P,urticaria:P,pruritus:P,throat_tight:P,dyspnea:P,wheeze:P,vomiting:P,fever:N,angioedema:P,wheeze_pe:P},
    v:{hr:126,sbp:82,dbp:48,rr:26,t:36.8,spo2:93,gcs:15}, lab:{}, text:'Kumain ng hipon, after 15 minutes nangangati, namamaga ang labi, hirap huminga.'}},
{id:'ptb', name:'Pulmonary TB (42 M)', expect:'ptb', mnm:[],
 I:{age:42, sex:'M', cc:'Cough', onset:'gradual', dur:5, durU:'wk',
    chips:{cough:P,chronic_cough:P,hemoptysis:P,wt_loss:P,night_sweats:P,fever:P,tb_contact:P,smoker:P,cachexia:P,dvt_signs:N},
    v:{hr:96,sbp:118,dbp:72,rr:20,t:37.9,spo2:96,gcs:15}, lab:{}, text:'Matagal na ubo, 5 linggo, may dugo sa plema minsan, pumapayat, pinagpapawisan sa gabi. May TB sa bahay (tatay).'}},
{id:'typhoid', name:'Typhoid fever (26 F, day 9)', expect:'typhoid', mnm:[],
 I:{age:26, sex:'F', preg:'no', cc:'Fever', onset:'gradual', dur:9, durU:'d', feverDay:9,
    chips:{fever:P,headache:P,abd_pain:P,constipation:P,anorexia:P,malaise:P,unsafe_food:P,flood:N,bleeding:N,cough:N,splenomegaly:P,hepatomegaly:P,conj_suff:N},
    v:{hr:92,sbp:110,dbp:70,rr:18,t:39.4,spo2:98,gcs:15}, lab:{wbc:4.2,plt:160}, text:'Lagnat nang 9 araw na tumataas tuwing hapon, masakit ang ulo at tiyan, tibi. Kumakain sa street food.'}},
{id:'snake', name:'Cobra bite – neurotoxic (40 M, farmer)', expect:'snake', mnm:['snake'],
 I:{age:40, sex:'M', cc:'Snakebite', onset:'acute', dur:2, durU:'h',
    chips:{snake_bite:P,vomiting:P,speech:P,dyspnea:P,fang_marks:P,ptosis:P},
    v:{hr:104,sbp:130,dbp:80,rr:24,t:36.9,spo2:94,gcs:15}, lab:{}, text:'Tinuklaw ng ahas sa bukid 2 oras na ang nakaraan, namumungay ang mata.'}},
// ---------- Trauma mode cases (I.tr = trauma-section inputs) ----------
{id:'tr_moto_edh', name:'🩻 Motorcycle crash, walang helmet – EDH (24 M, GCS 9)', expect:'tr_edh', mnm:['tr_edh','tr_tbi'],
 I:{age:24, sex:'M', cc:'Trauma / injury', tr:{on:true, injT:90, injU:'min', air:'threat', bs:'equal', pup:'uni', gcsE:2, gcsV:3, gcsM:4, wt:65},
    chips:{mech_moto:P,no_helmet:P,head_inj:P,loc:P,lucid:P,intox:P,scalp_hematoma:P,skull_fx:P,vomit2:P,lateralizing:P,ext_hemorrhage:N,pelvic_unstable:N,fast_neg:P},
    v:{hr:58,sbp:172,dbp:88,rr:12,t:36.6,spo2:94,glu:110,gluU:'mg'}, lab:{},
    text:'Naaksidente sa motor, walang helmet, sumalpok sa poste 90 minutes ago. Nawalan ng malay, nagising at nakausap pa, tapos lumala – nagsuka ng 2 beses, ngayon hindi na sumasagot nang maayos. Nakainom daw.'}},
{id:'tr_stab_tamp', name:'🩻 Sinaksak sa dibdib – cardiac tamponade (30 M)', expect:'tr_tamponade', mnm:['tr_tamponade','tr_shock'],
 I:{age:30, sex:'M', cc:'Trauma / injury', tr:{on:true, injT:25, injU:'min', air:'patent', bs:'equal', pup:'equal', gcsE:4, gcsV:4, gcsM:6, wt:60},
    chips:{mech_stab:P,chest_pen:P,box_wound:P,jvd:P,muffled:P,fast_peri:P,cool_periph:P,hyperres:N,trach_dev:N,ext_hemorrhage:N,open_chest:N},
    v:{hr:132,sbp:78,dbp:64,rr:28,t:36.4,spo2:95}, lab:{},
    text:'Sinaksak ng kutsilyo sa kaliwang dibdib malapit sa sternum mga 25 minuto ang nakaraan. Nanghihina, malamig ang pawis, hirap huminga.'}},
{id:'tr_fall_pelvis', name:'🩻 Nahulog sa scaffolding – pelvic fracture in shock (52 M)', expect:'tr_pelvis', mnm:['tr_pelvis','tr_shock'],
 I:{age:52, sex:'M', cc:'Trauma / injury', tr:{on:true, injT:1, injU:'h', fallM:6, air:'patent', bs:'equal', pup:'equal', gcsE:4, gcsV:4, gcsM:6, bd:9, wt:70},
    chips:{mech_fall:P,pelvic_unstable:P,pelvic_pain:P,perineal:P,blood_meatus:P,fast_neg:P,cool_periph:P,ext_hemorrhage:N,abd_tender_tr:N,neck_midline:N},
    v:{hr:134,sbp:82,dbp:60,rr:26,t:35.8,spo2:96}, lab:{},
    text:'Nahulog mula sa scaffolding sa construction site, mga 6 m, isang oras na ang nakaraan. Masakit ang balakang, hindi makatayo, may dugo sa dulo ng ari.'}},
{id:'tr_mvc_spleen', name:'🩻 Nabangga ang jeep – splenic injury (34 M)', expect:'tr_solid', mnm:['tr_solid'],
 I:{age:34, sex:'M', cc:'Trauma / injury', tr:{on:true, injT:2, injU:'h', air:'patent', bs:'equal', pup:'equal', gcsE:4, gcsV:5, gcsM:6, wt:68},
    chips:{mech_mvc:P,luq_tender:P,abd_tender_tr:P,chest_wall:P,fast_abd:P,ext_hemorrhage:N,pelvic_unstable:N,neck_midline:N,head_inj:N},
    v:{hr:118,sbp:98,dbp:66,rr:22,t:36.8,spo2:97}, lab:{},
    text:'Nabangga ang jeep na sinasakyan, tumama ang kaliwang tagiliran sa bakal. Masakit ang kaliwang itaas ng tiyan at kaliwang balikat. Walang nawalan ng malay.'}},
{id:'tr_geri_sdh', name:'🩻 Nadulas sa banyo, naka-apixaban – acute SDH (78 F)', expect:'tr_sdh', mnm:['tr_sdh','tr_geri'],
 I:{age:78, sex:'F', cc:'Trauma / injury', tr:{on:true, injT:6, injU:'h', air:'patent', bs:'equal', pup:'equal', gcsE:3, gcsV:4, gcsM:6, wt:52},
    chips:{mech_fall_low:P,head_inj:P,scalp_hematoma:P,m_anticoag:P,af:P,htn:P,headache:P,vomit2:P,confusion:P,lateralizing:N,ext_hemorrhage:N,neck_midline:N},
    v:{hr:84,sbp:168,dbp:92,rr:18,t:36.5,spo2:96,glu:128,gluU:'mg'}, lab:{},
    text:'Nadulas sa banyo kaninang umaga, nauntog ang ulo. Naka-apixaban dahil sa AF. Ngayon inaantok, masakit ang ulo at nagsuka ng 2 beses.'}},
{id:'tr_burn30', name:'🩻 Sumabog ang LPG – 30 % TBSA burn + inhalation (32 M, 65 kg)', expect:'tr_burn', mnm:['tr_burn','tr_inhal'],
 I:{age:32, sex:'M', cc:'Trauma / injury', tr:{on:true, injT:1, injU:'h', tbsa:30, wt:65, air:'threat', bs:'equal', pup:'equal', gcsE:4, gcsV:5, gcsM:6},
    chips:{mech_burn:P,burn_enclosed:P,face_burn:P,voice_change:P,burn_full:P,burn_special:P,burn_circ:N,ext_hemorrhage:N},
    v:{hr:124,sbp:118,dbp:76,rr:24,t:36.9,spo2:95}, lab:{},
    text:'Sumabog ang LPG sa kusina, nasunog ang mukha, dibdib at dalawang braso, isang oras na ang nakaraan. Paos ang boses, may uling sa ilong.'}},
{id:'tr_tension', name:'🩻 Motor vs jeep – tension pneumothorax (27 M)', expect:'tr_tension', mnm:['tr_tension','tr_shock'],
 I:{age:27, sex:'M', cc:'Trauma / injury', tr:{on:true, injT:40, injU:'min', air:'patent', bs:'R', pup:'equal', gcsE:4, gcsV:4, gcsM:6, wt:62},
    chips:{mech_moto:P,chest_wall:P,subq_emph:P,hyperres:P,trach_dev:P,jvd:P,cool_periph:P,fast_ptx:P,ext_hemorrhage:N,fast_peri:N},
    v:{hr:136,sbp:78,dbp:50,rr:34,t:36.5,spo2:82}, lab:{},
    text:'Nabangga ng jeep ang motor, tumama ang dibdib sa manibela. Hirap na hirap huminga, nahihilo.'}},
{id:'tr_preg', name:'🩻 Buntis 32 wk, tricycle crash – placental abruption (26 F)', expect:'tr_preg', mnm:['tr_preg'],
 I:{age:26, sex:'F', preg:'yes', ga:32, cc:'Trauma / injury', tr:{on:true, injT:2, injU:'h', air:'patent', bs:'equal', pup:'equal', gcsE:4, gcsV:5, gcsM:6, wt:60},
    chips:{mech_moto:P,uterine_tender:P,fhr_abn:P,vag_bleed:P,abd_pain:P,abd_tender_tr:P,ext_hemorrhage:N,pelvic_unstable:N},
    v:{hr:112,sbp:100,dbp:62,rr:22,t:36.8,spo2:98}, lab:{},
    text:'Buntis, 32 weeks AOG, naaksidente sa tricycle, tumama ang tiyan. Masakit ang tiyan, naninigas, may pagdurugo sa ari. Parang hindi gumagalaw ang baby.'}},
{id:'tr_peds_head', name:'🩻 Nahulog sa hagdan – minor head injury, PECARN (6 M)', expect:'tr_mtbi', mnm:[],
 I:{age:6, sex:'M', cc:'Trauma / injury', tr:{on:true, injT:3, injU:'h', fallM:2, air:'patent', bs:'equal', pup:'equal', gcsE:4, gcsV:5, gcsM:6, wt:20},
    chips:{mech_fall:P,head_inj:P,loc:P,vomiting:P,scalp_hematoma:P,basilar:N,skull_fx:N,sev_headache:N,not_normal:N,ext_hemorrhage:N,neck_midline:N},
    v:{hr:104,sbp:104,dbp:66,rr:22,t:36.9,spo2:99}, lab:{},
    text:'Nahulog sa hagdan mga 2 m, nauntog ang ulo, saglit na nawalan ng malay, nagsuka minsan. Ngayon gising at naglalaro.'}},
// ───────── pediatric cases (pediatric mode switches on automatically for age < 18) ─────────
{id:'pd_febinf_21d', name:'🧒 Lagnat sa 3-linggong sanggol – febrile neonate (21 d M)', expect:'pd_febinf', mnm:['pd_febinf'],
 I:{age:21, ageU:'d', sex:'M', cc:'Fever (infant / child)', onset:'acute', dur:10, durU:'h',
    pd:{wt:3.6, imm:'complete', feed:'reduced', uo:'normal', act:'irritable', patA:'n', patB:'n', patC:'n', crp:28, pct:0.9, anc:5.2},
    chips:{fever:P,poor_feed:P,irritable:P,cough:N,coryza:N,diarrhea:N,rash:N},
    v:{hr:178,sbp:72,dbp:44,rr:52,t:38.4,spo2:98,glu:82,gluU:'mg'}, lab:{wbc:15,neut:35},
    text:'3 linggong sanggol, mainit simula kagabi, 38.4 sa bahay. Medyo ayaw dumede at iyak nang iyak. Walang ubo, walang sipon.'}},
{id:'pd_croup_2y', name:'🧒 Ubo na parang tahol – croup (2 M)', expect:'pd_croup', mnm:[],
 I:{age:2, sex:'M', cc:'Difficulty breathing / noisy breathing (child)', onset:'acute', dur:1, durU:'d',
    pd:{wt:12, imm:'complete', feed:'reduced', uo:'normal', act:'irritable', patA:'n', patB:'a', patC:'n', wLoc:'0', wCy:'0', wSt:'1', wAe:'0', wRe:'1'},
    chips:{barking:P,stridor:P,coryza:P,fever:P,cough:P,drooling:N,choking:N,tripod:N,toxic:N},
    v:{hr:136,sbp:96,dbp:60,rr:36,t:38.1,spo2:96}, lab:{},
    text:'May sipon at sinat kahapon. Ngayong gabi parang tahol ng aso ang ubo at maingay ang paghinga pag umiiyak. Hindi naglalaway, nakakainom pa.'}},
{id:'pd_bronch_4mo', name:'🧒 Sipon, ubo, humuhuni – bronchiolitis (4 mo F)', expect:'pd_bronchiolitis', mnm:['pd_cap'],
 I:{age:4, ageU:'mo', sex:'F', cc:'Difficulty breathing / noisy breathing (child)', onset:'subacute', dur:3, durU:'d',
    pd:{wt:6.2, imm:'complete', feed:'reduced', uo:'normal', act:'normal', patA:'n', patB:'a', patC:'n'},
    chips:{coryza:P,cough:P,wheeze_pe:P,crackles_bilat:P,chest_indraw:P,nasal_flare:P,fever:P,choking:N,stridor:N},
    v:{hr:158,sbp:84,dbp:50,rr:62,t:37.9,spo2:93}, lab:{},
    text:'4 na buwan, 3 araw nang may sipon at ubo, ngayon hirap huminga at humuhuni ang dibdib. Kalahati lang ang nadedede. Sinat lang.'}},
{id:'pd_age_severe', name:'🧒 Pagtatae at matamlay – AGE severe dehydration (14 mo M)', expect:'pd_age', mnm:['pd_age','pd_sepsis','pd_intuss'],
 I:{age:14, ageU:'mo', sex:'M', cc:'Vomiting / diarrhea (child)', onset:'acute', dur:2, durU:'d',
    pd:{wt:9, imm:'complete', feed:'unable', uo:'reduced', act:'lethargic', patA:'a', patB:'n', patC:'a'},
    chips:{diarrhea:P,vomiting:P,lethargy:P,sunken_eyes:P,pinch_vslow:P,drinks_poor:P,crt_prolonged:P,fever:P,hematochezia:N,currant:N,bilious:N},
    v:{hr:176,sbp:78,dbp:44,rr:40,t:37.9,spo2:98,glu:78,gluU:'mg'}, lab:{},
    text:'Pagtatae na parang tubig mga 10 beses mula kahapon, nagsusuka rin. Ngayon matamlay, lubog ang mata, hindi makainom, konti ang ihi.'}},
{id:'pd_intuss_9mo', name:'🧒 Iyak nang iyak, dugo sa dumi – intussusception (9 mo M)', expect:'pd_intuss', mnm:['pd_intuss'],
 I:{age:9, ageU:'mo', sex:'M', cc:'Crying / irritable infant', onset:'sudden', dur:12, durU:'h',
    pd:{wt:8.5, imm:'complete', feed:'reduced', uo:'normal', act:'irritable', patA:'n', patB:'n', patC:'n'},
    chips:{episodic_pain:P,vomiting:P,currant:P,sausage_mass:P,irritable:P,fever:N,diarrhea:N,bilious:N},
    v:{hr:150,sbp:88,dbp:52,rr:34,t:37.2,spo2:99}, lab:{},
    text:'Biglang iyak nang iyak na parang masakit ang tiyan, nakabaluktot ang tuhod, tapos tahimik ulit – paulit-ulit. Nagsuka 3 beses. Ang dumi ay parang jelly na may dugo.'}},
{id:'pd_dengue_8y', name:'🧒 Dengue with warning signs (8 F, fever day 5)', expect:'pd_dengue', mnm:['pd_dengue','pd_sepsis'],
 I:{age:8, sex:'F', cc:'Fever (infant / child)', onset:'acute', dur:5, durU:'d', feverDay:5,
    pd:{wt:24, imm:'complete', feed:'poor', uo:'reduced', act:'lethargic', patA:'n', patB:'n', patC:'n'},
    chips:{fever:P,abd_pain:P,persist_vomit:P,vomiting:P,petechiae:P,lethargy:P,hepatomegaly:P,myalgia:P,dengue_area:P,cough:N,coryza:N,dysuria:N,flood:N},
    v:{hr:124,sbp:96,dbp:80,rr:24,t:37.4,spo2:98}, lab:{wbc:2.9,plt:68,hct:44},
    text:'5 araw nang nilalagnat, ngayon wala nang lagnat pero masakit ang tiyan at suka nang suka. May mga pulang tuldok sa braso, matamlay. Maraming may dengue sa barangay.'}},
{id:'pd_kawasaki_3y', name:'🧒 6 na araw na lagnat, pulang mata at labi – Kawasaki (3 M)', expect:'pd_kawasaki', mnm:['pd_kawasaki'],
 I:{age:3, sex:'M', cc:'Rash with fever (child)', onset:'subacute', dur:6, durU:'d', feverDay:6,
    pd:{wt:14, imm:'complete', feed:'poor', uo:'normal', act:'irritable', patA:'n', patB:'n', patC:'n', crp:85, esr:70},
    chips:{fever:P,kd_conj:P,kd_oral:P,kd_rash:P,kd_extrem:P,kd_node:P,irritable:P,exudate:N,hand_vesicles:N,koplik:N,cough:N},
    v:{hr:150,sbp:94,dbp:56,rr:28,t:39.4,spo2:98}, lab:{wbc:17,plt:420},
    text:'6 na araw nang mataas ang lagnat kahit uminom ng gamot. Namumula ang mata pero walang muta, pula at bitak ang labi, may rashes sa katawan, namamaga ang kamay at paa. Iritable.'}},
{id:'pd_febsz_18mo', name:'🧒 Nangisay habang nilalagnat – simple febrile seizure (18 mo F)', expect:'pd_febsz', mnm:[],
 I:{age:18, ageU:'mo', sex:'F', cc:'Seizure / kumbulsyon (child)', onset:'sudden', dur:1, durU:'h',
    pd:{wt:10.5, imm:'complete', feed:'normal', uo:'normal', act:'normal', patA:'n', patB:'n', patC:'n'},
    chips:{seizure:P,sz_brief:P,fever:P,coryza:P,sz_complex:N,sz_long:N,neck_stiff:N,fontanelle_bulge:N,petechiae:N,head_inj:N,epilepsy:N},
    v:{hr:140,sbp:92,dbp:58,rr:30,t:39.3,spo2:98,glu:104,gluU:'mg'}, lab:{},
    text:'May sipon at lagnat simula kaninang umaga. Nangisay ng mga 2 minuto, buong katawan, isang beses lang. Ngayon gising na, umiiyak at naglalaro.'}},
{id:'pd_dka_12y', name:'🧒 Ihi nang ihi, pumapayat, nagsusuka – DKA (12 F)', expect:'pd_dka', mnm:['pd_dka'],
 I:{age:12, sex:'F', cc:'Vomiting / diarrhea (child)', onset:'subacute', dur:3, durU:'d',
    pd:{wt:35, imm:'complete', feed:'poor', uo:'normal', act:'lethargic', patA:'n', patB:'a', patC:'n', ph:7.12, hco3:8},
    chips:{polyuria:P,polydipsia:P,wt_loss:P,vomiting:P,abd_pain:P,kussmaul:P,ketones:P,diarrhea:N,fever:N},
    v:{hr:128,sbp:104,dbp:64,rr:32,t:36.8,spo2:99,gcs:15,glu:486,gluU:'mg'}, lab:{},
    text:'Ilang linggo nang ihi nang ihi at uhaw na uhaw, pumayat. 3 araw nang nagsusuka at masakit ang tiyan, ngayon malalim at mabilis ang paghinga, matamlay.'}},
{id:'pd_fb_2y', name:'🧒 Nabulunan sa mani – foreign body aspiration (2 M)', expect:'pd_fb', mnm:['pd_fb'],
 I:{age:2, sex:'M', cc:'Cough', onset:'sudden', dur:6, durU:'h',
    pd:{wt:12, imm:'complete', feed:'normal', uo:'normal', act:'normal', patA:'n', patB:'a', patC:'n'},
    chips:{choking:P,cough:P,unilat_wheeze:P,air_entry_dec:P,fever:N,coryza:N,barking:N},
    v:{hr:128,sbp:96,dbp:60,rr:34,t:37.0,spo2:95}, lab:{},
    text:'Habang kumakain ng mani, biglang nabulunan at ubo nang ubo. Ngayon may huni sa kanang dibdib. Walang lagnat, walang sipon.'}},
{id:'pd_pyloric_5wk', name:'🧒 Sumusuka nang pabuga pagkadede – pyloric stenosis (5 wk M)', expect:'pd_pyloric', mnm:[],
 I:{age:5, ageU:'wk', sex:'M', cc:'Vomiting / diarrhea (child)', onset:'subacute', dur:5, durU:'d',
    pd:{wt:3.9, imm:'complete', feed:'normal', uo:'reduced', act:'normal', patA:'n', patB:'n', patC:'n'},
    chips:{projectile:P,vomiting:P,olive:P,bilious:N,fever:N,diarrhea:N},
    v:{hr:150,sbp:76,dbp:44,rr:40,t:36.9,spo2:99}, lab:{},
    text:'5 linggong sanggol, sumusuka nang pabuga pagkatapos dumede, hindi berde ang suka. Gutom pa rin pagkatapos sumuka. Konti ang ihi.'}},
{id:'pd_cap_3y', name:'🧒 Lagnat, ubo, mabilis huminga – pediatric CAP (3 F)', expect:'pd_cap', mnm:['pd_cap'],
 I:{age:3, sex:'F', cc:'Cough', onset:'acute', dur:3, durU:'d',
    pd:{wt:14, imm:'complete', feed:'reduced', uo:'normal', act:'normal', patA:'n', patB:'a', patC:'n'},
    chips:{fever:P,cough:P,chest_indraw:P,crackles_focal:P,wheeze_pe:N,choking:N,barking:N},
    v:{hr:146,sbp:94,dbp:58,rr:48,t:39.0,spo2:93}, lab:{wbc:18},
    text:'3 araw nang may lagnat at ubo, ngayon mabilis at hirap huminga, humihila ang dibdib. Walang huni.'}},
{id:'pd_torsion_13y', name:'🧒 Biglang sakit ng bayag – testicular torsion (13 M)', expect:'pd_torsion', mnm:['pd_torsion'],
 I:{age:13, sex:'M', cc:'Abdominal pain', onset:'sudden', dur:3, durU:'h',
    pd:{wt:45, act:'normal'},
    chips:{testis_pain:P,high_testis:P,scrotal_swell:P,vomiting:P,nausea:P,fever:N,dysuria:N,trauma:N},
    v:{hr:110,sbp:122,dbp:74,rr:20,t:36.9,spo2:99}, lab:{},
    text:'Nagising sa biglang matinding sakit ng kaliwang bayag, umaabot sa puson. Nagsuka 2 beses. Walang lagnat, hindi masakit umihi.'}},
{id:'pd_kero_2y', name:'🧒 Nakainom ng gaas – hydrocarbon ingestion (2 M)', expect:'pd_hydrocarbon', mnm:['pd_hydrocarbon'],
 I:{age:2, sex:'M', cc:'Ingestion (child)', onset:'sudden', dur:1, durU:'h',
    pd:{wt:12, imm:'complete', feed:'normal', uo:'normal', act:'normal', patA:'n', patB:'n', patC:'n'},
    chips:{ingest_kero:P,cough:P,choking:P,vomiting:P,fever:N},
    v:{hr:130,sbp:96,dbp:60,rr:36,t:37.0,spo2:96}, lab:{},
    text:'Nakainom ng gaas na nakalagay sa bote ng softdrinks mga 1 oras na ang nakaraan. Nabulunan at ubo nang ubo, nagsuka minsan.'}},
{id:'pd_uti_8mo', name:'🧒 Lagnat na walang sipon o ubo – febrile UTI (8 mo F)', expect:'pd_uti', mnm:['pd_mening'],
 I:{age:8, ageU:'mo', sex:'F', cc:'Fever (infant / child)', onset:'acute', dur:2, durU:'d',
    pd:{wt:7.8, imm:'complete', feed:'reduced', uo:'normal', act:'irritable', patA:'n', patB:'n', patC:'n'},
    chips:{fever:P,ua_pos:P,irritable:P,cough:N,coryza:N,diarrhea:N,rash:N,ear_pain:N},
    v:{hr:160,sbp:88,dbp:52,rr:34,t:39.2,spo2:99}, lab:{wbc:19},
    text:'2 araw nang mataas ang lagnat, iritable, mabaho ang ihi sa diaper. Walang ubo, walang sipon, walang pagtatae.'}},
];
if(typeof module!=='undefined') module.exports={CASES};
