// =====================================================================
// DDx Assist – finding vocabulary + free-text lexicon (English / Tagalog / Taglish)
// Every finding is tri-state in the UI: unknown · present (+) · absent (−).
// =====================================================================
'use strict';
const FGROUPS = {
  // ---- HPI symptom chips ----
  'hx_gen':  {t:'General', sec:'hpi', f:[
    ['fever','Fever (history)'],['chills','Chills / rigors'],['malaise','Malaise / weakness'],['myalgia','Myalgia / body aches'],
    ['calf_pain','Calf muscle pain'],['arthralgia','Joint pains'],['retro_orb','Retro-orbital pain'],['anorexia','Anorexia'],
    ['wt_loss','Weight loss'],['night_sweats','Night sweats'],['rash','Rash (macular / flushing)'],['pruritus','Itching'],
    ['jaundice','Jaundice / yellow eyes'],['syncope','Syncope / near-syncope'],['dizziness','Dizziness / light-headed'],
    ['lethargy','Lethargy / restlessness'],['bleeding','Mucosal bleeding (gum / nose)'],['oliguria','Decreased urine output']]},
  'hx_cr':   {t:'Chest / breathing', sec:'hpi', f:[
    ['chest_pain','Chest pain'],['cp_pressure','Pressure / heavy / crushing'],['cp_radiate','Radiates to arm / jaw'],
    ['cp_back','Tearing / radiates to back'],['cp_pleuritic','Pleuritic (worse on breathing)'],['cp_exertional','Exertional'],
    ['cp_positional','Better sitting forward'],['diaphoresis','Diaphoresis / cold sweat'],['palpitations','Palpitations'],
    ['dyspnea','Dyspnea'],['orthopnea','Orthopnea / PND'],['cough','Cough'],['sputum','Productive sputum'],['hemoptysis','Hemoptysis'],
    ['wheeze','Wheeze'],['chronic_cough','Cough ≥ 2 weeks'],['sore_throat','Sore throat'],['throat_tight','Throat tightness / hoarse voice']]},
  'hx_gi':   {t:'Abdomen / GI', sec:'hpi', f:[
    ['abd_pain','Abdominal pain'],['epi_pain','Epigastric pain'],['ruq_pain','RUQ pain'],['rlq_pain','RLQ pain'],['llq_pain','LLQ / pelvic pain'],
    ['diffuse_abd','Diffuse abdominal pain'],['migration','Periumbilical → RLQ migration'],['flank_pain','Flank pain (colicky)'],
    ['abd_back','Abdominal pain radiating to back'],['pain_oop','Pain out of proportion to exam'],['nausea','Nausea'],['vomiting','Vomiting'],
    ['persist_vomit','Persistent vomiting / cannot keep fluids'],['diarrhea','Diarrhea'],['dysentery','Bloody / mucoid diarrhea'],
    ['hematemesis','Hematemesis / coffee-ground'],['melena','Melena'],['hematochezia','Hematochezia'],['obstipation','No stool / flatus'],
    ['distension','Abdominal distension'],['fatty_meal','Pain after fatty meal'],['constipation','Constipation']]},
  'hx_gu':   {t:'GU / OB-GYN', sec:'hpi', f:[
    ['dysuria','Dysuria'],['frequency','Frequency / urgency'],['hematuria','Hematuria'],['vag_bleed','Vaginal bleeding'],
    ['amenorrhea','Missed / late period'],['vag_discharge','Vaginal discharge'],['testis_pain','Testicular / scrotal pain'],
    ['polyuria','Polyuria'],['polydipsia','Polydipsia']]},
  'hx_neuro':{t:'Neuro', sec:'hpi', f:[
    ['headache','Headache'],['thunderclap','Sudden "worst ever" headache'],['neck_stiff_sx','Neck stiffness (complaint)'],
    ['photophobia','Photophobia'],['confusion','Confusion / altered sensorium'],['seizure','Seizure'],['focal_weak','One-sided weakness / numbness'],
    ['facial_droop','Facial droop'],['speech','Slurred speech / aphasia'],['vision','Vision loss / diplopia'],['vertigo','Vertigo (spinning)'],
    ['tremor','Tremor / anxiety / heat intolerance']]},
  'hx_exp':  {t:'Exposures / triggers', sec:'hpi', f:[
    ['allergen','Exposure to likely allergen (food, drug, sting)'],['flood','Flood / mud wading (2–30 d ago)'],['animal_bite','Dog / cat bite or scratch'],
    ['snake_bite','Snakebite'],['pesticide','Pesticide / insecticide exposure'],['overdose','Drug overdose / ingestion'],['apap_od','Paracetamol ingestion'],
    ['alcohol','Heavy alcohol use'],['lambanog','Home-brewed / illicit alcohol (lambanog)'],['heat_exp','Heat exposure / exertion'],
    ['travel_mal','Travel to malaria area (e.g. Palawan forest)'],['tb_contact','TB contact'],['unsafe_food','Street food / unsafe water'],
    ['dengue_area','Dengue cases in household / barangay'],['dirty_wound','Dirty / puncture wound'],['missed_insulin','Missed insulin / DM meds'],
    ['infection_sx','Recent infection / illness']]},
  // ---- Trauma mode (ATLS xABCDE primary survey + secondary survey by region) ----
  'tr_mech': {t:'Mechanism', sec:'tr', f:[
    ['mech_mvc','Car / jeepney / bus crash (MVC)'],['mech_moto','Motorcycle / tricycle crash'],['no_helmet','No helmet (rider)'],
    ['mech_ped','Pedestrian struck / run over (nasagasaan)'],['mech_hienergy','High energy: high speed, rollover, ejection, death in same vehicle'],
    ['mech_fall','Fall from height'],['mech_fall_low','Ground-level fall / slip (nadulas, natumba)'],['mech_axial','Axial load / diving into shallow water'],
    ['mech_assault','Assault / blunt blow (binugbog)'],['mech_stab','Stab wound (sinaksak)'],['mech_gsw','Gunshot wound (binaril)'],
    ['mech_burn','Burn – flame / scald / contact'],['burn_elec','Electrical / lightning injury'],['burn_enclosed','Fire in enclosed space / smoke exposure'],
    ['mech_crush','Crush / entrapment (naipit, nadaganan)'],['mech_drown','Drowning / submersion (nalunod)'],['head_inj','Head struck / head injury'],
    ['loc','Loss of consciousness'],['intox','Intoxicated now (alcohol / drugs)']]},
  'tr_x':    {t:'x – Exsanguinating external hemorrhage', sec:'tr', f:[['ext_hemorrhage','Catastrophic external bleeding']]},
  'tr_a':    {t:'A – Airway (with C-spine protection)', sec:'tr', f:[['face_burn','Facial burns / singed hair / soot / carbonaceous sputum'],['voice_change','Hoarse voice / voice change'],['airway_blood','Blood / vomitus / teeth in airway']]},
  'tr_b':    {t:'B – Breathing', sec:'tr', f:[['flail_seg','Paradoxical (flail) chest segment'],['open_chest','Open (sucking) chest wound'],['chest_wall','Chest wall tenderness / crepitus / rib fractures'],['subq_emph','Subcutaneous emphysema']]},
  'tr_c':    {t:'C – Circulation', sec:'tr', f:[['pelvic_unstable','Pelvic instability / pain on gentle compression (do not rock)']]},
  'tr_fast': {t:'eFAST', sec:'tr', f:[['fast_neg','eFAST negative'],['fast_abd','Free fluid – abdomen / pelvis'],['fast_peri','Pericardial fluid'],['fast_ptx','No lung sliding (pneumothorax)'],['fast_htx','Pleural fluid (hemothorax)']]},
  'tr_d':    {t:'D – Disability', sec:'tr', f:[['lateralizing','Lateralizing signs (one-sided weakness / posturing)'],['cord_deficit','Spinal cord deficit (weakness / sensory level / priapism)']]},
  'tr_e':    {t:'E – Exposure / burns', sec:'tr', f:[['burn_full','Full-thickness burn'],['burn_circ','Circumferential burn (limb / chest)'],['burn_special','Burn to face, hands, feet, genitalia, perineum or major joints']]},
  'tr_head': {t:'Head / face', sec:'tr', f:[
    ['scalp_hematoma','Scalp hematoma / laceration'],['basilar','Basal skull fracture signs (raccoon eyes, Battle sign, hemotympanum, CSF leak)'],['skull_fx','Open / depressed / palpable skull fracture'],
    ['lucid','Lucid interval, then deterioration'],['amnesia','Amnesia ≥ 30 min before impact'],['vomit2','Vomiting ≥ 2 times after injury'],['sev_headache','Severe headache'],
    ['post_seizure','Seizure after injury'],['not_normal','Child not acting normally (per parent)'],['face_fx','Facial fracture (midface instability, malocclusion, deformity)']]},
  'tr_neck': {t:'Neck', sec:'tr', f:[
    ['neck_midline','Midline C-spine tenderness'],['neck_pain','Neck pain'],['paresthesia','Paresthesias in hands / feet'],['distract','Painful distracting injury'],
    ['cs_simple','Simple rear-end MVC'],['cs_amb','Ambulatory at any time / sitting up in ED'],['cs_delayed','Delayed onset of neck pain'],['cs_rotate','Can actively rotate neck 45° left and right'],
    ['neck_pen','Neck wound breaching platysma'],['neck_hard','Hard sign: expanding / pulsatile hematoma, bruit / thrill, active bleeding, air bubbling'],['dysphagia','Dysphagia / hoarseness / hemoptysis after neck injury']]},
  'tr_chest':{t:'Chest', sec:'tr', f:[
    ['chest_pen','Penetrating chest wound'],['box_wound','Wound in the "cardiac box" (between nipples, clavicles to costal margin)'],['seatbelt','Seat-belt sign (chest / abdomen)'],
    ['sternal','Sternal tenderness / fracture'],['first_rib','1st–2nd rib or scapular fracture'],['cxr_htx','CXR / US: hemothorax'],['tube_1500','Chest tube ≥ 1500 mL at once or > 200 mL/h']]},
  'tr_abd':  {t:'Abdomen / pelvis / perineum', sec:'tr', f:[
    ['abd_tender_tr','Abdominal tenderness / guarding'],['luq_tender','LUQ / left lower rib tenderness or left shoulder (Kehr) pain'],['ruq_tender_tr','RUQ / right lower rib tenderness'],
    ['abd_pen','Penetrating abdominal / flank / back wound'],['evisceration','Evisceration'],['flank_ecchy','Flank ecchymosis / flank pain'],['pelvic_pain','Pelvic / hip pain'],
    ['blood_meatus','Blood at urethral meatus'],['perineal','Perineal / scrotal ("butterfly") hematoma'],['high_prostate','High-riding prostate / vaginal laceration'],['unable_void','Unable to void']]},
  'tr_spine':{t:'Spine / cord pattern', sec:'tr', f:[
    ['tl_tender','Thoracolumbar midline tenderness / step-off'],['arms_weak','Arms weaker than legs (central cord pattern)'],['bs_pattern','One-sided weakness + opposite pain/temperature loss (Brown-Séquard)'],
    ['ant_cord','Motor + pain/temperature loss, position sense spared (anterior cord)'],['saddle','Saddle anesthesia / sphincter loss']]},
  'tr_ext':  {t:'Extremities / soft tissue', sec:'tr', f:[
    ['long_bone','Long-bone deformity / suspected fracture'],['femur_fx','Femur fracture (one or both)'],['open_fx','Wound over fracture / bone exposed'],
    ['hard_vasc','Hard signs: pulsatile bleeding, expanding hematoma, absent distal pulse, bruit / thrill'],['soft_vasc','Soft signs: weak pulse, ABI < 0.9, small stable hematoma, wound near vessel'],
    ['comp_pain','Pain out of proportion / pain on passive stretch'],['comp_tense','Tense, swollen compartment'],['crush_long','Limb crushed / entrapped ≥ 1 h'],
    ['dark_urine','Dark / cola-coloured urine'],['contaminated','Heavily contaminated wound (soil, farm, floodwater)']]},
  'tr_preg': {t:'Pregnancy (if pregnant)', sec:'tr', f:[['uterine_tender','Uterine tenderness / contractions / rigid uterus'],['fhr_abn','Abnormal / absent fetal heart rate'],['rom','Leaking amniotic fluid']]},
  // ---- Pediatric mode (IMCI general danger signs · pediatric history / exam · Kawasaki criteria) ----
  'pd_ds':   {t:'IMCI general danger signs', sec:'pd', f:[
    ['ds_drink','Not able to drink or breastfeed'],['ds_vomit','Vomits everything'],['ds_conv','Convulsions during this illness'],
    ['ds_leth','Lethargic or unconscious'],['ds_convnow','Convulsing now']]},
  'pd_hx':   {t:'Pediatric history', sec:'pd', f:[
    ['poor_feed','Poor feeding / ayaw dumede o kumain'],['irritable','Irritable / excessive crying'],['inconsolable','Inconsolable'],['coryza','Runny nose / sipon'],
    ['barking','Barking ("seal") cough / hoarse cry'],['choking','Witnessed choking / sudden cough while eating or playing'],['drooling','Drooling / cannot swallow saliva'],
    ['ear_pain','Ear pain / ear tugging / ear discharge'],['apnea','Apnea / pauses in breathing / BRUE'],['cyanosis','Cyanosis / blue spells'],['sweat_feed','Sweating or breathless with feeds / poor weight gain'],
    ['bilious','Bilious (green) vomiting'],['projectile','Projectile non-bilious vomiting after feeds'],['episodic_pain','Episodic inconsolable crying, legs drawn up'],
    ['currant','Currant-jelly / bloody mucoid stool'],['delayed_meconium','Meconium > 48 h / constipation since birth'],['jaundice_24h','Jaundice in the first 24 h of life'],
    ['pale_stool','Pale stools / dark urine (cholestasis)'],['limp','Limp'],['nwb','Refuses to bear weight'],['hop_pain','Pain on coughing / hopping / percussion'],
    ['enuresis','New bed-wetting'],['oral_ulcers','Mouth sores / ulcers (singaw)'],['ingestion','Accidental ingestion (nakalunok / nakainom)'],
    ['ingest_iron','Iron tablets / ferrous sulfate ingestion'],['ingest_kero','Kerosene / gasoline / thinner (hydrocarbon) ingestion'],
    ['sz_long','Seizure ≥ 5 min or repeated without recovery'],['sz_complex','Focal seizure, > 15 min, or > 1 in 24 h'],['sz_brief','Generalised seizure < 15 min, back to baseline'],
    ['measles_contact','Measles case / outbreak contact'],['covid_exp','COVID-19 illness / exposure 2–6 weeks ago'],['abuse_concern','History inconsistent with injury / development, or delay in care'],['preterm','Born preterm (< 37 wk)'],
    ['imm_complete','Immunizations complete for age (per card)'],['unimmunized','Incomplete / no immunizations']]},
  'pd_pe':   {t:'Pediatric exam', sec:'pd', f:[
    ['chest_indraw','Chest indrawing / retractions'],['grunting','Grunting'],['nasal_flare','Nasal flaring / head bobbing'],['stridor_rest','Stridor at rest (calm)'],
    ['air_entry_dec','Decreased air entry'],['tripod','Tripod / sniffing position, toxic'],['unilat_wheeze','Unilateral wheeze / ↓ breath sounds on one side'],
    ['sunken_eyes','Sunken eyes'],['pinch_slow','Skin pinch goes back slowly'],['pinch_vslow','Skin pinch goes back very slowly (≥ 2 s)'],
    ['drinks_eager','Drinks eagerly, thirsty'],['drinks_poor','Drinks poorly'],['fontanelle_sunken','Sunken fontanelle'],['fontanelle_bulge','Bulging fontanelle'],
    ['crt_prolonged','Capillary refill > 2 s'],['mottled','Mottled / grey skin'],['sausage_mass','Sausage-shaped abdominal mass'],['olive','Palpable "olive" / visible peristalsis'],
    ['tm_bulge','Bulging / red, immobile ear drum'],['hand_vesicles','Vesicles on hands / feet / buttocks'],['koplik','Koplik spots'],['conj_red','Red eyes / conjunctivitis'],
    ['femoral_weak','Weak femoral pulses / pre- vs post-ductal SpO₂ gap > 3 %'],['hip_rom','Hip held flexed, painful / limited range'],['scrotal_swell','Scrotal swelling / redness'],['hard_testis','Hard / tender testis'],
    ['bruise_pattern','Bruise in non-mobile infant, or on torso / ear / neck (TEN-4-FACESp)'],['wasting','Severe wasting / bilateral pitting edema of feet']]},
  'pd_kd':   {t:'Kawasaki criteria (AHA)', sec:'pd', f:[
    ['kd_conj','Bilateral non-exudative conjunctival injection'],['kd_oral','Red cracked lips / strawberry tongue / red mouth'],['kd_rash','Polymorphous rash'],
    ['kd_extrem','Red / swollen hands & feet or periungual peeling'],['kd_node','Cervical node ≥ 1.5 cm (usually one side)']]},
  // ---- PMH / risk factors ----
  'pmh':     {t:'PMH / risk factors', sec:'pmh', f:[
    ['htn','Hypertension'],['dm','Diabetes'],['dm1','Type 1 DM'],['smoker','Smoker'],['dyslipid','Dyslipidemia'],['obesity','Obesity'],
    ['cad','Known CAD / prior MI'],['fam_cad','Family hx premature CAD'],['stroke_hx','Prior stroke / TIA'],['af','Atrial fibrillation'],
    ['hf','Heart failure'],['copd','COPD'],['asthma','Asthma'],['ckd','CKD'],['cirrhosis','Cirrhosis / liver disease'],['malignancy','Active cancer'],
    ['immobil','Surgery / immobilization ≤ 4 wk'],['dvt_hx','Prior DVT / PE'],['postpartum','Postpartum ≤ 6 wk'],['immuno','HIV / immunosuppressed'],
    ['tb_hx','Prior TB'],['gallstones','Gallstones'],['pud','Peptic ulcer disease'],['ctd','Marfan / bicuspid valve / aortic dz'],
    ['ectopic_rf','Prior ectopic / PID / tubal surgery / IVF'],['iud','IUD in place'],['epilepsy','Epilepsy'],['stones','Kidney stones'],
    ['thyroid','Hyperthyroidism'],['migraine_hx','Migraine history'],['atopy','Atopy / prior anaphylaxis']]},
  'meds':    {t:'Medications', sec:'meds', f:[
    ['m_anticoag','Anticoagulant'],['m_antiplt','Antiplatelet'],['m_insulin','Insulin'],['m_oha','Oral hypoglycemic'],['m_sglt2','SGLT2 inhibitor'],
    ['m_steroid','Steroids'],['m_nsaid','NSAIDs'],['m_estrogen','OCP / estrogen'],['m_bb','β-blocker / CCB'],['m_diuretic','Diuretic'],['m_abx','Recent antibiotics']]},
  // ---- Physical exam by system ----
  'pe_gen':  {t:'General', sec:'pe', f:[
    ['toxic','Ill / toxic-looking'],['pallor','Pallor'],['dehydration','Dry mucosa / poor turgor'],['cool_periph','Cold clammy skin / CRT > 2 s'],['cachexia','Cachexia']]},
  'pe_heent':{t:'HEENT / neck', sec:'pe', f:[
    ['conj_suff','Conjunctival suffusion'],['icterus','Scleral icterus'],['exudate','Tonsillar exudate / swelling'],['cerv_nodes','Tender anterior cervical nodes'],
    ['angioedema','Lip / tongue / face swelling'],['miosis','Pinpoint pupils'],['stridor','Stridor'],['jvd','Raised JVP'],['neck_stiff','Neck stiffness / meningism'],
    ['ptosis','Ptosis / bulbar weakness'],['goiter','Goiter']]},
  'pe_resp': {t:'Respiratory', sec:'pe', f:[
    ['crackles_focal','Focal crackles'],['crackles_bilat','Bilateral crackles'],['wheeze_pe','Wheeze on exam'],['bronchial','Bronchial breath sounds / dullness'],
    ['dec_bs_uni','Unilateral ↓ breath sounds'],['hyperres','Hyperresonance'],['accessory','Accessory muscles / speaks in words'],['silent_chest','Silent chest'],
    ['trach_dev','Tracheal deviation']]},
  'pe_cvs':  {t:'Cardiovascular', sec:'pe', f:[
    ['murmur','New murmur'],['s3','S3 / gallop'],['pulse_deficit','Pulse deficit / arm SBP Δ > 20'],['irregular','Irregularly irregular pulse'],
    ['muffled','Muffled heart sounds'],['rub','Pericardial rub'],['edema','Bilateral leg edema'],['dvt_signs','Unilateral leg swelling / calf tenderness']]},
  'pe_abd':  {t:'Abdomen / pelvis', sec:'pe', f:[
    ['murphy','RUQ tenderness / Murphy sign'],['epi_tender','Epigastric tenderness'],['rlq_tender','RLQ (McBurney) tenderness'],['llq_tender','LLQ / suprapubic tenderness'],
    ['rebound','Rebound / guarding'],['rigid','Board-like rigidity'],['rovsing','Rovsing / psoas sign'],['distended','Distended / tympanitic'],
    ['hepatomegaly','Tender hepatomegaly'],['splenomegaly','Splenomegaly'],['ascites','Ascites / pleural effusion (fluid accumulation)'],
    ['cva_tender','CVA (kidney-punch) tenderness'],['adnexal','Adnexal tenderness / mass'],['cmt','Cervical motion tenderness'],
    ['pulsatile','Pulsatile abdominal mass'],['high_testis','High-riding testis / absent cremasteric'],['blood_dre','Melena / blood on DRE']]},
  'pe_neuro':{t:'Neuro', sec:'pe', f:[
    ['kernig','Kernig / Brudzinski'],['hemiparesis','Hemiparesis'],['aphasia','Aphasia / dysarthria (exam)'],['facial_pe','Facial palsy (exam)'],
    ['fasciculation','Fasciculations'],['ataxia','Ataxia / central signs'],['hyperreflexia','Hyperreflexia / clonus'],['kussmaul','Kussmaul breathing'],['trismus','Trismus / generalized spasms']]},
  'pe_skin': {t:'Skin / extremities', sec:'pe', f:[
    ['petechiae','Petechiae / purpura / + tourniquet test'],['urticaria','Urticaria'],['cellulitis','Erythema / warmth / swelling'],
    ['crepitus','Crepitus / bullae / skin necrosis'],['fang_marks','Fang marks / local swelling'],['hot_joint','Hot swollen joint'],
    ['secretions','Salivation / lacrimation / bronchorrhea'],['bleed_site','Bleeding from puncture sites']]},
  // ---- Optional bedside results ----
  'bed':     {t:'Bedside results (optional)', sec:'bed', f:[
    ['ecg_ste','ECG: ST elevation / new LBBB'],['ecg_std','ECG: ST depression / T inversion'],['ecg_af','ECG: AF / SVT'],['ecg_rv','ECG: S1Q3T3 / RV strain'],
    ['ecg_diffuse','ECG: diffuse STE + PR depression'],['trop_pos','Troponin elevated'],['plt_low','Platelets ≤ 100k'],['hct_rise','Hct rising ≥ 20%'],
    ['wbc_low','WBC < 5k (leukopenia)'],['ketones','Ketones ≥ 2+ / β-OHB ≥ 3'],['acidosis','pH < 7.3 or HCO₃ < 18'],['ua_pos','UA: pyuria / nitrite +'],
    ['hcg_pos','Pregnancy test positive'],['hcg_neg','Pregnancy test negative'],['lipase_high','Lipase / amylase > 3× ULN'],['cr_high','Creatinine elevated'],
    ['ns1_pos','Dengue NS1 / IgM positive'],['bili_high','Bilirubin elevated'],['cxr_consol','CXR: consolidation'],['cxr_ptx','CXR / US: pneumothorax'],
    ['cxr_edema','CXR: pulmonary edema / B-lines'],['cxr_mediast','CXR: widened mediastinum'],['cxr_cavity','CXR: upper-lobe / cavitary infiltrate'],
    ['us_fluid','POCUS: free fluid (FAST +)'],['us_rv','POCUS: RV dilation'],['us_effusion','POCUS: pericardial effusion'],['us_aaa','POCUS: aorta > 3 cm'],
    ['us_gb','US: gallstones + wall thickening'],['xpert_pos','Xpert MTB/RIF positive']]},
};
const FLABEL = {}; const FGROUP_OF = {};
Object.entries(FGROUPS).forEach(([g,G])=>G.f.forEach(([id,l])=>{ FLABEL[id]=l; FGROUP_OF[id]=g; }));
// derived (vitals / demographics) labels
Object.assign(FLABEL, {
  hr_gt100:'HR > 100', hr_ge125:'HR ≥ 125', hr_lt60:'HR < 60', sbp_lt90:'SBP < 90', sbp_le100:'SBP ≤ 100', dbp_le60:'DBP ≤ 60', htn_sev:'BP ≥ 180/120', bp_ge140:'BP ≥ 140/90', rr_lt12:'RR < 12', ga_ge20:'Gestation ≥ 20 wk',
  rr_ge22:'RR ≥ 22', rr_ge30:'RR ≥ 30', t_ge38:'T ≥ 38 °C', t_ge39:'T ≥ 39 °C', t_ge40:'T ≥ 40 °C', t_lt36:'T < 36 °C', spo2_lt94:'SpO₂ < 94 %',
  spo2_lt90:'SpO₂ < 90 %', gcs_lt15:'GCS < 15', gcs_le8:'GCS ≤ 8', glu_high:'Glucose > 250 mg/dL', glu_vhigh:'Glucose > 600 mg/dL', glu_low:'Glucose < 70 mg/dL',
  narrow_pp:'Pulse pressure ≤ 20', si_ge1:'Shock index ≥ 1', rel_brady:'Relative bradycardia (T ≥ 38.5, HR < 100)', wbc_high:'WBC > 10k',
  wbc_vhigh:'WBC > 15k', neut_high:'Neutrophils > 75 %', urea_high:'Urea > 7 mmol/L (BUN > 19)', lactate_high:'Lactate ≥ 2', lactate_4:'Lactate ≥ 4',
  age_ge50:'Age ≥ 50', age_ge65:'Age ≥ 65', age_lt40:'Age < 40', age_lt16:'Age < 16', male:'Male', female:'Female', repro_f:'Female 12–50 y', pregnant:'Pregnant',
  onset_sudden:'Sudden onset (seconds–minutes)', dur_lt24h:'Duration < 24 h', dur_le7d:'Duration ≤ 7 d', dur_gt7d:'Duration > 7 d', dur_ge14d:'Duration ≥ 14 d',
  fever_d3_7:'Fever day 3–7 (critical phase window)', fever_any:'Fever (history or measured)',
  // trauma-derived
  trauma:'Trauma / injury', penetrating:'Penetrating mechanism', blunt:'Blunt mechanism', fall_ge1m:'Fall ≥ 1 m / 5 stairs', fall_ge3m:'Fall ≥ 3 m (≈ 1 storey)',
  air_threat:'Airway threatened', air_obst:'Airway obstructed', dec_bs_bil:'↓ Breath sounds both sides', pupil_uni:'Unilateral dilated / unreactive pupil', pupil_bil:'Both pupils fixed & dilated',
  gcs_9_12:'GCS 9–12 (moderate TBI)', gcs_13_15:'GCS 13–15', gcs_lt13:'GCS < 13', t_lt35:'T < 35 °C (hypothermia)', sbp_lt110:'SBP < 110', hr_ge120:'HR ≥ 120',
  inj_le3h:'Injury ≤ 3 h ago', inj_gt3h:'Injury > 3 h ago', tbsa_ge10:'Burn ≥ 10 % TBSA', tbsa_ge20:'Burn ≥ 20 % TBSA', bd_ge6:'Base deficit ≥ 6', helmet:'Helmet worn'
});

// pediatric-derived (age-specific vital signs, PAT, intake, age bands)
Object.assign(FLABEL, {
  peds:'Pediatric patient (< 18 y)', age_le21d:'Age ≤ 21 days', age_le28d:'Age ≤ 28 days (neonate)', age_le60d:'Age ≤ 60 days', age_lt3mo:'Age < 3 months', age_lt6mo:'Age < 6 months', age_lt1y:'Age < 1 year',
  age_lt2y:'Age < 2 years', age_lt5y:'Age < 5 years', age_6mo_5y:'Age 6 months – 5 years', age_3mo_3y:'Age 3 months – 3 years', age_2_12wk:'Age 2–12 weeks', age_ge5:'Age ≥ 5 years', age_ge10:'Age ≥ 10 years',
  hr_hi_age:'Tachycardia for age', hr_vhi_age:'HR ≥ 220 (infant) / ≥ 180 (child)', hr_lo_age:'Bradycardia for age', rr_hi_age:'Tachypnea for age', fast_breath:'Fast breathing (WHO / PAPP-PIDSP cut-off for age)',
  sbp_lo_age:'Hypotension for age (PALS)', pat_appear:'PAT: abnormal appearance', pat_wob:'PAT: increased work of breathing', pat_circ:'PAT: abnormal circulation to skin',
  danger_sign:'IMCI general danger sign', fever_ge5d:'Fever ≥ 5 days', fever_ge7d:'Fever ≥ 7 days', fever_lt24h:'Fever < 24 h', t_ge385:'T ≥ 38.5 °C', anc_high:'ANC > 4 ×10⁹/L', anc_10:'ANC > 10 ×10⁹/L',
  pct_high:'Procalcitonin > 0.5 ng/mL', crp_high:'CRP > 20 mg/L', crp_30:'CRP ≥ 30 mg/L (3 mg/dL)', esr_40:'ESR > 40 mm/h', ph_lt73:'pH < 7.3 or HCO₃ < 18', wbc_12:'WBC > 12k', swelling:'Swelling (namamaga)'
});

// ---------------- Free-text lexicon ----------------
// [regex source (matched on lower-cased text, word-ish boundaries), finding ids]
// Tagalog stems are written to catch common affixed forms (nilalagnat, inuubo, nagtatae, nagsusuka …).
const LEX = [
  // fever / systemic
  ['lagnat|nilalagnat|nilagnat|sinat|sinisinat|mainit ang katawan|fever|febrile|pyrexia', ['fever']],
  ['giniginaw|ginaw|nanginginig sa lamig|chills|rigors?', ['chills']],
  ['panghihina|nanghihina|mahina ang katawan|matamlay|malaise|weakness|fatigue', ['malaise']],
  ['pananakit ng katawan|masakit ang katawan|sakit ng katawan|body ?aches?|myalgias?|ngalay', ['myalgia']],
  ['masakit ang binti|sakit ng binti|pananakit ng binti|masakit ang alak-?alakan|calf (pain|tenderness)|calf myalgia', ['calf_pain']],
  ['masakit ang kasukasuan|joint pains?|arthralgias?|rayuma', ['arthralgia']],
  ['(?:masakit|sakit|kirot)?\\s*(?:sa\\s+)?likod ng mata|retro-?orbital|behind (?:the )?eyes?', ['retro_orb']],
  ['walang gana kumain|walang ganang kumain|walang gana|anorexia|poor appetite', ['anorexia']],
  ['pumayat|pumapayat|nangayayat|weight loss|lost weight', ['wt_loss']],
  ['pinagpapawisan sa gabi|pawis sa gabi|night sweats?', ['night_sweats']],
  ['pantal|rashes|rash', ['rash']],
  ['nangangati|kati|itchy|itching|pruritus', ['pruritus']],
  ['naninilaw|paninilaw|dilaw ang mata|dilaw ang balat|jaundice|yellowish|icteric', ['jaundice']],
  ['nahimatay|hinimatay|himatay|nawalan ng malay|syncope|fainted|passed out', ['syncope']],
  ['nahihilo|hilo|dizzy|dizziness|light-?headed', ['dizziness']],
  ['dumudugo ang gilagid|dugo sa gilagid|balinguyngoy|gum bleeding|epistaxis|nosebleed', ['bleeding']],
  ['konti ang ihi|kaunti ang ihi|hindi umiihi|oliguria|decreased urine', ['oliguria']],
  // chest / resp
  ['pananakit ng dibdib|masakit ang dibdib|sakit sa dibdib|sakit ng dibdib|kirot sa dibdib|chest pain|chest discomfort', ['chest_pain']],
  ['parang dinadaganan|mabigat sa dibdib|bigat sa dibdib|(?<!blood )pressure|crushing|squeezing|heaviness', ['cp_pressure']],
  ['papunta sa braso|radiat\\w* to (the )?(left )?(arm|jaw)|jaw pain', ['cp_radiate']],
  ['tearing|ripping|tumatagos sa likod|radiat\\w* to (the )?back', ['cp_back']],
  ['pleuritic|masakit pag huminga|masakit kapag humihinga', ['cp_pleuritic']],
  ['pinagpapawisan nang malamig|malamig na pawis|pawis na pawis|diaphore\\w*|cold sweat', ['diaphoresis']],
  ['kabog ng dibdib|kumakabog|palpitasyon|palpitations?', ['palpitations']],
  ['hirap huminga|hirap sa paghinga|nahihirapang huminga|hinihingal|hingal|kinakapos ng hininga|kapos sa hininga|sikip ng dibdib|dyspnea|shortness of breath|sob|difficulty breathing', ['dyspnea']],
  ['hindi makahiga|orthopnea|pnd|paroxysmal nocturnal', ['orthopnea']],
  ['ubo|inuubo|umuubo|cough\\w*', ['cough']],
  ['plema|may plema|productive|sputum|phlegm', ['sputum']],
  ['umuubo ng dugo|dugo sa plema|hemoptysis|coughing (up )?blood', ['hemoptysis']],
  ['hika|asthma attack|wheez\\w*|humahagok|halak', ['wheeze']],
  ['(2|dalawang|two|3|tatlong) ?(linggo|weeks?).{0,15}(ubo|cough)|(ubo|cough).{0,25}(2|dalawang|two|3|tatlong|ilang) ?(linggo|weeks?)|matagal na ubo|chronic cough', ['chronic_cough']],
  ['masakit ang lalamunan|sakit ng lalamunan|sore throat|pharyngitis', ['sore_throat']],
  ['makati ang lalamunan|sumisikip ang lalamunan|throat tightness|hoarse', ['throat_tight']],
  // abdomen
  ['sakit ng tiyan|masakit ang tiyan|pananakit ng tiyan|sumasakit ang tiyan|abdominal pain|stomach ache|tummy ache', ['abd_pain']],
  ['sikmura|hapdi ng sikmura|epigastric|heartburn|ulcer pain', ['epi_pain','abd_pain']],
  ['kanang itaas ng tiyan|right upper quadrant|ruq', ['ruq_pain','abd_pain']],
  ['kanang ibaba ng tiyan|right lower quadrant|rlq|right iliac', ['rlq_pain','abd_pain']],
  ['puson|pelvic pain|left lower quadrant|llq|hypogastric', ['llq_pain']],
  ['lumipat sa kanan|migrat\\w* to (the )?(rlq|right)|periumbilical', ['migration']],
  ['masakit ang tagiliran|sakit sa tagiliran|tagiliran|flank pain|renal colic', ['flank_pain']],
  ['nasusuka|naduduwal|nausea|nauseous', ['nausea']],
  ['nagsusuka|pagsusuka|sumusuka|suka nang suka|vomit\\w*|emesis', ['vomiting']],
  ['suka nang suka|hindi makakain|hindi makainom|persistent vomiting|intractable vomiting|cannot tolerate (oral|fluids)', ['persist_vomit','vomiting']],
  ['pagtatae|nagtatae|natatae|lbm|loose bowel|diarrh\\w*|watery stools?', ['diarrhea']],
  ['dugo sa dumi.{0,10}(tae|pagtatae)|duguang pagtatae|bloody diarrh\\w*|dysentery|mucoid', ['dysentery','diarrhea']],
  ['nagsuka ng dugo|suka na may dugo|hematemesis|coffee[- ]ground', ['hematemesis']],
  ['itim na dumi|maitim na dumi|melena|black stools?|tarry', ['melena']],
  ['dugo sa dumi|may dugo ang dumi|hematochezia|rectal bleeding|bright red blood', ['hematochezia']],
  ['hindi makadumi|hindi nakakautot|obstipation|no flatus', ['obstipation']],
  ['kabag|lumalaki ang tiyan|bloat\\w*|distension|distended', ['distension']],
  ['matatabang pagkain|fatty (meal|food)|after eating (lechon|fatty)', ['fatty_meal']],
  ['tibi|constipat\\w*', ['constipation']],
  // GU / OB
  ['masakit umihi|mahapdi umihi|hapdi sa pag-?ihi|mahapdi ang pag-?ihi|balisawsaw|dysuria|burning (on|with) urination', ['dysuria']],
  ['madalas umihi|ihi nang ihi|frequency|urgency', ['frequency']],
  ['dugo sa ihi|mapulang ihi|hematuria|tea-?colou?red urine', ['hematuria']],
  ['dinudugo sa ari|pagdurugo sa ari|vaginal bleeding|spotting|regla na malakas', ['vag_bleed']],
  ['hindi dinadatnan|hindi pa dinadatnan|delayed (mens|period)|missed period|atrasado ang regla|late period|amenorrh\\w*', ['amenorrhea']],
  ['buntis|nagdadalang-?tao|pregnant', ['hcg_pos']],
  ['discharge sa ari|vaginal discharge', ['vag_discharge']],
  ['masakit ang bayag|bayag|testicular pain|scrotal pain', ['testis_pain']],
  ['ihi nang ihi|polyuria', ['polyuria']],
  ['uhaw na uhaw|laging nauuhaw|polydipsia|very thirsty', ['polydipsia']],
  // neuro
  ['sakit ng ulo|masakit ang ulo|sumasakit ang ulo|pananakit ng ulo|headache|cephalgia', ['headache']],
  ['biglang sumakit ang ulo|pinakamasakit na sakit ng ulo|worst headache|thunderclap', ['thunderclap','headache']],
  ['paninigas ng batok|matigas ang batok|matigas ang leeg|stiff neck|neck stiffness', ['neck_stiff_sx']],
  ['silaw|photophobia', ['photophobia']],
  ['nalilito|wala sa sarili|tulala|lito|confus\\w*|disorient\\w*|altered sensorium', ['confusion']],
  ['kombulsyon|kumbulsyon|nangisay|nangingisay|seizures?|convuls\\w*', ['seizure']],
  ['hindi maigalaw|nanghihina ang (kalahati|kanan|kaliwa)|one-?sided weakness|hemiparesis|left-?sided weakness|right-?sided weakness', ['focal_weak']],
  ['tabingi ang mukha|ngiwi ang mukha|facial droop|facial asymmetry', ['facial_droop']],
  ['bulol|hindi makapagsalita|slurred speech|aphasia|dysarthria', ['speech']],
  ['malabo ang paningin|nawalan ng paningin|doble ang paningin|diplopia|vision loss|blurred vision', ['vision']],
  ['umiikot ang paligid|vertigo|spinning', ['vertigo']],
  // exposures
  ['allergic|allergy|ate shrimp|ate peanuts?|kumain ng hipon|bee sting|kinagat ng bubuyog|new drug', ['allergen']],
  ['namamaga ang labi|namamaga ang mata|lip swelling|tongue swelling|angioedema', ['angioedema']],
  ['tagulabay|hives|urticaria|wheals', ['urticaria']],
  ['baha|lumusong|nilusong|floodwater|flood|wading', ['flood']],
  ['kinagat ng aso|kagat ng aso|kinagat ng pusa|kalmot ng pusa|dog bite|cat bite|cat scratch', ['animal_bite']],
  ['tuklaw|tinuklaw|kinagat ng ahas|ahas|snake ?bite|cobra', ['snake_bite']],
  ['pesticide|insecticide|organophosph\\w*|carbamate|lason sa daga|uminom ng lason|baygon|folidol|malathion', ['pesticide']],
  ['overdose|uminom ng maraming gamot|ininom lahat ng gamot|intentional ingestion', ['overdose']],
  ['paracetamol|acetaminophen|biogesic', ['apap_od']],
  ['lasing|nag-?inom|alcoholic|heavy drink\\w*|alcohol', ['alcohol']],
  ['lambanog|tuba|bahalina|methanol', ['lambanog']],
  ['init ng araw|bilad sa araw|nainitan|heat ?stroke|heat exposure', ['heat_exp']],
  ['exertional|on exertion|pag naglalakad|kapag napapagod', ['cp_exertional']],
  ['palawan|malaria', ['travel_mal']],
  ['tb contact|may tb sa bahay|kasama sa bahay.{0,10}tb|household tb', ['tb_contact']],
  ['street food|kumain sa labas|unsafe water|deep well|poso', ['unsafe_food']],
  ['may dengue sa bahay|kapitbahay.{0,15}dengue|dengue (cases|outbreak)', ['dengue_area']],
  ['natusok ng pako|kalawang|rusty nail|puncture wound', ['dirty_wound']],
  ['hindi nag-?insulin|missed insulin|ran out of insulin|stopped (insulin|meds)', ['missed_insulin']],
  // trauma (English / Tagalog / Taglish)
  ['naaksidente\\w*|aksidente|(?<!vascular )accident|(?<!(kidney|liver|lung|renal|needle-?stick) )injur(y|ed)|trauma|nasugatan|sugatan|nadisgrasya|disgrasya', ['trauma']],
  ['nabangga|bumangga|binangga|nabanggaan|banggaan|car crash|vehicular|mvc|motor vehicle (crash|collision|accident)|road crash|road traffic|tumaob|bumaligtad', ['mech_mvc','trauma']],
  ['motor(?! ?(weakness|deficit|function|exam|power|vehicle|strength))|motorsiklo|motorcycle|motorbike|naka-?motor|habal-?habal|tricycle|traysikel|scooter|angkas|rider', ['mech_moto','trauma']],
  ['walang helmet|walang suot na helmet|hindi naka-?helmet|no helmet|without (a )?helmet|unhelmeted', ['no_helmet','mech_moto','trauma']],
  ['naka-?helmet|may helmet|with (a )?helmet|helmeted|wearing (a )?helmet', ['helmet']],
  ['nasagasaan|sinagasaan|nabundol|binundol|pedestrian|struck by (a )?(car|vehicle|jeep\\w*|bus|truck|tricycle|motorcycle)|hit by (a )?(car|vehicle|jeep\\w*|bus|truck|tricycle|motorcycle)', ['mech_ped','trauma']],
  ['tumilapon|ejected|ejection|rollover|high[- ]speed|mabilis ang takbo|may namatay', ['mech_hienergy','trauma']],
  ['nahulog|nalaglag|fell from|fall from|fallen from|nahulog mula|bumagsak mula', ['mech_fall','trauma']],
  ['nadulas|natumba|napatid|slipped|tripped|ground[- ]level fall|fell (at home|in the bathroom|from standing)', ['mech_fall_low','trauma']],
  ['puno ng niyog|niyog|coconut tree|bubong|roof|scaffold\\w*|ikalawang palapag|2nd floor|second floor|3rd floor|third floor|construction site', ['mech_fall','fall_ge3m','trauma']],
  ['diving|nag-?dive|tumalon sa (ilog|dagat|pool)', ['mech_axial','trauma']],
  ['sinuntok|binugbog|bugbog|pinalo|hinampas|sinipa|pinagtulungan|assault\\w*|mauled|beaten|rumble', ['mech_assault','trauma']],
  ['sinaksak|nasaksak|saksak|tinaga|stab(bed)?|stab wounds?|knife|kutsilyo|patalim|balisong|ice ?pick|machete|itak|bolo', ['mech_stab','penetrating','trauma']],
  ['binaril|nabaril|baril|tama ng bala|bala|gunshot|gsw|was shot|got shot|shot (in|at) the|bullet', ['mech_gsw','penetrating','trauma']],
  ['napaso|nasunog|nalapnos|paso|sunog|burns?|burned|burnt|scald\\w*|flame|kumukulong tubig|mantika|lpg|sumabog|explosion', ['mech_burn','trauma']],
  ['nakuryente|kinuryente|electrocut\\w*|electrical injury|kidlat|lightning|high[- ]voltage', ['burn_elec','mech_burn','trauma']],
  ['usok|smoke inhalation|nakalanghap ng usok|enclosed space|sa loob ng bahay na nasusunog', ['burn_enclosed']],
  ['naipit|nadaganan|nabagsakan|nabagsak(an)? ng|gumuho|crush(ed)? (injury|by|under)|crush injury|crushed|entrap\\w*|pinned (under|by)|trapped under', ['mech_crush','trauma']],
  ['nalunod|nalulunod|nalubog|drown\\w*|submersion|submerged', ['mech_drown','trauma']],
  ['basag ang ulo|putok ang ulo|pumutok ang ulo|bukol sa ulo|nauntog|untog|tumama ang ulo|head (injury|trauma|wound)|hit (his|her|the) head|struck (his|her|the) head', ['head_inj','trauma']],
  ['nawalan ng ulirat|loss of consciousness|\\bloc\\b|knocked out|unconscious', ['loc']],
  ['nakainom|amoy alak|lasing na lasing|intoxicated|drunk', ['intox']],
  ['nagising (tapos|pero)|nakausap pa|lucid interval|talked and deteriorated', ['lucid']],
  ['bukol sa (gilid|likod) ng ulo|scalp hematoma', ['scalp_hematoma']],
  ['raccoon eyes|battle.?s sign|hemotympanum|csf (leak|rhinorrh\\w*|otorrh\\w*)|tumutulo ang tubig sa ilong', ['basilar']],
  ['masakit ang batok|masakit ang leeg|neck pain', ['neck_pain']],
  ['manhid|namamanhid|tingling|paresthesia\\w*', ['paresthesia']],
  ['hindi maigalaw ang (dalawang )?(paa|binti)|paralyzed|paraplegi\\w*|quadripleg\\w*|tetrapleg\\w*|walang pakiramdam sa (paa|binti)', ['cord_deficit']],
  ['balakang|pelvic (pain|fracture)|hip pain', ['pelvic_pain']],
  ['kaliwang balikat|left shoulder (tip )?pain|kehr', ['luq_tender']],
  ['dumudugo nang malakas|malakas ang pagdurugo|maraming dugo|duguan|bumubulwak|sumisirit ang dugo|active bleeding|profuse bleeding|spurting|arterial bleeding', ['ext_hemorrhage']],
  ['bali|nabali|baling|fracture[ds]?|deformity|deformed', ['long_bone']],
  ['lumabas ang buto|nakalabas ang buto|bone (exposed|sticking out)|open fracture|compound fracture', ['open_fx','long_bone']],
  ['femur fracture|fractured femur|bali sa hita|baling hita', ['femur_fx']],
  ['hindi makaihi|unable to void|cannot void|urinary retention', ['unable_void']],
  ['kulay coke ang ihi|cola-colou?red urine|dark urine|maitim na ihi', ['dark_urine']],
  ['blood thinner|pampalabnaw ng dugo|warfarin|apixaban|rivaroxaban|dabigatran|edoxaban|anticoagula\\w*', ['m_anticoag']],
  ['clopidogrel|aspirin|antiplatelet', ['m_antiplt']],
  ['paos|namamaos|hoarse voice|voice change|singed|carbonaceous|uling sa ilong', ['voice_change']],
  ['hindi gumagalaw ang baby|walang heartbeat ang baby|fetal (distress|bradycardia)', ['fhr_abn']],
  // pediatric (Taglish caregiver phrases)
  ['kinukumbulsyon|kinumbulsyon|kinokombulsyon|nagkukumbulsyon|nagkombulsyon|kumbulsiyon|kombulsiyon|nangingisay|nanginig ang buong katawan|febrile seizure', ['seizure']],
  ['ayaw dumede|ayaw nang dumede|ayaw dumedede|hindi dumedede|ayaw sumuso|mahina dumede|mahinang dumede|ayaw kumain|ayaw nang kumain|poor (feeding|suck)|feeding poorly|not feeding', ['poor_feed']],
  ['hindi makadede|hindi na makadede|hindi makasuso|hindi na makainom|unable to (drink|breastfeed|feed)', ['ds_drink','poor_feed']],
  ['isinusuka lahat|sinusuka lahat|lahat ng (kinakain|iniinom|dinede) (ay )?(sinusuka|isinusuka)|vomits everything', ['ds_vomit','vomiting']],
  ['matamlay|lantang-?lanta|malata|walang sigla|lethargic|floppy|hard to wake|mahirap gisingin', ['lethargy']],
  ['iyak nang iyak|umiiyak nang umiiyak|iritable|irritable|fussy|maligalig', ['irritable']],
  ['hindi mapatahan|ayaw tumahan|inconsolable', ['inconsolable','irritable']],
  ['sipon|sinisipon|tumutulo ang sipon|barado ang ilong|runny nose|coryza|rhinorrh\\w*', ['coryza']],
  ['parang tahol|tumatahol|tahol ng aso|barking|barky|seal-?like|croupy', ['barking','cough']],
  ['humuhuni|maingay ang paghinga|stridor', ['stridor']],
  ['naglalaway|tumutulo ang laway|drooling', ['drooling']],
  ['nabulunan|nabilaukan|nasamid|naka-?lunok ng (mani|barya|laruan|buto)|choking|choked', ['choking']],
  ['sakit ng tainga|masakit ang tainga|masakit ang tenga|sakit ng tenga|hinihila ang tenga|hinihila ang tainga|nana sa tenga|ear ?ache|ear pain|otalgia|otorrh\\w*', ['ear_pain']],
  ['humihinto ang paghinga|tumitigil ang paghinga|apnea|apnoea|brue', ['apnea']],
  ['nangingitim|nangangasul|nagkukulay ube|kulay ube ang labi|cyanosis|cyanotic|bluish|blue lips', ['cyanosis']],
  ['pinagpapawisan habang dumedede|hinihingal habang dumedede|sweating with feeds|breathless with feeds', ['sweat_feed']],
  ['berde ang suka|kulay berde ang suka|green vomit\\w*|bilious', ['bilious','vomiting']],
  ['pumupulandit|bumubulwak na suka|projectile', ['projectile','vomiting']],
  ['iyak nang iyak tapos tumitigil|paputol-putol na iyak|nakabaluktot ang (paa|binti)|legs drawn up|episodic (crying|pain)|colicky pain', ['episodic_pain']],
  ['parang jelly ang dumi|currant[- ]jelly|dugo at sipon sa dumi|may sipon at dugo ang dumi', ['currant','hematochezia']],
  ['naninilaw (na )?(sa|noong) unang araw|jaundice (in the )?first 24', ['jaundice_24h','jaundice']],
  ['maputla ang dumi|puti ang dumi|pale stools?|acholic', ['pale_stool']],
  ['paika-?ika|pilay|limping|limp', ['limp']],
  ['ayaw tumapak|ayaw tumayo|ayaw maglakad|hindi makalakad|refuses to (walk|bear weight)|non-?weight-?bearing', ['nwb']],
  ['naiihi sa kama|bed-?wetting|enuresis', ['enuresis']],
  ['singaw|sugat sa bibig|sugat-sugat sa bibig|mouth (sores|ulcers)|oral ulcers', ['oral_ulcers']],
  ['butlig sa (kamay|palad|paa|talampakan)|paltos sa (kamay|paa)|hand,? foot,? (and )?mouth|hfmd', ['hand_vesicles','rash']],
  ['tigdas|measles|rubeola', ['measles_contact','rash']],
  ['nakalunok|nakainom ng|accidental ingestion|ingested', ['ingestion']],
  ['gaas|kerosene|gasolina|gasoline|thinner|lamp oil|paint thinner|hydrocarbon', ['ingest_kero','ingestion']],
  ['ferrous|iron (tablets?|pills?|supplements?)|pampadugo', ['ingest_iron','ingestion']],
  ['lumulubog ang dibdib|hinihila ang dibdib|lubog ang dibdib|chest indrawing|retractions?|subcostal', ['chest_indraw']],
  ['umuungol|grunting', ['grunting']],
  ['lubog ang mata|malalim ang mata|sunken eyes', ['sunken_eyes']],
  ['lubog ang bunbunan|sunken fontanel\\w*', ['fontanelle_sunken']],
  ['nakaumbok ang bunbunan|umbok ang bunbunan|bulging fontanel\\w*', ['fontanelle_bulge']],
  ['uhaw na uhaw ang bata|sabik uminom|drinks eagerly', ['drinks_eager']],
  ['namumula ang mata|mapula ang mata|pula ang mata|red eyes|conjunctivitis', ['conj_red']],
  ['namamaga ang (kamay|paa|palad|talampakan)|swollen (hands|feet)', ['kd_extrem','swelling']],
  ['namamaga ang (leeg|kulani)|kulani sa leeg|bukol sa leeg|neck (swelling|lump)', ['cerv_nodes','swelling']],
  ['namamaga ang bayag|swollen scrotum|scrotal swelling', ['scrotal_swell','testis_pain','swelling']],
  ['namamaga ang (tuhod|balakang|kasukasuan|siko|bukung-?bukong)', ['hot_joint','swelling']],
  ['namamaga|maga|swelling|swollen', ['swelling']],
  ['mapula at bitak-?bitak ang labi|bitak ang labi|strawberry tongue|cracked lips', ['kd_oral']],
  ['walang bakuna|kulang ang bakuna|hindi bakunado|hindi nabakunahan|unvaccinated|unimmuni[sz]ed|incomplete (immuni[sz]ations?|vaccinations?)|no vaccines?', ['unimmunized']],
  ['kumpleto ang bakuna|kumpleto sa bakuna|complete (immuni[sz]ations?|vaccinations?|vaccines)|fully (immuni[sz]ed|vaccinated)|up to date (on|with) (vaccines|immuni[sz]ations)', ['imm_complete']],
  ['pinalo|sinaktan ng (magulang|tatay|nanay|tito|tiyuhin|stepfather)|hindi tugma ang kwento|child abuse|pang-?aabuso|inconsistent (history|story)', ['abuse_concern']],
  ['premature|preterm|kulang sa buwan', ['preterm']],
  // PMH
  ['high blood|altapresyon|hypertensi\\w*|\\bhtn\\b', ['htn']],
  ['diabet\\w*|\\bdm\\b|mataas ang asukal|may sugar', ['dm']],
  ['naninigarilyo|nagyoyosi|yosi|smoker|smoking|cigarettes?', ['smoker']],
  ['tb dati|nagka-?tb|treated for tb|prior tb|ptb', ['tb_hx']],
  ['nakaratay|bedridden|immobili\\w*|recent surgery|post-?op|long (flight|bus trip)', ['immobil']],
  ['birth control pills?|contraceptive pills?|contraceptives?|\\bocp\\b|estrogen', ['m_estrogen']],
  ['kanser|cancer|malignan\\w*|chemo\\w*', ['malignancy']],
  ['bato sa apdo|gallstones?', ['gallstones']],
  ['bato sa bato|kidney stones?|nephrolithiasis', ['stones']],
  ['dialysis|ckd|kidney disease', ['ckd']],
];
const NEG_CUES = /(\b(no|not|denies|denied|without|negative for|walang|wala|hindi|di|never|absent)\b)[^.;,]{0,25}$/;
