// =====================================================================
// DDx Assist – knowledge base. Original summaries; organised by the Tintinalli 9e
// SECTION / TOPIC MAP only (no book text). PH CPG preferred where one exists.
// Weights: points ≈ log2(likelihood ratio). +1 ≈ LR 2, +2 ≈ LR 4, +3 ≈ LR 8, −2 ≈ LR 0.25.
//   w = weight when finding PRESENT · a = weight when finding explicitly ABSENT (−)
//   g = gate (≥1 present for the condition to be considered) · p = prior (prevalence in PH ED)
//   rf = red flags · ex(S) = hard exclusion (returns reason) · mnm = must-not-miss
//   "[V]" renders as ⚠ VERIFY – every dose carries it.
// =====================================================================
'use strict';
const TK_SEC = {3:'S3 Resuscitation',7:'S7 Cardiovascular',8:'S8 Pulmonary',9:'S9 Gastrointestinal',10:'S10 Renal & GU',11:'S11 Obstetrics & Gynecology',
  12:'S12 Pediatrics',13:'S13 Infectious Diseases',14:'S14 Neurology',15:'S15 Toxicology',16:'S16 Environmental',17:'S17 Endocrine',19:'S19 EENT',
  20:'S20 Dermatology',23:'S23 Musculoskeletal',24:'S24 Psychosocial'};
const notMale = S => S.sex==='M' ? 'male patient' : null;
const KB = [];
// ───────────────────────── S7 CARDIOVASCULAR ─────────────────────────
KB.push(
{id:'stemi', n:'ACS – STEMI', sec:7, topic:'Acute coronary syndromes / STEMI', mnm:1, p:0,
 g:['chest_pain','cp_pressure','ecg_ste'],
 w:{chest_pain:1,cp_pressure:1.5,cp_radiate:1.5,diaphoresis:1.5,cp_exertional:0.5,nausea:0.5,ecg_ste:5,trop_pos:2,age_ge50:0.5,male:0.5,htn:0.5,dm:0.5,smoker:0.5,dyslipid:0.5,cad:1,fam_cad:0.5,sbp_lt90:0.5,
    cp_pleuritic:-1.5,cp_positional:-1.5,ecg_diffuse:-3,age_lt40:-1,cp_back:-0.5},
 a:{ecg_ste:-3},
 rf:['ecg_ste','sbp_lt90','crackles_bilat','s3','cool_periph'],
 dx:['12-lead ECG within 10 min of arrival; repeat q15–30 min if non-diagnostic; add V7–V9 and V4R (posterior / RV infarct)',
     'Troponin (hs-cTn if available) – never delay reperfusion waiting for it','CBC, creatinine, electrolytes, glucose, PT/aPTT (before lytics)',
     'Portable CXR (do not delay reperfusion); bedside echo for wall motion / complications'],
 dxs:'PHA 2014 CPG on CAD (PH CPG) · ESC 2023 ACS (intl)',
 tx:['Reperfusion decision now: primary PCI if achievable ≤ 120 min from first medical contact (call the PCI centre); otherwise fibrinolysis within 30 min door-to-needle unless contraindicated',
     'Fibrinolytic (PH availability varies): streptokinase 1.5 million IU IV over 30–60 min [V]; or tenecteplase weight-based single bolus (half-dose if ≥ 75 y) [V]; or alteplase accelerated regimen [V]',
     'Aspirin 160–325 mg chewed [V]',
     'P2Y12: clopidogrel 300 mg PO load with lytics (75 mg if ≥ 75 y), 600 mg if primary PCI [V]; or ticagrelor 180 mg load for primary PCI [V]',
     'Anticoagulant: enoxaparin 30 mg IV bolus then 1 mg/kg SC q12h (≥ 75 y: no bolus, 0.75 mg/kg) [V]; or UFH weight-based [V]',
     'Nitroglycerin 0.4 mg SL q5 min × 3 for ongoing pain if SBP > 90 and no RV infarct / PDE-5 inhibitor [V]; O₂ only if SpO₂ < 90 %; high-intensity statin (atorvastatin 40–80 mg) [V]'],
 txs:'PHA 2014 CPG on CAD (PH CPG) · ESC 2023 ACS (intl)',
 dispo:'CCU / cath lab. If no PCI on site: lytics then transfer (pharmaco-invasive, angiography 2–24 h).',
 tk:['acs','STEMI','ACS / STEMI timeline']},
{id:'nstemi', n:'ACS – NSTE-ACS (NSTEMI / unstable angina)', sec:7, topic:'Acute coronary syndromes · Low-probability ACS (HEART)', mnm:1, p:0,
 g:['chest_pain','cp_pressure','ecg_std','trop_pos'],
 w:{chest_pain:1,cp_pressure:1.5,cp_radiate:1.5,diaphoresis:1,cp_exertional:1.5,dyspnea:0.5,ecg_std:2.5,trop_pos:2.5,age_ge50:0.5,male:0.3,htn:0.5,dm:0.5,smoker:0.5,dyslipid:0.5,cad:1.5,fam_cad:0.5,
    cp_pleuritic:-1.5,cp_positional:-1.5,ecg_ste:-2,ecg_diffuse:-2,age_lt40:-1},
 rf:['trop_pos','ecg_std','sbp_lt90','crackles_bilat'],
 dx:['Serial ECGs (and with any recurrent pain)','hs-troponin 0/1 h or 0/2 h algorithm (conventional troponin: 0/3–6 h)','HEART score for low-risk pathway (shown in Scores)',
     'CBC, creatinine, electrolytes, glucose, lipid profile; CXR; echo if available'],
 dxs:'PHA 2014 CPG on CAD (PH CPG) · ESC 2023 ACS (intl)',
 tx:['Aspirin 160–325 mg loading then 75–100 mg daily [V]','P2Y12 inhibitor per risk / cath plan: clopidogrel 300–600 mg load [V] or ticagrelor 180 mg load [V]',
     'Anticoagulation: enoxaparin 1 mg/kg SC q12h (CrCl < 30: q24h) [V] or fondaparinux 2.5 mg SC daily [V]',
     'Nitrates for ongoing pain [V]; β-blocker if no HF, hypotension or bradycardia [V]; high-intensity statin [V]'],
 txs:'PHA 2014 CPG on CAD (PH CPG) · ESC 2023 ACS (intl)',
 dispo:'High risk (positive troponin, dynamic ECG, instability) → admit CCU, invasive strategy < 24 h. HEART 0–3 with negative serial troponins → discharge with early follow-up.',
 tk:['heart','HEART score','HEART score / ACS']},
{id:'dissection', n:'Acute aortic dissection', sec:7, topic:'Aortic dissection & acute aortic syndromes', mnm:1, p:-0.5,
 g:['chest_pain','cp_back','abd_back','pulse_deficit','cxr_mediast'],
 a:{cp_back:-1,pulse_deficit:-0.5},
 w:{cp_back:3.5,onset_sudden:2,chest_pain:0.5,pulse_deficit:3.5,htn:1,ctd:2,age_ge50:0.5,cxr_mediast:2.5,murmur:1,focal_weak:1,hemiparesis:1,syncope:1,htn_sev:1,sbp_lt90:1,abd_back:0.5,
    cp_pleuritic:-1,age_lt40:-1,cp_exertional:-0.5},
 rf:['pulse_deficit','sbp_lt90','focal_weak','murmur','syncope'],
 dx:['CT aortography (definitive) – do not delay for other tests if ADD-RS ≥ 2','Bedside echo: flap, pericardial effusion, aortic root > 4 cm, AR',
     'ECG (dissection can involve the RCA → inferior STEMI: check before lytics), CXR, troponin, type & crossmatch, creatinine',
     'ADD-RS ≤ 1 with D-dimer < 500 ng/mL lowers probability (not for high-risk patients)'],
 dxs:'ESC 2024 peripheral arterial & aortic diseases · ACC/AHA 2022 aortic disease (intl)',
 tx:['Analgesia (IV opioid, e.g. morphine 2–4 mg IV titrated) [V]',
     'Impulse control first: target HR < 60 and SBP 100–120 mmHg within ~20 min – esmolol 500 mcg/kg bolus then 50–300 mcg/kg/min [V] or labetalol 20 mg IV then 20–80 mg q10 min [V]',
     'Then vasodilator if SBP still high: nicardipine 5 mg/h, titrate 2.5 mg/h q5–15 min (max 15 mg/h) [V]',
     'NO fibrinolytics / anticoagulation. Type A → emergency cardiothoracic surgery; type B uncomplicated → medical therapy, ICU'],
 txs:'ESC 2024 aortic (intl) · see also 2024 PH CPG on Acute Severe BP Elevation (PH CPG)',
 dispo:'ICU; immediate CT surgery referral / transfer for type A.',
 tk:['aorta','aortic dissection','Aortic dissection']},
{id:'ahf', n:'Acute heart failure / cardiogenic pulmonary edema', sec:7, topic:'Acute heart failure', mnm:1, p:0,
 g:['dyspnea','orthopnea','edema','crackles_bilat','cxr_edema'],
 w:{dyspnea:1,orthopnea:2.5,edema:1.5,crackles_bilat:2,jvd:2.5,s3:3,hf:2.5,cad:0.5,htn:0.5,cxr_edema:3,spo2_lt94:0.5,htn_sev:1,wheeze:0.3,ckd:0.5,
    fever:-1,t_ge38:-1,sputum:-0.5,cp_pleuritic:-1,dvt_signs:-0.5},
 rf:['sbp_lt90','spo2_lt90','cool_periph','trop_pos'],
 dx:['ECG + troponin (ACS precipitant?)','POCUS: bilateral B-lines, LV function, IVC; CXR','BNP / NT-proBNP if available','Electrolytes, creatinine, CBC, glucose; ABG/VBG if distressed'],
 dxs:'ESC 2021 HF + 2023 focused update (intl) – PH 2023 HF CPG covers chronic HFrEF only',
 tx:['Sit upright; O₂ to SpO₂ ≥ 94 %; early CPAP/BiPAP for respiratory distress or pulmonary edema',
     'Furosemide 40 mg IV (or 1–2.5 × usual oral dose IV) for congestion [V]',
     'Hypertensive (SCAPE): nitroglycerin 0.4 mg SL q5 min then infusion 10–20 mcg/min titrated [V]',
     'Cardiogenic shock (SBP < 90 + hypoperfusion): norepinephrine 0.05–0.5 mcg/kg/min ± dobutamine 2–20 mcg/kg/min [V]; avoid nitrates/diuretic boluses until perfused',
     'Treat precipitant: ACS, arrhythmia, hypertension, infection, non-adherence, anemia'],
 txs:'ESC 2021 HF (intl)',
 dispo:'Admit; ICU/CCU if NIV, shock or ACS.',
 tk:['ahf','heart failure','Acute heart failure & cardiogenic shock']},
{id:'htnemerg', n:'Hypertensive emergency (incl. encephalopathy)', sec:7, topic:'Systemic hypertension / hypertensive emergencies', mnm:1, p:0,
 g:['htn_sev'],
 w:{htn_sev:3,headache:1,confusion:1.5,vision:1.5,seizure:1,chest_pain:0.5,dyspnea:0.5,crackles_bilat:0.5,htn:1,cr_high:1,hematuria:0.5,focal_weak:0.5,cxr_edema:0.5},
 rf:['confusion','seizure','vision','chest_pain','cr_high'],
 dx:['Look for acute target-organ damage: fundoscopy, neuro exam, ECG, troponin, creatinine, UA (protein/blood), CBC + smear (TMA)','CT head if neuro signs (exclude stroke/ICH)',
     'Pregnancy test in women of reproductive age (pre-eclampsia)','No organ damage = severe asymptomatic hypertension (urgency) – avoid rapid lowering'],
 dxs:'2024 PH CPG on Acute Severe BP Elevation (PH CPG) · 2020 PH Hypertension CPG (PH CPG)',
 tx:['Emergency (organ damage): IV titratable agent; reduce MAP by ≤ 25 % in the first hour, then to ~160/100–110 over 2–6 h, normal over 24–48 h (exceptions: dissection, pre-eclampsia, acute stroke)',
     'Nicardipine 5 mg/h IV, titrate 2.5 mg/h q5–15 min (max 15 mg/h) [V]; or labetalol 20 mg IV then 20–80 mg q10 min (max 300 mg) [V]',
     'Urgency (no organ damage): oral agents, rest, recheck; SL nifedipine NOT recommended; arrange follow-up'],
 txs:'2024 PH CPG on Acute Severe BP Elevation (PH CPG – details recalled, verify) · ESC 2024 (intl)',
 dispo:'Emergency → ICU/step-down. Urgency → discharge with follow-up within days.',
 tk:['cvhtn','hypertensive emergency','Hypertensive emergencies']},
{id:'pericarditis', n:'Acute pericarditis / myopericarditis', sec:7, topic:'Cardiomyopathies & pericardial disease', mnm:0, p:0,
 g:['chest_pain','rub','ecg_diffuse'],
 w:{cp_pleuritic:1.5,cp_positional:3.5,rub:4,ecg_diffuse:4,fever:0.5,infection_sx:1,age_lt40:0.5,us_effusion:1,chest_pain:0.5,
    cp_exertional:-1,cp_pressure:-0.5,diaphoresis:-0.5,age_ge65:-0.5},
 rf:['muffled','sbp_lt90','trop_pos','t_ge38'],
 dx:['ECG (diffuse STE + PR depression), troponin (myopericarditis if raised)','CRP/ESR, CBC; echo for effusion','PH context: consider TB pericarditis (Xpert / ADA on fluid), uremia, autoimmune'],
 dxs:'ESC 2025 myocarditis & pericarditis (intl)',
 tx:['Ibuprofen 600 mg PO q8h × 1–2 wk with gastroprotection [V] or aspirin 750–1000 mg q8h [V]','Colchicine 0.5 mg BID (0.5 mg daily if < 70 kg) × 3 months [V]',
     'Avoid steroids first-line; restrict exercise'],
 txs:'ESC 2025 pericardial (intl)',
 dispo:'Outpatient if no high-risk features (fever > 38, large effusion, tamponade, troponin +, immunosuppressed, anticoagulated, NSAID failure).',
 tk:['peri','pericarditis','Pericarditis, myocarditis, tamponade']},
{id:'tamponade', n:'Cardiac tamponade', sec:7, topic:'Pericardial disease (tamponade)', mnm:1, p:-1,
 g:['muffled','jvd','us_effusion','sbp_lt90','dyspnea'],
 w:{muffled:3,jvd:2,sbp_lt90:1.5,hr_gt100:1,us_effusion:4,narrow_pp:1,malignancy:1.5,ckd:1,tb_hx:1,dyspnea:0.5,crackles_bilat:-1.5,cxr_edema:-1},
 rf:['sbp_lt90','muffled'],
 dx:['POCUS: effusion with RA/RV diastolic collapse, plethoric IVC','ECG: low voltage, electrical alternans','Send fluid: cell count, Gram/AFB, Xpert MTB/RIF, ADA, cytology'],
 dxs:'ESC 2015/2025 pericardial (intl)',
 tx:['Small fluid bolus as bridge (e.g. 250–500 mL crystalloid) [V]','Urgent ultrasound-guided pericardiocentesis; avoid positive-pressure ventilation if possible','Treat cause (TB, malignancy, uremia → dialysis)'],
 txs:'ESC pericardial (intl)', dispo:'ICU / cardiology.', tk:['peri','tamponade','Pericarditis, myocarditis, tamponade']},
{id:'aaa', n:'Ruptured / symptomatic AAA', sec:7, topic:'Aneurysmal disease (AAA)', mnm:1, p:-1,
 g:['abd_pain','flank_pain','abd_back','pulsatile','us_aaa'],
 w:{pulsatile:4,us_aaa:4,age_ge65:1.5,age_ge50:0.5,male:1,smoker:1,htn:0.5,abd_back:2,flank_pain:1,syncope:1.5,sbp_lt90:1.5,onset_sudden:1,age_lt40:-3,female:-0.5,fever:-1},
 rf:['sbp_lt90','syncope'],
 dx:['Bedside US of aorta (> 3 cm) – a "renal colic" in a > 50 y man is AAA until proven otherwise','CTA if stable','Type & crossmatch, CBC, creatinine, coags'],
 dxs:'ESVS 2024 AAA (intl)',
 tx:['Permissive hypotension (SBP 70–90 if mentating); blood products / massive transfusion protocol','Immediate vascular surgery; transfer if unavailable'],
 txs:'ESVS 2024 (intl)', dispo:'OR / transfer.', tk:['aorta','AAA','Aortic dissection (AAA)']},
{id:'tachy', n:'Tachyarrhythmia (AF with RVR / SVT / VT)', sec:7, topic:'Brady/tachy arrhythmias', mnm:0, p:0,
 g:['palpitations','irregular','ecg_af','hr_ge125'],
 w:{palpitations:2,irregular:2.5,ecg_af:4,hr_gt100:1,hr_ge125:1.5,syncope:0.5,dizziness:0.5,af:2,thyroid:1,chest_pain:0.3,dyspnea:0.3},
 rf:['sbp_lt90','syncope','chest_pain','gcs_lt15'],
 dx:['12-lead ECG + rhythm strip','K⁺, Mg²⁺, TSH, troponin if chest pain, CBC','Echo; look for precipitant (sepsis, PE, thyrotoxicosis, alcohol)'],
 dxs:'AHA 2025 ACLS (intl) · ESC 2024 AF (intl)',
 tx:['Unstable → synchronized cardioversion (e.g. AF 120–200 J biphasic) with sedation [V]','Stable SVT: modified Valsalva, then adenosine 6 mg rapid IV push, 12 mg if needed [V]',
     'AF with RVR: diltiazem 0.25 mg/kg IV over 2 min [V] or metoprolol 2.5–5 mg IV [V]; HF/hypotension → amiodarone 150 mg IV over 10 min [V] or digoxin',
     'Stable VT: amiodarone 150 mg IV over 10 min [V]; anticoagulation decision (CHA₂DS₂-VA)'],
 txs:'AHA 2025 ACLS · ESC 2024 AF (intl)', dispo:'Admit if unstable, new AF with comorbidity, VT; stable SVT converted → home.', tk:['arrhy','arrhythmia','Arrhythmias']},
{id:'brady', n:'Symptomatic bradycardia / heart block', sec:7, topic:'Brady arrhythmias · cardiac pacing', mnm:1, p:-0.5,
 g:['hr_lt60'],
 w:{hr_lt60:3,syncope:2,dizziness:1,m_bb:1.5,sbp_lt90:1,age_ge65:0.5,confusion:0.5,secretions:-2,miosis:-2,pesticide:-3},
 rf:['sbp_lt90','syncope','gcs_lt15'],
 dx:['ECG (AV block type; inferior MI?)','K⁺ (hyperkalemia), glucose, troponin, TSH','Drug review: β-blocker, CCB, digoxin (level)'],
 dxs:'AHA 2025 ACLS (intl)',
 tx:['Atropine 1 mg IV q3–5 min (max 3 mg) [V]','Transcutaneous pacing if unresponsive; or epinephrine 2–10 mcg/min / dopamine 5–20 mcg/kg/min infusion [V]',
     'Treat cause: hyperkalemia (calcium gluconate 10 % 30 mL IV [V]), β-blocker/CCB toxicity (calcium, glucagon, high-dose insulin) [V]'],
 txs:'AHA 2025 ACLS (intl)', dispo:'CCU; transvenous pacing / cardiology.', tk:['pacing','pacing','Cardiac pacing & implanted devices']},
{id:'pe', n:'Pulmonary embolism', sec:7, topic:'Venous thromboembolism incl. PE', mnm:1, p:0,
 g:['dyspnea','cp_pleuritic','chest_pain','syncope','hemoptysis','dvt_signs','spo2_lt94'],
 w:{dyspnea:1.5,cp_pleuritic:1.5,onset_sudden:1,dvt_signs:3,hemoptysis:1,hr_gt100:1,spo2_lt94:1,syncope:1,immobil:2,dvt_hx:2,malignancy:1.5,m_estrogen:1.5,postpartum:1.5,pregnant:1,ecg_rv:2,us_rv:2.5,
    sputum:-1.5,t_ge39:-1,crackles_bilat:-1,wheeze_pe:-1,cxr_consol:-1,cxr_edema:-2,orthopnea:-1,cp_pressure:-0.5,cp_radiate:-0.5,ecg_ste:-1.5},
 a:{hr_gt100:-0.5,spo2_lt94:-0.5},
 rf:['sbp_lt90','spo2_lt90','us_rv','syncope'],
 dx:['Wells → if PE unlikely: PERC (if gestalt low) then D-dimer (age-adjusted: age × 10 ng/mL if > 50 y)','PE likely or D-dimer + → CTPA (V/Q or leg compression US if contrast contraindicated / pregnant)',
     'Bedside echo (RV dilation) and leg compression US – key in unstable patients who cannot go to CT','ECG, troponin, BNP for risk stratification; sPESI'],
 dxs:'ESC 2019 PE (intl)',
 tx:['Start anticoagulation while awaiting imaging if probability high/intermediate and bleeding risk acceptable: enoxaparin 1 mg/kg SC q12h [V] or UFH 80 U/kg IV bolus then 18 U/kg/h [V]',
     'High-risk PE (shock): systemic thrombolysis – alteplase 100 mg IV over 2 h [V] or streptokinase 250 000 IU over 30 min then 100 000 IU/h × 12–24 h [V]',
     'Hypotension: cautious fluids (≤ 500 mL), norepinephrine [V]; avoid intubation if possible',
     'Low-risk (sPESI 0): DOAC, e.g. rivaroxaban 15 mg BID × 21 d then 20 mg daily [V] – early discharge'],
 txs:'ESC 2019 PE (intl)', dispo:'High-risk → ICU; intermediate → admit; low-risk (sPESI 0) → consider early discharge.',
 tk:['pe','pulmonary embolism','Pulmonary embolism – ESC 2019']},
{id:'dvt', n:'Deep vein thrombosis (isolated)', sec:7, topic:'Venous thromboembolism', mnm:0, p:0,
 g:['dvt_signs'],
 w:{dvt_signs:3,immobil:1.5,dvt_hx:1.5,malignancy:1,m_estrogen:1,pregnant:1,postpartum:1,cellulitis:-1,fever:-0.5,dyspnea:-0.5,cp_pleuritic:-0.5},
 rf:['dyspnea','spo2_lt94'],
 dx:['Wells DVT; D-dimer if unlikely','Compression ultrasound (2-point POCUS or formal)'],dxs:'ASH 2020 / ACCP 2021 VTE (intl)',
 tx:['Anticoagulate: rivaroxaban 15 mg BID × 21 d then 20 mg daily [V] or enoxaparin 1 mg/kg SC q12h bridging to warfarin (INR 2–3) [V]','Screen for PE symptoms'],
 txs:'ASH 2020 VTE (intl)', dispo:'Outpatient if stable and reliable.', tk:['pe','DVT','Pulmonary embolism / VTE']}
);
// ───────────────────────── S8 PULMONARY ─────────────────────────
KB.push(
{id:'cap', n:'Community-acquired pneumonia', sec:8, topic:'Pneumonia (CAP)', mnm:0, p:1,
 g:['cough','fever','dyspnea','crackles_focal','cxr_consol','bronchial'],
 a:{cough:-1},
 w:{cough:1.5,sputum:1.5,fever:1,t_ge38:1,dyspnea:1,cp_pleuritic:0.5,crackles_focal:2.5,bronchial:2.5,cxr_consol:4,rr_ge22:0.5,spo2_lt94:0.5,hr_gt100:0.3,wbc_high:0.5,chills:0.5,dur_le7d:0.5,
    dur_ge14d:-1,orthopnea:-1,cxr_edema:-1.5,dvt_signs:-1,edema:-0.5,cxr_cavity:-1},
 rf:['rr_ge30','sbp_lt90','spo2_lt90','gcs_lt15','hr_ge125'],
 dx:['CXR PA/lateral (required to classify risk)','Moderate/high risk: CBC, BUN/creatinine, glucose, electrolytes, ABG or SpO₂','Blood cultures × 2 and sputum Gram stain/culture BEFORE antibiotics in moderate/high risk',
     'Sputum Xpert MTB/RIF if cough ≥ 2 wk, upper-lobe/cavitary infiltrate or TB risk (high-burden country)','Influenza / COVID-19 test when circulating'],
 dxs:'PCAP 2016 – PH CPG on CAP in Immunocompetent Adults (PH CPG)',
 tx:['Classify with PCAP 2016 risk (see Scores) – site of care follows risk class',
     'Low risk, no comorbid: amoxicillin 1 g PO TID [V] (alt: extended macrolide, e.g. azithromycin 500 mg OD × 3 d [V] or clarithromycin 500 mg BID [V])',
     'Low risk + stable comorbid: oral β-lactam/BLI (co-amoxiclav 625 mg TID or 1 g BID [V]; sultamicillin 750 mg BID [V]) or cefuroxime 500 mg BID [V] ± extended macrolide',
     'Moderate risk (ward): IV non-antipseudomonal β-lactam – ceftriaxone 2 g IV OD [V], ampicillin-sulbactam 1.5–3 g IV q6h [V] or co-amoxiclav 1.2 g IV q8h [V] – PLUS macrolide (azithromycin 500 mg OD [V]); OR respiratory FQ (levofloxacin 750 mg OD [V], moxifloxacin 400 mg OD [V])',
     'High risk (ICU), no Pseudomonas risk: IV non-antipseudomonal β-lactam (incl. ertapenem 1 g OD [V]) + IV azithromycin or IV respiratory FQ. Pseudomonas risk: piperacillin-tazobactam 4.5 g IV q6h [V], cefepime 2 g IV q8h [V] or meropenem 1 g IV q8h [V] + azithromycin or levofloxacin ± aminoglycoside',
     'First antibiotic dose in the ED (within 4 h); O₂ to SpO₂ ≥ 94 % (88–92 % in COPD). Children: PAPP-PIDSP 2021 pediatric CAP guideline'],
 txs:'PCAP 2016 (PH CPG – regimens recalled, verify) · PAPP-PIDSP 2021 for children (PH CPG)',
 dispo:'PCAP low risk → outpatient; moderate → ward; high → ICU.', tk:['cap','pneumonia','Pneumonia (CAP) – CURB-65']},
{id:'asthma', n:'Acute asthma exacerbation', sec:8, topic:'Acute asthma', mnm:0, p:0.5,
 g:['wheeze','wheeze_pe','asthma','silent_chest'],
 w:{wheeze:2,wheeze_pe:2,asthma:3,dyspnea:1,accessory:1,silent_chest:2,cough:0.5,atopy:0.5,age_lt40:0.5,
    fever:-0.5,t_ge38:-0.5,copd:-1,crackles_bilat:-1,orthopnea:-1,cxr_edema:-2,dvt_signs:-1,age_ge65:-0.5},
 rf:['silent_chest','spo2_lt90','gcs_lt15','accessory','hr_ge125'],
 dx:['PEF or FEV₁ (% predicted/best) before and after treatment; SpO₂','ABG/VBG if severe – a normal or rising PaCO₂ is ominous','CXR only if pneumothorax/pneumonia suspected or no response'],
 dxs:'GINA 2025 (intl)',
 tx:['Salbutamol 2.5–5 mg nebulized q20 min × 3 (or 4–10 puffs MDI + spacer) [V]','Severe: add ipratropium 0.5 mg neb q20 min × 3 [V]',
     'Systemic steroid within 1 h: prednisone 40–50 mg PO [V] (or hydrocortisone 100–200 mg IV / methylprednisolone 40–125 mg IV) [V]',
     'Severe / not responding: MgSO₄ 2 g IV over 20 min [V]; O₂ to SpO₂ 93–95 %; avoid sedation; anticipate difficult ventilation'],
 txs:'GINA 2025 (intl)', dispo:'PEF > 60–80 % after 1 h → home on ICS-formoterol + prednisone 5–7 d; otherwise admit; ICU if silent chest/drowsy.',
 tk:['asthma','asthma','Asthma exacerbation']},
{id:'copd', n:'COPD exacerbation', sec:8, topic:'COPD', mnm:0, p:0,
 g:['copd','dyspnea','wheeze','sputum'],
 w:{copd:3.5,smoker:1,age_ge50:1,dyspnea:1,sputum:1,wheeze:1,wheeze_pe:1,cough:0.5,accessory:0.5,hyperres:0.5,age_lt40:-2,asthma:-0.5,cxr_edema:-1.5,dvt_signs:-0.5},
 rf:['gcs_lt15','spo2_lt90','accessory'],
 dx:['ABG (hypercapnia, pH)','CXR, ECG, CBC, electrolytes; sputum culture if purulent','Consider PE, HF, pneumothorax, pneumonia as triggers'],dxs:'GOLD 2025 (intl)',
 tx:['Salbutamol ± ipratropium nebulized [V]','Prednisone 40 mg PO daily × 5 d [V]','Antibiotic if increased sputum purulence: co-amoxiclav 625 mg TID [V], doxycycline 100 mg BID [V] or azithromycin 500 mg OD [V] × 5 d',
     'Controlled O₂ to SpO₂ 88–92 %; NIV if pH < 7.35 and PaCO₂ > 45 mmHg'],
 txs:'GOLD 2025 (intl)', dispo:'Admit if NIV, hypoxemia, no home support; otherwise home with follow-up.', tk:['copd','COPD','COPD exacerbation – GOLD 2025']},
{id:'ptx', n:'Pneumothorax (spontaneous / tension)', sec:8, topic:'Pneumothorax', mnm:1, p:-0.5,
 g:['cp_pleuritic','chest_pain','dyspnea','dec_bs_uni','cxr_ptx','hyperres'],
 a:{dec_bs_uni:-1},
 w:{onset_sudden:1.5,cp_pleuritic:1.5,dyspnea:1,dec_bs_uni:3,hyperres:3,cxr_ptx:5,trach_dev:2,copd:0.5,smoker:0.5,male:0.5,age_lt40:0.5,tb_hx:0.5,
    fever:-1,sputum:-1,crackles_bilat:-1,dvt_signs:-0.5},
 rf:['sbp_lt90','trach_dev','spo2_lt90'],
 dx:['POCUS: absent lung sliding / lung point; or upright CXR','Tension is a clinical diagnosis – do not wait for imaging'],dxs:'BTS 2023 pleural disease (intl)',
 tx:['Tension: immediate needle/finger decompression (4th–5th ICS anterior-axillary line, or 2nd ICS MCL) then chest tube',
     'Primary, small, minimally symptomatic: conservative / observation ± needle aspiration','Secondary (COPD, TB) or large/symptomatic: small-bore chest drain; admit'],
 txs:'BTS 2023 (intl)', dispo:'Tension/secondary → admit; small primary → possible outpatient with review.', tk:['ptx','pneumothorax','Pneumothorax']},
{id:'ptb', n:'Pulmonary tuberculosis', sec:8, topic:'Tuberculosis', mnm:0, p:1,
 g:['chronic_cough','hemoptysis','wt_loss','night_sweats','cxr_cavity','xpert_pos','tb_contact'],
 w:{chronic_cough:3,dur_ge14d:1.5,cough:0.5,hemoptysis:1.5,wt_loss:2,night_sweats:2,fever:1,tb_contact:2,tb_hx:1.5,immuno:1.5,dm:0.5,smoker:0.3,cachexia:1,cxr_cavity:4,xpert_pos:6,
    dur_lt24h:-2,onset_sudden:-1.5,cxr_edema:-1},
 rf:['hemoptysis','spo2_lt90'],
 dx:['Sputum Xpert MTB/RIF as the primary test for ALL presumptive TB (DOH DM 2020-0129)','CXR','HIV test (opt-out), glucose/HbA1c, CBC','Massive hemoptysis: CBC, coags, type & crossmatch, CT angiography'],
 dxs:'DOH NTP Manual of Procedures 6th ed. 2020 (PH program) · PH TB CPG (PhilCAT/PSMID) (PH CPG)',
 tx:['Airborne precautions / surgical mask on patient in the ED; notify TB-DOTS',
     'Drug-susceptible TB: 2HRZE/4HR fixed-dose combination by weight band, started by the TB-DOTS facility [V]',
     'Massive hemoptysis: airway, bleeding side down, tranexamic acid 1 g IV [V], urgent IR/surgery'],
 txs:'DOH NTP MOP 6th ed. 2020 (PH)', dispo:'Stable → refer to TB-DOTS; admit if hemoptysis, hypoxia or severe illness (isolation room).', tk:['tropical','tuberculosis','Malaria, typhoid, measles, influenza, TB & tropical fever']},
{id:'viral', n:'Influenza / viral respiratory infection (incl. COVID-19)', sec:13, topic:'Serious viral infections', mnm:0, p:1.5,
 g:['cough','fever','sore_throat','myalgia'],
 w:{fever:1,cough:1.5,sore_throat:1,myalgia:1,headache:0.5,malaise:0.5,dur_le7d:0.5,crackles_focal:-1,cxr_consol:-2,sputum:-0.3,dur_ge14d:-2,petechiae:-1.5,plt_low:-1,rash:-0.5,calf_pain:-1,conj_suff:-1},
 rf:['spo2_lt94','rr_ge30'],
 dx:['Clinical; influenza / COVID-19 rapid antigen or PCR if it changes management','CXR if hypoxic or focal signs','In dengue season: CBC / NS1 if fever with low WBC/platelets'],dxs:'WHO 2024 influenza clinical guideline (intl)',
 tx:['Supportive; paracetamol 500–1000 mg PO q6h (max 4 g/day) [V]; avoid NSAIDs until dengue excluded','Oseltamivir 75 mg PO BID × 5 d for severe or high-risk influenza [V]','Isolation / mask'],
 txs:'WHO 2024 influenza (intl)', dispo:'Home unless hypoxic / high risk.', tk:['tropical','influenza','Malaria, typhoid, measles, influenza, TB']}
);
// ───────────────────────── S9 GASTROINTESTINAL ─────────────────────────
KB.push(
{id:'appy', n:'Acute appendicitis', sec:9, topic:'Acute abdominal pain · appendicitis', mnm:1, p:1,
 g:['abd_pain','rlq_pain','rlq_tender','migration'],
 a:{rlq_tender:-2},
 w:{abd_pain:0.5,migration:3,rlq_pain:2,rlq_tender:3,rebound:2,rovsing:2,anorexia:1,nausea:0.5,vomiting:0.5,fever:0.5,t_ge38:0.5,wbc_high:1.5,neut_high:1,age_lt40:0.5,
    diarrhea:-1,vag_discharge:-1,cmt:-1.5,flank_pain:-1,ua_pos:-0.5,hcg_pos:-1,dur_gt7d:-2,cva_tender:-1,adnexal:-1},
 rf:['rigid','sbp_lt90','toxic'],
 dx:['Alvarado / AIR score (see Scores)','CBC, CRP, urinalysis; pregnancy test in all women of reproductive age','Graded-compression ultrasound first (young, pregnant, thin); CT abdomen if equivocal in adults'],
 dxs:'WSES Jerusalem 2020 (intl) – no PH CPG found',
 tx:['NPO, IV fluids, early analgesia (does not mask diagnosis): morphine 0.1 mg/kg IV [V] or ketorolac 30 mg IV [V]',
     'Once diagnosed: ceftriaxone 1–2 g IV + metronidazole 500 mg IV q8h [V] (or cefoxitin / ampicillin-sulbactam) [V]','Surgical consult for appendectomy'],
 txs:'WSES 2020 (intl)', dispo:'Admit surgery.', tk:['abdpain','appendicitis','Acute abdominal pain – Alvarado']},
{id:'chole', n:'Acute cholecystitis / biliary colic', sec:9, topic:'Pancreatitis & biliary disease', mnm:0, p:1,
 g:['ruq_pain','murphy','epi_pain','us_gb'],
 a:{murphy:-1.5},
 w:{ruq_pain:2.5,murphy:3.5,epi_pain:0.5,fatty_meal:2,gallstones:2,nausea:0.5,vomiting:0.5,fever:1,t_ge38:0.5,wbc_high:1,us_gb:4,female:0.5,obesity:0.5,
    diarrhea:-1,rlq_tender:-1,calf_pain:-1,conj_suff:-1},
 rf:['jaundice','sbp_lt90','gcs_lt15'],
 dx:['RUQ ultrasound: stones, wall > 4 mm, pericholecystic fluid, sonographic Murphy','CBC, CRP, LFTs, bilirubin, lipase','ECG in older/diabetic patients (inferior MI mimic)'],
 dxs:'Tokyo Guidelines 2018 (intl)',
 tx:['NPO, IV fluids, analgesia: ketorolac 30 mg IV [V] or opioid','Cholecystitis: ceftriaxone 2 g IV OD + metronidazole 500 mg IV q8h [V] or ampicillin-sulbactam 3 g IV q6h [V]','Early surgical referral (laparoscopic cholecystectomy)'],
 txs:'TG18 (intl)', dispo:'Colic resolved → outpatient surgery; cholecystitis → admit.', tk:['pancbil','cholecystitis','Pancreatitis, biliary colic, cholecystitis & cholangitis']},
{id:'cholangitis', n:'Acute cholangitis', sec:9, topic:'Pancreatitis & biliary disease', mnm:1, p:-0.5,
 g:['jaundice','icterus','bili_high'],
 w:{jaundice:2.5,icterus:2,fever:1.5,t_ge38:1,chills:1,ruq_pain:1.5,murphy:1,gallstones:1.5,confusion:1,sbp_lt90:1,bili_high:2,us_gb:1,wbc_high:0.5,
    calf_pain:-1.5,conj_suff:-2,flood:-2,oliguria:-0.5},
 rf:['sbp_lt90','confusion'],
 dx:['TG18 criteria: inflammation + cholestasis (bilirubin, ALP/GGT) + imaging (CBD dilation)','LFTs, CBC, blood cultures, lactate, lipase','Ultrasound ± MRCP/CT'],dxs:'Tokyo Guidelines 2018 (intl)',
 tx:['Sepsis bundle','Piperacillin-tazobactam 4.5 g IV q6h [V] or ceftriaxone 2 g IV OD + metronidazole 500 mg IV q8h [V]','Urgent biliary decompression (ERCP / PTBD) – timing by severity grade'],
 txs:'TG18 (intl)', dispo:'Admit; ICU if grade III.', tk:['pancbil','cholangitis','Pancreatitis, biliary colic, cholecystitis & cholangitis']},
{id:'pancreatitis', n:'Acute pancreatitis', sec:9, topic:'Pancreatitis & biliary disease', mnm:0, p:0,
 g:['epi_pain','abd_back','lipase_high','abd_pain'],
 w:{epi_pain:2,abd_back:2.5,epi_tender:1.5,vomiting:1,nausea:0.5,alcohol:2,gallstones:1.5,lipase_high:5,distension:0.5,ruq_pain:0.3,murphy:-0.5,diarrhea:-1,dur_gt7d:-1,rlq_tender:-1},
 rf:['sbp_lt90','spo2_lt94','cr_high','gcs_lt15'],
 dx:['Lipase (or amylase) > 3 × ULN – Revised Atlanta: 2 of pain / enzyme / imaging','RUQ ultrasound for gallstones','CBC, BUN, creatinine, calcium, triglycerides, LFTs, glucose; BISAP','CT only if diagnosis uncertain or deterioration after 48–72 h'],
 dxs:'ACG 2024 acute pancreatitis (intl)',
 tx:['Moderate goal-directed fluids: lactated Ringer’s 1.5 mL/kg/h (10 mL/kg bolus only if hypovolemic) [V]; reassess often – avoid overload','Analgesia (opioids acceptable) [V]; early oral feeding as tolerated',
     'No prophylactic antibiotics; ERCP within 24 h only if cholangitis'],
 txs:'ACG 2024 · WATERFALL trial (intl)', dispo:'Admit; ICU if organ failure.', tk:['pancbil','pancreatitis','Pancreatitis, biliary colic, cholecystitis & cholangitis']},
{id:'ugib', n:'Upper GI bleeding (PUD / variceal)', sec:9, topic:'Upper GI bleeding', mnm:1, p:0,
 g:['hematemesis','melena','blood_dre'],
 w:{hematemesis:4,melena:3.5,blood_dre:2,epi_pain:0.5,pud:1,m_nsaid:1,m_anticoag:0.5,m_antiplt:0.5,cirrhosis:1.5,alcohol:1,hr_gt100:0.5,sbp_lt90:0.5,syncope:0.5,pallor:0.5,hematochezia:-0.5},
 rf:['sbp_lt90','si_ge1','syncope','gcs_lt15'],
 dx:['Glasgow-Blatchford score; CBC, BUN, creatinine, PT/INR, type & crossmatch','Endoscopy within 24 h (≤ 12 h if variceal suspected or unstable after resuscitation)'],
 dxs:'ACG 2021 UGIB · Baveno VII (intl)',
 tx:['Two large-bore IVs; restrictive transfusion (Hb < 7 g/dL; < 8 if CAD)','PPI: omeprazole/pantoprazole 80 mg IV bolus then 40 mg IV q12h [V]',
     'Suspected variceal: octreotide 50 mcg IV bolus then 50 mcg/h [V] (or terlipressin 2 mg IV q4h [V]) + ceftriaxone 1 g IV daily [V]','Reverse anticoagulation; GBS 0–1 → outpatient management'],
 txs:'ACG 2021 · Baveno VII (intl)', dispo:'Admit (ICU if unstable / variceal); GBS 0–1 → discharge.', tk:['ugib','upper GI bleed','Upper GI bleeding – Glasgow-Blatchford']},
{id:'lgib', n:'Lower GI bleeding', sec:9, topic:'Lower GI bleeding', mnm:0, p:0,
 g:['hematochezia'],
 w:{hematochezia:4,blood_dre:1,age_ge65:1,m_anticoag:1,melena:-1,hematemesis:-2,dysentery:-1,fever:-0.5},
 rf:['sbp_lt90','si_ge1'],
 dx:['CBC, coags, type & crossmatch; DRE ± anoscopy','Oakland score','CTA if brisk active bleeding; colonoscopy after prep','Massive hematochezia: consider brisk UGIB → NGT aspirate / endoscopy'],
 dxs:'ACG 2023 LGIB (intl)', tx:['Resuscitate; reverse anticoagulants','Oakland ≤ 8 → outpatient colonoscopy'], txs:'ACG 2023 (intl)', dispo:'Admit if unstable / Oakland > 8.', tk:['ugib','GI bleeding','GI bleeding']},
{id:'sbo', n:'Bowel obstruction', sec:9, topic:'Bowel obstruction', mnm:1, p:0,
 g:['distension','obstipation','distended','vomiting'],
 a:{distension:-1},
 w:{distension:2.5,distended:2,obstipation:3,vomiting:1,abd_pain:0.5,diffuse_abd:0.5,constipation:1,diarrhea:-1.5,fever:-0.5},
 rf:['rebound','t_ge38','sbp_lt90','lactate_high'],
 dx:['Upright abdominal X-ray / POCUS (dilated loops > 2.5 cm, to-and-fro peristalsis); CT abdomen','Electrolytes, creatinine, lactate, CBC'],dxs:'WSES Bologna 2017 ASBO (intl)',
 tx:['NPO, NGT decompression, IV fluids, correct electrolytes','Analgesia/antiemetic [V]','Surgical consult; strangulation signs (fever, peritonism, rising lactate) → urgent OR'],
 txs:'WSES 2017 (intl)', dispo:'Admit surgery.', tk:['abdpain','bowel obstruction','Acute abdominal pain']},
{id:'perf', n:'Perforated viscus / generalized peritonitis', sec:9, topic:'Acute abdominal pain', mnm:1, p:-0.5,
 g:['rigid','rebound','abd_pain'],
 w:{rigid:4,rebound:2,onset_sudden:1.5,diffuse_abd:1.5,epi_pain:0.5,pud:1.5,m_nsaid:1.5,m_steroid:0.5,toxic:1,t_ge38:0.5,hr_gt100:0.5,sbp_lt90:0.5,distended:0.5,migration:-1,rlq_tender:-0.5},
 rf:['sbp_lt90','rigid'],
 dx:['Upright CXR (free air) or CT abdomen','CBC, lactate, lipase, creatinine, blood cultures'],dxs:'WSES 2017 intra-abdominal infection (intl)',
 tx:['Sepsis bundle; piperacillin-tazobactam 4.5 g IV q6h [V] or ceftriaxone 2 g + metronidazole 500 mg IV q8h [V]','NPO, NGT; emergency surgery'],
 txs:'WSES 2017 (intl)', dispo:'OR / ICU.', tk:['abdpain','perforation','Acute abdominal pain']},
{id:'age', n:'Acute gastroenteritis / dehydration (incl. cholera)', sec:9, topic:'Nausea, vomiting & diarrhea', mnm:0, p:1.5,
 g:['diarrhea','vomiting'],
 w:{diarrhea:3,vomiting:1,nausea:0.5,abd_pain:0.3,diffuse_abd:0.5,fever:0.3,unsafe_food:1.5,dehydration:1,dur_le7d:0.5,dur_lt24h:0.3,
    rlq_tender:-1.5,rebound:-2,rigid:-3,migration:-2,murphy:-1,hematemesis:-2,melena:-1.5,petechiae:-1,plt_low:-1},
 rf:['sbp_lt90','gcs_lt15','oliguria','dysentery'],
 dx:['Clinical; grade dehydration','Electrolytes, creatinine if severe/elderly','Stool exam/culture if bloody, prolonged > 7 d, outbreak; cholera RDT if rice-water stools'],
 dxs:'WHO diarrhoea / DOH (intl / PH program)',
 tx:['Some dehydration: low-osmolarity ORS ~75 mL/kg over 4 h (WHO Plan B) [V]','Severe: IV lactated Ringer’s / PNSS 100 mL/kg (adults 30 mL/kg in 30 min, then 70 mL/kg over 2.5 h) [V]',
     'Children: zinc 10–20 mg/day × 10–14 d [V]','Antibiotics only for dysentery or cholera (e.g. azithromycin 1 g PO single dose for cholera [V]); antiemetic (ondansetron 4–8 mg) [V]'],
 txs:'WHO / DOH (intl / PH)', dispo:'Home if tolerating ORS; admit if severe dehydration / unable to drink.', tk:['nvd','gastroenteritis','Nausea, vomiting, diarrhea & dehydration']},
{id:'mesenteric', n:'Acute mesenteric ischemia', sec:9, topic:'Mesenteric ischemia', mnm:1, p:-1,
 g:['abd_pain','pain_oop'],
 w:{pain_oop:4,af:2.5,irregular:1,age_ge65:1.5,cad:0.5,hf:0.5,onset_sudden:1,lactate_high:1.5,acidosis:1,hematochezia:1,vomiting:0.3,diarrhea:0.3,age_lt40:-2},
 rf:['sbp_lt90','lactate_high'],
 dx:['CT angiography early – a normal lactate does NOT exclude','Lactate, CBC, ABG, creatinine, ECG'],dxs:'ESVS 2017 · WSES 2022 (intl)',
 tx:['Resuscitate; broad-spectrum antibiotics [V]','UFH 80 U/kg IV bolus then infusion unless contraindicated [V]','Emergency vascular / surgical consult'],
 txs:'ESVS / WSES (intl)', dispo:'OR / ICU.', tk:['abdpain','mesenteric ischemia','Acute abdominal pain']},
{id:'pud', n:'Peptic ulcer disease / gastritis / dyspepsia', sec:9, topic:'Peptic ulcer disease', mnm:0, p:1,
 g:['epi_pain','epi_tender'],
 w:{epi_pain:2.5,epi_tender:1.5,pud:1.5,m_nsaid:1.5,alcohol:0.5,nausea:0.5,dur_gt7d:0.5,fever:-1,t_ge38:-1,rigid:-2,abd_back:-1,ruq_pain:-0.5,rlq_pain:-1.5,cp_radiate:-1,diaphoresis:-1},
 rf:['hematemesis','melena','rigid'],
 dx:['ECG ± troponin in older or risk-factor patients (epigastric pain = MI mimic)','Lipase, CBC','Outpatient H. pylori test (urea breath / stool antigen)'],dxs:'ACG 2024 H. pylori (intl)',
 tx:['PPI: omeprazole 40 mg PO daily [V]; stop NSAIDs; antacid for symptom relief [V]','H. pylori eradication if positive'],
 txs:'ACG (intl)', dispo:'Home with follow-up.', tk:['abdpain','peptic ulcer','Acute abdominal pain']},
{id:'hepatitis', n:'Acute viral hepatitis', sec:9, topic:'Liver disorders', mnm:0, p:0,
 g:['jaundice','icterus','bili_high'],
 w:{jaundice:2.5,icterus:1.5,anorexia:1,nausea:0.5,ruq_pain:1,hepatomegaly:1,malaise:0.5,bili_high:1,fever:0.3,calf_pain:-1.5,conj_suff:-1.5,flood:-1,oliguria:-0.5,chills:-0.5},
 rf:['confusion','bleeding'],
 dx:['ALT/AST (often > 10 × ULN), bilirubin, INR, albumin, glucose','HAV IgM, HBsAg / anti-HBc IgM, anti-HCV; ultrasound','Leptospirosis / dengue serology if exposure'],dxs:'EASL 2017 acute liver failure (intl)',
 tx:['Supportive; avoid hepatotoxins (paracetamol ≤ 2 g/day) [V]','Acute liver failure (INR ≥ 1.5 + encephalopathy) → ICU, NAC, transplant-centre referral'],
 txs:'EASL (intl)', dispo:'Home if INR normal and tolerating oral; admit otherwise.', tk:['liver','hepatitis','Liver disease']}
);
// ───────────────────────── S10 RENAL & GU ─────────────────────────
KB.push(
{id:'cystitis', n:'Acute uncomplicated cystitis', sec:10, topic:'UTI & hematuria', mnm:0, p:1,
 g:['dysuria','frequency','ua_pos'],
 w:{dysuria:2.5,frequency:2,hematuria:0.5,llq_tender:0.5,ua_pos:2,female:1,vag_discharge:-2,fever:-1,t_ge38:-1,flank_pain:-1,cva_tender:-1.5,chills:-1},
 rf:['t_ge38','pregnant'],
 dx:['Urinalysis (pyuria, nitrite); urine culture if pregnant, recurrent, male or treatment failure','Pregnancy test'],
 dxs:'PSMID UTI in Adults 2013 Update Part 1 (PH CPG)',
 tx:['Nitrofurantoin 100 mg PO BID × 5–7 d [V] or fosfomycin 3 g PO single dose [V]','Pregnancy: treat (incl. asymptomatic bacteriuria) per culture, e.g. cefalexin / co-amoxiclav × 7 d [V]'],
 txs:'PSMID UTI 2013 Part 1 (PH CPG – recalled, verify)', dispo:'Home.', tk:[null,'urinary tract infection','S10 Renal & GU – UTI (not yet a toolkit card)']},
{id:'pyelo', n:'Acute pyelonephritis / complicated UTI', sec:10, topic:'UTI & hematuria', mnm:0, p:0.5,
 g:['dysuria','flank_pain','cva_tender','ua_pos'],
 w:{cva_tender:3,flank_pain:2,fever:1.5,t_ge38:1,chills:1,dysuria:1.5,frequency:1,nausea:0.3,vomiting:0.5,ua_pos:2.5,female:0.5,dm:0.5,migration:-2,rlq_tender:-1,cough:-0.5,calf_pain:-1},
 rf:['sbp_lt90','pregnant','cr_high'],
 dx:['UA + urine Gram stain/culture BEFORE antibiotics','CBC, creatinine; blood cultures if septic','KUB ultrasound / CT if obstruction, stone, no improvement in 48–72 h (infected obstructed kidney = urologic emergency)','Pregnancy test'],
 dxs:'PSMID UTI 2013 Part 1 / 2015 Part 2 (complicated) (PH CPG)',
 tx:['Outpatient (mild, tolerating oral): ciprofloxacin 500 mg BID × 7 d [V] or levofloxacin 750 mg OD × 5 d [V] – if local FQ resistance acceptable; alternatives oral cefuroxime / co-amoxiclav × 10–14 d [V]',
     'Inpatient: ceftriaxone 1–2 g IV OD [V], or IV FQ / aminoglycoside (amikacin 15 mg/kg OD) [V]; ESBL risk → ertapenem 1 g IV OD [V]'],
 txs:'PSMID UTI 2013/2015 (PH CPG – recalled, verify)', dispo:'Admit if septic, vomiting, pregnant, obstructed, or failed oral therapy.', tk:[null,'pyelonephritis','S10 Renal & GU – UTI (not yet a toolkit card)']},
{id:'stone', n:'Ureterolithiasis (renal colic)', sec:10, topic:'Urologic stone disease', mnm:0, p:1,
 g:['flank_pain','hematuria'],
 w:{flank_pain:3,onset_sudden:1,hematuria:2,nausea:0.5,vomiting:0.5,stones:2,male:0.5,cva_tender:0.5,fever:-1.5,t_ge38:-1,rebound:-1.5,age_ge65:-0.5,pulsatile:-3},
 rf:['t_ge38','cr_high'],
 dx:['UA (hematuria), creatinine','POCUS hydronephrosis; non-contrast CT KUB','> 50 y first episode → exclude AAA; pregnancy test'],dxs:'EAU 2025 urolithiasis (intl)',
 tx:['Ketorolac 30 mg IV [V] or diclofenac 75 mg IM [V]; paracetamol 1 g IV [V]','Tamsulosin 0.4 mg PO daily for distal stones 5–10 mm [V]','Urgent urology: infection + obstruction, AKI, solitary kidney, intractable pain'],
 txs:'EAU 2025 (intl)', dispo:'Home if pain controlled, afebrile, normal renal function.', tk:[null,'kidney stone','S10 Renal & GU – stones (not yet a toolkit card)']},
{id:'torsion', n:'Testicular torsion', sec:10, topic:'Male genital problems', mnm:1, p:-0.5,
 g:['testis_pain'],
 w:{testis_pain:3,onset_sudden:2,high_testis:4,vomiting:1,age_lt40:1,fever:-1,dysuria:-1},
 ex:S=>S.sex==='F'?'female patient':null, rf:['high_testis'],
 dx:['Clinical (TWIST score); Doppler US only if it does not delay surgery'],dxs:'EAU 2024 (intl)',
 tx:['Immediate urology – exploration within 6 h of onset','Manual detorsion ("open the book") as a bridge; analgesia [V]'],
 txs:'EAU (intl)', dispo:'OR.', tk:['pedabd','testicular torsion','Pediatric abdomen & GU']}
);
// ───────────────────────── S11 OB-GYN ─────────────────────────
KB.push(
{id:'ectopic', n:'Ectopic pregnancy', sec:11, topic:'Ectopic pregnancy / early pregnancy', mnm:1, p:0,
 g:['amenorrhea','hcg_pos','vag_bleed','llq_pain','adnexal','abd_pain'],
 w:{hcg_pos:3,amenorrhea:2,vag_bleed:2,llq_pain:2,abd_pain:0.5,adnexal:3,cmt:1,ectopic_rf:2,iud:1,syncope:1.5,dizziness:0.5,sbp_lt90:1,hr_gt100:0.5,us_fluid:2.5,si_ge1:0.5,rlq_pain:0.5,
    vag_discharge:-0.5,fever:-1,dysuria:-0.5},
 ex:S=>S.sex==='M'?'male patient':(S.age!=null&&(S.age<10||S.age>55))?'age outside reproductive range':S.f.hcg_neg===1?'negative pregnancy test':null,
 rf:['sbp_lt90','us_fluid','syncope','si_ge1'],
 dx:['Urine / serum β-hCG in every woman of reproductive age with abdominal pain, bleeding or syncope','Transvaginal US (no IUP, adnexal mass, free fluid) + FAST for hemoperitoneum',
     'CBC, blood type & Rh, crossmatch; serial β-hCG (48 h) if pregnancy of unknown location'],
 dxs:'POGS (PH CPG – year not verified) · ACOG PB 193 2018 / RCOG GTG 21 (intl)',
 tx:['Unstable / hemoperitoneum: 2 large-bore IVs, blood, massive transfusion, emergency OB-GYN for laparotomy/laparoscopy',
     'Stable & eligible (hCG < 5000, no cardiac activity, mass < 3.5–4 cm, reliable follow-up): methotrexate 50 mg/m² IM single dose [V]','Rh-negative: anti-D immunoglobulin [V]'],
 txs:'POGS (PH) · ACOG / RCOG (intl)', dispo:'OB-GYN; OR if unstable.', tk:['obearly','ectopic','Early pregnancy (ectopic)']},
{id:'preeclampsia', n:'Pre-eclampsia / eclampsia / HELLP', sec:11, topic:'Hypertension in pregnancy', mnm:1, p:0,
 g:['htn_sev','bp_ge140','seizure','headache','vision'],
 w:{pregnant:1,ga_ge20:2,postpartum:1.5,htn_sev:3,bp_ge140:2,headache:1.5,vision:1.5,epi_pain:1.5,ruq_pain:1,seizure:3,edema:0.5,hyperreflexia:1.5,plt_low:1,cr_high:0.5,confusion:1},
 ex:S=>S.sex==='M'?'male patient':(!(S.pregnant||S.f.postpartum===1)?'not pregnant / postpartum':(S.ga!=null&&S.ga<20&&S.f.postpartum!==1?'< 20 weeks gestation':null)),
 rf:['seizure','htn_sev','plt_low','confusion'],
 dx:['Repeat BP; urine protein (dipstick / protein:creatinine)','CBC (platelets), creatinine, AST/ALT, LDH (HELLP)','Fetal assessment (CTG / US); OB-GYN'],
 dxs:'POGS CPG on Hypertension in Pregnancy 2022 (PH CPG – details recalled) · ACOG 2020 (intl)',
 tx:['Severe BP ≥ 160/110: treat within 30–60 min – labetalol 20 mg IV then 40, 80 mg q10 min (max 220–300 mg) [V]; or hydralazine 5–10 mg IV q20 min [V]; or nifedipine IR 10 mg PO (not SL) q20 min [V]',
     'MgSO₄ for eclampsia / severe features: Pritchard 4 g IV over 15–20 min + 10 g IM (5 g each buttock), then 5 g IM q4h [V]; or Zuspan 4–6 g IV load then 1–2 g/h [V]',
     'Monitor reflexes, RR, urine output; Mg toxicity → calcium gluconate 1 g IV [V]','Definitive: delivery – urgent OB-GYN'],
 txs:'POGS 2022 (PH CPG – recalled, verify) · ACOG 2020 (intl)', dispo:'Admit OB.', tk:['obhtn','pre-eclampsia','Pre-eclampsia & eclampsia']},
{id:'ovtorsion', n:'Ovarian torsion', sec:11, topic:'Gynecologic pelvic pain', mnm:1, p:-0.5,
 g:['llq_pain','rlq_pain','adnexal'],
 w:{onset_sudden:2,llq_pain:1.5,rlq_pain:1,adnexal:3,vomiting:1.5,nausea:0.5,repro_f:0.5,fever:-0.5,vag_bleed:-0.5,migration:-1.5,vag_discharge:-1},
 ex:notMale, rf:['adnexal'],
 dx:['Pelvic US with Doppler (normal flow does NOT exclude)','β-hCG, CBC'],dxs:'ACOG CO 783 2019 (intl)',
 tx:['Urgent gynecology – laparoscopic detorsion','Analgesia, antiemetic [V]'],txs:'ACOG (intl)', dispo:'OR.', tk:['obother','ovarian torsion','Other obstetric/gynecologic emergencies']},
{id:'pid', n:'PID / tubo-ovarian abscess', sec:11, topic:'Pelvic inflammatory disease', mnm:0, p:0,
 g:['cmt','vag_discharge','adnexal','llq_pain'],
 w:{cmt:3,adnexal:2,vag_discharge:2,llq_pain:1.5,fever:1,t_ge38:0.5,dysuria:0.3,iud:0.5,repro_f:0.5,hcg_pos:-2,migration:-1.5,onset_sudden:-1},
 ex:notMale, rf:['t_ge38','rebound'],
 dx:['β-hCG (exclude ectopic)','NAAT / Gram stain for gonorrhea & chlamydia, wet mount; HIV, syphilis','TVS if TOA suspected'],dxs:'CDC STI 2021 (intl)',
 tx:['Outpatient: ceftriaxone 500 mg IM once + doxycycline 100 mg PO BID × 14 d + metronidazole 500 mg PO BID × 14 d [V]','Inpatient if TOA, pregnancy, severe illness or failed oral therapy; treat partners'],
 txs:'CDC STI 2021 (intl)', dispo:'Outpatient with 72-h review unless criteria for admission.', tk:['hivsti','PID','HIV, opportunistic infections, STIs']},
{id:'miscarriage', n:'Threatened / incomplete miscarriage', sec:11, topic:'Early pregnancy bleeding', mnm:0, p:0,
 g:['vag_bleed'],
 w:{vag_bleed:2.5,hcg_pos:2,amenorrhea:1.5,llq_pain:1,repro_f:0.5,adnexal:-1,us_fluid:-1},
 ex:S=>S.sex==='M'?'male patient':S.f.hcg_neg===1?'negative pregnancy test':null, rf:['sbp_lt90','t_ge38'],
 dx:['β-hCG, TVS (IUP? retained products?) – always exclude ectopic','CBC, blood type & Rh; speculum exam (os open/closed)'],dxs:'WHO 2022 abortion care · POGS (intl / PH)',
 tx:['Heavy bleeding / unstable: resuscitate; uterine evacuation (MVA) or misoprostol 400–800 mcg per protocol [V]','Rh-negative: anti-D [V]; septic abortion → broad-spectrum antibiotics'],
 txs:'WHO 2022 (intl)', dispo:'OB-GYN.', tk:['obearly','miscarriage','Early pregnancy']}
);
// ───────────────────────── S13 INFECTIOUS DISEASES ─────────────────────────
KB.push(
{id:'sepsis', n:'Sepsis / septic shock (source to identify)', sec:13, topic:'Sepsis & septic shock', mnm:1, p:-0.5,
 g:['fever','t_ge38','t_lt36','chills'],
 w:{t_ge38:1,fever:0.5,t_lt36:1.5,hr_gt100:1,rr_ge22:1,sbp_le100:1,sbp_lt90:1.5,gcs_lt15:1,confusion:0.5,toxic:1.5,cool_periph:1,lactate_high:1.5,lactate_4:1,wbc_vhigh:1,immuno:1,chills:0.5,oliguria:0.5},
 rf:['sbp_lt90','lactate_4','gcs_lt15','cool_periph'],
 dx:['Lactate; blood cultures × 2 before antibiotics (do not delay them)','CBC, creatinine, bilirubin, platelets, PT, ABG/VBG, glucose','Source work-up: CXR, UA, POCUS; dengue NS1 / lepto serology / malaria smear per exposure'],
 dxs:'Surviving Sepsis Campaign 2021 (intl)',
 tx:['Antibiotics within 1 h if shock / probable sepsis (≤ 3 h if possible sepsis without shock), empiric for source and local resistance [V]',
     'Hypotension or lactate ≥ 4: 30 mL/kg balanced crystalloid within 3 h, reassess after each bolus [V] – NOT in suspected dengue shock (use DOH/WHO dengue fluid protocol)',
     'Norepinephrine 0.05–0.1 mcg/kg/min titrated to MAP ≥ 65 (peripheral line acceptable short-term) [V]','Hydrocortisone 200 mg/day if ongoing vasopressor need [V]'],
 txs:'SSC 2021 (intl)', dispo:'ICU if shock / lactate ≥ 4.', tk:['sepfluid','sepsis','Sepsis – fluids & vasopressors']},
{id:'dengue', n:'Dengue', sec:13, topic:'Serious viral infections (dengue)', mnm:1, p:1.5,
 g:['fever','t_ge38','ns1_pos'],
 a:{fever:-3},
 w:{fever:2,t_ge38:0.5,myalgia:1,retro_orb:2,headache:0.5,arthralgia:0.5,rash:1,petechiae:2,bleeding:1.5,plt_low:2.5,wbc_low:2,hct_rise:2,ns1_pos:5,dengue_area:1.5,abd_pain:0.5,persist_vomit:0.5,
    hepatomegaly:1,ascites:1,lethargy:0.5,fever_d3_7:0.5,dur_le7d:1,
    dur_gt7d:-2,cough:-0.5,sputum:-1,cxr_consol:-1.5,dysuria:-1,wbc_vhigh:-2,ua_pos:-1,conj_suff:-1,jaundice:-1,flood:-0.5,calf_pain:-0.5},
 rf:['abd_pain','persist_vomit','bleeding','lethargy','hepatomegaly','ascites','hct_rise','sbp_lt90','narrow_pp','cool_periph'],
 dx:['NS1 antigen (days 1–5) ± dengue IgM/IgG (from day 4–5)','CBC with platelet and Hct baseline, then serial (frequency by group); tourniquet test',
     'Group B/C: AST/ALT, albumin, creatinine, electrolytes, glucose; CXR / US for effusion, ascites, GB-wall edema; type & crossmatch if bleeding',
     'Monitor vitals, urine output, warning signs especially at defervescence (critical phase days 3–7)'],
 dxs:'DOH-approved 2023 Dengue CPG (RITM/UP-NIH) · DOH 2011 Revised Dengue CCM / WHO 2009 (PH CPG)',
 tx:['Group A (no warning signs, tolerating oral, voiding): home – oral fluids/ORS; paracetamol 10–15 mg/kg/dose (adult 500–1000 mg) q6h, max 4 g/day [V]; NO NSAIDs/aspirin/IM injections; daily CBC & return precautions',
     'Group B (warning signs or coexisting condition): admit – isotonic crystalloid 5–7 mL/kg/h × 1–2 h, then 3–5 mL/kg/h × 2–4 h, then 2–3 mL/kg/h, titrated to Hct, vitals and urine output ≥ 0.5 mL/kg/h [V]; use ideal body weight if obese',
     'Group C compensated shock: crystalloid 5–10 mL/kg/h × 1 h then reassess [V]; hypotensive shock: 20 mL/kg bolus over 15–30 min, repeat or colloid if no improvement [V]',
     'Severe bleeding: fresh whole blood 10 mL/kg or PRBC 5 mL/kg [V]; prophylactic platelet transfusion NOT recommended'],
 txs:'DOH 2011 / WHO 2009 dengue fluids (PH CPG) · 2023 DOH-approved Dengue CPG',
 dispo:'Group A → home with daily follow-up; Group B → admit; Group C → resuscitation / HDU-ICU.', tk:['dengue','dengue','Dengue – phases, warning signs & fluid calculator']},
{id:'lepto', n:'Leptospirosis', sec:13, topic:'Zoonoses (leptospirosis)', mnm:1, p:0,
 g:['fever','t_ge38','flood'],
 a:{flood:-1},
 w:{flood:4,fever:1.5,t_ge38:0.5,calf_pain:3,myalgia:1,conj_suff:3.5,jaundice:2,icterus:1,oliguria:2,cr_high:2,hemoptysis:1.5,dyspnea:0.3,headache:0.5,chills:0.5,bili_high:1,plt_low:0.5,wbc_high:0.5,male:0.5,dur_le7d:0.3,
    rash:-0.5,wbc_low:-0.5,retro_orb:-0.5},
 rf:['oliguria','jaundice','hemoptysis','sbp_lt90','spo2_lt94','cr_high'],
 dx:['Exposure history (flood, mud, rats, farming) 2–30 days before','CBC, creatinine/BUN, K⁺, bilirubin, AST/ALT, CK, UA; CXR (pulmonary hemorrhage)',
     'Confirm: lepto IgM RDT/ELISA (after ~day 5), MAT (paired sera), PCR / blood culture in week 1','Test for dengue (± malaria) concurrently'],
 dxs:'PH CPG on Leptospirosis 2010 (PSMID/DOH) (PH CPG)',
 tx:['Mild (outpatient): doxycycline 100 mg PO BID × 7 d [V]; alternatives amoxicillin 500 mg TID [V] or azithromycin 1 g then 500 mg daily × 2 d [V]',
     'Moderate–severe: penicillin G 1.5 million units IV q6h [V] or ceftriaxone 1 g IV OD [V] (or cefotaxime) × 7 d',
     'Watch urine output; early dialysis for oliguric AKI, hyperkalemia, uremia, fluid overload; pulmonary hemorrhage → ICU, lung-protective ventilation',
     'Exposed household/co-waders – prophylaxis: doxycycline 200 mg once (low risk) / 200 mg daily × 3–5 d (moderate) / 200 mg weekly during continuous exposure (high) [V]'],
 txs:'PH Leptospirosis CPG 2010 (PH CPG)', dispo:'Mild → home on doxycycline with review; moderate–severe (jaundice, oliguria, bleeding, dyspnea) → admit, dialysis-capable facility.', tk:['lepto','leptospirosis','Leptospirosis (post-flood fever)']},
{id:'typhoid', n:'Typhoid (enteric) fever', sec:13, topic:'Food- & waterborne illness', mnm:0, p:0.5,
 g:['fever','t_ge38'],
 w:{fever:1.5,dur_gt7d:2,abd_pain:1,constipation:1,diarrhea:0.5,headache:1,malaise:0.5,anorexia:0.5,rel_brady:2,hepatomegaly:0.5,splenomegaly:1.5,unsafe_food:1.5,wbc_low:0.5,toxic:0.5,
    dur_lt24h:-2,retro_orb:-0.5,petechiae:-1,bleeding:-1,calf_pain:-1,conj_suff:-1.5,flood:-0.5,sputum:-0.5,ns1_pos:-3},
 rf:['rigid','melena','hematochezia','confusion','sbp_lt90'],
 dx:['Blood culture (best yield in week 1; bone-marrow culture if antibiotics already given)','Typhoid RDTs and Widal: limited accuracy – do not rely on them alone','CBC, LFTs; exclude dengue, lepto, malaria'],
 dxs:'PSMID Typhoid Fever in Adults CPG 2017 (PH CPG)',
 tx:['Uncomplicated: azithromycin 500 mg–1 g PO daily × 5–7 d [V] or cefixime 200 mg PO BID × 7–10 d [V]; first-line agents (amoxicillin, chloramphenicol, co-trimoxazole) if isolate susceptible',
     'Severe / complicated: ceftriaxone 2 g IV daily × 10–14 d [V]','Typhoid encephalopathy / shock: dexamethasone 3 mg/kg IV then 1 mg/kg q6h × 8 doses [V]; perforation → surgery'],
 txs:'PSMID Typhoid 2017 · DOH National Antibiotic Guidelines 2017 (PH)', dispo:'Uncomplicated → home; complicated → admit.', tk:['nvd','typhoid','Nausea, vomiting, diarrhea (typhoid, cholera)']},
{id:'malaria', n:'Malaria', sec:13, topic:'Malaria', mnm:1, p:-0.5,
 g:['travel_mal','splenomegaly'],
 a:{travel_mal:-3},
 w:{travel_mal:4,fever:1.5,chills:1.5,headache:0.5,myalgia:0.3,splenomegaly:1.5,jaundice:1,plt_low:1,confusion:0.5,pallor:0.5,dur_le7d:0.3},
 rf:['confusion','jaundice','sbp_lt90','spo2_lt94','glu_low'],
 dx:['Malaria RDT + thick/thin smear (repeat q12–24 h × 3 if negative)','CBC, glucose, creatinine, bilirubin, lactate'],dxs:'WHO 2024 malaria · DOH Malaria Control Program (intl / PH program)',
 tx:['Uncomplicated P. falciparum: artemether-lumefantrine 20/120 mg weight-band 6-dose regimen (≥ 35 kg: 4 tablets BID × 3 d) with fatty food [V] + single low-dose primaquine 0.25 mg/kg [V]',
     'P. vivax: AL + primaquine 0.25–0.5 mg/kg daily × 14 d after G6PD testing [V]','Severe: IV artesunate 2.4 mg/kg at 0, 12, 24 h then daily [V]; check glucose'],
 txs:'WHO 2024 · DOH MCP (intl / PH)', dispo:'Severe → admit/ICU.', tk:['tropical','malaria','Malaria, typhoid, measles, influenza, TB']},
{id:'meningitis', n:'Bacterial meningitis / encephalitis', sec:14, topic:'CNS infections', mnm:1, p:-0.5,
 g:['headache','fever','neck_stiff','neck_stiff_sx','confusion','kernig'],
 a:{neck_stiff:-2,kernig:-1},
 w:{fever:1.5,t_ge38:0.5,headache:1.5,neck_stiff:3.5,neck_stiff_sx:2,kernig:2.5,photophobia:1.5,confusion:2,gcs_lt15:1,seizure:1.5,petechiae:1.5,vomiting:0.5,immuno:0.5,toxic:1,
    thunderclap:-1.5,dur_gt7d:-1},
 rf:['petechiae','gcs_le8','seizure','sbp_lt90'],
 dx:['Blood cultures, then antibiotics – never delay for CT/LP','CT before LP only if focal deficit, papilledema, new seizure, immunocompromise or GCS < 10','LP: opening pressure, cells, glucose, protein, Gram stain, culture (+ CSF Xpert MTB/RIF, cryptococcal Ag if HIV)','Glucose, CBC, lactate, creatinine'],
 dxs:'ESCMID 2016 / IDSA (intl) – no PH adult CPG found',
 tx:['Dexamethasone 10 mg (0.15 mg/kg) IV q6h × 4 d, with or before first antibiotic dose [V]','Ceftriaxone 2 g IV q12h [V] + vancomycin 15–20 mg/kg IV q8–12h [V]',
     'Add ampicillin 2 g IV q4h if > 50 y, immunocompromised or pregnant (Listeria) [V]; acyclovir 10 mg/kg IV q8h if encephalitis possible [V]','Droplet precautions; meningococcal contacts: ciprofloxacin 500 mg PO single dose [V]'],
 txs:'ESCMID 2016 / IDSA (intl)', dispo:'Admit (ICU if GCS low / shock).', tk:['cnsinf','meningitis','Meningitis, encephalitis & brain abscess']},
{id:'nsti', n:'Necrotizing soft-tissue infection', sec:13, topic:'Soft-tissue infections', mnm:1, p:-1,
 g:['cellulitis','crepitus','pain_oop'],
 w:{crepitus:4,pain_oop:3,cellulitis:1.5,toxic:1.5,t_ge38:0.5,sbp_lt90:1,hr_gt100:0.5,dm:1,dirty_wound:0.5,alcohol:0.5,cirrhosis:1,immuno:0.5},
 rf:['sbp_lt90','crepitus'],
 dx:['Clinical diagnosis – surgical exploration is diagnostic; LRINEC has limited sensitivity','CBC, Na, glucose, creatinine, CRP, CK, lactate, blood cultures; POCUS/CT for gas (do not delay surgery)'],
 dxs:'IDSA SSTI 2014 · WSES 2022 (intl)',
 tx:['Emergency surgical debridement','Piperacillin-tazobactam 4.5 g IV q6h + clindamycin 600–900 mg IV q8h + vancomycin 15–20 mg/kg IV [V]; seawater + cirrhosis → add doxycycline (Vibrio) [V]','Sepsis resuscitation'],
 txs:'IDSA 2014 (intl)', dispo:'OR / ICU.', tk:['skininf','necrotizing fasciitis','Skin infections (necrotizing fasciitis)']},
{id:'cellulitis', n:'Cellulitis / skin abscess', sec:13, topic:'Soft-tissue infections', mnm:0, p:1,
 g:['cellulitis'],
 w:{cellulitis:3,fever:0.5,t_ge38:0.3,dirty_wound:0.5,dm:0.5,crepitus:-2,pain_oop:-1.5,dvt_signs:-0.5},
 rf:['crepitus','pain_oop','sbp_lt90'],
 dx:['Clinical; POCUS for abscess; mark margins','CBC / cultures if systemic features'],dxs:'IDSA SSTI 2014 (intl)',
 tx:['Non-purulent: cefalexin 500 mg QID or cloxacillin 500 mg QID × 5–7 d [V]','Purulent: incision & drainage ± co-trimoxazole or clindamycin for MRSA risk [V]','Systemic: cefazolin 1–2 g IV q8h [V]; elevate limb'],
 txs:'IDSA 2014 (intl)', dispo:'Home unless systemic / failed oral.', tk:['skininf','cellulitis','Skin infections']},
{id:'rabies', n:'Rabies exposure – post-exposure prophylaxis', sec:13, topic:'Rabies', mnm:1, p:0,
 g:['animal_bite'],
 w:{animal_bite:6},
 rf:[],
 dx:['Classify exposure (DOH): Cat I touch/lick on intact skin; Cat II nibbling / minor scratch without bleeding; Cat III transdermal bite/scratch with bleeding, lick on broken skin or mucosa (Cat II on head/neck managed as Cat III)','Animal status (observe dog/cat 14 days), prior vaccination, wound assessment'],
 dxs:'DOH AO 2018-0013 Revised Guidelines on Management of Rabies Exposures; superseded by DOH AO 2026-0010 (PH CPG – verify current)',
 tx:['Wash wound immediately with soap and running water × 10–15 min; antiseptic','Cat II: vaccine. Cat III: vaccine + rabies immunoglobulin (HRIG 20 IU/kg or ERIG 40 IU/kg infiltrated into/around wounds) [V]',
     'Intradermal regimen: 0.1 mL per site at 2 sites (deltoids) on days 0, 3, 7 and 28 – day 28 may be omitted if the biting dog/cat is healthy after 14 days (not in immunocompromised) [V]',
     'Tetanus prophylaxis; co-amoxiclav 625 mg PO TID × 3–5 d for high-risk bites [V]; refer to an Animal Bite Treatment Center (ABTC)'],
 txs:'DOH AO 2018-0013 / AO 2026-0010 (PH CPG – verify)', dispo:'Home after first dose; ABTC follow-up schedule.', tk:['rabies','rabies','Rabies post-exposure prophylaxis']},
{id:'tetanus', n:'Tetanus', sec:13, topic:'Tetanus', mnm:1, p:-1,
 g:['trismus','dirty_wound'],
 w:{trismus:5,dirty_wound:2,animal_bite:0.5,fever:0.3},
 rf:['trismus','spo2_lt94'],
 dx:['Clinical diagnosis (no confirmatory test)','Electrolytes, CK; airway assessment'],dxs:'WHO 2017 tetanus (intl)',
 tx:['Wound debridement; human tetanus immunoglobulin 3000–6000 IU IM (dose varies by source) [V]','Metronidazole 500 mg IV q6–8h × 7–10 d [V]','Spasms: diazepam / midazolam titrated [V]; MgSO₄ [V]; quiet dark room; early airway; Td/Tdap vaccination'],
 txs:'WHO (intl)', dispo:'ICU.', tk:['tetanus','tetanus','Tetanus prophylaxis table']}
);
// ───────────────────────── S19 EENT · S14 NEUROLOGY ─────────────────────────
KB.push(
{id:'strep', n:'Streptococcal pharyngitis', sec:19, topic:'Mouth & throat', mnm:0, p:1,
 g:['sore_throat'],
 w:{sore_throat:2,exudate:2,cerv_nodes:1.5,t_ge38:1,fever:0.5,cough:-1.5,age_lt16:0.5,stridor:-2},
 rf:['stridor','throat_tight','trismus'],
 dx:['Centor / McIsaac (see Scores); rapid antigen test or culture if score ≥ 2–3'],dxs:'IDSA 2012 GAS pharyngitis (intl)',
 tx:['Amoxicillin 500 mg PO BID (or 1 g OD) × 10 d [V] or penicillin V 500 mg BID–TID × 10 d [V]; benzathine penicillin G 1.2 million units IM once [V]','Analgesia (paracetamol / ibuprofen) [V]'],
 txs:'IDSA 2012 (intl)', dispo:'Home.', tk:['oral','pharyngitis','Oral & dental emergencies']},
{id:'deepneck', n:'Deep neck infection / epiglottitis (PTA, Ludwig angina)', sec:19, topic:'Neck & upper airway', mnm:1, p:-1,
 g:['sore_throat','stridor','throat_tight'],
 w:{stridor:3,sore_throat:1,exudate:0.5,fever:1,t_ge38:0.5,trismus:1.5,toxic:1,throat_tight:1.5,dm:0.5,cough:-1,urticaria:-2,angioedema:-1,allergen:-2},
 rf:['stridor','spo2_lt94'],
 dx:['Airway first – keep upright, avoid throat instrumentation in suspected epiglottitis','CT neck with contrast if airway secure / stable; lateral neck X-ray'],dxs:'Expert consensus / AAO-HNS (intl)',
 tx:['Prepare difficult airway (awake fiberoptic, double set-up for surgical airway)','Ampicillin-sulbactam 3 g IV q6h or clindamycin 600 mg IV q8h [V]; dexamethasone 10 mg IV [V]','ENT for drainage'],
 txs:'Expert consensus (intl)', dispo:'Admit (ICU if airway threat).', tk:['neckair','epiglottitis','Neck & upper airway']},
{id:'stroke', n:'Acute stroke (ischemic or hemorrhagic)', sec:14, topic:'Stroke syndromes · intracerebral hemorrhage', mnm:1, p:0,
 g:['focal_weak','facial_droop','speech','hemiparesis','aphasia','facial_pe','ataxia','vision'],
 w:{focal_weak:2.5,hemiparesis:3,facial_droop:2,facial_pe:1.5,speech:2,aphasia:2,vision:1,ataxia:1,onset_sudden:2,age_ge65:1,age_ge50:0.5,htn:1,af:1.5,irregular:0.5,dm:0.5,smoker:0.3,stroke_hx:1,htn_sev:1,headache:0.3,
    glu_low:-3,seizure:-0.5,fever:-0.5,dur_gt7d:-1.5},
 rf:['gcs_le8','htn_sev','m_anticoag'],
 dx:['Capillary glucose immediately (hypoglycemia mimic)','Non-contrast CT head (door-to-CT ≤ 25 min) ± CTA for large-vessel occlusion; NIHSS; time last known well',
     'CBC, PT/INR, aPTT, creatinine, ECG, troponin'],
 dxs:'SSP 2024 CPG on Acute Ischemic Stroke & ICH (PH CPG)',
 tx:['Ischemic, ≤ 4.5 h, eligible: alteplase 0.9 mg/kg IV (max 90 mg) – 10 % bolus, rest over 60 min [V] or tenecteplase 0.25 mg/kg single bolus (max 25 mg) [V]',
     'BP < 185/110 before and < 180/105 for 24 h after lysis [V]; large-vessel occlusion → thrombectomy (≤ 6 h; selected up to 24 h) – transfer',
     'Not lysed: permissive BP unless > 220/120; aspirin 160–325 mg within 24–48 h once ICH excluded (24 h after lysis) [V]',
     'ICH: lower SBP towards 140–160 mmHg without abrupt drops – nicardipine infusion [V]; reverse anticoagulation; neurosurgery','NPO until swallow screen; head of bed 30°'],
 txs:'SSP 2024 CPG (PH CPG) · 2020 PH Hypertension CPG (ICH BP)', dispo:'Stroke unit / ICU; transfer for thrombectomy if indicated.', tk:['stroke','stroke','Stroke']},
{id:'sah', n:'Subarachnoid hemorrhage', sec:14, topic:'Headache · SAH', mnm:1, p:-0.5,
 g:['headache','thunderclap'],
 a:{thunderclap:-2},
 w:{thunderclap:5,onset_sudden:2,headache:1,neck_stiff:1.5,neck_stiff_sx:1,syncope:1.5,vomiting:0.5,seizure:1,gcs_lt15:1,htn:0.5,htn_sev:0.5,fever:-1.5,migraine_hx:-0.5,dur_gt7d:-2},
 rf:['gcs_lt15','seizure','htn_sev'],
 dx:['Ottawa SAH rule','Non-contrast CT head (≤ 6 h from onset: very high sensitivity)','CT > 6 h and negative → LP (xanthochromia) or CTA','ECG'],dxs:'AHA/ASA 2023 aSAH (intl)',
 tx:['Neurosurgery; SBP < 160 mmHg with nicardipine or labetalol [V]','Nimodipine 60 mg PO q4h × 21 d [V]','Reverse anticoagulation; analgesia, antiemetic'],
 txs:'AHA/ASA 2023 (intl)', dispo:'ICU / neurosurgical centre.', tk:['ich','subarachnoid hemorrhage','Intracerebral & subarachnoid hemorrhage']},
{id:'seizure', n:'Seizure / status epilepticus', sec:14, topic:'Seizures', mnm:0, p:0.5,
 g:['seizure'],
 w:{seizure:4,epilepsy:1.5,confusion:0.5,alcohol:0.5,glu_low:1,syncope:-1},
 rf:['gcs_le8','fever','hcg_pos'],
 dx:['Capillary glucose now; Na, Ca, Mg; pregnancy test; AED levels; toxicology','CT head for first seizure, focal deficit, trauma or anticoagulation; LP if fever / immunocompromise'],
 dxs:'AES 2016 status epilepticus (intl)',
 tx:['≥ 5 min: lorazepam 0.1 mg/kg IV (max 4 mg) [V] or diazepam 0.15–0.2 mg/kg IV (max 10 mg) [V] or midazolam 10 mg IM (> 40 kg) [V]; repeat once',
     'Second line: levetiracetam 60 mg/kg IV (max 4500 mg) [V] or phenytoin 20 mg/kg IV (≤ 50 mg/min) [V] or valproate 40 mg/kg IV (max 3000 mg) [V]',
     'Refractory → intubate, midazolam/propofol infusion [V]; thiamine 100–500 mg IV before glucose if malnourished/alcohol [V]; pregnant ≥ 20 wk → MgSO₄ (eclampsia)'],
 txs:'AES 2016 (intl)', dispo:'First unprovoked seizure back to baseline → outpatient neuro; status → ICU.', tk:['seizure','status epilepticus','Status epilepticus ladder']},
{id:'migraine', n:'Migraine / primary headache', sec:14, topic:'Headache', mnm:0, p:1.5,
 g:['headache'],
 w:{headache:2,migraine_hx:2.5,photophobia:1,nausea:0.5,vomiting:0.3,age_lt40:0.5,female:0.5,
    thunderclap:-3,onset_sudden:-1,fever:-1.5,t_ge38:-1.5,neck_stiff:-3,focal_weak:-1.5,hemiparesis:-2,confusion:-2,age_ge50:-1.5,htn_sev:-1,pregnant:-0.5,immuno:-1,petechiae:-1.5,plt_low:-1.5,retro_orb:-0.5,myalgia:-0.5},
 rf:[],
 dx:['Clinical; imaging only if red flags (SNOOP4: systemic, neuro, onset sudden, older, pattern change, positional, precipitated by Valsalva, papilledema, pregnancy)'],dxs:'AHS 2021 (intl)',
 tx:['Metoclopramide 10 mg IV [V] ± diphenhydramine 25 mg IV [V]','Ketorolac 30 mg IV [V] or ibuprofen 400–600 mg PO [V] / paracetamol 1 g [V] (avoid NSAIDs if dengue possible)','Dexamethasone 10 mg IV reduces recurrence [V]; avoid opioids'],
 txs:'AHS 2021 (intl)', dispo:'Home.', tk:['headache','headache','Headache – red flags, Ottawa SAH rule']},
{id:'vertigo', n:'Peripheral vertigo (BPPV / vestibular neuritis)', sec:14, topic:'Vertigo', mnm:0, p:1,
 g:['vertigo','dizziness'],
 w:{vertigo:3,dizziness:1,nausea:0.5,vomiting:0.5,ataxia:-3,focal_weak:-2,speech:-2,facial_droop:-2,hemiparesis:-2,headache:-0.5,age_ge65:-0.5,af:-0.5,syncope:-1,chest_pain:-1},
 rf:['ataxia','focal_weak'],
 dx:['TiTrATE (timing & triggers); Dix-Hallpike for episodic positional vertigo','HINTS by a trained examiner for acute continuous vertigo; any central sign → MRI / stroke pathway'],dxs:'AAO-HNS 2017 BPPV (intl)',
 tx:['BPPV: Epley maneuver','Short course meclizine 25 mg PO [V] or promethazine 25 mg [V]; antiemetic'],txs:'AAO-HNS 2017 (intl)', dispo:'Home if peripheral and walking.', tk:['vertigo','vertigo','Dizziness & vertigo – HINTS']}
);
// ───────────────────────── S15 TOX · S16 ENV ─────────────────────────
KB.push(
{id:'op', n:'Organophosphate / carbamate poisoning', sec:15, topic:'Pesticides', mnm:1, p:-0.5,
 g:['pesticide','miosis','secretions','fasciculation'],
 w:{pesticide:4,miosis:2.5,secretions:3,fasciculation:2.5,hr_lt60:1.5,wheeze:0.5,crackles_bilat:1,vomiting:0.5,diarrhea:0.5,diaphoresis:1,confusion:0.5,gcs_lt15:0.5,spo2_lt94:0.5},
 rf:['spo2_lt90','gcs_le8','hr_lt60','secretions'],
 dx:['Clinical (SLUDGE / DUMBELS + bronchorrhea, bronchospasm, bradycardia)','RBC / plasma cholinesterase if available – do not wait','ABG, ECG (QTc), CXR, electrolytes, glucose','Call UP-PGH National Poison Management & Control Center (NPMCC)'],
 dxs:'UP-PGH NPMCC (PH) · WHO / Eddleston (intl)',
 tx:['Decontaminate (remove clothes, wash skin; staff PPE); airway – avoid succinylcholine',
     'Atropine 1–3 mg IV, double the dose every 5 min until atropinized (clear chest, HR > 80, SBP > 80, dry axillae), then infusion 10–20 % of loading dose per hour [V]',
     'Pralidoxime 30 mg/kg IV over 30 min then 8 mg/kg/h (benefit uncertain) [V]','Diazepam for seizures / agitation [V]; observe 24–96 h for intermediate syndrome (neck flexion, proximal weakness)'],
 txs:'UP-PGH NPMCC (PH) · WHO (intl)', dispo:'ICU.', tk:['pest','organophosphate','Pesticides']},
{id:'apap', n:'Paracetamol (acetaminophen) overdose', sec:15, topic:'Acetaminophen', mnm:1, p:-0.5,
 g:['apap_od','overdose'],
 w:{apap_od:4,overdose:2,nausea:0.5,vomiting:0.5,ruq_pain:0.5,jaundice:0.5},
 rf:['jaundice','confusion'],
 dx:['Serum paracetamol level at ≥ 4 h post-ingestion → Rumack-Matthew nomogram','AST/ALT, INR, creatinine, glucose, lactate; salicylate level; ECG','UP-PGH NPMCC consult'],
 dxs:'AACT/ACMT 2023 consensus (intl) · UP-PGH NPMCC (PH)',
 tx:['Activated charcoal 1 g/kg (max 50 g) if ≤ 1–2 h and airway safe [V]','IV NAC: 150 mg/kg over 1 h, 50 mg/kg over 4 h, 100 mg/kg over 16 h [V] (or 2-bag SNAP); oral NAC 140 mg/kg then 70 mg/kg q4h × 17 [V]',
     'Start NAC empirically if level not available within 8 h of ingestion or presentation > 8 h','Psychiatric assessment for intentional ingestion'],
 txs:'AACT/ACMT 2023 (intl)', dispo:'Admit for NAC; psychiatry.', tk:['apap','paracetamol','Acetaminophen / paracetamol']},
{id:'opioid', n:'Opioid / sedative toxicity', sec:15, topic:'Opioids · sedatives', mnm:0, p:-1,
 g:['overdose','miosis','rr_lt12'],
 w:{overdose:2,miosis:2.5,gcs_lt15:1.5,rr_lt12:3,spo2_lt94:0.5,secretions:-2,fasciculation:-2,pesticide:-3,fever:-1},
 rf:['rr_lt12','spo2_lt90','gcs_le8'],
 dx:['Clinical; glucose; ECG; paracetamol level (co-ingestion)'],dxs:'AHA 2025 (intl)',
 tx:['Support ventilation (BVM) first','Naloxone 0.04–0.4 mg IV titrated to breathing (2 mg IN/IM if no IV) [V]; infusion for long-acting opioids [V]','Observe ≥ 4–6 h after last naloxone'],
 txs:'AHA 2025 (intl)', dispo:'Observe / admit.', tk:['naloxone','naloxone','Naloxone']},
{id:'toxalc', n:'Toxic alcohol (methanol / adulterated lambanog)', sec:15, topic:'Toxic alcohols', mnm:1, p:-1,
 g:['lambanog','alcohol','vision'],
 w:{lambanog:4,alcohol:1,vision:3,acidosis:2.5,abd_pain:0.5,vomiting:0.5,headache:0.5,confusion:1,gcs_lt15:0.5,kussmaul:1,dyspnea:0.3},
 rf:['vision','acidosis','gcs_lt15'],
 dx:['ABG: high anion-gap metabolic acidosis; serum osmolality (osmolal gap)','Electrolytes, glucose, creatinine, lactate, ethanol level; methanol level if available; fundoscopy'],
 dxs:'EXTRIP 2015 (intl) · UP-PGH NPMCC (PH)',
 tx:['Fomepizole 15 mg/kg IV load [V] or ethanol loading to serum 100–150 mg/dL if fomepizole unavailable [V]','Sodium bicarbonate for pH < 7.3 [V]; folic / folinic acid 50 mg IV q6h [V]',
     'Hemodialysis for severe acidosis, visual signs, coma, AKI'],
 txs:'EXTRIP 2015 (intl)', dispo:'ICU / dialysis-capable centre.', tk:['toxalc','methanol','Toxic alcohols']},
{id:'snake', n:'Snakebite envenomation', sec:16, topic:'Snakebite', mnm:1, p:0,
 g:['snake_bite','fang_marks'],
 w:{snake_bite:5,fang_marks:3,ptosis:3,bleeding:1,bleed_site:1.5,dyspnea:0.5,vomiting:0.5,speech:0.5},
 rf:['ptosis','dyspnea','bleed_site','spo2_lt94'],
 dx:['20-minute whole-blood clotting test (20WBCT)','CBC, PT/aPTT, creatinine, CK, UA, ECG','Serial neuro checks hourly × 24 h (ptosis, bulbar weakness, single-breath count / peak flow)'],
 dxs:'WHO SEARO snakebite guideline 2016 (intl) · RITM PCAV program (PH)',
 tx:['Immobilize limb, remove rings; no tourniquet, incision or suction',
     'Neurotoxic signs (Philippine cobra): Purified Cobra Antivenom (PCAV, RITM) per RITM protocol [V] – contact RITM / poison centre early; polyvalent antivenom under special permit elsewhere',
     'Neostigmine 0.5–2.5 mg IV with atropine 0.6 mg for neurotoxic paralysis (trial) [V]; early airway / ventilation',
     'Epinephrine 0.5 mg IM ready for antivenom reactions [V]; tetanus prophylaxis'],
 txs:'WHO SEARO 2016 (intl) · RITM (PH)', dispo:'Admit ≥ 24 h observation; ICU if neurotoxic.', tk:['snake','snakebite','Snakebite']},
{id:'heatstroke', n:'Heat stroke', sec:16, topic:'Heat emergencies', mnm:1, p:-0.5,
 g:['heat_exp','t_ge40'],
 w:{heat_exp:3.5,t_ge40:3,t_ge39:1,confusion:2,gcs_lt15:1,seizure:0.5,hr_gt100:0.5,sbp_lt90:0.5,neck_stiff:-1.5,rash:-1},
 rf:['gcs_lt15','seizure','sbp_lt90'],
 dx:['Core (rectal) temperature','Electrolytes, creatinine, CK, LFTs, glucose, coags (DIC), ABG, UA','Exclude sepsis / meningitis, thyroid storm, sympathomimetics, NMS'],dxs:'WMS 2019 heat illness (intl)',
 tx:['Cool to < 39 °C within 30 min: cold-water immersion (exertional) or evaporative + ice packs','Cautious IV fluids (cool NS 1–2 L) [V]; benzodiazepine for shivering / seizures [V]; no antipyretics'],
 txs:'WMS 2019 (intl)', dispo:'ICU.', tk:['heat','heat stroke','Heat illness']}
);
// ───────────────────────── S17 ENDOCRINE ─────────────────────────
KB.push(
{id:'dka', n:'Diabetic ketoacidosis', sec:17, topic:'Diabetic emergencies (DKA)', mnm:1, p:0,
 g:['glu_high','ketones','polyuria','polydipsia','kussmaul','missed_insulin','dm1','acidosis'],
 w:{glu_high:2.5,glu_vhigh:0.5,ketones:4,acidosis:3,polyuria:1.5,polydipsia:1.5,vomiting:1,abd_pain:1,kussmaul:2.5,dm1:2,dm:0.5,missed_insulin:2,m_sglt2:1.5,dehydration:1,age_lt40:0.5,rr_ge22:0.5,confusion:0.3,infection_sx:0.3},
 rf:['gcs_lt15','sbp_lt90'],
 dx:['Glucose, ketones (β-hydroxybutyrate ≥ 3 mmol/L), VBG/ABG (pH < 7.3 or HCO₃ < 18)','Electrolytes – K⁺ BEFORE insulin; anion gap, BUN/creatinine, osmolality, CBC, UA, ECG',
     'Precipitant: cultures, CXR, lipase, troponin, pregnancy test'],
 dxs:'ADA/EASD/JBDS/AACE/DTS 2024 hyperglycemic crises consensus (intl) – no PH DKA CPG (UNITE for DM excludes inpatient care)',
 tx:['IV fluids: 0.9 % NaCl or balanced crystalloid 1–1.5 L in the first hour [V], then 250–500 mL/h by volume status','Potassium: if K⁺ < 3.5 replace before insulin; 3.5–5.0 add 20–40 mEq per litre [V]',
     'Regular insulin IV 0.1 U/kg/h (± 0.1 U/kg bolus) [V]; add dextrose when glucose < 250 mg/dL (14 mmol/L) [V]','Bicarbonate only if pH < 7.0; resolution: pH ≥ 7.3, HCO₃ ≥ 18, β-OHB < 0.6; overlap SC basal insulin 1–2 h before stopping infusion'],
 txs:'ADA 2024 consensus (intl)', dispo:'ICU / HDU (insulin infusion).', tk:['dka','DKA','DKA quick card']},
{id:'hhs', n:'Hyperosmolar hyperglycemic state', sec:17, topic:'Diabetic emergencies (HHS)', mnm:1, p:-0.5,
 g:['glu_vhigh','glu_high'],
 w:{glu_vhigh:4,glu_high:1,confusion:2,gcs_lt15:1,dehydration:2,age_ge65:1.5,dm:1,polyuria:1,polydipsia:1,ketones:-2,acidosis:-2,kussmaul:-1.5,age_lt40:-1.5,dm1:-1},
 rf:['gcs_lt15','sbp_lt90'],
 dx:['Glucose > 600 mg/dL, effective osmolality > 300, no significant ketoacidosis','Electrolytes, creatinine, CBC, cultures, ECG; CT head if focal'],dxs:'ADA 2024 consensus (intl)',
 tx:['0.9 % NaCl ~1 L/h initially, aim osmolality fall 3–8 mOsm/kg/h [V]','Insulin only once fluids stop lowering glucose (or if ketonemia): 0.05 U/kg/h [V]','Potassium replacement; VTE prophylaxis'],
 txs:'ADA 2024 (intl)', dispo:'ICU / HDU.', tk:['hhs','HHS','Hyperosmolar hyperglycemic state']},
{id:'hypogly', n:'Hypoglycemia', sec:17, topic:'Hypoglycemia', mnm:1, p:0,
 g:['glu_low','confusion','seizure','gcs_lt15'],
 w:{glu_low:6,m_insulin:1.5,m_oha:1.5,confusion:0.5,diaphoresis:1,seizure:0.5,gcs_lt15:0.5,alcohol:0.5,ckd:0.5},
 a:{glu_low:-6},
 rf:['gcs_lt15','seizure'],
 dx:['Fingerstick glucose (< 70 mg/dL / 3.9 mmol/L); repeat 15 min after treatment','Cause: sulfonylurea, insulin, sepsis, liver failure, alcohol, adrenal insufficiency'],dxs:'ADA Standards of Care 2025 (intl)',
 tx:['Alert: 15–20 g oral glucose [V]','Altered: dextrose 50 % 25 g (50 mL) IV [V] or D10 250 mL [V]; glucagon 1 mg IM if no IV [V]','Thiamine 100 mg IV if malnourished / alcohol [V]; sulfonylurea → admit, octreotide 50 mcg SC q6–8h [V]'],
 txs:'ADA 2025 (intl)', dispo:'Home if insulin-related and eating; admit if sulfonylurea / recurrent.', tk:['hypogly','hypoglycemia','Hypoglycemia']},
{id:'storm', n:'Thyroid storm', sec:17, topic:'Thyroid storm', mnm:1, p:-1,
 g:['thyroid','goiter','tremor'],
 w:{thyroid:3,goiter:2,tremor:2,hr_ge125:2,hr_gt100:1,t_ge39:1.5,t_ge38:0.5,confusion:1.5,diarrhea:0.5,vomiting:0.5,ecg_af:1,irregular:0.5,wt_loss:1,infection_sx:0.5},
 rf:['gcs_lt15','sbp_lt90','t_ge40'],
 dx:['Burch-Wartofsky score','TSH, FT4/FT3, CBC, LFT, glucose, electrolytes, ECG, cultures'],dxs:'ATA 2016 (intl)',
 tx:['Propranolol 60–80 mg PO q4h (or 0.5–1 mg IV) [V]','PTU 500–1000 mg load then 250 mg q4h [V] or methimazole 20 mg q4–6h [V]; iodine ≥ 1 h after thionamide [V]','Hydrocortisone 300 mg IV then 100 mg q8h [V]; cooling, paracetamol (no aspirin); treat precipitant'],
 txs:'ATA 2016 (intl)', dispo:'ICU.', tk:['storm','thyroid storm','Thyroid storm']}
);
// ───────────────────────── S3 · S23 · S24 ─────────────────────────
KB.push(
{id:'anaphylaxis', n:'Anaphylaxis', sec:3, topic:'Allergy & anaphylaxis', mnm:1, p:0,
 g:['urticaria','angioedema','allergen','throat_tight','stridor'],
 w:{allergen:3,urticaria:2.5,angioedema:2.5,throat_tight:1.5,stridor:1.5,wheeze:1,wheeze_pe:1,dyspnea:0.5,sbp_lt90:1.5,onset_sudden:1.5,vomiting:0.5,abd_pain:0.3,pruritus:1,atopy:1,dur_lt24h:0.5,
    fever:-1.5,t_ge38:-1.5,dur_gt7d:-3},
 rf:['stridor','sbp_lt90','spo2_lt90','throat_tight'],
 dx:['Clinical diagnosis (WAO 2020 criteria) – treat first','Serum tryptase within 1–2 h if available'],dxs:'WAO 2020 · EAACI 2021 (intl)',
 tx:['Epinephrine 0.01 mg/kg IM (1 mg/mL; max 0.5 mg adult) anterolateral thigh, repeat q5–15 min [V]','Supine / legs up; high-flow O₂; crystalloid 20 mL/kg bolus for hypotension [V]',
     'Refractory: epinephrine infusion 0.05–0.1 mcg/kg/min [V]; glucagon 1–5 mg IV if on β-blocker [V]','Adjuncts only: salbutamol neb for bronchospasm [V]; cetirizine 10 mg PO / diphenhydramine 25–50 mg IV for skin symptoms [V]'],
 txs:'WAO 2020 · RCUK 2021 (intl)', dispo:'Observe ≥ 4–6 h (longer if severe / biphasic risk); discharge with action plan and epinephrine plan.', tk:['anaph','anaphylaxis','Anaphylaxis']},
{id:'septicjoint', n:'Septic arthritis', sec:23, topic:'Hot swollen joint', mnm:1, p:-0.5,
 g:['hot_joint'],
 w:{hot_joint:3.5,fever:1.5,t_ge38:1,arthralgia:0.5,immuno:0.5,dm:0.5},
 rf:['sbp_lt90'],
 dx:['Arthrocentesis before antibiotics: WBC, Gram stain, culture, crystals','Blood cultures, CBC, CRP/ESR; X-ray'],dxs:'BSR/BOA 2006 · EULAR (intl)',
 tx:['Cefazolin 2 g IV q8h or ceftriaxone 2 g IV OD (gonococcal risk) ± vancomycin [V]','Orthopedics for washout'],txs:'BSR/BOA (intl)', dispo:'Admit.', tk:['hotjoint','septic arthritis','Hot swollen joint']},
{id:'awd', n:'Alcohol withdrawal (incl. delirium tremens)', sec:24, topic:'Alcohol & substance use', mnm:0, p:-0.5,
 g:['alcohol'],
 w:{alcohol:3,tremor:2,hr_gt100:1,diaphoresis:1,confusion:1.5,seizure:1.5,t_ge38:0.5,lambanog:-1,vision:-1},
 rf:['confusion','seizure','t_ge39'],
 dx:['CIWA-Ar','Glucose, electrolytes (Mg, K, PO₄), LFTs; CT head if seizure/trauma; exclude infection'],dxs:'ASAM 2020 (intl)',
 tx:['Symptom-triggered diazepam 10–20 mg PO/IV q1–2h when CIWA ≥ 10 [V] (lorazepam if liver failure [V])','Thiamine 100–500 mg IV before glucose [V]; correct Mg/K'],
 txs:'ASAM 2020 (intl)', dispo:'Admit if DTs, seizures, CIWA > 15.', tk:['awd','alcohol withdrawal','Alcohol withdrawal (CIWA-Ar)']},
{id:'panic', n:'Panic attack / anxiety (diagnosis of exclusion)', sec:24, topic:'Mood & anxiety disorders', mnm:0, p:-1,
 g:['palpitations','chest_pain','dyspnea'],
 w:{palpitations:1,dyspnea:0.5,chest_pain:0.3,dizziness:0.5,age_lt40:1,female:0.3,tremor:0.5,
    spo2_lt94:-3,sbp_lt90:-3,t_ge38:-2,ecg_ste:-4,ecg_std:-2,trop_pos:-4,age_ge50:-1.5,dvt_signs:-2,hemoptysis:-2,syncope:-1,cad:-1.5,fever:-1.5,crackles_focal:-2,crackles_bilat:-2,diaphoresis:-0.5},
 rf:[],
 dx:['Exclude organic causes first: ECG, glucose, SpO₂; consider PE, ACS, arrhythmia, thyrotoxicosis, hypoglycemia'],dxs:'NICE CG113 (intl)',
 tx:['Reassurance, breathing coaching','Lorazepam 0.5–1 mg PO sparingly [V]','Mental health referral (PH NCMH crisis line 1553)'],
 txs:'NICE (intl)', dispo:'Home.', tk:['psychosis','anxiety','Psychosis, mood & anxiety disorders']}
);
